### ISSUE TITLE
tests for parallel bulk rely on Mock.call_count which is not thread safe

### ISSUE THREAD

**Issue by honzakral** [elastic/elasticsearch-py#1000]
We need to change the logic used to checking the calls made to something that can be incremented atomically like appending to a list or something.

**Comment by mosi-kha** [comment]
i wrote a test(pytest) for my elasticsearch project, when i run it, this error raise `RequestError(400, 'index_closed_exception', 'closed')` but, when run as debug and run step by step it's ok ...
can this prove elasticsearch is not threading safe?

**Comment by HonzaKral** [comment]
@mosi-kha Elasticsearch is thread safe, it is mock which is not and it only affects this one test. What you are seeing is unrelated.

**Comment by pquentin** [comment]
[Since November 2018](https://github.com/elastic/elasticsearch-py/pull/875) (way before this issue was created), TestParallelBulk uses `threading.Lock()` to increment `call_count`. Since I've never seen this test fail, I'm closing this issue.
