### ISSUE TITLE
Failed Bulk Requests Should Mark Connection As Dead

### ISSUE THREAD

**Issue by speedplane** [elastic/elasticsearch-py#1002]
When processing items in bulk, it's possible that some of the bulk actions will fail, but the main call to `bulk` will return a 200. This can happen, for example, if bulk indexing into multiple indexes and one of the indexes goes down. Some of the requests will get 503, others will return 200, and the main call to `bulk` will also return 200. 

It would be nice if the connection was marked as dead when one of the bulk operations fails (or at least an option to enable this feature). Marking it as dead will prevent repeated attempts to index to downed indexes. This logic works nicely for all of the endpoints, but it isn't implemented for the `bulk` endpoint.

I'm not sure the best way to do this, but it will likely require abstracting some of the retry and error handling code in `Transport.perform_request` and make it accessible to `_process_bulk_chunk` or `streaming_bulk`.

Note: This is somewhat related to #645, which is focused on retry handling. Retry handling will be a bit more complex (as some of the bulk operations may have succeeded).

**Comment by HonzaKral** [comment]
There is no reason to mark a node as dead as the node is alive and running since it processed the `bulk` request. There is no expectation that the request, if sent to a different node, would succeed.
