### ISSUE TITLE
put_mapping() and doc_type

### ISSUE THREAD

**Issue by mihalikv** [elastic/elasticsearch-py#1007]
I have following error message
`put_mapping() missing 1 required positional argument: 'doc_type'`

I think because of removed document types in ES 7. If i provide some document type for example '_doc', result is error from ES: 

`'Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.'`

Is it some workaround for this issue or is it something bad on my side ?

**Comment by imdadahad** [comment]
@mihalikv how did you go about solving this?

**Comment by mihalikv** [comment]
@imdadahad  I am not sure, but I think it was just mismatch with library versions. Just check versions https://github.com/elastic/elasticsearch-py#compatibility
