### ISSUE TITLE
Sniffing fails if -Des.http.cname_in_publish_address=true is set on nodes

### ISSUE THREAD

**Issue by phoerious** [elastic/elasticsearch-py#1008]
I have a cluster running Elasticsearch 6.8, which throws deprecation warnings if `-Des.http.cname_in_publish_address=true` is not set. Unfortunately, setting this option causes the Python client to fail with `Name or service not known` due to connection errors in urllib3 if sniffing is enabled.

It appears that it's trying to connect to `http://HOST/IP:PORT/_nodes/_all/http` on all sniffed nodes, which is obviously incorrect. The correct address would either be `http://IP:PORT/_nodes/_all/http` or `http://HOST:PORT/_nodes/_all/http`, which needs to be parsed properly from the returned publish address.

If I unset `es.http.cname_in_publish_address` and restart my cluster nodes or disable sniffing on client side, I can connect to the cluster without issues.

**Comment by HonzaKral** [comment]
This has been fixed in 71840d315a1a9b72b6849423f5cec3be49680095
