### ISSUE TITLE
Count function returns different document count

### ISSUE THREAD

**Issue by Narzhan** [elastic/elasticsearch-py#1015]
When using a method to count the records in Elasticsearch the count of documents is zero. When I use a direct query to Elasticsearch the number of records is correct.

Requests example:
```
>>> req=requests.get("http://elasticsearch:9200/index/_count", headers= {"Content-Type": "application/json"})
>>> req.content
b'{"count":2829320,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0}}'
>>> host = elasticsearch.Elasticsearch("elasticsearch", port=9200)
>>> counts=host.count("index", body={"query": {"match_all": {}}}, ignore_unavailable=True,
...                                      request_timeout=60)
>>> counts
{'count': 0, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}}
>>> counts=host.count("index", ignore_unavailable=True, request_timeout=60)
>>> counts
{'count': 0, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}} 
```

**Comment by dpereira** [comment]
I can reproduce it with ES v6.7.2 and elasticsearch-py client v7.0.4

@Narzhan , if I change the call to:

```
counts=host.count(index="index", body={"query": {"match_all": {}}}, ignore_unavailable=True,
                                      request_timeout=60)
```

It works as expected.

The problem seems to be the handling of the `index` parameter as a posicional parameter: if it is passed in only as a positional parameter, the url built for performing the request is: `/_all/index/_count`, whereas if the `index` is passed in as a keyword parameter, the url seems to get correctly built: `/index/_count`

I was also able to reproduce it with a simpler call:

```
In [11]: c.count("index")
Out[11]:
{'count': 0,
 '_shards': {'total': 5, 'successful': 5, 'skipped': 0, 'failed': 0}}
```

````
In [12]: c.count(index="index")
Out[12]:
{'count': 2,
 '_shards': {'total': 5, 'successful': 5, 'skipped': 0, 'failed': 0}}
```

**Comment by dpereira** [comment]
Also, it is woth to check your client version against the ES version you're running against: if you are running with elasticsearch-py 7 against an ES 6 that may be what's causing this; if you use the elastisearch-py 6 client against an ES 6 instance, the problem does not occur.

**Comment by Narzhan** [comment]
@dpereira The keyword argument worked. However it is strange since in the docs and in my version of Elasticsearch (6.x.x) the index is the first argument

`def count(self, index=None, doc_type=None, body=None, params=None):`
