### ISSUE TITLE
urllib3.connection.HTTPConnection when using elasticsearch.helpers.bulk

### ISSUE THREAD

**Issue by prateekponnuru** [elastic/elasticsearch-py#1017]
Here is my code -
```
try:
        bulk(client=es, 
                actions=(rec.index(using=conn) for rec in models.XYZ_model.objects.all().order_by('_id')[start:end].iterator()),
                chunk_size=100)
    except ConnectionError as e:
        print(e.info)
```

This is what i get - 
<urllib3.connection.HTTPConnection object at 0x0000020CC3AEB278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

But weirdly this only happens after all the records are indexed. No matter how small or how big the range of records i try - i tried between 1 and 10000.

**Comment by HonzaKral** [comment]
I am sorry but I cannot replicate this issue. It looks like a network issue in your environment.

Sorry I cannot be more help but please feel free to reopen the issue with more information!

**Comment by prateekponnuru** [comment]
It is definitely not a network issue, coz it keeps happening every single time, after all the records are indexed.
I am happy to provide more information, please tell me what will be helpful to you.
