### ISSUE TITLE
Bulk on 7.0.4 does not support `version` and `version_type` fields 

### ISSUE THREAD

**Issue by StefanSmith** [elastic/elasticsearch-py#1020]
As part of upgrading our cluster to Elasticsearch v7.1, we updated the elasticsearch library to v7.0.4. Unfortunately, we encountered a regression in the `bulk` function when changing our `_version` and `_version_type` action properties to `version` and `version_type`, respectively, as suggested [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_camel_case_and_underscore_parameters_deprecated_in_6_x_have_been_removed).

The hardcoded whitelist referred to in this [old issue](https://github.com/elastic/elasticsearch-py/issues/564) is to blame. We have worked around this for now by overriding the `expand_action_callback` parameter on `bulk` but this feels like something the library should support out of the box.

**Comment by thomasthiebaud** [comment]
I had the same problem recently and did a PR to fix it. For the moment I'm also using an hotfix by using my own `expand_action_callback`
