### ISSUE TITLE
fix typing of index creation timeout parameter

### ISSUE THREAD

**Issue by tomkralidis** [elastic/elasticsearch-py#1026]
Hi: we use this awesome package as part of the [pygeoapi](https://pygeoapi.io) project.  Our builds started to [break](https://travis-ci.org/geopython/pygeoapi/jobs/592275226) with version 7.0.5 of the package.  The issue seems to be bound to [setting request timeouts](https://github.com/geopython/pygeoapi/blob/master/tests/load_es_data.py#L74).

Note that this works fine using 7.0.4.

**Comment by HonzaKral** [comment]
This has been fixed in `master` by https://github.com/elastic/elasticsearch-py/pull/1051
