### ISSUE TITLE
bulk() and streaming_bulk() helpers don't apply the `ignore` argument to op results

### ISSUE THREAD

**Issue by jboning** [elastic/elasticsearch-py#1027]
The documentation for `ignore` indicates:

> An API call is considered successful (and will return a response) if elasticsearch returns a 2XX response. Otherwise an instance of TransportError (or a more specific subclass) will be raised. You can see other exception and error states in Exceptions. If you do not wish an exception to be raised you can always pass in an ignore parameter with either a single status code that should be ignored or a list of them

The `bulk()` and `streaming_bulk()` helpers parameters accept the `ignore` argument and pass it through to the underlying API call, but don't otherwise consider it while processing results. It would be more useful (and more consistent with how `ignore` works with other client methods) to apply the value to individual op results, treating ops with ignored statuses as successful.

**Comment by jboning** [comment]
If this is desirable, I'd be willing to assemble a PR!

**Comment by HonzaKral** [comment]
The `bulk` and `streaming_bulk` helpers have different mechanisms on how to control the flow in case of errors (`raise_on_error` and `raise_on_exception`) so they don't use the `ignore` parameter.

I understand this is confusing and perhaps we could document it but overall I do believe it to be the correct behavior.

Thank you for raising the issue!

**Comment by arusahni** [comment]
I'd love to have some client-side filter for the status codes - for example, I may want to ignore version conflict errors (409), but not others. In order to reduce confusion (and boiler-plate across various code-bases), would a `dont_raise_on_status=` kwarg be more palatable?

**Comment by HonzaKral** [comment]
@arusahni that is a great idea, thank you! Just not sure about the best naming. But definitely doable and quite simple to do.

Reopening the issue to keep track of this.

**Comment by Sparkycz** [comment]
@sethmlarson Guess you forgot to close the issue...
