### ISSUE TITLE
Connection in CLOSE WAIT state 

### ISSUE THREAD

**Issue by ravidelcj** [elastic/elasticsearch-py#1030]
After running the bulk() function to update objects.
I noticed that the connections are not being reused and are on CLOSE_WAIT state
Also the garbage collector is not flushing out the connections.
I have closed the connection pool manually which resulted in flushing out of all CLOSE_WAIT connections.

I am wondering why the library is not able to close connection and why am i having so many CLOSE_WAIT connections ?
I have read in few issue reported earlier that the library depends on the gc to collect the connections.
But in my case it is not able to collect the connections, i am wondering why this is happening?

**Comment by HonzaKral** [comment]
Can you share the code that leads to this behavior? In general we don't manage our connections and instead rely on `urllib3` for that functionality. If there is any issue with the connection handling it is most likely within `urllib3`

**Comment by sethmlarson** [comment]
Going to close this issue as no follow-up information was provided.
