### ISSUE TITLE
request_timeout value is in string instead of int/float in elasticsearch-py 7.0.5

### ISSUE THREAD

**Issue by awangku92** [elastic/elasticsearch-py#1031]
input :
`int_timeout = int('1024')`
`bulk(es, df_data, index=index, doc_type=doc, raise_on_error=True, request_timeout=int_timeout)`

output :
ConnectionError(Timeout value connect was 1024, but it must be an int, float or None.) caused by: ValueError(Timeout value connect was 1024, but it must be an int, float or None.)

Note :
works fine using 7.0.4

**Comment by HonzaKral** [comment]
This has been fixed in 1438d66045e05855dcdbb01680f5c521584af6a8
