### ISSUE TITLE
random.choice() elasticsearch/helpers/actions.py not seeded?

### ISSUE THREAD

**Issue by jjlin453** [elastic/elasticsearch-py#1032]
We are using the ES client in distributed kubernetes containers and noticed our bulk writes are all targeting one host (out of 50), despite us passing all available hosts to the ES client initializer.  Through some investigation, we have determined it may be because the random function in actions.py doesn't seem to be seeded, and therefore uses system time by default.  Therefore when our kubernetes containers spin up at the same time they have the same seed and therefore "randomly" choose the same node to target.  

1. Just to make sure we aren't missing something, is it possible to initialize the client and or function so that it seeds differently?
2.  Would it be possible for you to confirm this on your  end?

Best,

JJ

**Comment by HonzaKral** [comment]
There is no `random` use in the library outside of `connection_pool` where it is used to select a different connection in `RandomSelector` as well as when randomizing the initial conneciton list for round robin load balancing. These features are not critical (`RandomSelector` is not even used by defalut), and it doesn't affect the functionality if `random` is not seeded. 

Also even if the random module is not seeded the current time used by default is used with fractions of seconds so it is highly unlikely that many containers would end up with the same seed. You can also always seed the `random` module yourself before instantiating the Elasticsearch class.

Hope this helps!
