### ISSUE TITLE
Issue with elasticsearch 7.4 instances and ids with spaces 

### ISSUE THREAD

**Issue by chrisbennight** [elastic/elasticsearch-py#1037]
**Overview**:  
Issue is an interaction between existing url path encoding behaviour and changes made in 7.4 https://www.elastic.co/guide/en/elasticsearch/reference/7.x/breaking-changes-7.4.html which no longer interpret a + in a url path as a space.

**Details**: 
Id's with spaces in them are encoded with python's  quote_plus method:  https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L52  

This method (docs here:  https://docs.python.org/3/library/urllib.parse.html ) encodes spaces as the `+` character instead of `%20`.   When an id field contains a space previously (es < 7.4) these `+` symbols would be translated back to a space.

Since this behaviour has changed in es this now causes spaces in id's to be turned into the `+` character, which is then directly stored in elasticsearch.  

Note that since bulk methods don't have the id in the URL field they continue to work correctly - so indexing the same data with the single and bulk methods results in different id's.  

**Suggested Fix:**
I don't believe the use of the python `urllib.parse.quote_plus` is appropriate;  I believe just using `urllib.parse.quote`  here:  https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L52  will fix the issue.    The only difference between the two methods (see docs for both method:  https://docs.python.org/3/library/urllib.parse.html ) is the handling of spaces.   the `urllib.parse.quote` method encodes spaces with %20 instead of +,  which I believe should work as expected in es 7.4  (and I think should work correctly with earlier versions - though haven't confirmed).

**Comment by chrisbennight** [comment]
PR Above, and CLA paperwork signed

**Comment by HonzaKral** [comment]
This has been fixed by #1040, thank you again for the help!
