### ISSUE TITLE
mark_dead() in ConnectionPool always removes the first connection in the pool

### ISSUE THREAD

**Issue by tongwang** [elastic/elasticsearch-py#1044]
`ConnectionPool`'s `mark_dead()` method is supposed to remove the dead `connection` from the `connections` list:

`self.connections.remove(connection)`

However the equality comparison implementation `__eq__` in the `Connection` class is incorrect. It always returns `True` as long as both objects are `Connection` instances:

```
def __eq__(self, other):
        if not isinstance(other, Connection):
            raise TypeError(
                "Unsupported equality check for %s and %s" % (self, other)
            )
        return True
```

This defect manifests itself by removing all good connections until the connections is empty. One dead connection will bring down the whole connection pool.

Proposed solution: removing `__eq__` from `Connection`. Thoughts?

**Comment by HonzaKral** [comment]
That is definitely the correct solution, would you be open to sending a PR?

Thank you!
