### ISSUE TITLE
how to change index.number_of_replicas

### ISSUE THREAD

**Issue by guanxudong** [elastic/elasticsearch-py#105]
sorry, i cannot find how to do this with elasticsearch-py, could you give me a help?

**Comment by iamtodor** [comment]
I could not manage to achieve this purpose with the example above with `elasticsearch==6.3.1`
I got `{ "acknowledged": false }` but actually the value still be the same.

The worked solution:
```
import requests
requests.put(f'{ELASTIC_URL}/{elastic_index}/_settings',
                                data=json.dumps({'number_of_replicas': 2, 'refresh_interval': '1s'}),
                                headers={'Content-type': 'application/json', 'Accept': 'text/plain'})
```
requests==2.21.0

**Comment by petergaultney** [comment]
I am having a similar problem. I actually get `acknowledged: True` but the setting remains unchanged. The workaround of skipping the Python client works for me.
