### ISSUE TITLE
docs on RTD not getting updated

### ISSUE THREAD

**Issue by freddrake** [elastic/elasticsearch-py#1060]
The formatted documentation on readthedocs.io (https://elasticsearch-py.readthedocs.io/en/master/) is not showing recent updates, and still refers to 7.0.0 as a development version.

**Comment by adamchainz** [comment]
This is still not updated, please check RtD :)

**Comment by freddrake** [comment]
This looks better to me!  Thanks.

**Comment by adamchainz** [comment]
Doesn't look like it to me:

* Latest changelog is 7.1.0 : https://github.com/elastic/elasticsearch-py/blob/master/Changelog.rst - but this isn't on RtD: https://elasticsearch-py.readthedocs.io/en/stable/Changelog.html
* Latest index.rst mentions Elasticsearch 7.0.0: https://github.com/elastic/elasticsearch-py/blob/master/docs/index.rst - but again not on RtD: https://elasticsearch-py.readthedocs.io/en/master/index.html

**Comment by freddrake** [comment]
Guess RtD is falling behind still.  --sigh--

**Comment by sethmlarson** [comment]
This is fixed again.
