### ISSUE TITLE
retry_on_conflict missing for bulk actions?

### ISSUE THREAD

**Issue by ChadTaljaardt** [elastic/elasticsearch-py#1063]
I am having a conflict issue with my application, I came across this issue: https://github.com/elastic/elasticsearch/issues/17165 and the solution was to try the retry_on_bulk argument. I don't see this argument being available for bulk operations though. How would I go about re-trying on conflict when using bulk indexing?

**Comment by marshallmain** [comment]
You can add the retry_on_conflict argument to the action itself when making bulk actions.  https://www.elastic.co/guide/en/elasticsearch/reference/7.x/docs-bulk.html#bulk-update
Here is a quick and dirty example of what this might look like:
`es.index(index="my-index", id=42, body={"any": "data"})
body = "{\"update\":{\"_id\":42,\"_index\":\"my-index\",\"retry_on_conflict\":3}}\n{\"doc\":{\"any\":\"data3\"}}"
es.bulk(body)`

**Comment by HonzaKral** [comment]
As @marshallmain said, the parameters for operations inside a bulk request need to be passed in the body. You can also pass them into the bulk helper:

```python
from elasticsearch import helpers, Elasticsearch
es = Elasticsearch()

def generate_actions():
    yield {"_op_type": "update", "retry_on_conflict": True, "doc": {"any": "data"}}

helpers.bulk(es, generate_actions())
```

hope this helps!

**Comment by saifrehman15** [comment]
I am also updating document in bulk using painless script. but unable to update with _retry_on_conflict parameter.

**Comment by sethmlarson** [comment]
@saifrehman15 Have you tried adding `"retry_on_conflict": True` to the JSON body as mentioned above?

**Comment by saifrehman15** [comment]
Yes i have tries it. It's working fine with single document . but it's not working on bulk update. 
Following is my script in php 

> [
            'index' => $this->esIndex,
            'type' => 'doc',
            "retry_on_conflict" => 3,
            'body' => [
                "script" => [
                    "source" => "ctx._source.box_posts.addAll(params.pay_load.get(ctx._source.id))",
                    "lang" => "painless",
                    'params' => [
                        'pay_load' => $pay_load
                    ],
                ],
                "query" => [
                    "bool" => [
                        "must" => [
                            [
                                ["term" => ["type" => "box"]],
                                ["terms" => ["db_id" => array_values(array_unique($box_ids))]]
                            ]
                        ]
                    ]
                ]
            ]
        ]

**Comment by davidkong0987** [comment]
I believe it should be `{"retry_on_conflict": 3}` instead of` { "retry_on_conflict": True}`

**Comment by davidkong0987** [comment]
Oh you have already done that. 
`"inline" => "ctx._source.box_posts.addAll(params.pay_load.get(ctx._source.id))",`
I remember needing to change my stuff from `source` to `inline`
