### ISSUE TITLE
Does it support SQL queries? 

### ISSUE THREAD

**Issue by EdgeSync** [elastic/elasticsearch-py#1066]
Hi, 

Does anyone know if this package supports sending SQL queries to Elastic?

e.g. from Dev Tools I can run something like this:

```
POST _sql?format=csv
{
    "query": "select * from sample_index where message = 'hello_world'"
}
```

How would I do that with this package?
I normally do searches something like this:

```
from elasticsearch import Elasticsearch as E
es = E(["https://username:password@localhost:9200"], verify_certs=False, timeout=60)

es.search(index='sample_index', body={"query": 
                                                                  { "multi_match": 
                                                                      { "query": "hello_world" }
                                                                  }
                                                              }
```

Having trouble understanding how to put the SQL syntax in.

**Comment by HonzaKral** [comment]
You can use the `.sql.query` method:

```python
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.sql.query(body={'query': 'select 1'})
```

Hope this helps!

**Comment by EdgeSync** [comment]
> You can use the `.sql.query` method:
> 
> ```python
> from elasticsearch import Elasticsearch
> es = Elasticsearch()
> es.sql.query(body={'query': 'select 1'})
> ```
> 
> Hope this helps!

Hey @HonzaKral  - Yes that worked prefect, thank you.

Just noting, can also add in the format like so:

```from elasticsearch import Elasticsearch
es = Elasticsearch()
es.sql.query(body={format=txt, 'query': 'select 1'})
```
I did notice the pydocs documentation doesn't seem to have this, so will see about writing a piece for it. 

Thanks for the assistance.
