### ISSUE TITLE
Can major versions of the library be used with later versions of the server?

### ISSUE THREAD

**Issue by jarshwah** [elastic/elasticsearch-py#1067]
Apologies for the issue, but I couldn't find a better place to ask this question.

I'm trying to figure out the best way to upgrade our elasticsearch cluster from version 5 to version 6 (and then 7..) without coordinating an upgrade of both the client and server.

Can library version 5.x work with server version 6.x?

The readme says

> For Elasticsearch 5.0 and later, use the major version 5 (5.x.y) of the library.

Which makes it sound like 5.x will work with a "later" server version of 6, but I'd like to confirm that possibility. I don't expect library versions to work against lesser server versions.

Thanks!

**Comment by HonzaKral** [comment]
You should really match the major version of the library to the Elastcsearch version. things may work across versions, but there is no guarantee unfortunately. You want to be using version `6.x` to talk to Elasticsearch `6.x` and `7.x` for `7.x`.

Apologies for the confusion

**Comment by jarshwah** [comment]
Yep I get that - we have two clusters in the same application and wanted to upgrade each cluster independently. This would necessitate having a single library version that could talk to v5 and v6 servers, or two separate vendored libraries that would need to update at the same time as any cutover.

Appreciate there's no guarantee here, I'll just need to do some old fashioned testing.

**Comment by HonzaKral** [comment]
If you have two clusters that is a different situation - we always release the outgoing version as a separate pypi package (0) so you can do: `pip install elasticsearch6` and then use `import elasticsearch6`. That way you can have both versions in your code base, one for each cluster.

Hope this helps!

0 - https://pypi.org/project/elasticsearch6/
