### ISSUE TITLE
Support for Repository cleanup API

### ISSUE THREAD

**Issue by nemo-rb** [elastic/elasticsearch-py#1074]
Currently there is no easy way to call the repository [cleanup](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_repository_cleanup) API from elasticsearch-py.

*Definition of done:*
* Add support for the repository cleanup API;
* Add tests.

**Comment by viglia** [comment]
@nemo-rb at the moment the python client supports the APIs up to `7.1.0`

The `_cleanup` API was added in `7.4` see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.4.0.html#enhancement-7.4.0).

As we'll release new versions for the client (7.4, 7.5, etc.) it will be made available.

**Comment by HonzaKral** [comment]
This has been implemented in `master` and will go out with next release. Hope this helps!

https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/snapshot.py#L192
