### ISSUE TITLE
How to index large documents

### ISSUE THREAD

**Issue by bordercore** [elastic/elasticsearch-py#1079]
I am trying to index individual documents that are larger than 10M using AWS Elasticsearch. However, this exceeds the HTTP request size limit for the instance I'm using, and going up to 100M would basically cost me ten times as much.

I have tried using the `max_chunk_bytes` option used by the bulk helpers, but this doesn't help. Based on inspection of the code here https://github.com/elastic/elasticsearch-py/blob/cc461fdc3c9e33d1c31ae0f9681f16b0e163cc3a/elasticsearch/helpers/actions.py#L56 it appears that it's assuming you're bulk inserting multiple smaller documents, which it can then chunk up based on the `max_chunk_bytes` and `chunk_size` values you chose. But if you're just indexing a single document, it seems to always create a chunk with the entire document regardless of size. In other words, it can't chunk up parts of an individual document.

Can someone verify if this is the case? If so, is it theoretically possible to alter the code to support chunking parts of a document? I don't mind doing the work if the experts out there think it's doable. And if there's no demand for this sort of modification, I can just keep it on a private branch.

Other than that, are there other options I can explore?

**Comment by HonzaKral** [comment]
>  it appears that it's assuming you're bulk inserting multiple smaller documents, which it can then chunk up based on the max_chunk_bytes and chunk_size values you chose. But if you're just indexing a single document, it seems to always create a chunk with the entire document regardless of size. In other words, it can't chunk up parts of an individual document.

Indeed, that is so, there is no easy automatic way to split documents since this is an arbitrary limit imposed by AWS and not Elasticsearch. You can try and send the documents in parts using the `update` API by creating a document and then send multiple requests appending individual fields and/or values to said document using `update`. This will, however, have negative impact on performance as the document will need to be reindexed every time.

Hope this helps!

**Comment by bordercore** [comment]
Thanks for the info. I ended up running my own Elasticsearch on EC2 to get around the limitation rather than using Amazon Elasticsearch Service.
