### ISSUE TITLE
Elasticsearch.search() defines invalid default parameters

### ISSUE THREAD

**Issue by Godron629** [elastic/elasticsearch-py#1082]
https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L705

`Elasticsearch.search()` is defined as
```
    def search(self, index=None, body=None, params=None):
```

Yet is immediately iterated over, making `params=None` invalid.
```
        # from is a reserved word so it cannot be used, use from_ instead
        if "from_" in params:
            params["from"] = params.pop("from_")
```

**Comment by HonzaKral** [comment]
This is actually handled in the `query_params` decorator correctly: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L71
