### ISSUE TITLE
how to create watcher or logstash pipeline using python

### ISSUE THREAD

**Issue by yamamoto52** [elastic/elasticsearch-py#1084]
Is there any way to create watcher or logstash pipeline ? To do this I tried sth like this : 
es.indices.create(index='watcher/watch/test-index5', ignore=400) but '/' character is invalid

**Comment by HonzaKral** [comment]
to create a logstash pipeline simply index a document into the `.logstash` index. To create a watcher please use the `put_watch` api: `es.watcher.put_watch` (might be `es.xpack.watcher.put_watch` in older versions)

hope this helps!
