### ISSUE TITLE
max_reties > 0 sometimes causes duplicate data loaded into ES when TransportError happens

### ISSUE THREAD

**Issue by zealot-shin** [elastic/elasticsearch-py#1085]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.4.2, Build: default/rpm/2f90bbf7b93631e52bafb59b3b049cb44ec25e96/2019-10-28T20:40:44.881551Z, JVM: 13.0.1
**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 
>>> elasticsearch.__versionstr__
'7.1.0'
>>>
**Description of the problem including expected versus actual behavior**:
Using helpers.streaming_bulk with max_retries > 0 causes same data being bulk into es more than 1 time.

**Steps to reproduce**:
code example:

```python
es = Elasticsearch(
    [address.strip() for address in self.args["es_address"]],
    http_auth=(self.args['es_user'], self.args['es_pw']),
    sniff_on_start=self.args['sniff'], sniff_on_connection_fail=True,
    sniffer_timeout=self.args['sniffer_timeout'], retry_on_timeout=True, max_retries=3)

if es_data:
    exc_errors = []
    for ok, result in streaming_bulk(
            client=es, actions=self.gendata(es_data), request_timeout=30,
            chunk_size=self.args["chunk_size"], max_chunk_bytes=self.args["max_chunk_bytes"] * 1024 * 1024,
            raise_on_error=False, raise_on_exception=False, yield_ok=False):
        action, result = result.popitem()
        exc_errors.append({action: result})
        self.loger.error('Failed to %s document: %r' % (action, result))
```

Error log example：
```
[ERROR] Failed to index document: {'status': 'N/A', 'exception': TransportError('N/A', 'Unable to sniff hosts.'), 'error': "TransportError(N/A, 'Unable to sniff hosts.')", '_index': u'qtevent_3314_test', 'data': {u'host_memo': u'', u'datatime': 1550479616, 'uid': 0, 'ppname': u'tcp_status.sh', 'pid': 19132, u'group_name': u'\u963f\u91cc\u4e91\u4e1a\u52a1', 'uname': u'root', u'internal_ip': [u'10.26.248.74'], 'cmd': u'awk /SYN_RECV/{print $2} /tmp/tcp_status.txt', 'gname': u'root', u'comid': u'03ae0864a737143e3236', 'ppuid': 0, u'group': 668, 'severity': '0', 'id': 'a3e742b22af011ea8540000c29a370c8', 'ppuname': u'root', u'host_tag': [], 'ppid': 19129, u'type': 1, u'agent_ip': u'114.55.42.200', u'external_ip': [u'114.55.42.200'], 'pname': u'awk', u'agent_id': u'67ef6db638dc779e', 'path': u'/usr/bin/gawk', u'datatype': u'proc_create', u'host_name': u'go_mp_message04', 'euname': u'root', 'pppath': u'/usr/bin/bash', u'os': u'linux', 'euid': 0}, '_type': '_doc'}
```

**data with this log failed to being bulk into es, while some other data without error logs loaded into es triple times:**
```
GET test_idx/_search
{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "id": "55b194262af011eab988000c29a370c8"
        }
      }
    }
  }
}

reponse:
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "test_idx",
        "_type" : "_doc",
        "_id" : "QkthVm8B5c7WNuY7v4M3",
        "_score" : 0.0,
        "_source" : {
       ......
      }
    ]
  }
}
```

from what I've learnt from source code in elasticsearch-py, this TransportError is raised after 3 times retry set by es client parameter. I guess the same reason could explain why some data appear in es triple times. 

As to the code aspect, when exception happens,  _process_bulk_chunk_ wrap each data and the same exception together and return this tuple. It seems that in this case, data already loaded also return with error and then enter the retrying process. Thus duplicate data being saved into ES:
```
try:
        # send the actual request
        resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
    except TransportError as e:
        # default behavior - just propagate exception
        if raise_on_exception:
            raise e

        # if we are not propagating, mark all actions in current chunk as failed
        err_message = str(e)
        exc_errors = []

        for data in bulk_data:
            # collect all the information about failed actions
            op_type, action = data[0].copy().popitem()
            info = {"error": err_message, "status": e.status_code, "exception": e}
            if op_type != "delete":
                info["data"] = data[1]
            info.update(action)
            exc_errors.append({op_type: info})

        # emulate standard behavior for failed actions
        if raise_on_error:
            raise BulkIndexError(
                "%i document(s) failed to index." % len(exc_errors), exc_errors
            )
        else:
            for err in exc_errors:
                yield False, err
            return
```
Well, If I've got anything wrong, could u plz tell me.

**Comment by HonzaKral** [comment]
Thank you for a detailed report! It looks like something is interfering with Elasticsearch properly responding to you, or the communication just going through properly.

There are several options here, the most likely one is being cause by a timeout - since you specify `retry_on_timeout` set to `True` then, when a bulk is sent to Elasticsearch and the indexing doesn't finish in time, the client resends the same bulk. The first one is, however, *not* cancelled in Elasticsearch and will finish properly.

The ideal solution here is to not retry on timeout and make sure the cluster has enough capacity to process your bulk chunks in the time given by `timeout`, increase the timeout, or decrease the chunk size, if necessary.

Another approach (ideally use both together) is to control your `_id` values. That way a duplicate documents will overwrite the previous versions  instead of creating a copy.

Hope this helps!

**Comment by zealot-shin** [comment]
Thank u! This really helps
