### ISSUE TITLE
is there any possibility to work with ilm policies ?

### ISSUE THREAD

**Issue by yamamoto52** [elastic/elasticsearch-py#1088]
Is there anybpossibility to work with ilm policies ?

I'm looking for solution for sth similar like 'get _ilm/policy' or 'PUT _ilm/policy/my_policy' but nothing works.

My tries : 
```
body = {
    "policy": {
        "phases": {
        "warm": {
            "min_age": "10d",
            "actions": {
            "forcemerge": {
                "max_num_segments": 1
            }
            }
        },
        "delete": {
            "min_age": "30d",
            "actions": {
            "delete": {}
            }
        }
        }
    }
}

es.indices.create( index='_ilm/policy/'+policy_name,body=data )
```
output 
```
elasticsearch.exceptions.RequestError: RequestError(400, 'parse_exception', 'unknown key [policy] for create index')
```

or get 
```
es.indices.get("_ilm", "policy", "logstash-policy")
```

with output:
```
TypeError: get() got multiple values for argument 'params'
```

'Get' like this : es.indices.get("_ilm", "policy")  works correctly

**Comment by HonzaKral** [comment]
Depending on the version of the library you can do `es.ilm.get_lifecycle("logstash-policy")` or `es.expack.ilm.get_lifecycle("logstash-policy")`.

Hope this helps!

**Comment by yamamoto52** [comment]
works great, thanks!

**Comment by CR-MarkDavidov** [comment]
@yamamoto52 on what version of the elasticsearch client did you manage to get it working? 
@HonzaKral Maybe you know as well..

Thanks!
