### ISSUE TITLE
Warning _type when insert document

### ISSUE THREAD

**Issue by stegausaq** [elastic/elasticsearch-py#1091]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

**Comment by stegausaq** [comment]
{"type": "deprecation", "timestamp": "2020-01-09T10:10:34,724-05:00", "level": "WARN", "component": "o.e.d.r.a.d.RestDeleteAction", "cluster.name": "XXXELKQ", "node.name": "slqelk0315", "message": "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).", "cluster.uuid": "d-N9X7FUQFeGZOJdqmIxOA", "node.id": "J3JOH8tbTlKT5WYryxlouA"  }

**Comment by stegausaq** [comment]
# pip freeze
elasticsearch==7.1.0

# python --version
Python 3.6.3

Elastic version 7.x

**Comment by stegausaq** [comment]
Command : 
p_conn_cible.index(index=p_index_cible, id=f_document['_id'], body=l_source)

**Comment by stegausaq** [comment]
My document have "_type" : "_doc" and i don't want!

{'_index': 'test', '_type': '_doc', '_id': 'AW-LFmo6oEL_snFE2459', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 0, '_primary_term': 1}

**Comment by HonzaKral** [comment]
The deprecation message is from a different action as it is mentioning `RestDeleteAction`. The API you are using is correct and doesn't use types, you are seeing the default value of `_type` that is still left there for compatibility reasons, it is safe to ignore.

Hope this helps!
