### ISSUE TITLE
Bulk call don't support version and version_type field

### ISSUE THREAD

**Issue by Li-Shiang-Chi** [elastic/elasticsearch-py#1093]
```
@query_params(
        "_source",
        "_source_excludes",
        "_source_includes",
        "fields",
        "pipeline",
        "refresh",
        "routing",
        "timeout",
        "wait_for_active_shards",
    )
    def bulk(self, body, doc_type=None, index=None, params=None):
```

Posted from the source code, Can I know the reason of why query parameters don't support `version` or `version_type` field.

If don't support the version, all the es document will not encounter version conflict error and keep updating the document which bothers me a lot.

Or if I missing something, that each bulk item can actually specify `version` or `version_type` value.

Thanks for your help~

**Comment by marshallmain** [comment]
> Or if I missing something, that each bulk item can actually specify version or version_type value.

This is correct, each bulk item can individually specify a version and version_type.  Example: 
```
{ "index" : { "_index" : "test", "_id" : "1", "version_type": "external", "version": 3 } } 
{ "field1" : "value1" }
```
I based this example on https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk which has some additional information.
