### ISSUE TITLE
Timeout parameters are poorly documented

### ISSUE THREAD

**Issue by michelbl** [elastic/elasticsearch-py#1096]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.5

**Description of the problem including expected versus actual behavior**:

The ES API defines a parameter `timeout`: https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/indices.create.json#L29

This parameter is indeed documented (https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.create): "timeout – Explicit operation timeout".

The main ES doc is more precise (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#docs-index-api-query-params): "(Optional, time units) Specifies the period of time to wait for a response. If no response is received before the timeout expires, the request fails and returns an error. Defaults to 30s."

This parameter is indeed passed to transport, then to connection, then encoded in the url: https://github.com/elastic/elasticsearch-py/blob/7.5.0/elasticsearch/connection/http_urllib3.py#L212

However, there is another parameter, `request_timeout`. This parameter is undocumented and handled manually here:
* https://github.com/elastic/elasticsearch-py/blob/7.5.0/elasticsearch/transport.py#L343
* https://github.com/elastic/elasticsearch-py/blob/7.5.0/elasticsearch/client/utils.py#L81

To effectively increase the timeout, one should call `create` with `timeout='60s', request_timeout=60`.

**Steps to reproduce**: Make a create request with `timeout='60s'` against an unresponsive server. The request fails 10s later instead of 60s.

**Comment by HonzaKral** [comment]
The behavior of the different `*timeout` parameters is described in the `Global Options` sections of the docs (0). Unfortunately we do not have control over the API methods and/or documentation, that is all driven by the data in `Elasticsearch` repository, for example (1) so any issues against that text should be filed in the `elastic/elasticsearch` repo.

Apologies for the inconvenience.

0 - https://elasticsearch-py.readthedocs.io/en/master/api.html#timeout
1- https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/indices.create.json#L31
