### ISSUE TITLE
Generated API missing scripts_painless_context

### ISSUE THREAD

**Issue by adamchainz** [elastic/elasticsearch-py#1098]
**Elasticsearch version** (`bin/elasticsearch --version`): n/a

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.5.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

The `Elasticsearch.scripts_painless_context` method has gone missing in version 7.5.0 from the autogeneration PR #1083. Since it's not mentioned in the documentation I assume this was an oversight?

**Steps to reproduce**: n/a

**Comment by HonzaKral** [comment]
We implement all the APIs, including their names, as defined by the upstream project (0). If there are any APIs missing please feel free to open an issue in the Elasticsearch repo to add them to the documentation. I am sorry I cannot be of more help.

0 - https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api
