### ISSUE TITLE
Generated API changed argument order

### ISSUE THREAD

**Issue by adamchainz** [elastic/elasticsearch-py#1099]
**Elasticsearch version** (`bin/elasticsearch --version`): n/a

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.5.1

**Description of the problem including expected versus actual behavior**:

I have some tests that run `search()` with and without positional arguments: https://github.com/scoutapp/scout_apm_python/blob/master/tests/integration/instruments/test_elasticsearch.py#L153

It seems version 7.5.1 has changed the order of arguments, meaning positional usage fails.

Version 7.1.0:

```
$ pip install 'elasticsearch<7.5'
...
$ ipython
Python 3.8.1 (default, Jan 13 2020, 22:08:42)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import inspect, elasticsearch

In [2]: inspect.signature(elasticsearch.Elasticsearch.search)
Out[2]: <Signature (self, index=None, body=None, params=None)>
```

Version 7.5.1:

```
$ pip install 'elasticsearch==7.5.1'
...
$ ipython
Python 3.8.1 (default, Jan 13 2020, 22:08:42)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import inspect, elasticsearch

In [2]: inspect.signature(elasticsearch.Elasticsearch.search)
Out[2]: <Signature (self, body=None, index=None, doc_type=None, params=None)>
```

This should be fixed to be the same as before, as signature changes break code. This probably applies to all the generated methods.

**Comment by HonzaKral** [comment]
This is indeed correct, as the API evolves and different parameters are marked as required or optional by the upstream we reflect those changes in the code. This is a reason why we always recommended (0) to only use keyword arguments when dealing with elasticsearch. Unfortunately there is nothing much we can do until we get rid of python 2 support (not expected any time soon as we still have significant user base on 2.7) and can enforce keyword-only required arguments. Apologies for the inconvenience!

**Comment by adamchainz** [comment]
Okay. I think you should consider this a breaking change though. Users' applications that have relied on argument order due to missing the documentation note will fail on upgrading.

Also consider decorating all functions with @kwargs_only, a project I previously maintained to allow keyword-argument-only functions on Python 2: 
https://github.com/adamchainz/kwargs-only/blob/master/src/kwargs_only.py .
