### ISSUE TITLE
Unable to serialize empty sets

### ISSUE THREAD

**Issue by senglebpcyber** [elastic/elasticsearch-py#1103]
ElasticSearch Version: 7.5.1
Python: 3.8.0

After upgrading to version 7.5.1 from Version 7.1.0, empty sets are unable to be serialized. Receiving error: elasticsearch.exceptions.SerializationError: ...... TypeError("Unable to serialize set() (type: <class 'set'>)")

**Comment by sethmlarson** [comment]
Did empty sets previously serialize to an empty list? What did non-empty sets serialize to, arbitrary order lists?

**Comment by senglebpcyber** [comment]
Both serialized to a JSON array, I'm unsure if the order was strict or not.

**Comment by sethmlarson** [comment]
Going to close this as expected, sets should be transformed into ordered collections before serialization so we know we're not coercing a type into something it's not supposed to be.

If you need this behavior you can override the `JSONSerializer` to call `list()` on sets.
