### ISSUE TITLE
Update X-Pack enrich documentation 

### ISSUE THREAD

**Issue by gegen07** [elastic/elasticsearch-py#1107]
There's a plan to add Enrich section to ```docs/xpack.rst```?

**Comment by sethmlarson** [comment]
That's a great idea! Would you like to try tackling this issue?

**Comment by gegen07** [comment]
Yes, I'd like to contribute!

**Comment by sethmlarson** [comment]
@gegen07 That's awesome, thank you! Feel free to ping me if you run into any issues or have questions.

I'd recommend you sign our [Contributor Agreement](http://www.elastic.co/contributor-agreement/) and read the [`CONTRIBUTING.md`](https://github.com/elastic/elasticsearch-py/blob/master/CONTRIBUTING.md) document for guidance.
