### ISSUE TITLE
AttributeError: 'Elasticsearch' object has no attribute 'ccr' on WSL

### ISSUE THREAD

**Issue by glazou** [elastic/elasticsearch-py#1109]
**Python version**: 3.6
**elasticsearch-py version**: 7.5.1
**ElasticSearch Server version**: tested with 7.5.1, 7.5.2, 7.6 on Elastic Cloud

**Description of the problem including expected versus actual behavior**:

For about 10 days, on WSL Ubuntu 18.04 LTS, I get the following stack when creating an Elasticsearch object. It used to work before and it continues to work on Ubuntu machine.

```
 es = Elasticsearch(
        hosts="xxx",
        verify_certs=True,
        timeout=600,
        use_ssl=True,
        ca_certs=certifi.where()
    )
```

```
Traceback (most recent call last):
  File "export_main.py", line 32, in <module>
    es = connect_es()
  File "/mnt/c/Users/greg/dev/AS/as_export_elastic/lib/elasticsearch.py", line 16, in connect_es
    ca_certs=certifi.where()
  File "/home/greg/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 239, in __init__
    self.xpack = XPackClient(self)
  File "/home/greg/.local/lib/python3.6/site-packages/elasticsearch/client/xpack/__init__.py", line 44, in __init__
    setattr(self, namespace, getattr(self.client, namespace))
AttributeError: 'Elasticsearch' object has no attribute 'ccr'
```

[Found a workaround here](https://github.com/Yelp/elastalert/issues/2646)

Thanks

**Comment by sethmlarson** [comment]
`elasticsearch-py` doesn't have a `client/xpack/__init__.py` file as your traceback suggests, this leads me to believe you're probably not actually using `python -m pip install elasticsearch==7.5.1`. Could you try installing with the `==7.5.1` as before and see if that fixes the issue?
