### ISSUE TITLE
Unbounded generator for parallel_bulk 

### ISSUE THREAD

**Issue by victorcadena** [elastic/elasticsearch-py#1113]
I receive some messages from kafka and the generator I wrap up is unbounded, meaning that it wont stop yielding until the server is down or the connection with kafka goes down, and if messages are not available, I won't yield. Something like this

```
def message_generator(consumer: Consumer):
    while True:
        msg = consumer.poll(1.0)
        if msg is None: continue
        if msg.error():
            logging.warning(msg.error())
            continue
        message: dict = json.loads(msg.value().decode("utf-8"))
        message.document.update({"_index": message.index_name, "_type": message.document_type,
                                 "_id": message.document_id})
        yield message.document
```

The problem is that I don't see the same number of documents in Kafka and the ES Index. The problem is that I believe this line wont ever be reached 

[https://github.com/elastic/elasticsearch-py/blob/1a1ab99d9a2b0825f5c23db6aedcce75d4cbf794/elasticsearch/helpers/actions.py#L95](url)

Is there a way to parallel_bulk with an unbounded generator like kafka? Or is there a workaround?

I use the parallel_bulk as follows:
```        
for success, info in parallel_bulk(client=es, actions=message_generator(consumer), thread_count=10,
                                           chunk_size=750, raise_on_exception=True,queue_size=10):
            if not success:
                # handle error
```

**Comment by Sparkycz** [comment]
@victorcadena Did you try `streaming_bulk()`? It might just be a little bit slower because `streaming_bulk` uses only one thread of sending data, and `parallel_bulk` with arg `thread_count=10` sends data in 10 threads parallelly. But I think it does what you need.

**Comment by victorcadena** [comment]
We ended up using the `streaming_bulk` to not face this issue. Thanks @Sparkycz
