### ISSUE TITLE
A wrong warning is shown when creating a secured elasticsearch ssl (since 7.5.0)

### ISSUE THREAD

**Issue by yogevyuval** [elastic/elasticsearch-py#1115]
**Elasticsearch version** not relevant:

**`elasticsearch-py` version 7.5.1**: 

**When creating a secured elasticsearch ssl connection a warning is shown**:
```
http_urllib3.py:148: UserWarning: When using `ssl_context`, all other SSL related kwargs are ignored
  "When using `ssl_context`, all other SSL related kwargs are ignored"
```

This happens because the new `ssh_show_warn` parameter defaults to `True` but also is in the or statement that shows the above error. 

The warning is wrong, because we are only setting the ssl_context parameter and nothing else.

**Comment by sethmlarson** [comment]
Yep this looks incorrect, I'll make a PR to fix the issue.
