### ISSUE TITLE
Unexpected keyword argument 'filter_path' in method call

### ISSUE THREAD

**Issue by nightan42643** [elastic/elasticsearch-py#1119]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.5.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

I seem to be having a problem with pylint false positives.  Following is my code:
```
res = es.search(index="logstash-emailqueue", filter_path=["hits.hits._source.IPAddress"], body=body)
```
I used the keyword parameter filter_path and it worked as expected, but pylint suggested an error
```
Unexpected keyword argument 'filter_path' in method call
```
It does not affect the working of the code, but it is very uncomfortable.

**Steps to reproduce**:

**Comment by sethmlarson** [comment]
pylint is inspecting the function signature of `es.search()` which doesn't have the `filter_path` parameter defined directly in the function signature. Currently we're decorating API functions to add all parameters that are directly turned into URL query params, like `filter_path` so pylint doesn't recognize the parameter as valid.

I'd recommend disabling that pylint error on that line? In the future we're hoping to move to type stubs and then errors like this can be detected with mypy, pyre, etc.

**Comment by nightan42643** [comment]
Thank you!

I ignored the pylint code related to the error in my IDE configuration file, thanks again



-------- 原始邮件 --------
发件人： Seth Michael Larson <notifications@github.com>
日期： 2020年2月26日周三 晚上10:57
收件人： elastic/elasticsearch-py <elasticsearch-py@noreply.github.com>
抄送： nightan <xs-nightan@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [elastic/elasticsearch-py] Unexpected keyword argument 'filter_path' in method call (#1119)

pylint is inspecting the function signature of es.search() which doesn't have the filter_path parameter defined directly in the function signature. Currently we're decorating API functions to add all parameters that are directly turned into URL query params, like filter_path so pylint doesn't recognize the parameter as valid.

I'd recommend disabling that pylint error on that line? In the future we're hoping to move to type stubs and then errors like this can be detected with mypy, pyre, etc.

―
