### ISSUE TITLE
Request method for search API (GET or POST) should be selectable by users

### ISSUE THREAD

**Issue by mtatsuma** [elastic/elasticsearch-py#1146]
**Describe the feature**:

Current elasticsearch-py uses GET method to call search API.
The GET request contains a body and a non-zero Content-Length header, which is not common usage of GET requests.

I run into 411 Length Required response when I use elasticsearch-py to call search API via Squid proxy because Squid proxy does not allow GET requests with non-zero Content-Length header.

I've checked existing issues and understand the background to use GET method instead of POST described in commit https://github.com/elastic/elasticsearch-py/commit/619e7eb6b20824b9e00de8e1fe402b29c8e0e96d

So, the request method for search API should be selectable by users depending on their own environments.

Thanks you!

**Comment by sethmlarson** [comment]
That's unfortunate that Squid errors on GET requests with bodies. They're not in the wrong though via RFC 7231:

```
A payload within a GET request message has no defined semantics;
sending a payload body on a GET request might cause some existing
implementations to reject the request.
```

Maybe I can figure out if we can switch the method to a `POST` if that is an option allowed by the REST API and we expect a request body to accompany the request.

**Comment by sethmlarson** [comment]
For now you can use `send_get_body_as="POST"` as a work-around for this issue. However the team is discussing a more holistic fix as well. :)

```python
import elasticsearch

es = elasticsearch.Elasticsearch(
    ...,
    send_get_body_as="POST",
)
es.search(body=...)
```

**Comment by mtatsuma** [comment]
That's good and, for now, it's enough for me!

I did not find the option because the method is hard-coded in client method and it was unexpected that the method is overwritten in transport class.

As you mention it a work-around,  I also think it's possible to improve.
Thank you for your response. I close this issue.
