### ISSUE TITLE
elasticsearch6 6.8.0 clobbers previously installed elasticsearch

### ISSUE THREAD

**Issue by zachgoulet** [elastic/elasticsearch-py#1186]
**Elasticsearch version** (`bin/elasticsearch --version`): `6.8.0`

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: `6.8.0`

**Description of the problem including expected versus actual behavior**:

As of `elasticsearch6==6.8.0`, install `elasticsearch6` will clobber the existing installation of `elasticsearch`. Previously, `elasticsearch6` could be installed alongside `elasticsearch` without issue.

**Steps to reproduce**:

## `elasticsearch6<6.8.0`

```
$ pip install elasticsearch
...
Successfully installed elasticsearch-7.6.0 urllib3-1.25.8
$ pip freeze
elasticsearch==7.6.0
urllib3==1.25.8
$ python -c 'import elasticsearch; print(elasticsearch.__version__)'
(7, 6, 0)
$ pip install 'elasticsearch6<6.8.0'
...
Successfully installed elasticsearch6-6.4.2
$ pip freeze
elasticsearch==7.6.0
elasticsearch6==6.4.2
urllib3==1.25.8
$ python -c 'import elasticsearch; print(elasticsearch.__version__)'
(7, 6, 0)
```

## `elasticsearch6~=6.8`

```
$ pip install elasticsearch
...
Successfully installed elasticsearch-7.6.0 urllib3-1.25.8
$ pip freeze
elasticsearch==7.6.0
urllib3==1.25.8
$ python -c 'import elasticsearch; print(elasticsearch.__version__)'
(7, 6, 0)
$ pip install 'elasticsearch6~=6.8.0'
...
Successfully installed elasticsearch6-6.8.0
$ pip freeze
elasticsearch==7.6.0
elasticsearch6==6.8.0
urllib3==1.25.8
$ python -c 'import elasticsearch; print(elasticsearch.__version__)'
(6, 8, 0)
```

**Comment by sethmlarson** [comment]
Thanks for raising this.

Confirmed that the wheel specifically for `elasticsearch6` contains both `elasticsearch` and `elasticsearch6` namespaces. Will require a rerelease to fix this issue.

**Comment by sethmlarson** [comment]
I've release v6.8.1 to PyPI so this should be fixed.
