### ISSUE TITLE
How to check max_file_descriptors ?

### ISSUE THREAD

**Issue by rmrf** [elastic/elasticsearch-py#12]
I can use :

curl -s  'http://<hostname>:9200/_nodes?pretty=true&process=true'

to get max_file_descriptors, but still can't figure out how to get this information with ClusterClient.node_stats()

Thanks
-Ryan

**Comment by jaisharma639** [comment]
How do i check this in ES=2.4.0. When i try _nodes/process=true, i do not get this info.
