### ISSUE TITLE
Should 'fields' be a list or a string?

### ISSUE THREAD

**Issue by phill-tornroth** [elastic/elasticsearch-py#120]
The client args for the `fields` param says `A comma-separated list of fields to return as part of a hit`. That's not super clear, but suggests to me that it expects a string (since specifying the delimiter implies a pseudo-list encoded as a string. However, this argument seems passed-through to Elasticsearch and appears to work if I send a list here (`'fields': ['first_name', 'last_name']`), but not if I send a string (`'fields': "first_name,last_name"`).

Either way I think we'll have a change to make in haystack to support this feature because it's currently assuming the client wants a string containing a space-delimited list of fields [1]. I figured I'd confirm the expectations here before issuing a pull request over there. Thanks!

[1] https://github.com/toastdriven/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L275

**Comment by HonzaKral** [comment]
Closing this issue since it was answered.
