### ISSUE TITLE
Support for CBOR?

### ISSUE THREAD

**Issue by bordercore** [elastic/elasticsearch-py#1204]
Does this package support the CBOR binary format, as mentioned [here](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html)? And if not, would it be feasible to add it? I'd like to use it with the ingest plugin to avoid the overhead of base64 for large documents.

**Comment by sethmlarson** [comment]
Currently we only support CBOR if you provide a custom serializer or send raw CBOR binary data.
