### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [elastic/elasticsearch-py#1213]
Can i use this project with `~=` operator? Does it follow [Semantic versioning](https://semver.org)?
 
```
elasticsearch~=7.6.0
```

**Comment by sethmlarson** [comment]
Yes, this is laid out in our compatibility section: https://github.com/elastic/elasticsearch-py#compatibility
The Elastic stack follows semantic versioning, we follow Elasticsearch major.minor so we also follow semantic versioning.

If your Elasticsearch instance is v6 or v7 you should use the same major version of this package.
