### ISSUE TITLE
bearer token connections

### ISSUE THREAD

**Issue by ryandawsonuk** [elastic/elasticsearch-py#1221]
I've an elasticsearch configured that I can connect to with requests using header `Authorization` of the form `Bear <token>`. It is [installed on openshift and using its auth](https://github.com/openshift/elasticsearch-operator/issues/325). I can connect to it using `curl` but can't see any way to connect using the python client.

I see that the client has support for [ApiKeys](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html) but that is different. I've tried using the form `ApiKey <token>` and `ApiKey <base64encoded-token>` but can't successfully connect like that.

**Comment by sethmlarson** [comment]
You can set your own custom authorization headers on the `Elasticsearch` instance:

```python
from elasticsearch import Elasticsearch
es = Elasticsearch(..., headers={"authorization": "Bearer <token>"})
```

Does that solve your problem?

**Comment by ryandawsonuk** [comment]
Yep that's good thanks
