### ISSUE TITLE
Has elasticsearch-py-async been abandoned?

### ISSUE THREAD

**Issue by shadiramadan** [elastic/elasticsearch-py#1224]
See https://github.com/elastic/elasticsearch-py-async/issues/78

**Comment by sethmlarson** [comment]
I replied in #78, we're working towards merging proper async aupport into the `elasticsearch` package.

**Comment by stevepentland** [comment]
> I replied in #78, we're working towards merging proper async aupport into the `elasticsearch` package.

Hey @sethmlarson, I don't believe that link points to the proper spot? Appears to be about adding a segment `_cat` api.
