### ISSUE TITLE
Mixing courseware_index from 2 servers

### ISSUE THREAD

**Issue by eazaika** [elastic/elasticsearch-py#1225]
elasticsearch-py 1.9.0, python 2.7
There are 2 same servers in one subnet. Using for indexing online courses (open edX, hawthorn). When you Reindex course on first server it appears in courseware_index of second server. 
I have no idea how it happens

**Comment by sethmlarson** [comment]
This doesn't seem like reporting a defect in `elasticsearch-py`. Also v1.9.0 is no longer supported. Maybe you should check your configuration for the individual servers.

**Comment by eazaika** [comment]
Found special settings for elasticsearch.yml:
```
discovery.zen.ping.multicast.enabled: false
node.local: true
```
service elasticsearch restart
