### ISSUE TITLE
illegal_argument_exception in bulk upload 

### ISSUE THREAD

**Issue by aninda052** [elastic/elasticsearch-py#1237]
I'm facing problem while i try to use helpers.bulk . 
The error is :  {'index': {'_index': 'product', '_type': '_doc', '_id': '', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'if _id is specified it must not be empty'}, 'data': {'index': {'_type': '_doc'}}}}

I do not specified any _id in my data, because i'm using a pipeline for auto insert _id . If i use terminal for bulk upload, it doesn't give me any error 

Library Version : 7.7.0
Python Version : 3.6.9
Elasticsearch Version : 7.6.2
Hosted On : Local Host

**Comment by sethmlarson** [comment]
Could you provide more information such as library version, Python version, Elasticsearch version and where it is hosted, etc.

**Comment by aninda052** [comment]
Sorry i forget to mention all those things .

Library Version : 7.7.0
Python Version : 3.6.9
Elasticsearch Version : 7.6.2
Hosted On : Local Host

NOTE : if i use Elasticsearch.bulk() then it worked without any error

**Comment by sethmlarson** [comment]
So the issue here is that for some reason `_id` is empty. I don't think this would happen unless being supplied an empty ID, could you check your own code for this issue? Closing for now, let me know if this is still an issue.
