### ISSUE TITLE
ConnectionError(HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url

### ISSUE THREAD

**Issue by akash-agr** [elastic/elasticsearch-py#1239]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

**Comment by akash-agr** [comment]
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /keywords (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1109ffb50>: Failed to establish a new connection: [Errno 61] Connection refused'))) caused by: ConnectionError(HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /keywords (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1109ffb50>: Failed to establish a new connection: [Errno 61] Connection refused')))

**Comment by sethmlarson** [comment]
Without additional information I don't think I can help you beyond the error you're receiving.
The client is unable to create a connection for `host=locahost port=9200`, if the Elasticsearch instance is running on a different host or port you should use those to connect.
