### ISSUE TITLE
 Raising the thread_count when using parallel_bulk does not increase the speed of bulk insertion

### ISSUE THREAD

**Issue by taogeYT** [elastic/elasticsearch-py#1245]
elasticsearch version: 7.5.0
elasticsearch-py version: 7.5.1
python version: 3.7.4

i try to use helpers.parallel_bulk to bulk insert, but the speed of bulk insertion seems does not increase while i change thread_count from 1 to 8, it seems es client instance limit speed. then i use mutiprocess and create es client instance for each process,the speed of bulk insertion can increase
```
import time
from elasticsearch import Elasticsearch, helpers

def read_docs():
    with open("dst.txt") as f:
        for line in f:
            doc = dict(zip(("a", "b"), line.strip().split(",")))
            yield {"_index": "dst_test", "_source": doc}

docs = read_docs()
start = time.time()
es = Elasticsearch()
for _ in helpers.parallel_bulk(es, docs, thread_count=2):
    pass
print(time.time() - start)
```

**Comment by sethmlarson** [comment]
Increasing the number of threads doesn't automatically mean better performance. If any section of your pipeline is at capacity you won't see any further performance improvement, I recommend verifying where the bottleneck is first.

If your cluster can only handle indexing X documents per second you may need more nodes on your cluster, better hardware, better network connection, etc.

**Comment by taogeYT** [comment]
@sethmlarson I've considered what you' re saying, but in the same environment I can improve performance with multiple processes
```
import time
from multiprocessing import Pool
from elasticsearch import Elasticsearch, helpers

def read_batch_docs():
    cache = []
    with open("dst.txt") as f:
        for line in f:
            doc = dict(zip(("a", "b"), line.strip().split(",")))
            cache.append({"_index": "dst_test", "_source": doc})
            if len(cache) >= 10000:
                yield cache
                cache = []
        if cache:
            yield cache

def bulk_insert(docs):
    es = Elasticsearch()
    helpers.bulk(es, docs)

pool = Pool(4)
for batch in read_batch_docs():
    pool.apply_async(bulk_insert, args=(batch,))
pool.close()
pool.join()
```

**Comment by nchauhan5** [comment]
@taogeYT - Did you not face any issue with this multiprocessing pool.async where one process always returns a Serialization error like JSONDecodeError("Expecting ':' delimiter: line 1 column 8069 (char 8068)",)
