### ISSUE TITLE
python elasticsearch 获取数据总是缺少最新的数据。

### ISSUE THREAD

**Issue by tigerbin** [elastic/elasticsearch-py#1250]
python2.7    elasticsearch-6.8.1   elasticsearch-7.0.0  elasticsearch-7.7.0  都测试过了，获取数据总缺少最新的一条数据。
获取的hits的total比如是7，结果从python es拿到的是6条数据，直接curl 拿取数据正常。

**Comment by sethmlarson** [comment]
Have you tried in the latest version 7.7.1? `python -m pip install -U elasticsearch`
Can you provide the command you are running in Python and curl?

**Comment by tigerbin** [comment]
写入数据python                          
es = Elasticsearch(hosts=["192.168.1.130:9200"], timeout=500)
es.index(index="logdot_index",doc_type='logdot', body=inesdata)

查询数据：
curl 192.168.1.130:9200/logdot_index/_search -d '{"sort": [{"time": {"order": "desc"}}], "query": {"bool": {"filter": {"range": {"time": {"gte": "20200528 00:00:00", "lte": "20200528 23:59:59"}}}, "must": [{"match": {"username": "ssss1111"}}]}}, "from": 1, "size": 20}' -H "content-Type:application/json"

结果是：
![屏幕快照 2020-05-28 上午11 12 05](https://user-images.githubusercontent.com/13775090/83095111-37087200-a0d5-11ea-805a-f22dd78ec70b.png)
不知道是写入问题还是查询问题？显示有3条hit，但是只查到2条，实际应该有3条。

**Comment by sethmlarson** [comment]
I'm suspicious of the `"from": 1`, the from field starts at 0, could that be your issue?
See this doc: https://www.elastic.co/guide/en/elasticsearch/reference/7.7/search-request-body.html#request-body-search-from-size
