### ISSUE TITLE
create(**kwargs) doesn't work if document id is not provided 

### ISSUE THREAD

**Issue by DuoPegla** [elastic/elasticsearch-py#1262]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.7.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
Calling [create(**kwargs)](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.create) without providing a document Id causes an error when it should create a new document with autogenerated Id using POST method (instead of PUT).

Issue in [__init__.py](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py):

        for param in (index, id, body): # id should be removed from here
            if param in SKIP_IN_PATH:
                raise ValueError("Empty value passed for a required argument.")

        if doc_type in SKIP_IN_PATH:
            path = _make_path(index, "_create", id)
        else:
            path = _make_path(index, doc_type, id)

        return self.transport.perform_request(
            "POST" if id in SKIP_IN_PATH else "PUT", # calling "POST" instead of "PUT" is already implemented
            path,
            params=params,
            headers=headers,
            body=body,
        )

**Steps to reproduce**:
Call `create` method without providing a document Id and it will throw a `ValueError`

**Comment by sethmlarson** [comment]
Thanks for catching this, this is potentially an issue with the REST API spec and so the generator assumed that `id` was required. Will look into this further. A work-around would be to use `.index()` without a document `id` to create a document.

**Comment by sethmlarson** [comment]
So upon reading more it looks like the the `create` API the `id` is intentionally not optional and there is no issue here beyond maybe slightly confusing docs.

Here is what the Elasticsearch 7.7 docs say for "Index Document" API routes:
```
PUT /<index>/_doc/<_id>
POST /<index>/_doc/
PUT /<index>/_create/<_id>
POST /<index>/_create/<_id>
```

Notice that for `_create` there is no route without `id` but for `_doc` (index) there is an optional ID. This is a minor problem with the docs as below it does mention that `id` is "optional" but doesn't clarify that it's only optional for `_doc` / `index`. Is this how you ran into this case?

Closing this as not an issue.

**Comment by DuoPegla** [comment]
Thanks for the quick reply @sethmlarson!

Yes, you're right, I missed that difference in the docs.

My main issue is that I would like to create new documents with elasticsearch generating the ids. That doesn't seem possible with the current client or am I missing something?

**Comment by DuoPegla** [comment]
Thanks a lot! I must have missed that in the docs, just assumed given the name that `create` is the one I'm looking for.
