### ISSUE TITLE
Implement the 'contains', 'transform_and_set', and 'arbitrary_key' features

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch-py#1265]
We're missing three features for the REST API spec tests: `contains`, `transform_and_set`, and `arbitrary_key` for parity with upstream. We should implement these features so we can run all REST API spec tests.

There is a description of each feature here: https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/README.asciidoc

**Comment by V1NAY8** [comment]
@sethmlarson Any inputs on this change? I am thinking of trying this. :)

**Comment by sethmlarson** [comment]
@V1NAY8 That'd be awesome! Each of the features is documented within [this document](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/README.asciidoc). I'd recommend creating a PR for each one individually.

The easiest is likely `contains`. Look in `test_elasticsearch/test_server/test_rest_api_spec.py`, this is where the code should go. You would add a `run_contains` function to `YamlRunner` and then implement the functionality there. Does this help? :)

**Comment by V1NAY8** [comment]
Yep, It helps 😃
