### ISSUE TITLE
[7.7.1] DeprecationWarning types removal on es.exists_source

### ISSUE THREAD

**Issue by kate-tel** [elastic/elasticsearch-py#1270]
**Describe the feature**: es.exists_source returns False (however source exists) and ElasticsearchDeprecationWarning, however I don't specify type in my request.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.7.1

**Description of the problem including expected versus actual behavior**:
I have a document with a source, but when I call es.exists_source, it throws a DeprecationWarning and returns False, however True is expected.
On contrary, es.get_source successfully returns the source of the same document.

**Steps to reproduce**:
`es.index(index='s', id=1, body={'name':'Morty'}, refresh=True)
print(es.exists_source(index='s', id=1))`

return:

`ElasticsearchDeprecationWarning: [types removal] Specifying types in document get requests is deprecated, use the /{index}/_doc/{id} endpoint instead.
  print(es.exists_source(index='s', id=1))
False`

I can see that create, update, explain, get_source, and termvectors APIs were fixed in  #1253 release, but not exists_source.

Thanks in advance.

**Comment by sethmlarson** [comment]
@kate-tel Thanks for reporting this, I'll investigate and get a fix on the 7.x branches.

**Comment by kate-tel** [comment]
Thanks for a quick reply. Looking forward

**Comment by sethmlarson** [comment]
This was resolved in 7.8.0

**Comment by kate-tel** [comment]
Thank you!
