### ISSUE TITLE
Improve function of _escape

### ISSUE THREAD

**Issue by anhzhi** [elastic/elasticsearch-py#1271]
https://github.com/elastic/elasticsearch-py/blob/6df172d0410dfa65a3ce11ffe663cb8d4daab93a/elasticsearch/client/utils.py#L68-L69
```
    # make sequences into comma-separated stings
    if isinstance(value, (list, tuple)):
        value = ','.join(_escape()value)
```

**Comment by anhzhi** [comment]
https://github.com/elastic/elasticsearch-py/blob/6df172d0410dfa65a3ce11ffe663cb8d4daab93a/elasticsearch/client/utils.py#L120

```
 params = { key: _escape(value) for key, value in  (kwargs.pop("params", None) or {}).items()}
```

**Comment by sethmlarson** [comment]
This is done in 8.0.
