### ISSUE TITLE
Python Elasticsearch create index mapping

### ISSUE THREAD

**Issue by vignesh0710** [elastic/elasticsearch-py#1275]
`elasticsearch version - 7.7.0`

`elasticsearch-py version - (7,6,0)`

I am trying to create a ES index with custom mapping with elasticsearch python to increase the size of text in each document:

```
mapping = {"mapping":{
           "properties":{
             "Apple":{"type":"text","ignore_above":1000},
             "Mango":{"type":"text","ignore_above":1000}
           }
          }}

from elasticsearch import Elasticsearch
es1 = Elasticsearch([{"host":"localhost","port":9200}])
es1.indices.create(index="hello",body=mapping)
```

Error:

`RequestError: RequestError(400, 'mapper_parsing_exception', 'Mapping definition for [Apple] has unsupported parameters: [ignore_above : 10000]')`

Any suggestions on how to rectify this will be great.

**Comment by bichitra95** [comment]
Are you sure you want to use ignore_above? Because ignore_above is used to skip indexing the text after the ignore_above value in a string but you are trying here to increase the size of the text.

**Comment by sethmlarson** [comment]
Your issue here is that `ignore_above` is not supported for the `text` type. `ignore_above` is only supported for `keyword` types. To apply an `ignore_above` to a text field you can apply it to `text_field.keyword`:

```python
es = Elasticsearch("http://localhost:9200")
es.indices.create(
    index="test-index",
    body={
        "mappings": {
            "properties": {
                "kw_field": {
                    "type": "keyword",
                    "ignore_above": 100
                },
                "text_field": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "type": "keyword",
                            "ignore_above": 100
                        }
                    }
                }
            }
        }
    }
)
```
