### ISSUE TITLE
Migrate all rST code blocks from :: to code-block: python

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch-py#1287]
Our documentation has a mix of `::` and ` .. code-block: python`, we should migrate to all `code-block: python` so it's less confusing and more apparent when a code block is defined.

**Comment by mesejo** [comment]
@sethmlarson When trying to build the documentation using:  
`$ sphinx-build -b html ./docs/ ../output`

I get the following warning:

> WARNING: html_static_path entry '/home/daniel/PycharmProjects/elasticsearch-py/docs/_static' does not exist

And indeed when checking the `conf.py` file:

html_static_path = ["_static"]

Additionally I get:


> WARNING: autodoc: failed to import class 'DanglingIndicesClient' from module 'elasticsearch.client'; the following exception was raised:

The documentation seems to be generated nonetheless. Any idea on how to address these issues?

**Comment by sethmlarson** [comment]
@mesejo You can probably remove the `_static` if it's not being used. And the `DanglingIndicesClient` warning I'm not sure of, it looks like `DanglingIndicesClient` is imported into `elasticsearch.client`?

**Comment by mesejo** [comment]
Hey, thanks for your answer. It was a problem with the version, two more questions:
1. Is DeprecationClient still in version 8.0.0? Should it be remove from the xpack documentation? I get this warning: 

> WARNING: autodoc: failed to import class 'DeprecationClient' from module 'elasticsearch.client.deprecation'

2. The PR #1180 appears twice in the changelog in 7.7.0 and in 6.8.1, is this correct?

**Comment by sethmlarson** [comment]
1) Yes that client is removed in v8.0.0
2) You can remove the top reference since it's referenced twice.
