### ISSUE TITLE
Documents not appearing after bulk operation in Elasticsearch 7

### ISSUE THREAD

**Issue by minhtuev** [elastic/elasticsearch-py#1294]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

We are running our tests which query an index after creating and updating the index with documents.

However, we run into issues with a version of ES7 (7.7.1). Basically, it seems that in the pytest fixture where the index is being set up, the index has not finished processing when the tests start running. Hence, the tests are failing. This did not happen with an earlier version of Elasticsearch (5 & 6).

https://github.com/cisco/mindmeld/runs/802073981

Has anything changed in the backend? In our backend, we call `streaming_bulk` to update the index.

**Steps to reproduce**:
You can see our tests and ssh into the instances here:
https://github.com/cisco/mindmeld/pull/160

You can also fork the repo and modify the test matrix to change the ES version.

**Comment by sethmlarson** [comment]
Thanks for opening this.

How many documents are you indexing in the bulk operation?

I believe the `indices.refresh()` command doesn't actually wait for the refresh to complete, it only waits for the refresh to begin.
There is a parameter `refresh="wait_for"` which can be added to a `Elasticsearch.bulk()` call that will actually wait for the refresh to complete before returning success however this may be slow if applied to each operation within your bulk helper call depending on number of documents being indexed.

There should probably be a better way to say "hey I want to call `bulk()` many times without `refresh=X` and then on the last call to `bulk()` add `refresh=X`. I'll do some more digging here.

**Comment by minhtuev** [comment]
Ah thanks, I believe the behavior was caused by the change in the flush API call in ES7.
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#flush-force-merge-no-longer-refresh

```
In previous versions issuing a _flush or _force_merge (with flush=true) had the undocumented side-effect of refreshing the index which made new documents visible to searches and non-realtime GET operations. From now on these operations don’t have this side-effect anymore. To make documents visible an explicit _refresh call is needed unless the index is refreshed by the internal scheduler.

**Comment by sethmlarson** [comment]
FYI @minhtuev I mispoke when I said that the `indices.refresh()` API doesn't wait for documents to be available, apparently it does block until the refresh is completed.
