### ISSUE TITLE
Create snapshot for localhost:9200 hosted index cause error

### ISSUE THREAD

**Issue by JunhaoWang** [elastic/elasticsearch-py#1306]
**Elasticsearch 7.8.0**:

**`elasticsearch-py` version (`7.8.0`)**: 

**Create snapshot for localhost:9200 hosted index cause error**:

**Steps to reproduce**:
Have a test index hosted on localhost:9200, and curl works:
`curl localhost:9200/test` gives response

However, creating snapshot does not work:
`from elasticsearch import Elasticsearch; es = Elasticsearch()`
`es.snapshot.create_repository(repository='test', body={
            "type": "url",
            "settings": {
                "url": "localhost:9200/test"
            }
        })
`
`es.snapshot.create(repository='test, snapshot='test_v1')`

**error**
  File "<ipython-input-9-56f7a065f42a>", line 4, in <module>
    "url": "localhost:9200/politifact"
  File "/opt/anaconda3/envs/scrapy/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/anaconda3/envs/scrapy/lib/python3.7/site-packages/elasticsearch/client/snapshot.py", line 144, in create_repository
    body=body,
  File "/opt/anaconda3/envs/scrapy/lib/python3.7/site-packages/elasticsearch/transport.py", line 352, in perform_request
    timeout=timeout,
  File "/opt/anaconda3/envs/scrapy/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/anaconda3/envs/scrapy/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 288, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(500, 'repository_exception', '[train_articles] failed to create repository')

**Comment by bartier** [comment]
You should specify a explicit protocol in settings.url field when you define a repository:

```
es.snapshot.create_repository(repository='test',
                              body=
                              {
                                  "type": "url",
                                  "settings":
                                      {
                                          # Your code does not have http explicit here
                                          "url": "http://localhost:9200/test" 
                                      }
                              }
                              )
```

[See docs for more information](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html#snapshots-read-only-repository).

After this change the repository can be created.

**Comment by sethmlarson** [comment]
Thanks for answering this question @bar. Closing as this is not a defect with the library.
