### ISSUE TITLE
Option to return streaming data from API responses

### ISSUE THREAD

**Issue by lrowe** [elastic/elasticsearch-py#131]
For potentially large responses which are simply passed directly as a response from my application, I'd like to avoid the overhead of reading in the complete response body, decoding to a string, and parsing the JSON.

I think the best way to expose this would be as an option on `Transport.__init__` and extending `Connection.perform_request` with a `stream` parameter.

For `Urllib3HttpConnection.perform_request` this would call urlopen with `preload_content=False` and returning the `response.stream()` instead of `response.data`.

`Transport.perform_request` could then simply return the iterator instead calling the deserializer.

**Comment by grjones** [comment]
This would be incredibly handy especially as ES continues to move more into the analytics space with large data.  A little sad to see this was closed.

**Comment by HonzaKral** [comment]
Just to update the `scan` helper (0) now enables ordering so you can use it. 

Also implementing this is much easier now, just implement a different connection class (whose `perform_request` will just return a lazy object) and a serializer (that will wrap the lazy object in another layer providing deserializarion). Everything else will remain working unchanged.

0 - http://elasticsearch-py.readthedocs.io/en/master/helpers.html
