### ISSUE TITLE
No `put_mapping` attribute

### ISSUE THREAD

**Issue by JerzySpendel** [elastic/elasticsearch-py#1319]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.0
**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.7.1

**Description of the problem including expected versus actual behavior**:

When trying to access `put_mapping` method, I get:

`'Elasticsearch' object has no attribute 'put_mapping'`

**Steps to reproduce**:

1. Create instance of elasticsearch.Elasticsearch
2. Try to get `put_mapping` attribute of that instance

**Comment by sethmlarson** [comment]
Thanks for opening this.

The `put_mapping` API is under the `indices` namespace and would be accessed like this: `client.indices.put_mapping()`.
Is there somewhere in the documentation / online that this is incorrect and needs to be updated?

**Comment by JerzySpendel** [comment]
Ah, I think this should be separate pages for Elasticsearch, Indices, Ingest etc. I went to Elasticsearch page, searched for `put_mapping` and I got some results so I thought it's for Elasticsearch object and I didn't notice it was for Indices already.
