### ISSUE TITLE
SQL scan helper

### ISSUE THREAD

**Issue by jamesharr** [elastic/elasticsearch-py#1335]
**Describe the feature**: SQL support in `elasticsearch.helpers.scan` or a separate helper for scanning SQL queries.

I couldn't find a way to submit SQL through the standard `search` API, so I don't think it's possible to use the existing scan helper with SQL. That said, if it is possible it could be as simple as an example in documentation.

Certain queries are easier to express in SQL than native ElasticSearch DSL. I think SQL results are easier to iterate over in Python scripts in many cases as well. Specifically queries with more than a couple buckets / `GROUP BY` columns.

**Comment by sethmlarson** [comment]
You may find this project useful: https://pypi.org/project/elasticsearch-dbapi

**Comment by jamesharr** [comment]
I will definitely be checking this out, thank you. I think this covers my use case.

I'll leave this ticket open and let the elastic team decide if they want to implement this or not. I think there's potentially value to not requiring another dependency in client code.

**Comment by technige** [comment]
Closing this issue, as there are no plans to add this feature.
