### ISSUE TITLE
Define connection parameters using environment variables

### ISSUE THREAD

**Issue by arthurlogilab** [elastic/elasticsearch-py#1349]
**Describe the feature**:

With an increasing number of application being deployed using docker and kubernetes type solutions, a number of libraries provide ways to override some parameters with environment variables. It would be super nice if elasticsearch-py would do the same. 

In our use case, we're deploying an application that uses two extra layers on top of elasticsearch-py (elasticsearch-dsl and cubicweb-elasticsearch), and in a environment with the excellent Elastic Cloud Enterprise on premise we would have wished for having an `ELASTICSEARCH_VERIFY_CERTS` that we could have set to `False` to ignore https/ssl self-signed certs errors and deploy faster. 

Any chance of seeing such environment variables ?

**Comment by sethmlarson** [comment]
I'm hesitant to add environment variable config as it'd turn into needing environment variables for every config options. I recommend opening a feature request on the product wrapping the Elasticsearch libraries for the ability to turn off certificate verification.

**Comment by sethmlarson** [comment]
Going to close this because of above.
