### ISSUE TITLE
Support http_compress for RequestsHttpConnection on 6.x

### ISSUE THREAD

**Issue by bruceduhamel** [elastic/elasticsearch-py#1355]
**Elasticsearch version** AWS Elastic Search 6.3 R20200721:

**`elasticsearch-py` version 6.4.0**: 

In short, the http_compress argument for the Elasticsearch class doesn't work with AWS auth because the underlying RequestsHttpConnection connection_class doesn't do anything with the argument (unlike Urllib3HttpConnection).

The [elasticsearch-py documentation](https://elasticsearch-py.readthedocs.io/en/master/#compression) has the following snippet for configuring http compression so responses from the elastic search cluster may use gzip.

```
from elasticsearch import Elasticsearch
es = Elasticsearch(hosts, http_compress=True)
```

There's also a [section immediately following that in the elasticsearch-py documentation](https://elasticsearch-py.readthedocs.io/en/master/#running-on-aws-with-iam) which details how to handle AWS authentication:

```
from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

host = 'YOURHOST.us-east-1.es.amazonaws.com'
awsauth = AWS4Auth(YOUR_ACCESS_KEY, YOUR_SECRET_KEY, REGION, 'es')

es = Elasticsearch(
    hosts=[{'host': host, 'port': 443}],
    http_auth=awsauth,
    use_ssl=True,
    verify_certs=True,
    connection_class=RequestsHttpConnection
)
print(es.info())
```

I found that the http_compress argument is passed from the Elasticsearch constructor along to the connection_class constructor. This probably works as expected when the connection_class is Urllib3HttpConnection, but for AWS auth, the recommended connection_class is RequestsHttpConnection, which doesn't honor this constructor argument.

A work around for this issue is to pass the headers keyword argument to the Elasticsearch constructor as below:

```
es = Elasticsearch(
    hosts=[{'host': host, 'port': 443}],
    http_auth=awsauth,
    use_ssl=True,
    verify_certs=True,
    connection_class=RequestsHttpConnection,
    headers={
      'accept-encoding': 'gzip',
    }
)
```

I verified that without the work around, Wireshark shows non-compressed data in the elastic search cluster responses when http_compress is set to True. With the work around above, I verified the response content encoding was gzip.

**Comment by sethmlarson** [comment]
I would accept a PR backporting `http_compress` support to `RequestsHttpConnection`.

**Comment by bruceduhamel** [comment]
Thanks @sethmlarson I'll see if I can put a PR together, but it won't be this week.

**Comment by sethmlarson** [comment]
As far as I can tell 6.8.0 supports this option, comment and I'll reopen if this isn't the case.
