### ISSUE TITLE
Feature request: add source_address in Urllib3HttpConnection params

### ISSUE THREAD

**Issue by rom1sqr** [elastic/elasticsearch-py#1361]
as requested by the `CONTRIBUTING.md`: here is the feature request.

`urllib3` has the ability to establish a connection using a user-defined source ip address.
https://urllib3.readthedocs.io/en/latest/reference/index.html#module-urllib3.connection
the `Urllib3HttpConnection` initializing function does not let the user specify such an address.
i'm planning to push a Merge Request implementing this feature in a few minutes.

**Comment by sethmlarson** [comment]
Going to close this, use a custom HTTP connection for this case.
