### ISSUE TITLE
AWS IAM Connection goes stale (refreshable auth)

### ISSUE THREAD

**Issue by michaelfedell** [elastic/elasticsearch-py#1377]
**Describe the feature**:
Connection class for AWS IAM authentication that refreshes the auth object as needed.

**The Issue**:
Connecting to AWS Elasticsearch hosts requires use of RequestsHttpConnection and auth from [requests-aws4auth](https://pypi.org/project/requests-aws4auth/) generated by boto3 session credentials (this is detailed in the [client documentation](https://elasticsearch-py.readthedocs.io/en/master/#running-on-aws-with-iam)). These credentials have a short shelf-life and once they expire, the `AWS4Auth` object is no longer valid and all requests fail.

**Details**:
When deployed with AWS resources (EC2, ECS, etc.), the credentials returned by `boto3.Session().get_credentials()` are actually of the class [`RefreshableCredentials`](https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L353) meaning they can be checked for expiration and refreshed if needed. We can leverage this at the transport layer to implement an easy and convenient connection class which refreshes the auth object as needed. I've tested this in a deployed application and thought I'd share the idea/code here and will open a feedback if this ConnectionClass may be accepted to the client.
https://gist.github.com/michaelfedell/d45825b78711568acc92086842a2c50f

**Comment by sethmlarson** [comment]
I'd recommend your own custom `RequestHttpConnection` implementation here as this is very custom functionality that doesn't have much to do with Elasticsearch itself.
