### ISSUE TITLE
What is start_elasticsearch.sh?

### ISSUE THREAD

**Issue by bsolomon1124** [elastic/elasticsearch-py#1384]
The [tests readme](https://github.com/elastic/elasticsearch-py/tree/master/test_elasticsearch#run-elasticsearch-in-a-container) mentions running a `start_elasticsearch.sh` script that presumably runs a Docker container and exposes 9200. This script doesn't seem to be present in this repo or upstream elastic. Is that an outdated reference now replaced by the docker compose makefile step?

**Comment by sethmlarson** [comment]
That document is out of date slightly, the script has moved from there to `.ci/run-elasticsearch.sh`
