### ISSUE TITLE
Add note in Changelog about parameter ordering changes 6.x -> 7.x

### ISSUE THREAD

**Issue by daveisfera** [elastic/elasticsearch-py#1389]
We recently upgrade to ES 7 and a script that's worked for a long time started failing and we traced it back to the use `.count()` failing. Using the old `elasticsearch` 6.8.1 module works and we'll use that as a workaround, but it would be nice to be able to use the ES 7 module to match our cluster

**Elasticsearch version** (`bin/elasticsearch --version`): `Version: 7.9.1, Build: default/docker/083627f112ba94dffc1232e8b42b73492789ef91/2020-09-01T21:22:21.964974Z, JVM: 14.0.1`

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: `7.9.1`

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

1. Run `.count(index)` where `index` is the name of an index
2. Observe that an exception is raised

```
Traceback (most recent call last):
  File "test_es.py", line 104, in <module>
    sys.exit(main())
  File "test_es.py", line 74, in main
    total = es_conn.count(index)['count']
  File "/Users/dlj/.pyenv/versions/3.8.5/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Users/dlj/.pyenv/versions/3.8.5/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 528, in count
    return self.transport.perform_request(
  File "/Users/dlj/.pyenv/versions/3.8.5/lib/python3.8/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/Users/dlj/.pyenv/versions/3.8.5/lib/python3.8/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/dlj/.pyenv/versions/3.8.5/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/dlj/.pyenv/versions/3.8.5/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', 'Failed to parse')
```

**Comment by sethmlarson** [comment]
Try using `.count(index=name_of_index)`, the parameter order has changed between v6 and v7 to add `body`. For this reason we recommend using keywords arguments when parameters to APIs rather than positional arguments.

**Comment by daveisfera** [comment]
That feels like a very odd change, but it's done now, so could a call out about that **breaking change** be added to the the changelog?

**Comment by sethmlarson** [comment]
Previously the APIs were written by hand but starting in v7 and onwards they're generated from an API spec. This led to a handful of changes with parameter orders to make sure all APIs are the same order of required API parameters, body, optional API parameters, global parameters.

In the future this is unlikely to be a problem due to API generation but can be completely avoided by using keyword arguments which is [documented as a best practice](https://elasticsearch-py.readthedocs.io/en/master/api.html#api-documentation).

**Comment by daveisfera** [comment]
That's all well and good, but having a list of breaking changes in the changelog would be very helpful and would have prevented us from running into this issue at all

**Comment by sethmlarson** [comment]
I can add an entry to the changelog to highlight this change.

**Comment by daveisfera** [comment]
That would be great!

**Comment by itayB** [comment]
I'm considering upgrading our cluster as well.
Currently, we running with Elasticseach 6.3.0 and we want to upgrade to the latest 7.10. 
1. Can I use py-elasticseach 7 with Elasticsearch 6.3.0? (so I could first upgrade my code and then upgrade the cluster)
There are conflicts [here](https://elasticsearch-py.readthedocs.io/en/v7.10.1/#compatibility), from one hand:

> have to use a matching major version

> For Elasticsearch 6.0 and later, use the major version 6 (6.x.y) of the library.

and from the other hand:

```
# Elasticsearch 6.x
elasticsearch>=6.0.0,<7.0.0
```
2. Will you recommend waiting for Elasticsearch 8? will I be able to do the same? do you know what's the timeline for 8?
3. What's the recommended way to upgrade / rollout with no downtime?

**Comment by akramsystems** [comment]
I second this it would be helpful to know the changes required in updating from the 6.x -> 7.x  really difficult figuring out what the breaking changes are.  As i'm in the same situation as @itayB
