### ISSUE TITLE
.count, when using `request_cache` as a parameter results in an Exception being raised, yet results are present

### ISSUE THREAD

**Issue by ericandrewmeadows** [elastic/elasticsearch-py#1391]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.9.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

When using `request_cache=False`, I would expect count to hit the Elasticsearch endpoint; instead an Exception is raised

**Steps to reproduce**:
Set `request_cache=True`, and request to get count, and the following will result in an error.

```
es.count(index=self._index, body=d, **self._params)["count"]
---
/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py in _wrapped(*args, **kwargs)
    150                 if p in kwargs:
    151                     params[p] = kwargs.pop(p)
--> 152             return func(*args, params=params, headers=headers, **kwargs)
    153 
    154         return _wrapped

TypeError: count() got an unexpected keyword argument 'request_cache'
```

**Linked ticket:  https://github.com/elastic/elasticsearch-dsl-py/issues/1429**

**Comment by sethmlarson** [comment]
As far as I can tell from the [API specification for the Count API](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/count.json) `request_cache` isn't supported, where are you seeing that this is an option?

If desired you can pass in the value via `params={"request_cache": True}`.

**Comment by NavyaZaveri** [comment]
@sethmlarson  @ericandrewmeadows count queries seem to be cached by default [based on this answer ](https://stackoverflow.com/questions/63824680/elasticsearch-count-query-request-cache)

**Comment by sethmlarson** [comment]
Closing this as its been answered above I believe.
