### ISSUE TITLE
AsyncElasticsearch transport uses sniff_timeout instead of sniffer_timeout

### ISSUE THREAD

**Issue by HarrySky** [elastic/elasticsearch-py#1423]
We can see that in sync version of Elasticsearch transport everything is according to docs (if `sniffer_timeout` is set - we use it):
https://github.com/elastic/elasticsearch-py/blob/8106c0eefc023990a7bf7eb6bc3887bd815e41c4/elasticsearch/transport.py#L227

But when we see async version - there is a typo (`sniff_timeout` is used instead of `sniffer_timeout`)
https://github.com/elastic/elasticsearch-py/blob/8106c0eefc023990a7bf7eb6bc3887bd815e41c4/elasticsearch/_async/transport.py#L135

Can send the PR to fix this if it is not intentional.

**Comment by sethmlarson** [comment]
@HarrySky Nice catch, this wasn't intentional. If you'd like to open a PR to fix this issue that'd be great.

**Comment by HarrySky** [comment]
@sethmlarson yes, here it is #1426 :smile:
