### ISSUE TITLE
`send_get_body_as` ignored in 7.6.0 and above

### ISSUE THREAD

**Issue by recvfrom** [elastic/elasticsearch-py#1432]
**Elasticsearch version** (`bin/elasticsearch --version`): unknown

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.10.0, but problem was introduced in 7.6.0

Please make sure the major version matches the Elasticsearch server you are running.

Using the following script:
```
from elasticsearch import Elasticsearch
import logging
import os
logging.basicConfig()
logging.getLogger('elasticsearch').setLevel(logging.DEBUG)
logging.getLogger('urllib3').setLevel(logging.DEBUG)

es = Elasticsearch([<URL>],port=443,send_get_body_as='GET',use_ssl=True,verify_certs=True,timeout=90)

body = \
{
...
}

res = es.search(index = <INDEX>, body=body, size=0, request_timeout=90, params={'api_key': os.environ["API_KEY"]})
...
```

In 7.5.1 and below, the script would issue the ES query via GET:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): <URL>:443
DEBUG:urllib3.connectionpool:https://<URL> "GET /<INDEX>/_search?api_key=<APIKEY>&size=0 HTTP/1.1" 200 314
INFO:elasticsearch:GET https://<URL>/<INDEX>/_search?api_key=<APIKEY>&size=0 [status:200 request:14.373s]
...
```

With 7.6.0 and above:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): <URL>:443
DEBUG:urllib3.connectionpool:https://<URL> "POST /<INDEX>/_search?api_key=<APIKEY>&size=0 HTTP/1.1" 404 1488
WARNING:elasticsearch:POST https://<URL>/<INDEX>/_search?api_key=<APIKEY>&size=0 [status:404 request:0.599s]
```

It seems that the Elasticsearch library is ignoring the `send_get_body_as` parameter?

**Comment by sethmlarson** [comment]
This is expected, instead of using `GET` with a body which is non-compliant with HTTP we send `POST` if the API endpoint supports using `POST`. Currently all endpoints which use a body support using `POST` in addition to `GET` so this basically removes needing to configure `send_get_body_as` and you'll get correct behavior by default.

All other clients were already doing this transformation pre-7.6.0.

**Comment by recvfrom** [comment]
@sethmlarson thanks for the feedback. In our case the Elasticsearch server is behind a firewall that blocks `POST` requests, so we were using `send_get_body_as` to force sending as a `GET` request.  Seeing as how no one else seems to have opened a bug report for this, I'll assume it's a pretty unusual case.
