### ISSUE TITLE
can not connect to Elasticsearch by nginx

### ISSUE THREAD

**Issue by josh7** [elastic/elasticsearch-py#1476]
## nginx conf

I have four nodes. Three nodes is for es data. The last node is for nginx.

```
upstream es {
    server es_1:9200;
    server es_2:9200;
    server es_3:9200;
}

server {
    listen 9200;
    server_name nginx_ip;

    location = / {
        proxy_pass  http://es;
    }
}
```

## connect Elasticsearch fail

```
es_url='http://nginx_ip:9200'
es = Elasticsearch(es_url, http_auth=(es_user, es_pwd)) 
not fund error
```

**Comment by dougbyrne** [comment]
That might be a nginx config issue. `location = /` is an exact match. `curl http://nginx_ip:9200` works, but what about other paths like `curl http://nginx_ip:9200/_search`?

**Comment by sethmlarson** [comment]
Sorry for replying to this so early. What error are you receiving, can you post a traceback? Since this is likely a config issue I'm closing this until you reply and show there's an issue with the library instead of the configuration.
