### ISSUE TITLE
Bulk helper: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by sfornengo** [elastic/elasticsearch-py#1481]
**Elasticsearch version**:  7.10.1
**elasticsearch-py version **:  (7,10,1)

Following the helpers with  doc https://elasticsearch-py.readthedocs.io/en/v7.10.1/helpers.html I wrote the following code:
```
    def index():
        for folder in folders:
            for name in os.listdir(folder):
                att=AttParser(folder+name)
                att.flatten()
                for d in att.flatten_data:
                    yield {
                        '_index':'att',
                        '_op_type':'index',
                        '_source':d,
                    }
    for success, info in bulk(es,index()):
        if not success:
            print('document failed:', info)
```
It works untils the end of the data where it fails with the following error:
```
    for success, info in bulk(es,index()):
TypeError: cannot unpack non-iterable int object
```
Saying that bulk() does not always return (success, info) but sometimes only an int object...

**Comment by sethmlarson** [comment]
You're confusing `bulk` behavior with `streaming_bulk`, `bulk` calls `streaming_bulk` internally and aggregates all the results into numbers. Try changing `bulk()` in your code to `streaming_bulk()`.

I don't see that exact example in the helper documentation? Can you point to a specific section?

**Comment by sfornengo** [comment]
Oh sorry, I was inspired by the first example of parallel_bulk() here: https://elasticsearch-py.readthedocs.io/en/v7.10.1/helpers.html
```
for success, info in parallel_bulk(...):
if not success:
    print('A document failed:', info)
```
And misreading the code of bulk() here: https://github.com/elastic/elasticsearch-py/blob/v7.10.1/elasticsearch/helpers/actions.py I was thinking that bulk() return a tuple too:
`return success, failed if stats_only else errors `
