### ISSUE TITLE
[feature request] support change http_compress level.

### ISSUE THREAD

**Issue by yumendy** [elastic/elasticsearch-py#1492]
**Describe the feature**:  

The http_compress argument for the Elasticsearch class  uses **_COMPRESS_LEVEL_BEST** by default.  I want to change it according to the need.

**Comment by sethmlarson** [comment]
To accomplish this you can subclass `Urllib3HttpConnection` and change the `_gzip_compress()` method? I don't think this is a common enough use-case to warrant its own config option.

**Comment by yumendy** [comment]
> To accomplish this you can subclass `Urllib3HttpConnection` and change the `_gzip_compress()` method? I don't think this is a common enough use-case to warrant its own config option. Request bodies are so small there is likely very little difference between compression levels.

Thank you for your reply.

We use 8000 cores for log preprocessing and write to ES. It took us about 800Gbps of bandwidth. Therefore, we need to enable Gzip compression to save bandwidth costs.

We tested different levels to balance CPU usage and outbound bandwidth. 

Compared with level 1,using the default level 9 only improves the compression rate by 4.7% but it takes almost 4 times cores to compress data.

There is very little diference in data size, but huge difference in CPU usage.  

SO, I post this issue and hope that our users can choose the compression level that suits them according to their needs.

**Comment by sethmlarson** [comment]
Declining support for this feature, see https://github.com/elastic/elasticsearch-py/pull/1494#issuecomment-788092292 for explanation.
