### ISSUE TITLE
Scroll signature is confused, and not matching with documentation

### ISSUE THREAD

**Issue by EmilBode** [elastic/elasticsearch-py#1501]
**Elasticsearch version**: 7.9.1 and others (all major version 7)

**`elasticsearch-py` version**: 7.9.1

**Description of the problem including expected versus actual behavior**:
The actual behaviour with regard to searching ES is fine, but there is some inconsistent behaviour on the signature and documentation regarding the arguments that can be passed on to `scroll`.

Note sure what information comes from where, but I noted:
- When working in Anaconda Spyder, when bringing up the (partly auto-generated) documentation, this starts with the signature `scroll(*args, **kwargs)`
- When trying to type in a `scroll`-command, the autocomplete suggests I can use the keyword-arguments `body`, `scroll_id`, `params` and `headers`.
- The pydoc itself gives possible arguments `body`, `scroll_id`, `rest_total_hits_as_int`, and `scroll`.
- In the python-code itself (`elasticsearch/client/__init__.py`), I find the signature with (like in the autocomplete) `body`, `scroll_id`, `params` and `headers`.
- Actually calling the code works fine with a parameter `scroll` (with a value of e.g. `5m`)
- However, having code with a parameter `scroll` in a method *does* generate a warning from pylint: `E1123: Unexpected keyword argument 'scroll' in method call (unexpected-keyword-arg)`

**Steps to reproduce**:
```
import elasticsearch as es
my_es = es.Elasticsearch('localhost:9200')
my_search = my_es.search({'query': {'match_all': {}}}, scroll='5m')
my_next_results = my_es.scroll(scroll_id=my_search['scroll_id'], scroll='5m') # Works fine, even though not according to signature

**Comment by sethmlarson** [comment]
The defined function signature doesn't have the parameter, however the type hint (released in v7.10) contains the proper signature. Try upgrading to the latest version. I'm not sure if pylint takes into account type hints, if not you may consider disabling that error in favor of using a tool like mypy which takes into account type hints.

Let me know if this answers your question.
