### ISSUE TITLE
Python True is not converted to JSON true, should it be?

### ISSUE THREAD

**Issue by int-ua** [elastic/elasticsearch-py#1503]
**Describe the feature**:

At least when calling `IndicesClient.delete` with `params={'ignore_unavailable': True}` it doesn't understand the `True` and requires it to be exactly `'true'` with the error: 

```
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Could not convert [ignore_unavailable] to boolean')
...
elasticsearch: DEBUG: < {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Could not convert [ignore_unavailable] to boolean"}],"type":"illegal_argument_exception","reason":"Could not convert [ignore_unavailable] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [True] as only [true] or [false] are allowed."}},"status":400}
```

It seems reasonable for the Python API to understand Python booleans, no?

**Comment by sethmlarson** [comment]
Booleans are automatically converted for any known query parameter (ie `indices.delete(ignore_unavailable=True)`) however the `params` option is different in that it allows 100% custom inputs so doesn't modify anything in case that's actually what you wanted. I'd recommend only using `str` for values in `params`.
