### ISSUE TITLE
Client for Kibana 

### ISSUE THREAD

**Issue by SelAnt** [elastic/elasticsearch-py#1534]
**Client to call Kibana REST API (similar way like ES REST API)**:

Kibana offers APIs to work with Saved Objects. It would be nice to be able to manipulate these objects from Python scripts. It allows, for example, find an existing Index Pattern and create a Visualization for it.

**Comment by sethmlarson** [comment]
Thanks for opening this.

This project is specifically for Elasticsearch so won't be implementing Kibana REST APIs. There is a roadmap item to eventually have clients for all services but there is no timeline for it at this time. Closing this issue for now.
