### ISSUE TITLE
7.11.0: no test suite?

### ISSUE THREAD

**Issue by kloczek** [elastic/elasticsearch-py#1539]
I've been trying "python3 setup.py test", pytest and tox and looks like there is no at all any test units.
How can I test elasticsearch-py during packaging?

**Comment by sethmlarson** [comment]
The test suite hasn't been included in the package for [at least 8 years](https://github.com/elastic/elasticsearch-py/blame/master/MANIFEST.in#L13). I recommend cloning the repository itself to access the test suite.
