### ISSUE TITLE
parallel_bulk does not insert the last bulk when it's not full ?

### ISSUE THREAD

**Issue by trantheanh** [elastic/elasticsearch-py#1548]
**Describe the feature**:
I've read the code of parallel_bulk (version 7.11.0). As the title, it seems not help processing the last bulk if it not full

**Comment by Sparkycz** [comment]
I've checked the process of `helpers.parallel_bulk()` by updating locally the test https://github.com/elastic/elasticsearch-py/blob/master/test_elasticsearch/test_helpers.py#L55 and it works correctly. I recommend closing the issue.
