### ISSUE TITLE
My fix  for allowing for Non-English text data("utf-8" encoding problem) to be uploaded to Elasticsearch Database

### ISSUE THREAD

**Issue by Anirudh42** [elastic/elasticsearch-py#1550]
**Describe the feature**:

My Fix to allow for the upload of text data other than english to support special characters which cannot be encoded with the standard "utf-8" encoding.

If this issue is not already addressed either I could create a pull request or you can update it. 

**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:7.10.2 

**Description of the problem including expected versus actual behavior**:
I have tried to upload data containing text with a different language. If lets say it is german, french or any other language these languages have some special characters like "è" or something else. When I was about to upload it I received the error 
**UnicodeEncodeError: 'utf-8' codec can't encode characters in position 67-69: surrogates not allowed**.
I fixed this issue by going `elasticsearch/helpers/actions.py` and changing the part where it says "utf-8" to "unicode-escape".

**Steps to reproduce**:
You can upload any non-english text data and check

**Comment by sethmlarson** [comment]
It's likely that your data includes unicode surrogates based on the error and the `.encode()` call isn't handling them. Could you try changing the `.encode("utf-8")` into `.encode("utf-8", "surrogatepass")`  and see if that indexes the data as you expect?

**Comment by Anirudh42** [comment]
Ok I will check this and get back to you soon.

**Comment by sethmlarson** [comment]
Haven't heard back in a while, closing for now. Let me know if you have more to add here.
