### ISSUE TITLE
AsyncElasticsearch does not support client_cert & client_key

### ISSUE THREAD

**Issue by joshblease** [elastic/elasticsearch-py#1557]
**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.12.0

**Description of the problem including expected versus actual behavior**:

I would expect this to work given the ElasticSeach cluster is healthy and the certificates are correct.

```
es = AsyncElasticsearch(
    ['host'],
    use_ssl=True,
    verify_certs=True,
    ca_certs='./ca.crt',
    client_cert='./admin.crt',
    client_key='./admin.key'
)
```

However, it results in a 401 error and instead I have to manually create the ssl context

```
cont = ssl.SSLContext(ssl.PROTOCOL_TLS)
cont.load_verify_locations(cafile="./ca.crt")
cont.load_cert_chain("./admin.crt", "./admin.key")

es = AsyncElasticsearch(
    ['host'],
    use_ssl=True,
    verify_certs=True,
    ssl_context=cont
)
```

**Comment by sethmlarson** [comment]
Yeah, looks like `AIOHttpConnection` doesn't use these parameters. This shouldn't be a tough fix, would you like to attempt it?
