### ISSUE TITLE
AsyncElasticsearch client not accepting AWS auth keys

### ISSUE THREAD

**Issue by harshit98** [elastic/elasticsearch-py#1567]
**Describe the feature**: Async Elasticsearch client.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.9

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: `elasticsearch[async]==7.12.0`

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

Not able to initialise Async Elasticsearch client using AWS4Auth library (used in AWS ES client Python examples)

It should successfully connect with the client. However, it gives me this error:

```
AttributeError: 'AWS4Auth' object has no attribute 'encode'
```  

**Steps to reproduce**:

Sharing the code snippet:

```python
from elasticsearch import AsyncElasticsearch, AIOHttpConnection
from requests_aws4auth import AWS4Auth
import asyncio

host = 'my-test-domain.us-east-1.es.amazonaws.com'
region = 'us-east-1'
service = 'es'

credentials = {
    'access_key': <MY_ACCESS_KEY>,
    'secret_key': <MY_SECRET_KEY>
}

awsauth = AWS4Auth(credentials['access_key'], credentials['secret_key'], region, service)

es = AsyncElasticsearch(
    hosts=[{'host': host, 'port': 443}],
    http_auth=awsauth,
    use_ssl=True,
    verify_certs=True,
    connection_class=AIOHttpConnection
)

async def test():
    print(await es.info())

asyncio.run(test())
```

**Comment by sethmlarson** [comment]
`AWS4Auth` isn't designed to be used with `AIOHttpConnection`, it only works with `RequestsHttpConnection`.

**Comment by harshit98** [comment]
@sethmlarson Any package recommendation? - Which AWS signer should I use to support `AIOHttpConnection` connection class ?

**Comment by AchuthAnderson** [comment]
then how can we use AIOHttpConnection with Async elastic search?

**Comment by gangaTR** [comment]
Please reopen this ticket and help in knowing the answer asked above.
