### ISSUE TITLE
transport.perform_request() - *timeout params type inconsistency

### ISSUE THREAD

**Issue by Sparkycz** [elastic/elasticsearch-py#1569]
There is type inconsistency among *timeout (`request_timeout`, `timeout`, `master_timeout) parameters. 
`request_timeout` supposed to be `integer` but `timeout` and `master_timeout` supposed to be time units in string.

Documentation of the python library API says nothing about these arguments' types https://elasticsearch-py.readthedocs.io/en/v7.12.0/api.html#elasticsearch.client.IndicesClient.create
Documentation of the ES API says about `timeout` and `master_timeout` type https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-query-params

Incoming arguments are checked by https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/indices.pyi#L77-L94 but at `timeout` and `master_timeout` is `Any` as a type.

My preferred solution:
Update the incoming argument `request_timeout` to consume also string (time units), and transform the string value to integer in this point https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L464 .

Additional feature no.1: It might be great to update the python lib API (add types of arguments). However, I can imagine it's a big issue..
Additional feature no.2 Merge `request_timeout` and `timeout` arguments because they're very similar to each other. The difference is only `request_timeout` is timeout on the client-side and `timeout` on server-side but checks the same (response time). The `request_timeout` is also automagically overwritten in https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L464 to `timeout` variable and it may also cause misunderstanding..

**Comment by sethmlarson** [comment]
This has been fixed in elastic-transport-python which will be used in 8.0.
