### ISSUE TITLE
New ConnectionError [Errno 111] Connection Refused using Google Colab ( Python )

### ISSUE THREAD

**Issue by MOPARTHISATISH69** [elastic/elasticsearch-py#1570]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

**Comment by sethmlarson** [comment]
This bug report doesn't have enough information to go on, if you could provide more information I may be able to help.
