### ISSUE TITLE
Broken URL within helpers documentation

### ISSUE THREAD

**Issue by zhbzhbzhbz** [elastic/elasticsearch-py#1574]
In this page, https://elasticsearch-py.readthedocs.io/en/v7.12.0/helpers.html#example

> For a more complete and complex example please take a look at https://github.com/elastic/elasticsearch-py/blob/master/example/load.py#L76-L130

The load.py may have been move to https://github.com/elastic/elasticsearch-py/blob/master/examples/bulk-ingest/bulk-ingest.py ?

**Comment by sethmlarson** [comment]
Yep, this looks like a fine documentation update to make, would you be interested in contributing this change?
