### ISSUE TITLE
ES <= 7.10 Watchers : Doesn't handle the version dependencies

### ISSUE THREAD

**Issue by munavirch** [elastic/elasticsearch-py#1588]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.10

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.12.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**: ES doesn't have `/_watcher/_query/watches` endpoint till 7.11. But the client, even if the ES version is < 7.11, tries to send request to the same endpoint resulting in below error.
`elasticsearch.exceptions.RequestError: RequestError(400, 'invalid_index_name_exception', "Invalid index name [_watcher], must not start with '_', '-', or '+'")`

**Steps to reproduce**:
1. Make sure the ES version >7 and <7.11
2. Execute `es.xpack.client.watcher.query_watches()`

**Comment by sethmlarson** [comment]
If I understand your situation properly then this is expected. You're trying to query an API that's only available in Elasticsearch 7.11+ but your Elasticsearch service version is 7.10 so the error is correct. Try upgrading your service to 7.11+ and everything will work fine.

If this doesn't answer your question let me know.
