### ISSUE TITLE
Fully synchronous write to an index

### ISSUE THREAD

**Issue by d4nielfr4nco** [elastic/elasticsearch-py#1591]
I'm not totally sure if this feature is already implemented, but I'll explain my use case.

I'm using an index to control the flow of an application. In short, this application needs to write information into the index, so then it can read this information to continue its flow.

I used the bulk helper and index API, which seems to be synchronous. However, they return before the write takes place in the index. This causes problems to the flow of my application, because it reads the index before the write is complete.

Is there a way to do a fully synchronous write in an index using this lib?

**Comment by sethmlarson** [comment]
Thanks for opening this. The concept you're looking for is called "[refresh](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html)" and is callable directly via the `indices.refresh()` API.

There are two ways to implement this, if you're trying to make sure all indexed documents from the entire bulk session are available at the end of the session or if you're trying to make sure each individual document is available once it's status is yielded by `streaming_bulk`.

#### Example 1: All indexed documents are available after bulk()

```python
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk

index = "example-index"
documents = [...]
client = Elasticsearch(...)

# Index all the documents
bulk(client=client, actions=documents, index=index)

# Refresh the index afterwards
client.indices.refresh(indices=index)
```

#### Example 2: Indexed documents available after yield during streaming_bulk()

You'll have to be careful with this implementation as each call to `bulk` will include an internal
call to `refresh` which will hurt your ingest performance a lot.

```python
from elasticsearch import Elasticsearch
from elasticsearch.helpers import streaming_bulk

index = "example-index"
documents = [...]
client = Elasticsearch(...)

# Index all the documents
for ok, action in streaming_bulk(client=client, actions=documents, index=index, refresh=True):
    # Within this context the document is indexed and available in Elasticsearch
```

Does this answer your question?

**Comment by d4nielfr4nco** [comment]
Yes, I was able to get what I wanted after I did the refresh. Thank you very much.
