### ISSUE TITLE
Helpers.bulk_index exception

### ISSUE THREAD

**Issue by Benoss** [elastic/elasticsearch-py#16]
When I am trying to do a bulk loading with a bad index config I get this error

```
  File "......./src/common/ElasticUtils.py", line 37, in csv_to_index
    helpers.bulk_index(self.es, document_iterator())
  File "......./local/lib/python2.7/site-packages/elasticsearch/helpers.py", line 66, in bulk_index
    if item[act]['ok']:
KeyError: 'ok'
```

If I print "item"

``` javascript
{
    'create':{
        '_type':'listing',
        '_id':'zsuuZ0QlTvGQiikD0t8KYw',
        'error':'IllegalArgumentException[enablePositionIncrements=false is not supported anymore as of Lucene 4.4 as it can create broken token streams]',
        '_index':'test'
    }
}
```

Looks like there is no Key 'ok' at all when an error is returned by Elasticsearch in this case

**Comment by NTAbraham** [comment]
src/espcap.py --file=test_pcaps/test2.pcap --node=localhost:9200
Loading packet capture file(s)
test_pcaps/test2.pcap
[ERROR]  (u'306 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k6_', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7Q', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7d', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7q', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7r', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7t', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7u', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7v', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7w', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'st



I still am getting this error and I cannot tell why? please can you help!

**Comment by HonzaKral** [comment]
@NTAbraham - the reason is mentioned in the response - `{u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}`

Elasticsearch limits the number of fields in a type to avoid users overwhelming the cluster which your data exceeds
