### ISSUE TITLE
Add warning/traceback error for AsyncElasticsearch importError when aiohttp is not installed

### ISSUE THREAD

**Issue by cmutrufflepig** [elastic/elasticsearch-py#1603]
Not sure this counts as a bug or a feature request. But currently if you try to import AsyncElasticsearch without aiohttp installed (maybe other packages can cause similar behavior, but I found it with aiohttp) It just report ImportError with no additional info which is hard to solve. 

If anything happens during import, it silently passes.
https://github.com/elastic/elasticsearch-py/blob/v7.13.1/elasticsearch/__init__.py#L103

**Elasticsearch version**  n/a
**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: all versions

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
```
pip uninstall aiohttp
from elasticsearch import AsyncElasticsearch
```

**Comment by cmutrufflepig** [comment]
Oh, and installing elasticsearch doesn't require aiohttp, just making it a requirement will solve this too.

**Comment by sethmlarson** [comment]
We can't unconditionally install aiohttp because we support Python 2.7, 3.4 and 3.5. Even once we start supporting only Python 3.6+ we likely won't install aiohttp by default because of the much larger number of dependencies.

Perhaps when we support Python 3.6+ I can add a better error message on instantiation of `AsyncElasticsearch`?

**Comment by cmutrufflepig** [comment]
Thank you! Feel free to close or backlog this then.

**Comment by sethmlarson** [comment]
This is complete in elastic-transport-python https://github.com/elastic/elastic-transport-python/commit/0550c36389bd4f763da3cb353fe9a92596efcf74 which will be used in 8.0.
