### ISSUE TITLE
Support using the reindex helper to target a datastream

### ISSUE THREAD

**Issue by jeska** [elastic/elasticsearch-py#1613]
**Describe the feature**: The `elasticsearch.helpers.reindex` function currently does not support re-indexing into a data stream. If you run something like the following code:

```python
helpers.reindex(
    client=source_client,
    source_index=source_index,
    target_client=target_client,
    target_index=target_data_stream,        
    )
```

it will return a `BulkIndexError` with the error `{'type': 'illegal_argument_exception', 'reason': 'only write ops with an op_type of create are allowed in data streams'}`. Per the Elastic API documentation for `reindex` under the [query parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-api-query-params): `To reindex to a data stream destination, this argument must be create.`

Would be great if this option was available in the helper!

**Comment by V1NAY8** [comment]
@sethmlarson By any chance, Should I be able to implement this ? If Yes any inputs on what to do.

**Comment by sethmlarson** [comment]
I think @jeska is already looking at this!

**Comment by jeska** [comment]
@V1NAY8 by all means go for it!
