### ISSUE TITLE
Connection error using Async Client

### ISSUE THREAD

**Issue by maya-harel** [elastic/elasticsearch-py#1630]
Hey :)

I have a server running with FASTAPI with version`fastapi==0.65.2`, and I am using the python Async Elasticsearch client versions `elasticsearch==7.13.1` `elasticsearch-async==6.2.0` and `asyncio==3.4.3`
with an Elasticsearch cluster using the AWS Elasticsearch Service (in region us-east-1)

`ELASTICSEARCH_CLIENT = AsyncElasticsearch(hosts=[{"host": es_host, "port": 443, "use_ssl": True,}], http_auth=(es_user, es_pass,),)`

I am getting an error each time I try to connect to the Elasticsearch client, each request returns a status code of N/A, and the error message is
`WARNING: 07-01-2021 19:16:30: elasticsearch: 299: POST https://<es-host>:443/<index-name>/_search?size=10&from=0 [status:N/A request:0.000s]`
`elasticsearch.exceptions.ConnectionError: ConnectionError(Timeout context manager should be used inside a task) caused by: RuntimeError(Timeout context manager should be used inside a task)` (this is thrown by the `aiohttp` library)

I tried also creating a workaround using the `.ping()` function and creating a new client if it returns False
The `.ping()` function returns false even though the cluster is up and running (no issues posting to it with the non-async client)

This happens for all requests - create, search, update, etc.

I have another project where I also use the python elasticsearch client (although not the async version) with version `elasticsearch==7.10.0` with the same host and I have never had this issue

**Comment by rodneykeeling** [comment]
Did you find a solution to this issue? I am also having this problem. Thanks!
