### ISSUE TITLE
Bug: 7.14.0a1 raises NotElasticsearchError upon connection to ES containers

### ISSUE THREAD

**Issue by vEpiphyte** [elastic/elasticsearch-py#1639]
**Elasticsearch version** (`bin/elasticsearch --version`): Using docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.14.0a1

**Description of the problem including expected versus actual behavior**:

The transport _do_verify_elasticsearch function returns false, preventing the use of the elasticsearch API since the transport refuses to talk to ES.

**Steps to reproduce**:

Start a 7.9.1 docker container

```
 docker run --rm --name es -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.1
```

Then try connecting to it via the python connector
```
>>> import elasticsearch
>>> es = elasticsearch.Elasticsearch(hosts='http://localhost:9200/')
>>> es.info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/3.8.10/envs/proj/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/user/.pyenv/versions/3.8.10/envs/proj/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 294, in info
    return self.transport.perform_request(
  File "/home/user/.pyenv/versions/3.8.10/envs/proj/lib/python3.8/site-packages/elasticsearch/transport.py", line 413, in perform_request
    raise NotElasticsearchError(
elasticsearch.exceptions.NotElasticsearchError: The client noticed that the server is not Elasticsearch and we do not support this unknown product
```

Logging the args given to ``_verify_elasticsearch`` contains the following information

```
INFO     elasticsearch:base.py:270 GET http://localhost:9200/ [status:200 request:0.003s]
INFO     elasticsearch:transport.py:499 {'content-type': 'application/json; charset=UTF-8', 'content-length': '537'}
INFO     elasticsearch:transport.py:500 {'name': 'df9e379eabf8', 'cluster_name': 'docker-cluster', 'cluster_uuid': 'NMWmEyckTqK2UMKgVM_zCA', 'version': {'number': '7.9.1', 'build_flavor': 'oss', 'build_type': 'docker', 'build_hash': '083627f112ba94dffc1232e8b42b73492789ef91', 'build_date': '2020-09-01T21:22:21.964974Z', 'build_snapshot': False, 'lucene_version': '8.6.2', 'minimum_wire_compatibility_version': '6.8.0', 'minimum_index_compatibility_version': '6.0.0-beta1'}, 'tagline': 'You Know, for Search'}
```

**Comment by lnielsen** [comment]
We also see the same error when using containers:

```
~$ curl http://127.0.0.1:9200
{
  "name" : "60865ffac484",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "eCYk6HMBSOu9jznjKXipzw",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "docker",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by ppanero** [comment]
The issue comes from [this line](https://github.com/elastic/elasticsearch-py/blob/7.14/elasticsearch/transport.py#L631):
```python
        bad_build_flavor = version.get("build_flavor", None) != "default"
```

The `build_flavor` is `oss`.

An alternative would be:
```python
bad_build_flavor = version.get("build_flavor", None) != "default" != "oss"
```

I can provide a PR for this if the above is correct in terms of what's desired

**Comment by philkra** [comment]
With the `7.11` the release of Elasticsearch, we will no longer be releasing oss-only distributions, as stated in the [FAQ on license change](https://www.elastic.co/pricing/faq/licensing). The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under [Elastic License v2](https://www.elastic.co/licensing/elastic-license). Otherwise, you can pin the client version to `<7.14`.

**Comment by lnielsen** [comment]
So am I assuming correctly that if there's a security fix in the future you'll be releasing e.g. a version``7.15+`` and then we'll be forced to upgrade our Elasticsearch cluster running e.g. ``7.10`` because the product check doesn't work against a version 7.10-oss distribution?

**Comment by vEpiphyte** [comment]
I'm also confused - do you plan on updating the published library compatibility such that 7.x.x major versions are not actually compatible as noted in the readme?

**Comment by philkra** [comment]
Thank you for the feedback about the compatibility of the README. We are addressing the wording to mitigate confusion. 

Elastic's recommendation is to upgrade the server first, then the client. Which entails a forward compatible of the language clients. The following paragraph is defined in [docs of the HLRC](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-compatibility.html):

> The High Level Client is guaranteed to be able to communicate with any Elasticsearch node running on the same major version and greater or equal minor version. It doesn’t need to be in the same minor version as the Elasticsearch nodes it communicates with, as it is forward compatible meaning that it supports communicating with later versions of Elasticsearch than the one it was developed for.

**Comment by vEpiphyte** [comment]
Is the readme going to be updated to add this language for the change in 7.14.0 release? Folks are already having to handle breakages and the release notes at https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/release-notes.html#rn-7-14-0 don't indicate that previously valid elasticsearch clusters are affected by this.

**Comment by sethmlarson** [comment]
@vEpiphyte The compatibility matrix will be updated soon in the README and elsewhere. I've also renamed your issue for discoverability.

**Comment by jre21** [comment]
If you're running a now-unsupported Elasticsearch server and concerned about the security implications of no longer being able to update elasticsearch-py, it looks like an alternative client will be available soon: https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/
