### ISSUE TITLE
Group similar tests and convert tests to use pytest framework

### ISSUE THREAD

**Issue by V1NAY8** [elastic/elasticsearch-py#1647]

**Comment by V1NAY8** [comment]
Assign this to me

**Comment by dannysepler** [comment]
Just released this and looking for folks to test it! https://github.com/dannysepler/pytestify

It's totally okay if it doesn't work out for you 👍

**Comment by sethmlarson** [comment]
Going to close this as refactor work for the test suite isn't planned at this time.
