### ISSUE TITLE
Request Body expected in open_point_in_time

### ISSUE THREAD

**Issue by ezzy1337** [elastic/elasticsearch-py#1653]
**Elasticsearch version  7.9.0**

**`elasticsearch-py` version 7.12.0**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Description:** When calling `open_point_in_time()` I get this error `elasticsearch.exceptions.RequestError: RequestError(400, 'parse_exception', 'request body is required')` according to the [docs](https://elasticsearch-py.readthedocs.io/en/v7.12.0/api.html#elasticsearch.Elasticsearch.open_point_in_time) there is no body parameter for the point_in_time_function. Digging into the code it looks the the open_point_in_time function needs to accept a body parameter and pass that into the transport.perform_request function.

**Actual Result:** RequestError is raised
```
Traceback (most recent call last):
  File "/Users/derek/sandbox/query_es.py", line 118, in <module>
    res = dev_client.open_point_in_time(index='user-scores-dev')
  File "/Users/derek/sandbox/venv/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Users/derek/sandbox/venv/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 2128, in open_point_in_time
    return self.transport.perform_request(
  File "/Users/derek/sandbox/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/Users/derek/sandbox/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/derek/sandbox/venv/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/derek/sandbox/venv/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'parse_exception', 'request body is required')
```

**Expected Results:** A dictionary containing the point in time id. For example, per the Elasticsearch [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after)
```
{
  "id": "46ToAwMDaWR5BXV1aWQyKwZub2RlXzMAAAAAAAAAACoBYwADaWR4BXV1aWQxAgZub2RlXzEAAAAAAAAAAAEBYQADaWR5BXV1aWQyKgZub2RlXzIAAAAAAAAAAAwBYgACBXV1aWQyAAAFdXVpZDEAAQltYXRjaF9hbGw_gAAAAA=="
}
```

**Steps to reproduce**:

Execute this code.
```
from elasticsearch import Elasticsearch
es = Elasticsearch()
res = es.open_point_in_time()
print(res)
```

**Comment by sethmlarson** [comment]
Thanks for opening this. I think your problem is coming from the `open_point_in_time` and `close_point_in_time` APIs being added to Elasticsearch in v7.10, you list your server version v7.9 so you're hitting an issue where the server thinks you're calling a different API than you want because of the URL path (I believe it's confusing `POST /_pit` for the `index` API?)

The solution to use Point-in-Time APIs is for you is to upgrade your server to at least 7.10 (preferably the latest!) to access all the APIs that the currently installed client offers.

Once you do start using Point-in-Time it'll look like this:

```python
from elasticsearch import Elasticsearch
client = Elasticsearch(...)

# Open a Point-in-Time, no body needed
resp = client.open_point_in_time(index="test-index", keep_alive="5m")

# Grab the Point-in-Time ID from the response
pit_id = resp["id"]

try:
    # Start the search with a 'pit.id' and 'pit.keep_alive'
    resp = client.search(
        # Notice: don't use 'index=...' here, Point-in-Time handles this.
        body={
            "pit": {
                "id": pit_id,
                "keep_alive": "5m"
            },
            "query": {
                "match_all": {}
            }
        }
    )

    # Update the 'pit_id' if one is given in the Search response
    pit_id = resp.get("pit_id", None)

    # Continue the pagination using 'search_after', etc
finally:
    # After all your searching is complete we close the Point-in-Time to
    # de-allocate all the resources.
    client.close_point_in_time(
        body={"id": pit_id}
    )
```
I ran the above example on Elasticsearch v7.13 and had a successful search on a test index.

Does this answer your question?
