### ISSUE TITLE
indeces.pyi has wrong signature for put_template and some other functions

### ISSUE THREAD

**Issue by haynesgt** [elastic/elasticsearch-py#1655]
Looks like the star is in the wrong place, and with mypy I see `error: Too many positional arguments for "put_template" of "IndicesClient"`:

https://github.com/elastic/elasticsearch-py/blob/76f8f85649d18f36018aab6bcdcd2dc87583b74a/elasticsearch/client/indices.py#L621

https://github.com/elastic/elasticsearch-py/blob/c36d31d1609b34db8da15e52f95e49c9f41b12d2/elasticsearch/client/indices.pyi#L413-L417

Similar issue for put_settings, put_index_template, update_aliases, and put_mapping

I think the pyi should list body before the `*` (or maybe the functions should have `body=None`)

**Comment by sethmlarson** [comment]
Thanks for opening this. The placement of the `*` is deliberate, we're trying to push users to use keyword arguments as that's the only way we can guarantee backwards compatibility when it comes to upgrades (plus it's more readable too!). In the case that a new parameter is added or becomes optional the order won't matter when using keyword arguments versus positional arguments.

I hope this answers your question.
