### ISSUE TITLE
UnsupportedProductError -> Using Ubuntu:20.04, ES Version 7.10 "The client noticed that the server is not a supported distribution of Elasticsearch"

### ISSUE THREAD

**Issue by shahzebutt** [elastic/elasticsearch-py#1670]
I was using elasticsearch in a docker file with a base image of paython:3.6.10. I was using the AWS elasticsearch instance with version 7.10 and it was working fine.
Now I changed my docker base image to ubuntu:20.04 and now I am getting this error.

I explored further in the package and I found: 
when this code is run: 
""
if self._verified_elasticsearch is None:
            self._do_verify_elasticsearch(headers=headers, timeout=timeout)
""
then the value of self._verified_elasticsearch is set to 3 (In my case)
and then I get an error of unsupported distribution from the package because of this line.
""
# If '_verified_elasticsearch' isn't 'True' then we raise an error.
if self._verified_elasticsearch is not True:
     _ProductChecker.raise_error(self._verified_elasticsearch)
""
I found from the docs that ubuntu:20.04 is supported by elasticsearch version 7.10 but still I am getting this error.
if I manually hardcode self._verified_elasticsearch = True then everything works fine and my error is resolved. 

Can anyone help me in this case? This is a huge blocker for me right now.

**Comment by sethmlarson** [comment]
Regarding AWS Elasticsearch you can see this issue: https://github.com/elastic/elasticsearch-py/issues/1666

And for Docker my guess if you're using the OSS-only distribution [which is no longer published or supported](https://github.com/elastic/elasticsearch-py/issues/1639). If this isn't the case please open a new issue with the result of the `.info()` API and I'll take a look.
