### ISSUE TITLE
Update README to reflect compatible distributions

### ISSUE THREAD

**Issue by paulharbulak-maxar** [elastic/elasticsearch-py#1671]
**Describe the feature**:

It would be helpful for users if the "Compatibility" section of the README were updated to reflect supported distributions, in addition to supported versions.  (i.e. - OSS is no longer supported.)

**Comment by sethmlarson** [comment]
Quoting the [current compatibility section](https://github.com/elastic/elasticsearch-py#compatibility):

> "...language clients are also backwards compatible with lesser **supported** minor Elasticsearch versions"

Emphasis mine, the OSS-only distribution of Elasticsearch is no longer supported, published, or tested so the language client isn't backwards compatible with it.
