### ISSUE TITLE
UnsupportedProduct in Elasticsearch-py 7.x with a 7.x server

### ISSUE THREAD

**Issue by mrkiko** [elastic/elasticsearch-py#1682]
Hello folks!!

For a project, we are using ElasticSearch 7.9.1 and ElasticSearch-py 7.14. By reading the documentation, we expected it to work, receiving an UnsupportedProduct message instead.

Digging a little bit further, we found out the problem is related to the build flavor: our server presents itself with the "oss" one, while the elasticsearch-py expects a "default" build flavor.
Not being in the position to replace or upgrade the server, what is the suggested course of action?

**Comment by philkra** [comment]
Hi @mrkiko , the general recommendation is to always upgrade the server first then the client, as the clients are forward compatible. If you are not in the position to upgrade your Elasticsearch cluster, the recommendation is to pin the client to the previous version. 

Is there anything we can help to unblock the upgrade of your cluster?

**Comment by mrkiko** [comment]
Hello!
In my opinion, this behaviour breaks compatibility, and goes against what is being reported in the docs:
https://elasticsearch-py.readthedocs.io/en/v7.14.0/#compatibility

Furthermore, the issue we are encountering has to do with the build flavor and not the version itself. I think this change should be limited to the next major version (version 8 in this case).

**Comment by MarcOnFire** [comment]
> 
> 
> Hello!
> In my opinion, this behaviour breaks compatibility, and goes against what is being reported in the docs:
> https://elasticsearch-py.readthedocs.io/en/v7.14.0/#compatibility
> 
> Furthermore, the issue we are encountering has to do with the build flavor and not the version itself. I think this change should be limited to the next major version (version 8 in this case).

I'm facing the same issue; 7.14 is not working with "oss" build flavor (server version 7.9.1).
This check is breaking compatibility.

**Comment by philkra** [comment]
Please refer to the README of this repository for the compatibility: https://github.com/elastic/elasticsearch-py/tree/7.14#compatibility 

Sorry if https://elasticsearch-py.readthedocs.io/en/v7.14.0/#compatibility caused confusion, we'll adjust the docs on RTD with the next patch release.

**Comment by MarcOnFire** [comment]
Ok thanks.

**Comment by mrkiko** [comment]
Thanks for the clarifications.

**Comment by sftim** [comment]
https://github.com/elastic/elasticsearch-py/issues/1676#issuecomment-896255707 might help?
