### ISSUE TITLE
Add ignore_status argument to bulk() and streaming_bulk() in elasticsearch 6

### ISSUE THREAD

**Issue by andrewhibbert** [elastic/elasticsearch-py#1689]
This exists in elasticsearch 7 API but not in 6. I'm wandering if the fix can be merged into a new release for elasticsearch 6. Issue/PR is https://github.com/elastic/elasticsearch-py/issues/1027 / https://github.com/elastic/elasticsearch-py/pull/1553

**Elasticsearch version** (`bin/elasticsearch --version`):
6.7.0
**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 
6.4.0
Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

**Comment by sethmlarson** [comment]
Since 6.x Elasticsearch and the client are no longer under active development no new features will be added therefore this is unlikely to happen. Sorry about that.
