### ISSUE TITLE
How to batch submit to Elasticsearch with null for date type fields.

### ISSUE THREAD

**Issue by otomori-k** [elastic/elasticsearch-py#1714]
The following program is used for batch input.

```
def es_doc_generator(index, df):
    records = [d[1] for d in df.iterrows()]
    docs_es = [{key: doc[key] for key in doc.keys()} for doc in records]
    for doc in docs_es:
        doc_id = hash(frozenset(doc.items())
                      ) if not "id" in doc else doc["id"]
        yield {
            "_index": index,
            "_id": doc_id,
            "_type": "_doc",
            "_source": doc,
        }

def bulk_insert(df, index_name):
    helpers.bulk(es, es_doc_generator(index_name, df))
```

The doc of _source is of type dict.
In the doc, "date" is stored as key and the date read from Excel as value.

### A) If we read a blank Excel file and batch input, the error message is as follows

> elasticsearch.exceptions.SerializationError: ({'date': NaT}, TypeError("Unable to serialize NaT (type: <class 'pandas._libs.tslibs.nattype.NaTType'>)"))

### B) If NaT in the pandas DataFrame is replaced with None and the batch is submitted, the error message is as follows

> elasticsearch.helpers.errors.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'test', '_type': '_doc', '_id': '-949190243596257389', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [date] of type [date] in document with id '-949190243596257389'. 
> Preview of field's value: ''", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'cannot parse empty date'}}, 'data': {'date': ''}}}]
> 

**We want to set the date type field to a null value.**
However, even if we set None as shown in B, it will be batch submitted **as an empty character ('')**.

Please let me know if there is a way to batch submit **as {'date': null}**.

**Comment by pquentin** [comment]
According to https://discuss.elastic.co/t/type-illegal-argument-exception-reason-cannot-parse-empty-date/194239, you should omit the `date` key altogether instead of passing `None`. Does that help?

**Comment by sethmlarson** [comment]
You might also want to take a look at [Eland](https://github.com/elastic/eland), it provides some [helpful utilities](https://eland.readthedocs.io/en/v7.14.1b1/reference/api/eland.pandas_to_eland.html#eland.pandas_to_eland) when going between pandas and Elasticsearch.

Going to close this as resolved, let me know if you have additional questions.
