### ISSUE TITLE
startup time regression traced to elasticsearch

### ISSUE THREAD

**Issue by yoav-orca** [elastic/elasticsearch-py#1715]
**Elasticsearch version** (`bin/elasticsearch --version`): N/A

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  >=7.10.0, >=6.8.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**: 
I have recently upgraded to elasticsearc-py from `7.6.0` to `7.9.1` and I have noticed a regression in the startup time of our cli utilities. Apparently since the introduction of https://github.com/elastic/elasticsearch-py/pull/1180 it will import and initialize pandas and numpy even if they are not not used.

I tested using `hyperfine` and I'm getting 500-800ms delay because of that.

**Steps to reproduce**:
1. install `pip install elasticsearch`
2. run `time python -c 'import elasticsearch'`
3. install pandas
4. run `time python -c 'import elasticsearch'`

See increased runtime of 500-800ms.

I would appreciate a switch to turn this thing off if it's not required since it's fairly expensive when not used.

**Comment by sethmlarson** [comment]
Thanks for reporting this! I think I have a way to reduce import time without requiring a switch for disabling numpy/pandas support.
