### ISSUE TITLE
Adding max_analyzed_offset option for highlighting

### ISSUE THREAD

**Issue by Tomptez** [elastic/elasticsearch-py#1719]
**Describe the feature**:

I have been using the highlighting when I came across this error message:
`elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'The length of [myfield] field of [37] doc of [my-index] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!')`

As suggested in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html) I tried to set `max_analyzed_offset` as an option, so the highlighting just stop at a certain point without returning an error message.

However, doing so has returned a different error message.
`elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', '[1:329] [highlight] unknown field [max_analyzed_offset]')`

It seems like [this merge](https://github.com/elastic/elasticsearch/pull/67325) has not been implemented in the python client. A fix for this would greatly be appreciated.

A suggestions for a temporary solution would be appreciated

**Comment by sethmlarson** [comment]
There might be some confusion about "query" parameter language being used in the documentation you linked to. If I understand the confusion correctly, you think there should be a `max_analyzed_offset` parameter on the `search` API for example, but actually the parameter should be placed like so:

```json
client.search(..., body={"query" : {"match" : {"field1" : "fox"}}, "highlight" : {"type" : "plain", "fields" : {"field1" : {}}, "max_analyzed_offset": 20}})
```

Does this make sense? I'm going to close this issue for now, will reopen if this it's not the solution to your issue.
