### ISSUE TITLE
Support List Logstash Pipelines API Call

### ISSUE THREAD

**Issue by nemhods** [elastic/elasticsearch-py#1726]
**Describe the feature**: Support the [List Logstash Pipelines](https://www.elastic.co/guide/en/kibana/master/logstash-configuration-management-api-list.html) API call.

Currently, the module supports only reading or deleting logstash pipelines by **id** (as well as adding pipelines). There is no way to discover the available **id**s.

Sample use-case would be a python script that creates a snapshot of all centrally managed logstash APIs - currently, I have to provide a list of pipeline ids externally.

**Comment by nemhods** [comment]
I just realized that the API i provided is part of the Kibana API. The issue is still relevant, as there is currently no way to discover managed logstash pipelines afaik, but this issue is probably out of scope, correct?

**Comment by sethmlarson** [comment]
Thanks for opening this @nemhods you're correct that this is out of scope for the Elasticsearch client.

**Comment by nemhods** [comment]
Thanks. For anyone else stumbling over this, you can simply search the `.logstash` index, it will contain all pipelines with their ids as well as the pipeline content.
