### ISSUE TITLE
Shorthand format for sort parameter incorrectly serialized in request body

### ISSUE THREAD

**Issue by jpittiglio** [elastic/elasticsearch-py#1743]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.15.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.15.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
Code that relies on Elasticsearch `search` API using the `sort` query parameter using `<field>:<direction>` breaks in the 7.15.0 library.  Confirmed it still works using 7.14.2.

In 7.14.2, the `perform_request` call produces a `full_url` with `sort` as a query parameter.  Equivalent example:
```GET testindex/_search?sort=@timestamp:asc```

In 7.15.0, `sort` instead gets added to the request `body` with a key/value pair as part of `perform_request`.  Equivalent example:
```
GET testindex/_search
{
    "sort": "@timestamp:asc"
}
```

Refs:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html - Query parameters, sort

**Steps to reproduce**:
* Create a simple index and add a document with some basic information:
```
POST testindex/_doc
{
  "@timestamp": "2021-09-29T12:00:00Z"
}
```

* Run the following search using `elasticsearch-py`:
```
import elasticsearch
es = elasticsearch.Elasticsearch('http://localhost:9200')
es.search(index='testindex', sort='@timestamp:asc')
```
With 7.14.2 (and earlier), a successful result returns; with 7.15.0, the following returns:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>/testing/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 301, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "<...>/testing/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1765, in search
    return self.transport.perform_request(
  File "<...>/testing/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 458, in perform_request
    raise e
  File "<...>/testing/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 419, in perform_request
    status, headers_response, data = connection.perform_request(
  File "<...>/testing/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 287, in perform_request
    self._raise_error(response.status, raw_data)
  File "<...>/testing/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 337, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [@timestamp:asc] in order to sort on')
```

**Comment by sethmlarson** [comment]
@jpittiglio Thanks for reporting this, I'll fallback on using `?sort=` for strings and only add to the body for lists/objects. For now you can either specify `params={"sort": "@timestamp:asc"}` or pin your version of `elasticsearch`.
