### ISSUE TITLE
Move type information from type stubs to .py files

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch-py#1745]
Since we're dropping Python 2.7 we can now safely move the type information in `.pyi` stubs to `.py` files.

**Comment by V1NAY8** [comment]
Does this mean inline type hints?  Perhaps I can get started at get 5 files per PR.

**Comment by sethmlarson** [comment]
@V1NAY8 I have an in-progress branch locally, luckily a lot of files are going away with the move to use [`elastic-transport-python`](https://github.com/elastic/elastic-transport-python/) so I'll skip those for now and remove them in another PR.
