### ISSUE TITLE
Missing `list_crawler_domains` API

### ISSUE THREAD

**Issue by tarekziade** [elastic/elasticsearch-py#1760]
I was trying to list the domains ([the API exists on AS](https://github.com/elastic/ent-search/blob/main/loco_moco/spec/integration/api/crawler/domains_api_spec.rb#L16)) and noticed that it's missing from the [AppSearch class](https://github.com/elastic/enterprise-search-python/blob/main/elastic_enterprise_search/client/_app_search.py).

**Comment by sethmlarson** [comment]
I believe this was meant for the [enterprise-search-python[(https://github.com/elastic/enterprise-search-python) repository, could you reopen there?
