### ISSUE TITLE
Issue with ES >= v7.15.0: TypeError: search() got multiple values for keyword argument 'size'

### ISSUE THREAD

**Issue by jgb** [elastic/elasticsearch-py#1766]
**Elasticsearch version** : 7.15.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.15.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

Hello,

I'm upgrading ES from v7.14.2 to v7.15.1 and I'm getting an error on code that used to work fine:

```
resp = client.search(
            scroll=scroll, size=size, request_timeout=request_timeout, **search_kwargs
        )
E       TypeError: search() got multiple values for keyword argument 'size'

/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py:571: TypeError
```

I'm doing a search.scan() without any extra parameters, and the search itself has from=0 and size=0.
If I remove the pagination entirely, it works.
Any idea what might be going on?
Downgrading ES to v7.14.2 solves the issue.
I've checked recent bug reports on elasticsearch and elasticsearch-dsl but nothing similar shows up.
The changelog of elasticsearch itself also doesn't give any clues.

Greetings,

Jan

**Steps to reproduce**:

**Comment by sethmlarson** [comment]
Could you print out what `search_kwargs` is in this API call?

**Comment by jgb** [comment]
> Printing `search_kwargs` is better, that way I can get an exact reproducer of the issue.

```
search_kwargs={'index': ['*test_watcher_2016_04'], 'query': {'bool': {'filter': [{'terms': {'location_id': [5101, 5102, 5103, 5104, 5105, 5106, 5107, 5108, 5109, 5110, 5111, 5112, 5113, 5114, 5115, 5116, 5117, 5118, 5119, 5120]}}, {'range'
: {'start_time': {'gte': datetime.datetime(2016, 4, 2, 12, 0), 'lte': datetime.datetime(2016, 4, 19, 12, 0)}}}]}}, 'track_total_hits': True, 'from': 0, 'size': 0, 'sort': '_doc'}
```

By the way I just tested this again with my ES cluster at v7.14.2 and only the elasticsearch pythoon library at v7.15.1 and the TypeError happens.
So it seems as if it's an issue in the library itself, not in ES?

**Comment by sethmlarson** [comment]
@jgb Thanks for digging into this, you're right that things have changed in 7.15 for some APIs, we're moving towards having all top-level API parameters (in path, query, **and body**) to be similarly top-level in the function signature. This means that we'll have to choose for the user where these parameters are serialized instead of having that be the user's responsibility (via `body=` and `params=`).

Looks like we could be merging the parameters in `scan` better to not run into this issue, I'll open a PR fixing that.

**Comment by jgb** [comment]
@sethmlarson awesome, thanks for following up on this! Looking forward to a future release where this is taken care of. Thanks again!

**Comment by jgb** [comment]
@sethmlarson @pquentin so my original issue is indeed solved in v7.16.0 of the library, however this similar thing pops up instead:

```
File /home/quividi/.local/share/virtualenvs/vidicenter/lib/python3.8/site-packages/elasticsearch_dsl/search.py line 731 in scan args locals
for hit in scan(es, query=self.to_dict(), index=self._index, **self._params):
File /home/quividi/.local/share/virtualenvs/vidicenter/lib/python3.8/site-packages/elasticsearch/helpers/actions.py line 576 in scan args locals
resp = client.search(**search_kwargs)
File /home/quividi/.local/share/virtualenvs/vidicenter/lib/python3.8/site-packages/elasticsearch/client/utils.py line 347 in _wrapped args locals
return func(*args, params=params, headers=headers, **kwargs)
TypeError: search() got an unexpected keyword argument 'from'
```

**Comment by sethmlarson** [comment]
Ah, we have to transform that keyword-argument too. This is already handled in 8.0 but not so in 7.16. Thanks for reporting I'll create a separate issue.

**Comment by sethmlarson** [comment]
Created a new issue: https://github.com/elastic/elasticsearch-py/issues/1828
