### ISSUE TITLE
retry_on_timeout meaning

### ISSUE THREAD

**Issue by huyhoangk50** [elastic/elasticsearch-py#1780]
**`elasticsearch-py` version (`7.13.1`)**: 

**Description of the problem including expected versus actual behavior**:
I want to ask these configs  timeout, max_retries, retry_on_timeout effect all of the request from this es_client or it only happens on this connection request. 
```
es_client = Elasticsearch(
    hosts=[{"host": es_endpoint, "port": 443}],
    use_ssl=True,
    verify_certs=True,
    connection_class=RequestsHttpConnection,
    timeout=20,
    max_retries=10,
    retry_on_timeout=True
)
```
I mean when I try to make a search request from this es_client, do those configs work?
eg: `es_client.search(index="test", body={})`

If not how can I retry the request

**Comment by sethmlarson** [comment]
Thanks for opening this issue. The options `retry_on_timeout`, `max_retries`, and `timeout` apply to both establishing a connection and waiting for a response from Elasticsearch since both can happen during a single API call. Does that answer your question?
