### ISSUE TITLE
[feature request] - Support for Alerting APIs

### ISSUE THREAD

**Issue by christophercutajar** [elastic/elasticsearch-py#1783]
**Describe the feature**:

It would be nice if Kibana [Alerting APIs](elastic.co/guide/en/kibana/7.16/alerting-apis.html) are supported through python. 

Currently we're building some automation using python that would create and update alerts on the fly. It would be nice if the elasticsearch python library be used rather than performing requests directly to Kibana.

**Comment by sethmlarson** [comment]
@christophercutajar Thanks for opening this! Those APIs are for Kibana, not Elasticsearch, so wouldn't be added to this client. Currently there's no Python client for Kibana APIs but it's something we want to tackle in the future. For now you'll likely need to call them directly with an HTTP client like urllib3, Requests or aiohttp.

**Comment by christophercutajar** [comment]
> @christophercutajar Thanks for opening this! Those APIs are for Kibana, not Elasticsearch, so wouldn't be added to this client. Currently there's no Python client for Kibana APIs but it's something we want to tackle in the future.
> 
> For now you'll likely need to [call them directly](https://www.elastic.co/guide/en/kibana/master/api.html) with an HTTP client like urllib3, Requests or aiohttp.

Thanks @sethmlarson for your reply! Yeah, as I couldn't find one I thought to raise the feature request here! No worries, once again thank you for your swift feedback 😄
