### ISSUE TITLE
Cannot remove `read_only` block on an index

### ISSUE THREAD

**Issue by philhagen** [elastic/elasticsearch-py#1788]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.15.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.0.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**: The client allows setting an index to `read_only` but does not allow setting it back to read-write.  Instead, it returns an AuthorizationException.  However, I can set it back to read-write with a direct `curl` API call.

**Steps to reproduce**:
```
>>> es.indices.add_block(index='name', block="read_only")
{'acknowledged': True, 'shards_acknowledged': True, 'indices': [{'name': 'name', 'blocked': True}]}
>>>  es.indices.put_settings(index=name', body='{"blocks": { "read_only": true } }')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elk_user/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 301, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/elk_user/.local/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 811, in put_settings
    body=body,
  File "/home/elk_user/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 458, in perform_request
    raise e
  File "/home/elk_user/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 426, in perform_request
    timeout=timeout,
  File "/home/elk_user/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 287, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/elk_user/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 338, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'cluster_block_exception', 'index [name] blocked by: [FORBIDDEN/5/index read-only (api)];')
```
However, I can immediately remove the `read_only` block with the following command:
```
curl -s -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -X PUT http://localhost:9200/name/_settings -d '{ "index": { "blocks.read_only": false } }'
{"acknowledged": true}
```

I would expect to have a method of reversing the `read_only` block, assuming the proper permissions, of course.

**Comment by philhagen** [comment]
In case it is useful, I also discussed this problem here: https://discuss.elastic.co/t/python-client-unable-to-remove-read-only-block/288032 but it's admittedly mostly a repeat of the information above.

**Comment by sethmlarson** [comment]
Thanks for opening this issue! Your requests are doing two different things. Modeling my API call to what you wrote in curl would give me:

```python
>>> es.indices.put_settings(
  index="name",
  body={
    "index": {"blocks.read_only": False}
  }
)
{'acknowledged': True}
```

This works fine for me locally.

I'm wondering if because your usage with the client was trying to set `blocks.read_only` (which isn't a setting) and `index.blocks.read_only` you received the error for the index being read-only instead of an error for "that setting not existing".

Confirming this locally:

```python
>>> es.indices.put_settings(index="name", body={"index": {"this.is.unknown": False}})
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'cluster_block_exception', 'index [name] blocked by: [FORBIDDEN/5/index read-only (api)];')
```

Yeah, that's a bit of a minor UX issue, perhaps I can raise this in the Elasticsearch repository. However because it's not a defect in the client I'm going to close this.

**Comment by philhagen** [comment]
Thanks for the detail and information on the Elastic bug filed.  I appreciate it!
I'll handle via the method you described.  I'm not sure if it warrants re-opening, but is there any value in a `remove_block` functionality to reverse the `add_block` one?  Just wondering on the need to add and remove via such different approaches.

**Comment by sethmlarson** [comment]
@philhagen It's a good suggestion, however you'd have to start on the Elasticsearch repository and suggest a new API there first, then if it's implemented it'll eventually bubble it's way down to the clients.
