### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [elastic/elasticsearch-py#1795]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/utils/build-dists.py b/utils/build-dists.py
index f0e1347..831ebcd 100644
--- a/utils/build-dists.py
+++ b/utils/build-dists.py
@@ -179,11 +179,11 @@ def main():
         if any(x in build_version for x in ("-SNAPSHOT", "-rc", "-alpha", "-beta")):
             # If a snapshot, then we add '+dev'
             if "-SNAPSHOT" in build_version:
-                version = version + "+dev"
+                version += "+dev"
             # alpha/beta/rc -> aN/bN/rcN
             else:
                 pre_number = re.search(r"-(a|b|rc)(?:lpha|eta|)(\d+)$", expect_version)
-                version = version + pre_number.group(1) + pre_number.group(2)
+                version += pre_number.group(1) + pre_number.group(2)
 
             expect_version = re.sub(
                 r"(?:-(?:SNAPSHOT|alpha\d+|beta\d+|rc\d+))+$", "", expect_version
```

**Comment by sethmlarson** [comment]
Thanks for the suggestion, however without a PR I likely won't go through an do this myself. If you have an automated tool that makes improvements (actually f-strings would be better in the case you mentioned) then I'd potentially accept such a PR.
