### ISSUE TITLE
Receiving 400 runtime_error from Elasticsearch using dense_vector field

### ISSUE THREAD

**Issue by benjtlv** [elastic/elasticsearch-py#1797]
Hello.

I am using elasticsearch with the Azure platform, and I am using the Python
API.

I created an index pattern named embeddings-* and I inserted 149000 docs to
the index embeddings-dev. (embeddings are of type dense_vector)

I have the following function in my code:

def query_script(vector):
return {"script_score": {"query": {"ids": {"values":
target_image_ids}},
"script": {
"source": "1 / (1 + l2norm(params.query_vector,
'embedding'))",
"params": {"query_vector": vector}
}
}
}

I run this query using:

es.search(index=self.target_index, body={"query":
query_script(source_embedding)}, size=num_neighbors, request_timeout=60)

I have a use case that runs the query with target_image_ids of length 26000.

I get the following error:

WARNING:elasticsearch:POST
https://a142a36d2b5041c4acf14c55f2b190ec.eastus.azure.elastic-cloud.com:9243/embeddings-dev/_search?size=500
[status:400 request:0.747s]
Exception in

...

File
"C:\Users\benja\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\client\utils.py",
line 168, in _wrapped
return func(*args, params=params, headers=headers, **kwargs)
File
"C:\Users\benja\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\client\__init__.py",
line 1668, in search
return self.transport.perform_request(
File
"C:\Users\benja\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\transport.py",
line 458, in perform_request
raise e
File
"C:\Users\benja\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\transport.py",
line 419, in perform_request
status, headers_response, data = connection.perform_request(
File
"C:\Users\benja\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\connection\http_urllib3.py",
line 277, in perform_request
self._raise_error(response.status, raw_data)
File
"C:\Users\benja\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\connection\base.py",
line 330, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400,
'search_phase_execution_exception', 'runtime error')

I have no idea what causes this. Some posts on the internet suggest a
broken index.

I would really need a solid on that one.

Thank you in advance for your help

**Comment by sethmlarson** [comment]
To better diagnose your error could you try running your search with the following options:

```python
import json
resp = client.search(
  <...the rest of your search...>,
  ignore=400,
  error_trace=True
)
print(json.dumps(resp, indent=2))
```

Then attaching the output of the response to the issue. I'm wondering if you're hitting [this issue?](https://stackoverflow.com/questions/67313858/get-requesterror400-search-phase-execution-exception-runtime-error-for-c)

**Comment by sethmlarson** [comment]
Going to close this as I don't think it's a defect in the client. Feel free to get back on this thread or check out the linked issue.

**Comment by benjtlv** [comment]
Hello and thank you for your answer.

The problem was on the index mappings levels.

What I did is creating an index pattern, along with an index mapping for this index template.

So I did suppose that every new index created with a doc insertion should be automatically mapped.

It seems that this wasn't the case.

What I did is recreating the index manually by calling the mapping endpoint with the following body:

`"mappings": {
      "properties": {
        "embedding": {
          "type": "dense_vector",
          "dims": 2048
        }
      }`

Maybe you can give me some input on how to setup this correctly at the index pattern level.

Many thanks
