### ISSUE TITLE
async_bulk: ignored status still get logged

### ISSUE THREAD

**Issue by zar3bski** [elastic/elasticsearch-py#1803]
**Elasticsearch version** version 7.14.1:

**`elasticsearch-py` version 7.14.1**: 

I am using `elasticsearch.helpers.async_bulk`, docstring of which states that:

> :arg stats_only: if `True` only report number of successful/failed
        operations instead of just number of successful and a list of error responses
    :arg ignore_status: list of HTTP status code that you want to ignore

I'm trying to lower my logs verbosity

```python
await async_bulk(
            self.session,
            self._rec_to_actions(df),
            stats_only=True,
            ignore_status=(200),
        )
```
But no matter what I use in `stats_only` or `ignore_status` (e.g. `[200]`, `["200"]`),  my logs are getting polluted by many
```
2021-11-19 17:42:08 INFO     POST https://localhost:9200/_bulk [status:200 request:0.031s]
2021-11-19 17:42:08 INFO     POST https://localhost:9200/_bulk [status:200 request:0.028s]
2021-11-19 17:42:08 INFO     POST https://localhost:9200/_bulk [status:200 request:0.031s]
2021-11-19 17:42:08 INFO     POST https://localhost:9200/_bulk [status:200 request:0.030s]
2021-11-19 17:42:08 INFO     POST https://localhost:9200/_bulk [status:200 request:0.034s]
```
Am I misunderstanding the precise purpose of these arguments. Is there an other way to fix this client verbosity?

**Comment by sethmlarson** [comment]
`ignore_status` and `stats_only` aren't connected, the former doesn't raise errors for a status code and the latter changes the return type of the `bulk` helper.

So this behavior is expected if your logging level is `INFO`. If you only want non-2XX status codes to be logged you must set the logging to `WARNING`. Closing this issue.
