### ISSUE TITLE
Allow usage of Point in time API

### ISSUE THREAD

**Issue by carlosrochap** [elastic/elasticsearch-py#1822]
We launched a cluster recently using https://cloud.elastic.co (V 7.15.2) and we need to paginate through thousands of results (more than 10k).  

The new recommended way of doing this is by using PIT https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html, but we are unable to do so using this api.  Is there a ETA for including this feature in this package?

**Comment by pquentin** [comment]
The point-in-time APIs are included:

 * https://elasticsearch-py.readthedocs.io/en/v7.15.2/api.html#elasticsearch.Elasticsearch.open_point_in_time
 * https://elasticsearch-py.readthedocs.io/en/v7.15.2/api.html#elasticsearch.Elasticsearch.close_point_in_time

Is anything else missing?

**Comment by sethmlarson** [comment]
@carlosrochap Are you asking specifically about the `scan` helper or are the individual APIs all you need?

**Comment by carlosrochap** [comment]
@pquentin sorry I missed that part when reading the documentation.  I'll try this, thanks a lot.
@sethmlarson I was looking for some helper, but the individual API calls work too, I just need to paginate a lot of docs xD.

**Comment by sethmlarson** [comment]
Awesome, I'll close this for now then. Thanks!
