### ISSUE TITLE
Query string missing from url path in log_request_success and log_request_fail

### ISSUE THREAD

**Issue by jkbak** [elastic/elasticsearch-py#1826]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.4.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.13.4

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**: 

When using AIOHttpConnection, url path is missing query string when being passed to `log_request_success` or `log_request_fail`

**Steps to reproduce**:

I will submit a PR shortly which includes tests which fail on current version
EDIT: https://github.com/elastic/elasticsearch-py/pull/1827

**Comment by sethmlarson** [comment]
Thanks for opening this! This is definitely a bug, working on a fix right now that'll be a part of 7.16.1.

**Comment by jkbak** [comment]
> Thanks for opening this! This is definitely a bug, working on a fix right now that'll be a part of 7.16.1.

Any change of backporting it to previous minor versions? I think we have to remain on 7.13 due to some client <-> server compatibility issues.

**Comment by sethmlarson** [comment]
It won't be backported to 7.13, we only release bug fixes in the current release stream (7.16.x) and the previous major release stream (6.8.x).

What incompatibilities are you running into? Unless you're using experimental or beta APIs the 7.16 client from an API perspective should be backwards compatible with Elasticsearch 7.13.

**Comment by jkbak** [comment]
I didn't check it myself but I can see that elasticsearch-py is pinned to 7.13.* in our project and [this](https://stackoverflow.com/questions/68762774/elasticsearchunsupportedproducterror-the-client-noticed-that-the-server-is-no) stackoverflow thread is linked in the comment. So I guess it's the same issue. Our server version is 7.4.2. If I understand the docs correctly, our client version shouldn't be higher than that, but that still wouldn't solve our problem.

**Comment by sethmlarson** [comment]
Closed in https://github.com/elastic/elasticsearch-py/pull/1829
