### ISSUE TITLE
Return an error in filter if some values don't exist

### ISSUE THREAD

**Issue by benjtlv** [elastic/elasticsearch-py#1868]
Elasticsearch 7.13

Hello.

I have a database of products, and I store the images in Elasticsearch along with product_id, image_id.

Because of inconsistencies between the DB and Elastic, Some ids are missing in elasticsearch, and in such case we want to know what ids are missing.

Sometimes, we use some product with a certain status. It can lead to a lot of ids. We have a use case with 40000 ids.

We only use these ids to filter before running a script score query for vector similarity, but if ids are missing in elastic, no flag would be raised by the API.

If ids are missing, we want to notify the client so the documents can be inserted.

Currently, our only solution to do this is to do a search call, with our 40000 ids, get the results from elastic and do the difference between our 40000 ids and what came back from Elastic.

Because there are 40000 possible results, we have to call the scroll API, or use search after. which complicates everything.

Even when bypassing the max result window of 10000, the results are horribly slow. All of this only for a simple existence verification.

Bite me if I'm wrong, but I haven't found any straightforward way to achieve this, although there should be one.

There should be a possibility to raise a flag if the not all of the ids provided in the filter have been found.

I would really appreciate some help as our whole service depends on it.

Many thanks

**Comment by sethmlarson** [comment]
If I'm understanding your question correctly, you want to check to see if all documents from a list of IDs are actually indexed in Elasticsearch? If that's the case I'd recommend the `mget` API: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html

You can use the API like so:

```python
# List of document IDs to check
document_ids = ["1", "2", "3", ...]

resp = client.mget(
  index="example-index",
  _source=False,
  body={
    "ids": document_ids
  }
)

# Which documents are indexed?
indexed_ids = [doc["_id"] for doc in resp["docs"]
```

The documentation doesn't mention a limit to the size of the response, but there may be some limit less than 10K, if so you'll need to make multiple requests. Does this answer your question?

**Comment by sethmlarson** [comment]
Going to close this as resolved.

**Comment by benjtlv** [comment]
Excellent. It works in no time! Thank you very much
