### ISSUE TITLE
Document that percent-encoding is done automatically for parameters

### ISSUE THREAD

**Issue by damianpfister** [elastic/elasticsearch-py#1879]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.16.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
 date-math does not appear to be supported for Index creation, however this is more of a misunderstanding and needs documentation to correct. 

We need to understand the difference of creating an index using the rest API where we need to escape special characters and creating the index in the python API where we do not need to do so.

**Steps to reproduce**:

With escape characters this does not work:
```
>>> es.indices.create(index="%3Cmy-index-%7Bnow%2Fd%7D%3E")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/elasticsearch/client/utils.py", line 301, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Library/Python/2.7/site-packages/elasticsearch/client/indices.py", line 135, in create
    "PUT", _make_path(index), params=params, headers=headers, body=body
  File "/Library/Python/2.7/site-packages/elasticsearch/transport.py", line 458, in perform_request
    raise e
elasticsearch.exceptions.RequestError: RequestError(400, u'invalid_index_name_exception', u'Invalid index name [%3Cmy-index-%7Bnow%2Fd%7D%3E], must be lowercase')
```

But works without:

```
>>> es.indices.create(index="<my-index-{now/d}>")
{u'index': u'my-index-2022.01.17', u'acknowledged': True, u'shards_acknowledged': True}
```

Created index:

```
{
  "my-index-2022.01.17" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "<my-index-{now/d}>",
        "creation_date" : "1642408878887",
        "number_of_replicas" : "1",
        "uuid" : "MxN68LJhRrObvxySsPd0DQ",
        "version" : {
          "created" : "8010099"
        }
      }
    }
  }
}
```

**Comment by sethmlarson** [comment]
So date math is supported, we however don't document that you don't need to do the percent encoding of parameters yourself so what's happening is the library is double percent encoding the requested index name. Maybe this is necessary to document but I actually feel that the default behavior of "what you request from the client is what you'll get" is a sensible default that doesn't necessarily *need* to be documented? What do you think?

**Comment by sethmlarson** [comment]
I think we're going to decline this one as its only come up once. All clients automatically percent-encode parameter values.
