### ISSUE TITLE
Builds timing out in Jenkins

### ISSUE THREAD

**Issue by V1NAY8** [elastic/elasticsearch-py#1880]
**Describe the issue**:

![image](https://user-images.githubusercontent.com/33659563/150633608-27086a74-5f9f-4cc3-b446-bde260cc0970.png)

Each test is taking 30 seconds to run and builds are timing out after 120 minutes

**Comment by sethmlarson** [comment]
Hm, I know our Jenkins instance got upgraded recently. Let me check on this, thanks for reporting.

**Comment by sethmlarson** [comment]
Looks like the build for `main` started timing out between these two builds:
- https://clients-ci.elastic.co/view/Python/job/elastic+elasticsearch-py+main/347
- https://clients-ci.elastic.co/view/Python/job/elastic+elasticsearch-py+main/348

Notice that the `revision` field is the same, meaning the commit being built is identical so nothing *should* have changed there. Going to follow up with our infra team on this.
