### ISSUE TITLE
Cannot execute search with PIT

### ISSUE THREAD

**Issue by test-user-19** [elastic/elasticsearch-py#1909]
**Elasticsearch version**: 7.16.2

**`elasticsearch-py` version**: 7.16.2

Hello,

I'm trying to paginate the results of a search by using **search_after** parameter together with **PIT** (point in time) as explained in the Elasticsearch official docs: https://www.elastic.co/guide/en/elasticsearch/reference/master/paginate-search-results.html. 
But using the **pit** parameter in the **search** method always raises a **action_request_validation_exception** with this reason:

> Validation Failed: 1: [indicesOptions] cannot be used with point in time

It seems that the request URL prepared by the client contains an index name, but a search request with PIT must not include an index name as by docs: 	

> A search request with the pit parameter must not specify index, routing, and preference as these parameters are copied from the point in time.

This is a small code snippet to reproduce the issue:

```
from elasticsearch import Elasticsearch
es_client = Elasticsearch(hosts=[{'host': 'localhost', 'port': 9200}])

resp = es_client.open_point_in_time(index='my-index', keep_alive='1m')
pit_id = resp['id']
pit_clause = { 'id': pit_id, 'keep_alive': '1m'}

my_query = { 'match_all': {} }
resp = es_client.search(query=my_query, size=10, pit=pit_clause)
```
This returns the error:
`elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: [indicesOptions] cannot be used with point in time;')`

Notice that I did not set the value of the parameter **index**. By default it should be `None`.

I tried to force the `None` value as in the following:

```
resp = es_client.search(index=None, query=my_query, size=10, pit=pit_clause)
```

but the outcome is the same. The same happens if I set `index=''`.

I looked into **`elasticsearch-py`** docs regarding the **pit** parameter but they just say:

> pit – Limits the search to a point in time (PIT). If you provide a PIT, you cannot specify an \<index\> in the request path. 

How is one supposed to change the request path?

**Comment by test-user-19** [comment]
Sorry everyone, I was actually wrong.
I was actually using this line of code:
```
resp = es_client.search(query=my_query, size=10, pit=pit_clause, ignore_unavailable=True)
```
and not the one in the original comment.

If I do not specify the **ignore_unavailable** parameter, the search request works as expected.
I admit that in a rush I did not test the code in the original comment.

So, if you want to execute a search operation with **PIT** remember to **not** specify any parameter that is related to an index.

**Comment by sethmlarson** [comment]
@test-user-19 Glad you figured out the problem!

**Comment by muammaralfa** [comment]
>i got Elasticsearch.search() got an unexpected keyword argument 'query' and 'pit'
anyone knows why?
