### ISSUE TITLE
Error: received plaintext http traffic on an https channel

### ISSUE THREAD

**Issue by boonware** [elastic/elasticsearch-py#1911]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.8.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 
7.12.0 and 7.17.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
Recently added new options for retry configuration to the client. Now connections are failing with the following message on the server:
`received plaintext http traffic on an https channel, closing connection Netty4HttpChannel`.

I can see from the client logs that even though I have HTTPS enabled (and the `host_url` also uses HTTPS) that a request is being made over plain HTTP:

```
2022-02-09 16:54:54,872 - INFO - elasticsearch - GET https://10.183.48.154:9200/_nodes/_all/http [status:200 request:0.068s]
2022-02-09 16:54:54,874 - INFO - REDACTED
2022-02-09 16:54:54,875 - INFO - REDACTED
2022-02-09 16:54:54,875 - INFO - REDACTED
2022-02-09 16:54:54,875 - INFO - REDACTED
2022-02-09 16:54:54,875 - INFO - REDACTED
2022-02-09 16:54:54,875 - INFO - REDACTED
2022-02-09 16:54:54,879 - WARNING - elasticsearch - GET http://172.30.112.56:9200/ [status:N/A request:0.003s]
```

**Steps to reproduce**:
My client setup code. The problem only occurs now that I have the retry config options.

```
client = Elasticsearch(
            [host_url],
            scheme='https',
            use_ssl=True,
            api_key=(api_key, api_key_id),
            retry_on_timeout=True,
            max_retries=5,
            timeout=30
        )
```

**Comment by sethmlarson** [comment]
Could you post the value of `host_url` even if you remove sensitive values, I need this so I can try exactly reproducing your issue.

**Comment by sethmlarson** [comment]
I'm going to close this one as I wasn't able to reproduce after testing a bunch of different configs locally. Provide your configuration and we can reopen this.

**Comment by harigkp** [comment]
**elasticsearch.yml**
**update following**
xpack.security.enabled: true    **to**   xpack.security.enabled: false

xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12


**to** 

xpack.security.http.ssl:
  enabled: false
  keystore.path: certs/http.p12


issue resolved

**Comment by Sahil-creater** [comment]
for me I have disabled this one too

xpack.security.transport.ssl:
  enabled: false
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12
