### ISSUE TITLE
Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported

### ISSUE THREAD

**Issue by ctrl-Felix** [elastic/elasticsearch-py#1933]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.1.0

**Description of the problem including expected versus actual behavior**:

I am using the basic example from the docs but I keep getting the error ```elasticsearch.ApiError: ApiError(406, 'Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported', 'Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported')   ```

**Steps to reproduce**:

```

from datetime import datetime
from elasticsearch import Elasticsearch
es = Elasticsearch('http://localhost:9200')


doc = {
    'author': 'author_name',
    'text': 'Interensting content...',
    'timestamp': datetime.now(),
}
resp = es.index(index="test-index", id="1", document=doc)
print(resp['result'])
es.indices.refresh(index="test-index")


resp = es.get(index="test-index", id=1)
print(resp['_source'])


doc = {
    'author': 'author_name',
    'text': 'Interensting content...',
    'timestamp': datetime.now(),
}


```

**Comment by bikram42** [comment]
I am facing the same issue while trying to do scan and scroll. How did you solve the issue? can you please tell me

**Comment by sethmlarson** [comment]
@bikram42 You shouldn't use the latest version (8.1.0) of the Elasticsearch client against a 6.x version of the Elasticsearch server. Instead you should use the same major version client (6.x) against the major version of Elasticsearch that you're using.

**Comment by bikram42** [comment]
Thanks Seth

**Comment by AlbertDev33** [comment]
This work for me. Thanks @sethmlarson

**Comment by chennian-dev** [comment]
I am facing the same issue, you can download Elasticsearch 6.8.15 ,to solve this issue.
[MACOS/LINUX](https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.15.tar.gz)

**Comment by erickgichukicorrelaction** [comment]
Thanks Seth. I encountered this issue today and I was able to reproduce it
