### ISSUE TITLE
Error Unable to deserialize as JSON while calling cluster.post_voting_config_exclusions

### ISSUE THREAD

**Issue by poleszcz** [elastic/elasticsearch-py#1934]
**Elasticsearch version** (`bin/elasticsearch --version`):

/usr/share/elasticsearch/bin/elasticsearch --version
Version: 8.1.0, Build: default/docker/3700f7679f7d95e36da0b43762189bab189bc53a/2022-03-03T14:20:00.690422633Z, JVM: 17.0.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 
(8, 1, 0)

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

After calling cluster.post_voting_config_exclusions(node_names="es01") I'm getting following stacktrace

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/elastic_transport/_serializer.py", line 88, in loads
>     return self.json_loads(data)
>   File "/usr/local/lib/python3.8/dist-packages/elastic_transport/_serializer.py", line 84, in json_loads
>     return json.loads(data)
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test.py", line 9, in <module>
>     el.cluster.post_voting_config_exclusions(node_names="es01")
>   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
>     return api(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/_sync/client/cluster.py", line 549, in post_voting_config_exclusions
>     return self.perform_request(  # type: ignore[return-value]
>   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/_sync/client/_base.py", line 390, in perform_request
>     return self._client.perform_request(
>   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
>     meta, resp_body = self.transport.perform_request(
>   File "/usr/local/lib/python3.8/dist-packages/elastic_transport/_transport.py", line 348, in perform_request
>     data = self.serializers.loads(raw_data, meta.mimetype)
>   File "/usr/local/lib/python3.8/dist-packages/elastic_transport/_serializer.py", line 191, in loads
>     return self.get_serializer(mimetype).loads(data)
>   File "/usr/local/lib/python3.8/dist-packages/elastic_transport/_serializer.py", line 90, in loads
>     raise SerializationError(
> elastic_transport.SerializationError: Unable to deserialize as JSON: b''`

**Steps to reproduce**:

My simple scripts is as following. First call (cat.nodes) works fine.

> import elasticsearch
> from pprint import pprint
> el = elasticsearch.Elasticsearch('http://127.0.0.1:9200/')
> 
> print(elasticsearch.__version__)
> pprint(el.cat.nodes(format="json"))
> 
> 
> el.cluster.post_voting_config_exclusions(node_names="es01")
> 

It's important to note that API request itself works fine - node is being added to exclusion list.

**Comment by sethmlarson** [comment]
Interesting! Could you run this API with curl and see which headers are coming back? If there's a `Content-Type: application/json` on the response when there isn't a response body that would be a bug in Elasticsearch server.

**Comment by sethmlarson** [comment]
Verified that this API does return `Content-Type` on an empty response:

```bash
$ curl -u elastic:... -vvv -k -X POST -H 'Accept: application/json' https://localhost:9200/_cluster/voting_config_exclusions?node_ids=...
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=ca9b4923d860
*  start date: Mar 16 12:59:43 2022 GMT
*  expire date: Mar 15 12:59:43 2024 GMT
*  issuer: CN=Elasticsearch security auto-configuration HTTP CA
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Server auth using Basic with user 'elastic'
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> POST /_cluster/voting_config_exclusions?node_ids=cdfhilmrstw HTTP/1.1
> Host: localhost:9200
> Authorization: Basic ZWxhc3RpYzpvLWlKKmdpaUFKQTdmbXBCUlNzdQ==
> User-Agent: curl/7.58.0
> Accept: application/json
> 
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 200 OK
< X-elastic-product: Elasticsearch
< content-type: application/json
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by sethmlarson** [comment]
Closed in https://github.com/elastic/elastic-transport-python/pull/73, update your `elastic-transport` with `python -m pip install -U elastic-transport`.
