### ISSUE TITLE
debug info between v7.x and v8.x

### ISSUE THREAD

**Issue by zapcity** [elastic/elasticsearch-py#1945]
It seems to me that v8.x is lacking debug info which v7.x is providing. 

I have version 7.13.1 installed on windows 10 within a venv and issued the following command:

```
# query 1
from elasticsearch import Elasticsearch
es = Elasticsearch('https://somehost.com', http_auth=('someusername', 'somepassword'))
print(es.info())
```
it gives me the following error:

`SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131))`

So obviously is a certificate expiration issue.

I then installed 8.1.1 within a different venv and ran the following:

```
# query 2
from elasticsearch import Elasticsearch
es = Elasticsearch('https://somehost.com:9200', basic_auth=('someusername', 'somepassword'))
print(es.info())
```

only to get a `ConnectionTimeout: Connection timed out` error.

Is 8.1.1 lacking debug info compared to 7.13.1? Or do I need to include extra parameters to Elasticsearch() ?

Thanks.

**Comment by pquentin** [comment]
Hi @zapcity! The errors are different, the second time you really got a connection timeout, which is a totally different, less verbose, error. Maybe you meant to use port `9200` instead of port `2900` in your second snippet?

**Comment by zapcity** [comment]
> Hi @zapcity! The errors are different, the second time you really got a connection timeout, which is a totally different, less verbose, error. Maybe you meant to use port `9200` instead of port `2900` in your second snippet?

Hi @pquentin , thanks for identifying that. It was a typing error in my post. I confirm that I am using 9200. I corrected my post above to reflect that.

It seems I found the issue. Query 1 was using `https://somehost.com` without a port being defined. I thought this was set to 9200 in the background by default. However, it's actually set to 443 by default, as `https://somehost.com:443` connects me to kibana in the browser, however `https://somehost.com:9200` doesn't.

Now `Elasticsearch('https://somehost.com:443', http_auth=('someusername', 'somepassword'))` in 7.x and `Elasticsearch('https://somehost.com:443', basic_auth=('someusername', 'somepassword'))` in 7.x and 8.x give me the same expired certificate error - which I need to address with our support team.

Thanks again for the help.
