### ISSUE TITLE
Calling options() on a client resets timeout related attributes

### ISSUE THREAD

**Issue by redbaron4** [elastic/elasticsearch-py#1947]
**Elasticsearch version** (8.1.1):

**`elasticsearch-py` version (`8.1.1`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

When the `options()` method is called for an existing `ElasticSearch` client instance, the timeout related parameters are not preserved. These parameters are:

- `self._request_timeout`
- `self._max_retries`
- `self._retry_on_timeout`
- `self._retry_on_status`

This is problematic in the `helpers` module, particularly `scan()` because that method calls the `options` and resets any timeout related settings we may have made on the client. We can re-specify the `request_timeout` there but retries parameters cannot be replicated

**Steps to reproduce**:
```
>>> import elasticsearch as ES
>>> es=ES.Elasticsearch("http://esmasters:9200", sniff_on_connection_fail=True, sniff_on_start=True, min_delay_between_sniffing=600, request_timeout=600, sniff_timeout=300, max_retries=5, retry_on_timeout=True)
>>> es._retry_on_timeout
True
>>> es2=es.options()
>>> es2._retry_on_timeout
<DEFAULT>
>>> es._max_retries
5
>>> es2._max_retries
<DEFAULT>
>>> es2._retry_on_status
<DEFAULT>
>>> es._retry_on_status
<DEFAULT>
>>> es._request_timeout
600
>>> es2._request_timeout
<DEFAULT>
```

**Comment by sethmlarson** [comment]
Thanks for reporting this, this does seem like something worth fixing. Let me take a look.

**Comment by mwbenowitz** [comment]
+1 to this. It's called in the `streaming_bulk` method as well, and I believe it is not possible to re-specify any of the affected parameters at that point (most importantly `request_timeout`)

**Comment by meganvw** [comment]
Yes +1 it would be great to see this fixed - ran into this problem today

**Comment by itayB** [comment]
Assuming you guys used the `retry_on_timeout` in `bulk` operations, I wonder if you also faced this [issue](https://github.com/elastic/elasticsearch-py/issues/2196) (value propagate but retries never happen)
