### ISSUE TITLE
N-Gram Library Missing?

### ISSUE THREAD

**Issue by MorganWeiss** [elastic/elasticsearch-py#1957]
I have read over the documentation and have not found any of the N-Gram methods that normally would be supported, why is that?

**Comment by sethmlarson** [comment]
@MorganWeiss Thanks for opening this, when you say "n-gram methods" could you clarify what you mean? Are you referencing an [Edge N-Gram Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html) or something else? Dropping a link to Elasticsearch documentation will help me answer your question.

**Comment by MorganWeiss** [comment]
Hi, I was reading this documentation of phrase suggester [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html) . I made a stackoverflow post [here](https://stackoverflow.com/questions/71788982/elasticsearch-in-python-is-there-a-phrase-suggestor/71791770#71791770) as well. What I am trying to evaluate is the autocompletion feature n-gram smoothing methods can be used for. As I understand elasicsearch has this capability since it has three N-Gram smoothing methods: stupid backoff, laplace, and linear interpolation.

**Comment by sethmlarson** [comment]
From the error that you're receiving on Stackoverflow:

> I also received this error ValueError: Either 'hosts' or 'cloud_id' must be specified

You need to do what the Stackoverflow comments suggested:

```python
from elasticsearch import Elasticsearch

es = Elasticsearch(['https://user:secret@localhost:443'])
```

Going to close this, let me know if this solved your issue.
