### ISSUE TITLE
KNN does not have filter option.

### ISSUE THREAD

**Issue by Ghost---Shadow** [elastic/elasticsearch-py#1962]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.1.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.1.2

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

The docs say that KNN has a filter argument, but the python client does not accept it

https://elasticsearch-py.readthedocs.io/en/latest/api.html?highlight=knn#elasticsearch.Elasticsearch.knn_search

![aaa](https://user-images.githubusercontent.com/7743925/163112234-a1f2e0d9-2644-47aa-89e7-e809f5d83df2.jpg)

**Comment by sethmlarson** [comment]
@Ghost---Shadow Thanks for opening, I'm not seeing the `filter` body parameter in the [kNN API documentation for 8.1](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/knn-search-api.html), I do see the value for the documentation on `master` though which is unreleased.

Does this resolve your issue?

**Comment by sethmlarson** [comment]
The feature is slated for release in v8.2.0 when that happens. You're finding the feature documented in the docs on the `master` branch but not for a released version of the package. For example if you look at our latest release docs the parameter isn't there yet: https://elasticsearch-py.readthedocs.io/en/v8.1.2/api.html

Going to close this as it's not a defect. Let me know if you have more questions.
