### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'host'

### ISSUE THREAD

**Issue by niladriforu** [elastic/elasticsearch-py#1981]
**Describe the feature**:
I am trying to simply login to elasticsearch with master username and password. My elasticsearch is hosted on AWS on a private subnet.
I am getting this error : 
TypeError: __init__() got an unexpected keyword argument 'host'

when trying to do : 
  es = Elasticsearch(
    host = ['<host>'],
    http_auth=('<user>', '<pwd>'),
    scheme="https",
    port=443
)

**Elasticsearch version** (`bin/elasticsearch --version`): 7.10

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  3.9

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

**Comment by sethmlarson** [comment]
The parameter is named `hosts`, not `host`: https://github.com/elastic/elasticsearch-py/blob/7.10/elasticsearch/client/__init__.py#L188
