### ISSUE TITLE
Bulk ingest into a data stream fails when using raw undecoded JSON strings

### ISSUE THREAD

**Issue by b0le** [elastic/elasticsearch-py#2031]
**Elasticsearch version**: `Version: 8.3.2, Build: deb/8b0b1f23fbebecc3c88e4464319dea8989f374fd/2022-07-06T15:15:15.901688194Z, JVM: 18.0.1.1`

**`elasticsearch-py` version**: `8.3.1`

**Description of the problem**: When passing an iterable containing raw undecoded JSON strings as the `actions` argument to `elasticsearch.helpers.bulk()` (and in turn to `elasticsearch.helpers.streaming_bulk()`) while specifying a data stream as the target `index` the bulk ingest fails with "`'error': {'type': 'illegal_argument_exception', 'reason': 'only write ops with an op_type of create are allowed in data streams'}`".

The issue is that when the data to be ingested is of `byte` or `str` types `actions.py` assumes an `op_type` of `index` with no ability to override it: https://github.com/elastic/elasticsearch-py/blob/2f64b0ccbaf71ac1f1dc7ab498bd0ccafd1777f4/elasticsearch/helpers/actions.py#L53-L61

There are several ways this could be handled:
1. The `reindex()` function in `helpers/actions.py` checks whether the destination index is a data stream, the part of the code could be split as a separate function and re-used: https://github.com/elastic/elasticsearch-py/blob/8c88fd2b3370d1e8e23ea5dfee0bd6cc1ca5ce6c/elasticsearch/helpers/actions.py#L824-L842
2. Introduce an optional `data_stream` parameter to bulk ingest functions in addition to `index` and if set always set `op_type` to `create`.
3. (Feature request?) Add support for passing in `(raw_json_action, raw_json_data)` tuples with neither of them requiring any additional processing and just chunked prior to sending to Elasticsearch. This would allow for per-document customization of `op_type`, the destination index etc.
4. (Another feature request?) Add support for iterating over NDJSON-formatted files where the action preceeds the document (as in the actual request to Elasticsearch's [`_bulk`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)). This would allow for ingesting of files that are already properly formatted (then again when chunking one would still need to decode the contents to properly determine the boundaries between action-doc pairs of lines).

**Steps to reproduce**:

1. Create an index template specifying that a data stream is to be created:
```json
PUT _index_template/data_stream_example
{
  "index_patterns": ["data_stream_example*"],
  "data_stream": { },
  "template": {
    "mappings": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "description": {
          "type": "keyword"
        }
      }
    }
  }
}
```

2. Run the following:
```python
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk, BulkIndexError
import elastic_transport

ES_URL="https://localhost:9200"
ES_USER="username"
ES_PASS="password"

es_client = Elasticsearch(
            ES_URL,
            basic_auth=(ES_USER, ES_PASS),
            verify_certs=False,
            http_compress=True)

elastic_transport.debug_logging()

docs = [
    '{"@timestamp": "2022-07-20T12:01:10.000Z", "description": "example1"}',
    '{"@timestamp": "2022-07-20T12:02:50.000Z", "description": "example2"}'
]
try:
    bulk(es_client, docs, index="data_stream_example")
except BulkIndexError as e:
    print(e.errors)
```

Output:
```
https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[2022-07-20T13:14:40] > PUT /data_stream_example/_bulk HTTP/1.1
> Accept: application/vnd.elasticsearch+json; compatible-with=8
> Accept-Encoding: gzip
> Authorization: Basic <hidden>
> Connection: keep-alive
> Content-Encoding: gzip
> Content-Type: application/vnd.elasticsearch+x-ndjson; compatible-with=8
> User-Agent: elasticsearch-py/8.3.1 (Python/3.9.7; elastic-transport/8.1.2)
> X-Elastic-Client-Meta: es=8.3.1,py=3.9.7,t=8.1.2,ur=1.26.10,h=bp
> {"index":{}}
{"@timestamp": "2022-07-20T12:01:10.000Z", "description": "example1"}
{"index":{}}
{"@timestamp": "2022-07-20T12:02:50.000Z", "description": "example2"}

< HTTP/1.1 200 OK
< X-Elastic-Product: Elasticsearch
< Content-Length: 420
< Content-Type: application/vnd.elasticsearch+json;compatible-with=8
< {"took":0,"errors":true,"items":[{"index":{"_index":"data_stream_example","_id":null,"status":400,"error":{"type":"illegal_argument_exception","reason":"only write ops with an op_type of create are allowed in data streams"}}},{"index":{"_index":"data_stream_example","_id":null,"status":400,"error":{"type":"illegal_argument_exception","reason":"only write ops with an op_type of create are allowed in data streams"}}}]}
[2022-07-20T13:14:40] PUT https://elasticsearch1.observe-stage.beenius.tv:9200/data_stream_example/_bulk [status:200 duration:0.222s]
[{'index': {'_index': 'data_stream_example', '_id': None, 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'only write ops with an op_type of create are allowed in data streams'}, 'data': b'{"@timestamp": "2022-07-20T12:01:10.000Z", "description": "example1"}'}}, {'index': {'_index': 'data_stream_example', '_id': None, 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'only write ops with an op_type of create are allowed in data streams'}, 'data': b'{"@timestamp": "2022-07-20T12:02:50.000Z", "description": "example2"}'}}]
```

**Comment by miriam-eid** [comment]
@b0le I'm closing this for now, let me know if you have any additional questions.
