### ISSUE TITLE
Cursor ID missing for SQL queries

### ISSUE THREAD

**Issue by adrianBischof** [elastic/elasticsearch-py#2032]
When sending a SQL single query to the elasticsearch server i get the results back, but without the cursor id to scroll or paginate through the results. Is there any workaround to get the cursor or achieve pagination?

https://www.elastic.co/guide/en/elasticsearch/reference/master/sql-pagination.html

**Comment by sethmlarson** [comment]
Thanks for opening this, the `cursor` property is optional on the response to `sql.query`. I believe the cursor isn't available when there isn't additional data for the query to use. So if there's no cursor it means that pagination is complete. Reopen this issue if this doesn't match your experience and be sure to include a code example of how you're using the APIs.
