### ISSUE TITLE
UnsupportedProductError  es client  7.14.x-7.17X  and es server 7.10.2

### ISSUE THREAD

**Issue by linshoubao** [elastic/elasticsearch-py#2046]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version 7.10.2`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__7.14-7.17`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
Elasticsearch client(7.14-7.17) is not supported wih elasticsearch server 7.10.2, but i can't update elasticsearch server, how to deal with the question?

**Steps to reproduce**:

**Comment by sethmlarson** [comment]
Quoting [this comment](https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286):

> With the `7.11` the release of Elasticsearch, we will no longer be releasing oss-only distributions, as stated in the [FAQ on license change](https://www.elastic.co/pricing/faq/licensing). The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under [Elastic License v2](https://www.elastic.co/licensing/elastic-license). Otherwise, you can pin the client version to `<7.14`.
