### ISSUE TITLE
TypeError: CatClient.indices() got an unexpected keyword argument 'time'

### ISSUE THREAD

**Issue by jpmat296** [elastic/elasticsearch-py#2066]
`bytes` option is well handled:
https://github.com/elastic/elasticsearch-py/blob/8896e5ba2372dcc771beaadee46956fa8ec3386f/elasticsearch/_sync/client/cat.py#L1888-L1889

But not `time` option. This option is documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html#cat-indices-api-request) for example.

I have got the error with elasticsearch-7.17.6 but the same issue exists on latest version.

Let me know if I can help.

**Comment by miriam-eid** [comment]
Hi @jpmat296, thank you for opening this! The referenced code is generated from the Elasticsearch specification. To fix this error, I've opened this PR: https://github.com/elastic/elasticsearch-specification/pull/1988

**Comment by miriam-eid** [comment]
Fixed in https://github.com/elastic/elasticsearch-py/pull/2108

**Comment by jpmat296** [comment]
Thank you for the fix !
