### ISSUE TITLE
Missing/wrong parameters in documentation

### ISSUE THREAD

**Issue by m1guelperez** [elastic/elasticsearch-py#2077]
**`elasticsearch-py` version (8.4.3)**: 

In the documentation for the `search` keyword, the list of parameters contains: `source_includes` and `source_excludes`. However, I am not able to use these two parameters in actual code, as they seem not to exist?

[Search documentation](https://elasticsearch-py.readthedocs.io/en/v8.4.3/api.html?highlight=search#elasticsearch.Elasticsearch.search) I am referring to.

**Comment by miriam-eid** [comment]
@m1guelperez Thanks for opening this! It's hard to understand what may cause this error. Please provide more information, such as the error you are receiving and an example of how to reproduce it.

The following code contains the [two parameters](https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/_async/client/__init__.py#L3465) for `search`: 

```python
async def search(
        ... 
        source_excludes: t.Optional[
            t.Union[str, t.Union[t.List[str], t.Tuple[str, ...]]]
        ] = None,
        source_includes: t.Optional[
            t.Union[str, t.Union[t.List[str], t.Tuple[str, ...]]]
        ] = None,
```
