### ISSUE TITLE
Set ignored status via Elasticsearch.options is not worked.

### ISSUE THREAD

**Issue by vmarunov** [elastic/elasticsearch-py#2080]
**Elasticsearch version** (`bin/elasticsearch --version`):  8.3.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.4.3

Set ignored status via Elasticsearch.options is not worked.

**Steps to reproduce**:
```python
from elasticsearch8 import Elasticsearch

es = Elasticsearch(
    hosts=[{'scheme': 'http', 'host': '127.0.0.1', 'port': 9200}],
)
es.options(ignore_status=(400, 404))
es.indices.delete_alias(index='tmp', name='tmp')  # Not work (raised exception)
es.indices.delete_alias(index='tmp', name='tmp', ignore=(400, 404))  # Work, but deprecation warning
```

**Comment by sethmlarson** [comment]
Thanks for opening this. Using `.options()` creates a contextualized client, ie a whole new client that has the options you set. So to use `.options()` with an API call you need to do one of the two:

```python
es.options(ignore_status=...).indices.delete_alias(...)

# or

es2 = es.options(ignore_status=...)

es2.indices.delete_alias(...)
```

This should solve your issue, but let me know if you have further questions or it doesn't work. Closing this for now.
