### ISSUE TITLE
Support for custom authentication objects for requests module

### ISSUE THREAD

**Issue by sim0nx** [elastic/elasticsearch-py#209]
Hi,

Several transport classes are available, one of them is "requests".
Requests supports basic-authentication but far more than that ([0]). In order to support this a few lines would need to be changed to allow for providing an authentication object ([1]).

I have the code ready ([1]) for this and am actively using it.

Would you be willing to accept this contribution ?

[0]: http://docs.python-requests.org/en/latest/user/advanced/#custom-authentication
[1]: https://github.com/elastic/elasticsearch-py/compare/master...sim0nx:requests_custom_authentication

**Comment by HonzaKral** [comment]
Hi, yes, this makes sense, just make sure it will work on python 3 please.

Thanks!

**Comment by sim0nx** [comment]
Hi,

Thanks, good point. I implemented a check for the python version and test for either basestring (py2) or str (py3).

Does that look OK ?

**Comment by HonzaKral** [comment]
We have a dependency on six, could you please just use `isinstance(http_auth, six.string_types)`? thanks!

**Comment by sim0nx** [comment]
Done

**Comment by HonzaKral** [comment]
Thanks for the cooperation! Can you send a PR please?
Also if you could add a test it would be great, but I am more than happy to do it myself.

**Comment by sim0nx** [comment]
Great, thanks for integrating my code :+1: 

I think I'd prefer if you write the test for it, but I'll have a look at how you did it :-)

**Comment by HonzaKral** [comment]
Thanks, merged!

Sorry about the `six` tip - it was wrong, we have our own mini version in `elasticsearch.compat` instead.
