### ISSUE TITLE
Error connect host in elasticsearch is automatic

### ISSUE THREAD

**Issue by lehoangHUST** [elastic/elasticsearch-py#2097]
Hello everyone, currently I have a problem for elasticsearch:
After about a few days, elasticsearch gateway is automatically disconnected despite doing nothing in the Linux (Ubuntu 18.04) environment. I don't solve problem.
Can anyone give me a solution ??

Thanks you for watching!!

**Comment by EduardoSaverin** [comment]
@lehoangHUST Can you elaborate more on this issue like what is exact issue you are facing. Also can you specify the `client` version and `elasticsearch` version

**Comment by technige** [comment]
@lehoangHUST It is not possible to offer any advice to help you here without more context. You will need to provide *at least* the following information:

- Versions of Elastic server and client software
- Details of your network topology
- What remedial steps you have tried, and their outcomes

**Comment by sethmlarson** [comment]
Going to close as we haven't received additional information, if you can provide the above info we can reopen this issue.

**Comment by lehoangHUST** [comment]
sorry for this late response

I think maybe it's because I run too many tasks on the computer that it can automatically disconnect
