### ISSUE TITLE
SSLError(Fingerprints did not match...) when using ssl_assert_fingerprint

### ISSUE THREAD

**Issue by ctrl-Felix** [elastic/elasticsearch-py#2133]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 8.5.3

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.5.3

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
I've configured my elasticsearch node to work with https. I got the fingerprint for my certificate by using `openssl x509 -fingerprint -sha256 -in certs/http_ca.crt | grep SHA256`. But when I now use this fingerprint in my python code I keep getting an error.

I tried two different python versions and got different behaviours. 

Code I am executing while having a vpn connection to the server :
```python
from elasticsearch import Elasticsearch

ELASTIC = Elasticsearch(
    'https://local_elasticsearch_ip:9200', 
    basic_auth=('user', 'passwd'),
    ssl_assert_fingerprint=("1a6846571bf046ae5fbc0739d566184afc5ec1cc676de90574b68323c1fb287c"),
)
print(ELASTIC.info())

```

Python 3.9.13 (I am aware of the note in the [docs](https://www.elastic.co/guide/en/elasticsearch/client/python-api/master/config.html) but the issue I have seems to be for a different reason:
`elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError(Fingerprints did not match. Expected "1a6846571bf046ae5fbc0739d566184afc5ec1cc676de90574b68323c1fb287c", got "b'4fa8c04043c09657a10cab1c1bee82296577b4ad4881d6156c4e0b4d24f434b5'".))
`
This seems weird to me as the fingerprint I provided is the same it's expecting. And yet it encodes it for some reason.
Someone also posted this on stackoverflow without response https://stackoverflow.com/questions/72302577/ssl-fingerprint-sent-to-elasticsearch-python-not-recognized.

Now I updated my python version to 3.11 and the code works. 

But then I used caddy to proxy the node to a subdomain and now I am getting this error `TlsError(TLS error caused by: SSLError(Fingerprints did not match. Expected "1a6846571bf046ae5fbc0739d566184afc5ec1cc676de90574b68323c1fb287c", got "9fc264f7b63a0f9af0a5ad2be6560755400e8036a7baa8bb1c6c0338a081394b", "5dd661d3cb33b5005cbed045a223ddc4445aaa41d1acb5df700884cad9ba4195", "a6cf64dbb4c8d5fd19ce48896068db03b533a8d1336c6256a87d00cbb3def3ea".))`

The only thing I did was changing the host from the local ip to elasticsearch.domain.tld:443. It still expects the fingerprint I provided but it somehow got 3 others. .

Am I doing something wrong or is this a bug?

**Comment by fedIce** [comment]
I have the same issue.

**Comment by pquentin** [comment]
> I've configured my elasticsearch node to work with https. I got the fingerprint for my certificate by using `openssl x509 -fingerprint -sha256 -in certs/http_ca.crt | grep SHA256`. But when I now use this fingerprint in my python code I keep getting an error.
> [...]
> Python 3.9.13 (I am aware of the note in the [docs](https://www.elastic.co/guide/en/elasticsearch/client/python-api/master/config.html) but the issue I have seems to be for a different reason: `elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError(Fingerprints did not match. Expected "1a6846571bf046ae5fbc0739d566184afc5ec1cc676de90574b68323c1fb287c", got "b'4fa8c04043c09657a10cab1c1bee82296577b4ad4881d6156c4e0b4d24f434b5'".)) ` This seems weird to me as the fingerprint I provided is the same it's expecting. And yet it encodes it for some reason. Someone also posted this on stackoverflow without response https://stackoverflow.com/questions/72302577/ssl-fingerprint-sent-to-elasticsearch-python-not-recognized.
> 
> Now I updated my python version to 3.11 and the code works.

This is actually expected, and mentioned in the docs as you saw. Before Python 3.10, it's only possible to use `ssl_assert_fingerprint` with the leaf certificate fingerprint, the one that is different for each Elasticsearch node. Using the root certificate authority (`http_ca.crt`) fingerprint won't work. With Python 3.10 and later, you can verify any other certificate in the chain, including the root certificate authority (`http_ca.crt`). See https://en.wikipedia.org/wiki/Chain_of_trust and https://sethmlarson.dev/experimental-python-3.10-apis-and-trust-stores if you're interested in the details.

That said, if you actually can use the full root certificate (`http_ca.crt`) in your application, [consider using it with `ca_certs=http_ca.crt`](https://www.elastic.co/guide/en/elasticsearch/client/python-api/master/config.html#_verifying_server_certificates). This will work across all supported Python versions.

> But then I used caddy to proxy the node to a subdomain and now I am getting this error `TlsError(TLS error caused by: SSLError(Fingerprints did not match. Expected "1a6846571bf046ae5fbc0739d566184afc5ec1cc676de90574b68323c1fb287c", got "9fc264f7b63a0f9af0a5ad2be6560755400e8036a7baa8bb1c6c0338a081394b", "5dd661d3cb33b5005cbed045a223ddc4445aaa41d1acb5df700884cad9ba4195", "a6cf64dbb4c8d5fd19ce48896068db03b533a8d1336c6256a87d00cbb3def3ea".))`
> 
> The only thing I did was changing the host from the local ip to elasticsearch.domain.tld:443. It still expects the fingerprint I provided but it somehow got 3 others. .

What this error is telling you is that the fingerprint you were expecting was not given part of the certificate chain presented to the Elasticsearch Python client. If this is a [Caddy reverse proxy](https://caddyserver.com/docs/quick-starts/reverse-proxy) then this is expected: you need to use a fingerprint from the Caddy certificate chain.

@fedIce If the above explanations don't help you, please open a new issue to explain your problem in more details.
