### ISSUE TITLE
Add the Python 3.11 trove classifier to the package

### ISSUE THREAD

**Issue by shay314** [elastic/elasticsearch-py#2142]
Can you please add support in the latest python3.11 version that was released 3 months ago?
Python3.11 is much faster and we want to upgrade, but currently elasticsearch don't support it.

Thanks,

**Comment by sethmlarson** [comment]
Python 3.11 is supported and we [test against it in CI](https://github.com/elastic/elasticsearch-py/blob/main/.github/workflows/ci.yml#L50). I'm guessing by this you mean to add the 3.11 trove classifier?

**Comment by shay314** [comment]
Hi @sethmlarson ,

I guess I should have deeper look.
According to the pypi page the package only support up to python3.10.

Maybe it's worth fixing?
![image](https://user-images.githubusercontent.com/45817758/215308229-a65be521-3bf4-43e8-9e85-a9975cf8e6cf.png)

Thanks,
