### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by linshoubao** [elastic/elasticsearch-py#2150]
**Describe the feature**:

sorry, I have one question:
Whether elasticsearch-py 7.13.4 is compatible with Elasticsearch 7.10.2 ?
I need a conclusion from the community,thank you。

**Comment by sethmlarson** [comment]
We [publish our compatibility guarantees in the README](https://github.com/elastic/elasticsearch-py#compatibility), clients are forward compatible meaning a lesser or equal client version will work with all greater or equal server versions. The client usage you're asking about in particular doesn't match that criteria, you'd need to use a 7.10 or earlier client to be using a supported configuration.
