### ISSUE TITLE
Consider using pyproject.toml replace setup.py

### ISSUE THREAD

**Issue by ischaojie** [elastic/elasticsearch-py#2154]
**Describe the feature**:

`pyproject.toml` has become the de facto python project standard, perhaps we should replace the current `setup.py` with a tool such as [hatch](https://github.com/pypa/hatch)?

**Comment by sethmlarson** [comment]
That would be a great improvement, let's use Hatch.

**Comment by NamanJainCG** [comment]
Hey, can someone help me solve this here, I am a beginner. Thanks in advance

**Comment by pquentin** [comment]
Hello, I would suggest that you read https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html and https://packaging.python.org/en/latest/tutorials/packaging-projects/ first. You will also have to remove `setup.py` from `noxfile.py` and `MANIFEST.in`, and adjust the code in `utils/build-dists.py` to change the version in `pyproject.toml`.

**Comment by pquentin** [comment]
Done in https://github.com/elastic/elasticsearch-py/pull/2600.
