### ISSUE TITLE
SnapshotClient.restore method is missing 'feature_states' keyword argument

### ISSUE THREAD

**Issue by b-deam** [elastic/elasticsearch-py#2168]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.6.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.6.2

**Description of the problem including expected versus actual behavior**:

[The `SnapshotClient.restore` method](https://elasticsearch-py.readthedocs.io/en/v8.6.2/api.html?highlight=feature_states#elasticsearch.client.SnapshotClient.restore) is missing the `feature_states` keyword argument as [documented by Elasticsearch's API](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/restore-snapshot-api.html#restore-snapshot-api-index-settings).

**Steps to reproduce**:

You'll need an ES cluster with a snapshot repository setup.

```
from elasticsearch import Elasticsearch
import ssl
import certifi

ssl_context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=certifi.where())
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE

# works, setting verify_certs means we don't verify the certificate
es = Elasticsearch(
    hosts=["https://localhost:9200"],
    ssl_context=ssl_context,
    verify_certs=False,
    basic_auth=("elastic", "changeme"),
)

es.snapshot.restore(repository="my-repo", snapshot="my-snapshot", wait_for_completion=False, feature_states=["none"])
```

We get:
```
   File "/home/esbench/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
     return api(*args, **kwargs) 
 TypeError: SnapshotClient.restore() got an unexpected keyword argument 'feature_states'
```

**Comment by sethmlarson** [comment]
Thanks for reporting this, this query parameter is missing in the Elasticsearch specification. I've created an issue there: https://github.com/elastic/elasticsearch-specification/issues/2030
