### ISSUE TITLE
Body parameters for templates do not work

### ISSUE THREAD

**Issue by honzakral** [elastic/elasticsearch-py#2180]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.6.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  8.6.2

**Description of the problem including expected versus actual behavior**: some body parameters, that are meant to be passed in `template` (a required argument) like `settings` are documented as being accepted by the API calls but they do not actually work as they are included in the body as top level keys which is not supported and results in `400`:

> BadRequestError(400, 'x_content_parse_exception', '[1:16] [component_template] unknown field [settings]')

**Steps to reproduce**:
```python
es = Elasticsearch()
es.cluster.put_component_template(name="ttt", settings={"number_of_shards": 1}, template={})
```

**Comment by sethmlarson** [comment]
Hey Honza, indeed it looks like the Elasticsearch API specification got this wrong. I've [created a PR](https://github.com/elastic/elasticsearch-specification/pull/2037) which removes the incorrectly nested fields for this API request. This will get fixed during the next round of code generation.

For now you can pass the `settings` field within the `template` object as is expected by Elasticsearch.
