### ISSUE TITLE
Elasticsearch-py connect from google app engine python SDK 2.7 to ElasticClout error: ConnectTimeoutError <urllib3.connection.VerifiedHTTPSConnectio>

### ISSUE THREAD

**Issue by GokuHiki** [elastic/elasticsearch-py#2198]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.17.9

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.17.9

**Description of the problem including expected versus actual behavior**:
The code below run on local computer there are no problems.
```python
def get_client():
  es = elasticsearch.Elasticsearch(
    cloud_id=ES_CLOUD_ID,
    http_auth=ES_HTTP_AUTH,
    http_compress=True,
    use_ssl=False,
    verify_certs=False,
    send_get_body_as='POST',
    timeout=30,
  )
  return es
```
But when deploy to google app engine python SDK 2.7 then have this error:
```
ConnectionError: ConnectionError((<urllib3.connection.VerifiedHTTPSConnection object at 0x3e3c532ec5d0>, u'Connection to dac92031b7fd480090f4a5c50dd2992f.us-central1.gcp.cloud.es.io timed out. (connect timeout=30)')) caused by: ConnectTimeoutError((<urllib3.connection.VerifiedHTTPSConnection object at 0x3e3c532ec5d0>, u'Connection to dac92031b7fd480090f4a5c50dd2992f.us-central1.gcp.cloud.es.io timed out. (connect timeout=30)'))
```
The only way I know to bypass this error by setting in app.yaml:
```yaml
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : True
```
But this effect the bill and may cause unwanted effect on other libraries that I don't know!

Can someone help me with this?
Many thanks and regards!

**Comment by sethmlarson** [comment]
Hello @GokuHiki, I believe you can accomplish what you're trying to do can be accomplished by using a combination of `requests`, `requests-toolbelt` and the `RequestsHttpConnection` class:

```python
# Changes the underlying 'urllib3' HTTP client to use App Engine URLFetch instead of sockets.
# Note this takes affect for all uses of requests in your project.
import requests_toolbelt.adapters.appengine
requests_toolbelt.adapters.appengine.monkeypatch()

from elasticsearch import Elasticsearch
from elasticsearch.connections import RequestsHttpConnection

es = Elasticsearch(
  ...  # Existing config
  connection_class=RequestsHttpConnection
)
```

I saw this in the [official Google App Engine docs](https://cloud.google.com/appengine/docs/legacy/standard/python/issue-requests#requests) but don't have a way of verifying that it'll work, hopefully this will give you something to start with?

**Comment by GokuHiki** [comment]
This not work!
```python
import requests_toolbelt.adapters.appengine
requests_toolbelt.adapters.appengine.monkeypatch() # only patch requests library not urllib3
```

the only way to make elasticsearch-py work with GAE python 2.7 SDK URLFetch service is make 'connection_class' with urllib, urllib2 or httplib library!
I try with the code and
```python
class Urllib2Connection(urllib2.HTTPSHandler):
  def __init__(self, host, *args, **kwargs):
    super(Urllib2Connection, self).__init__(*args, **kwargs)
    self.host = host

  def https_open(self, req):
    return self.do_open(self.getConnection, req)

  def getConnection(self, host, timeout=None):
    return httplib.HTTPSConnection(self.host, timeout=timeout)
```
but get error unexpected parameter 'http_auth'!
Can someone help me with this?
Thanks, and regards.

**Comment by GokuHiki** [comment]
Test again sethmlarson's answer with empty google app engine project and it WORK!
It means that my company GAE project has a conflict problem!
Thanks!
