### ISSUE TITLE
sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [elastic/elasticsearch-py#2205]
The sdist package at PyPI is missing tests.  Please add tests to sdist to make downstream testing easier.  Thank you.

**Comment by sethmlarson** [comment]
sdists are only meant to contain the materials required to build a wheel, they do not need to contain tests. Test suite can be fetched from a tag on GitHub which can also be downloaded as a tarball: https://github.com/elastic/elasticsearch-py/archive/refs/tags/v8.7.0.tar.gz

**Comment by mtelka** [comment]
> sdists are only meant to contain the materials required to build a wheel, they do not need to contain tests. Test suite can be fetched from a tag on GitHub which can also be downloaded as a tarball: https://github.com/elastic/elasticsearch-py/archive/refs/tags/v8.7.0.tar.gz

Unfortunately, this is unreliable. See #2263.
