### ISSUE TITLE
`pipeline` key in data triggers ingest_pipeline. and is not inserted in the data.

### ISSUE THREAD

**Issue by iArunava** [elastic/elasticsearch-py#2207]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.17.9

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.13.4

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

Im upgrading elasticsearch version from 2.4.6 to 7.x
There is a key:value `pipeline:open` in my data. and this is triggering ingest pipeline `open`
Is there anyway i can keep the key `pipeline` in my data without triggering a ingest pipeline?

Else i would need to change my prod data.

Even if i create an empty pipeline. then also. the key:value `pipeline:open` is removed from the data.

I believe this happens here.
`actions = map(expand_action_callback, actions)` in [actions.py](https://github.com/elastic/elasticsearch-py/blob/c3a564ba3e396b3de874e6d82669ffb0a005791a/elasticsearch/helpers/actions.py#L317)

where in `expand_action` the key `pipeline`[loc](https://github.com/elastic/elasticsearch-py/blob/c3a564ba3e396b3de874e6d82669ffb0a005791a/elasticsearch/helpers/actions.py#L70) gets [popped](https://github.com/elastic/elasticsearch-py/blob/c3a564ba3e396b3de874e6d82669ffb0a005791a/elasticsearch/helpers/actions.py#L88)

From how i see the code is written. I dont think theres a way. I would love if somebody can confirm the assumption. Thank you.

**Steps to reproduce**:

Call `bulk()` with `pipeline` key in data.

**Comment by iArunava** [comment]
Just came across this comment. Which would confirm that there is no other way than to change the prod data.
https://github.com/elastic/elasticsearch-py/issues/640#issuecomment-334612661

**Comment by pquentin** [comment]
Hello! And sorry for the delay. Can you please clarify why the workaround mentioned in https://github.com/elastic/elasticsearch-py/issues/640#issuecomment-334612661 (using `doc`) does not work for you? Providing a script that reproduces the problem would also help me help you.
