### ISSUE TITLE
Rank (rrf) missing in Python client search API.

### ISSUE THREAD

**Issue by foo-l** [elastic/elasticsearch-py#2226]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.8.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.8.0

**Description of the problem including expected versus actual behavior**:

Hi all, we are making heavy use of the vector search features of ElasticSearch for our products. Since ElasticSearch 8 we are experimenting the knn feature and we are trying to mix vector searches results with classical query results. 

Reading the [official ElasticSearch 8.8.0 documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html) i stumbled upon a feature that might be usefull for us: *rank (rrf)*.

In order to test the search results and evalute the scores i setup a python enviroment (3.9) with elasticsearch python client (8.8.0). Then, looking at the search python API, i could not find the *rank* keyword argument.

Moreover i looked at the official python client documentation: 

https://elasticsearch-py.readthedocs.io/en/v8.8.0/api.html?highlight=search#elasticsearch.Elasticsearch.search

The rank keyword argument is nowhere to be found. 

My questions are:

1. Am i missing something?
2. Is there a workaround?
3. Are there any plans to introduce it?

Thanks in advance and let me know if you need more details.

**Comment by ezimuel** [comment]
@foo-l This API specification is missing. I'll add it soon. Sorry for the inconvenience.

**Comment by sethmlarson** [comment]
This has been fixed in the API specification and [now is generated in the client](https://github.com/elastic/elasticsearch-py/pull/2227). It'll be available in the next release of the client (8.8.1).
