### ISSUE TITLE
Question: How to disconnect from elasticsearch-py client/connection-pool

### ISSUE THREAD

**Issue by firla** [elastic/elasticsearch-py#223]
Sorry for the perhaps stupid question, but  I cannot find any information in the docs... Whats the correct way to disconnect the client rsp. close an existing connection pool? Thank you.

**Comment by HonzaKral** [comment]
This is not a stupid question at all. Currently there is no way to close the connections or the client itself, partly because you are the first one to ask for it, we just rely on the garbage collector to close the socket when it cleans up the client.

Do you thnk that is sufficient for you or there is a use case for an explicit `close()`?

**Comment by firla** [comment]
Thanks for your answer and sorry for the late response. We haven't tested enough to know if we really need an explicit close. We expect high traffic rates for our service and I'm a friend of manual clean-ups to keep the process proper. So, we will test if the garbage collecor does a good job and close this ticket. Thank you.

**Comment by HonzaKral** [comment]
If you expect high traffic, the last thing you want to do is keep closing and opening the connection. At that point you need to have one persistent  connection open and reuse it.

**Comment by ourlord** [comment]
For some reason when I testing running elasticsearch_py_dsl in a self-implemented multithreading app, I ran into some IOErrors saying open too many files. Basically my app will run thousands of searches every minutes to collect some data from ES and for each search I create a single thread. A simple version of the code is as below.

    es = Elasticsearch(...)
    def a_specific_search(ret, *args):
        s = Search(using = es).query(...).filter(...)
        ret = s.execute()
    def run_every_minute():
        tasks = []
        for a loop:
            t = threading.Thread(target = a_specific_search, args = ...)
            tasks.append(t)
            t.start()
        clean_up_tasks(tasks)   # clean up tasks by looping tasks with a time out join() and 
                                               # clean not alive threads out of the queue
        timer = threading.Timer(60, run_every_minute)
        timer.start()

I only use one elasticsearch client instance from elasticsearch_py and passing it around in the Search() methods in elasticsearch_py_dsl. And I check the codes in elasticsearch_py and find that the default transport class is http_urllib3 which supposes to reuse sockets which should not cause that too many open files error. 

I'm still working on to isolate this issue to see whether it is related to my threads or ES connections. And would you please provide me a simple way to do a explicit `close()` ?

**Comment by ourlord** [comment]
Ok, I verified that the problem is causing by my careless manipulations to threads. The default `http_urllib3` should perform well with massive request along with one ES client instance. 

I wrote a test case to test a 10000 searches each in a single thread with no such IOError problem.

**Comment by revelc33** [comment]
> If you expect high traffic, the last thing you want to do is keep closing and opening the connection. At that point you need to have one persistent connection open and reuse it.
`es = Elasticsearch(...)`
How is working reusing now at days?
 Do i have to reuse the "es" object directly

**Comment by Thys3Potgieter** [comment]
es = Elasticsearch(...)
# do stuf...
es.transport.connection_pool.close()
