### ISSUE TITLE
Wrong type hint for return value of msearch

### ISSUE THREAD

**Issue by TzahiTaub** [elastic/elasticsearch-py#2233]
**`elasticsearch-py` version (v8.8.1 and below)**: 

**Description of the problem including expected versus actual behavior**:
The type hint for the return value of the search functions is `ObjectApiResponse` though the right type seems to be `ListApiResponse`. This causes errors e.g., when using mypy.

**Comment by pquentin** [comment]
Hello! And sorry for the late reply. The mapping appears to be correct to me:

```python3
import elastic_transport
from elasticsearch import Elasticsearch

es = Elasticsearch("http://localhost:9200")
r = es.search(index="test-index", query={"match_all": {}})
assert type(r) == elastic_transport.ObjectApiResponse
```

**Comment by TzahiTaub** [comment]
Hi, thanks. I've meant `msearch` as in the subject of the issue, and not `search` as I wrote in the body.
