### ISSUE TITLE
Support `percolate_format` param in `mpercolate` method

### ISSUE THREAD

**Issue by evansd** [elastic/elasticsearch-py#224]
The `percolate_format` parameter is supported in the `percolate` method, but not in the `mpercolate` method.

As far as I can tell, this has to be passed as a query parameter on the request and can't be passed in the header JSON of the bulk body.

This should just be a case of adding `percolate_format` to the `@query_params` decorator (I've tested this and it works), but I don't know if this violates some design principle of the library.

**Comment by HonzaKral** [comment]
Thanks, I just haven't updated the optional params in a while, I will do a sync with the official spec soon.

**Comment by HonzaKral** [comment]
So with `mpercolate` the situation is a little different - you need to specify the `percolate_format` in each *header* line since it's only relevant in the context of a single percolation request, for example:

    {"percolate" : {"index" : "twitter", "type" : "tweet", "percolate_format": "ids"}}
    {"doc" : {"message" : "some text"}}
    {"percolate" : {"index" : "twitter", "type" : "tweet", "id" : "1"}}
    {}

Hope this helps

**Comment by evansd** [comment]
Thanks! I thought I tried that earlier and it didn't work, but maybe I got the syntax wrong. I'll try again tomorrow.

**Comment by evansd** [comment]
I've just tried this and I doesn't seem to work. This is using v.1.4.0 of the library and v1.5.1 of Elasticsearch itself.

Adding `percolate_format` to the query params produces the desired effect, but adding it in the header does nothing.

I agree that it _ought_ to be possible to set it in the header. Possibly this is a bug in Elasticsearch.

**Comment by HonzaKral** [comment]
This is not really an issue of elasticsearch-py, belongs to elasticsearch instead.
