### ISSUE TITLE
on python 2.6, es-py requires unittest2 as runtime dependency

### ISSUE THREAD

**Issue by Xylakant** [elastic/elasticsearch-py#225]
in https://github.com/elastic/elasticsearch-py/blob/master/setup.py#L29, unittest2 is added as an install dependency instead of as a test dependency. I assume that's by mistake since it doesn't seem to be used except for the test suite.

**Comment by HonzaKral** [comment]
It is used in https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/test.py#L5

**Comment by GlenRSmith** [comment]
Right, and that's *test* code. Shouldn't setup.py then have:
```
# use external unittest for 2.6
if sys.version_info[:2] == (2, 6):
    test_requires.append('unittest2')
```
?

**Comment by HonzaKral** [comment]
That is code that other projects can use in their codes, it's not just there for our tests.
