### ISSUE TITLE
Update docs to refect the addition of search_application 

### ISSUE THREAD

**Issue by m-adams** [elastic/elasticsearch-py#2253]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.8.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  8.8.2

**Description of the problem including expected versus actual behavior**:

It looks like the python docs haven't been updated to include the search application APIs although it does seem to work in the client if you guess the correct calls.

e.g. https://www.elastic.co/guide/en/elasticsearch/reference/8.8/put-search-application.html

doesn't seem to be referenced in the master docs https://elasticsearch-py.readthedocs.io/en/latest/api.html

**Comment by szabosteve** [comment]
Docs are fixed, thanks @JoshMock for the fix and @m-adams for creating the issue.
