### ISSUE TITLE
Enable Private Vulnerability Reporting in GitHub

### ISSUE THREAD

**Issue by munahaf** [elastic/elasticsearch-py#2265]
In your repository, we have found a bug that may require your attention. We do not want to disclose the details. Therefore, we request you to enable private vulnerability reporting in your repository.

**Sponsorship and Support:**
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.

The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.

**Comment by pquentin** [comment]
Hello, here's how you can submit security issues for Elastic products: https://www.elastic.co/community/security. The relevant HackerOne asset name is "Elastic Clients". I think we should indeed add this info to the repositiry, so I'll keep this open until it's done.

**Comment by munahaf** [comment]
The bug is about replacing a potentially insecure library with a safe library call. I submitted the information by email. I did not report by HackerOne since the impact is probably low and I did not create a reproducer.

**Comment by harshlastic** [comment]
Hello @munahaf,
Please submit any vulnerability findings and reports to our bug bounty program at https://hackerone.com/elastic.

**Comment by munahaf** [comment]
Submitting the bug as an issue here, per suggestion.

**Comment by pquentin** [comment]
Also the repository *has* a security policy where this information is shared: https://github.com/elastic/elasticsearch-py/security/policy.
