### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by heinrichreimer** [elastic/elasticsearch-py#2274]
It would be incredibly useful for the Elasticsearch Python API to have type annotations for the API endpoints.

**Describe the feature**:
The package should include type annotations or stubs and be declared as a [PEP 561 compliant stub package](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages).

**Comment by JoshMock** [comment]
This project does already include type annotations, and declares itself to be PEP 561 compliant in the setup.py. https://github.com/elastic/elasticsearch-py/blob/21a97dc84843ffe0c7a397148472847951340147/setup.py#L73

Is there some other type annotation support missing that you still need?

**Comment by pquentin** [comment]
Closing, but I'll reopen if we get more details. Thank you!
