### ISSUE TITLE
Add synonyms and query rules APIs 

### ISSUE THREAD

**Issue by kderusso** [elastic/elasticsearch-py#2288]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.10.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.10.0

**Description of the problem including expected versus actual behavior**: The synonyms and query rules APIs have been added to the JavaScript client but still need to be added to the Python client. They should have gotten updated with 8.10 work but it looks like there may be additional work to do. 

Also per https://github.com/elastic/elasticsearch-py/pull/2269 there is some manual work required to add these APIs to the docs.

**Comment by JoshMock** [comment]
Looks like codegen is failing for the 8.10 branch, both in automation and when I try locally. Specifically when generating the synonyms API code. @pquentin had a possible fix in the code generator for it, but I don't think he's pushed it up yet. That might be the key to setting everything right again.

**Comment by kderusso** [comment]
@JoshMock Is there an ETA for this fix? Thanks!

**Comment by pquentin** [comment]
> @pquentin had a possible fix in the code generator for it, but I don't think he's pushed it up yet. That might be the key to setting everything right again.

The one-line fix was for #2273, but I opened #2299 to fix this issue. It did require some manual adjustments, I suspect the code generation does not fully work for net-new APIs.
