### ISSUE TITLE
Unable to use bulk helper operation

### ISSUE THREAD

**Issue by rodmaz** [elastic/elasticsearch-py#2298]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.10.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.9.0

We are currently unable to use the client helper function `bulk` due to inconsistent documentation and examples [here](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/client-helpers.html) and [here](https://elasticsearch-py.readthedocs.io/en/v8.9.0/helpers.html).
We are using data stream and operation should be `create` as documented by Elastic.

**Steps to reproduce**:

This is our basic code:

```
try: 
    response = elasticsearch.bulk(operations=bulk_entries, index='test-events.events')
    logger.info(f'result: {response}')
except:
    logger.exception(f'an error occurred while persisting events into Elastic')
```

And `build_entries` is a `list` of objects just like this:

```
{
      "_op_type": "create",
      "doc": {
            "@timestamp": 1691619563650,
            "event.id": "event-1"
      }
}
```
This fails with error `failed to parse: data stream timestamp field [@timestamp] is missing`.

We tried other combinations such as 

```
{
      "create": {},
      "doc": {
            "@timestamp": 1691619563650,
            "event.id": "event-1"
      }
}
```
The latter only bulk inserts the last item.

**Comment by pquentin** [comment]
Hello, and thanks for this question. There are three issues here.

## Issue 1 : not using the bulk helper 

> ```python3
> try: 
>     response = elasticsearch.bulk(operations=bulk_entries, index='test-events.events')
>     logger.info(f'result: {response}')
> except:
>     logger.exception(f'an error occurred while persisting events into Elastic')
> ```

You're using the bulk API directly, not the bulk helper (under `elasticsearch.helpers.bulk`). By the way, to reduce confusion, I would suggest that you name your `Elasticsearch()` instances `es` or `client`, not `elasticsearch`, which is the name of the package itself:

```python3
from elasticsearch import Elasticsearch
import elasticsearch.helpers

es = Elasticsearch("http://localhost:9200")

elasticsearch.helpers.bulk(es, ...)
```

## Issue 2: set vs list

> We tried other combinations such as
> 
> ```python3
> {
>       "create": {},
>       "doc": {
>             "@timestamp": 1691619563650,
>             "event.id": "event-1"
>       }
> }
> ```
> 
> The latter only bulk inserts the last item.

Your `bulk_entries` are [set literals](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset) with curly brackets, which means only one `create` or `doc` entry is going to be kept. You need to use a [list literal](https://docs.python.org/3/library/stdtypes.html#lists) with square brackets instead.

This could explain why you saw only the last item being kept.

## Issue 3: Providing `doc` when `op_type` is `create`

> And `build_entries` is a `list` of objects just like this:
> 
> ```python3
> {
>       "_op_type": "create",
>       "doc": {
>             "@timestamp": 1691619563650,
>             "event.id": "event-1"
>       }
> }
> ```
> 
> This fails with error `failed to parse: data stream timestamp field [@timestamp] is missing`.

I was confused for a while too, but then realized that `doc` is only used for partial upserts using the `update` operation type, as documented in https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html. And this is what is used as an example in the documentation. For `create`, you should inline the fields like this:

```python3
import elasticsearch.helpers

bulk_entries = [
    {
        "_op_type": "create",
        "_index": "my-data-stream",
        "@timestamp": 1691619563650,
        "event.id": "event-1",
    },
]

try:
    elasticsearch.helpers.bulk(es, bulk_entries)
except elasticsearch.helpers.BulkIndexError as e:
    print(e.errors)
```

The Python client also has a nice feature where you can use `_source` and it will convert it to the above form:

```python3
bulk_entries = [
    {
        "_op_type": "create",
        "_index": "my-data-stream",
        "_source": {
            "@timestamp": 1691619563650,
            "event.id": "event-1",
        },
    },
]
```

Note that if you do want to use the bulk API directly without the helper, you need to encode the body yourself, like this:

```python3
bulk_entries = [
    {"create": {"_index": "my-data-stream"}},
    {"@timestamp": 1691619563650, "event.id": "event-1"},
]
serialized_bulk_entries = "\n".join(json.dumps(entry) for entry in bulk_entries)

resp = es.bulk(operations=serialized_bulk_entries)
assert resp.body["errors"] is False
```
