### ISSUE TITLE
Multithread workers or asyncio for python api?

### ISSUE THREAD

**Issue by ourlord** [elastic/elasticsearch-py#233]
According to some restrictions, I'm developing some apps on top of es's python api (both py and dsl-py) and some performance issues come with doing multiple searches in a short period of time.
I've been thinking adding some asyncio support for this library or developing a mutlithread worker pool on my apps. Just wish to ask will this be a good idea for REST calls? As far as I know, both only using java API would allow me to manage a non-RESTful access to es.

Thanks.

**Comment by HonzaKral** [comment]
You can very easily just use the library from multithreaded environment. Doing requests in parallel from multiple threads should help performance. Asyncio though is currently not supported unfortunately.

Hope this helps

**Comment by ourlord** [comment]
Good to know! I heard some people said using asyncio for REST call would mess up things that's why I came up to ask. I'll try something first, thank you!

**Comment by HonzaKral** [comment]
The proper way would be to create a single instance and share it across threads - the underlying connection pooling (by `urllib3` by default) is thread safe so that way connections will be reused across threads.
