### ISSUE TITLE
7.17.10 and 7.17.11 are missing from PyPI

### ISSUE THREAD

**Issue by alyssais** [elastic/elasticsearch-py#2336]
https://pypi.org/project/elasticsearch/#history

**Comment by pquentin** [comment]
Hello! The versions were automatically updated in https://github.com/elastic/elasticsearch-py/commit/2df8131012a5d66be5f519a702cbc2937a3d8f67 and https://github.com/elastic/elasticsearch-py/commit/8df37a6925b7dc3695c0d497a5cb6a0f947353e6, but as there was no observable change, there is no need to perform a release, which is a manual process.
