### ISSUE TITLE
Index document using parent field example.

### ISSUE THREAD

**Issue by blacktop** [elastic/elasticsearch-py#234]
ERROR: TransportError(400, u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]")

I can't seem to find any examples of the parent child pattern.  Please help, thank you.

**Comment by HonzaKral** [comment]
To use the parent/child functionality it first needs to be enabled in the mappings: https://github.com/elastic/elasticsearch-py/blob/master/example/load.py#L79-L92

and then you can use the API: 

    es.index(index='index-name', doc_type='child_type', id='42', body={'doc': 'data'}, parent='parent_id')

hope this helps.

**Comment by HonzaKral** [comment]
Also note that this might be easier with `elasticsearch-dsl` (0) where you can specify the doc types more easily:

    class ParentType(DocType):
        pass

    class ChildType(DocType):
        class Meta:
            parent = MetaField(type='parent_type')

    i = Index('my-index')
    i.doc_type(ParentType)
    i.doc_type(ChildType)
    i.create()

    child = ChildType(meta={'parent': 'parent_id'})
    print(child.meta.parent)
    child.save()

0 - https://github.com/elastic/elasticsearch-dsl-py

**Comment by 0x64746b** [comment]
Should Google have brought you here, cf http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#class-meta-options
