### ISSUE TITLE
Possible Bug In Tracer Code?

### ISSUE THREAD

**Issue by rholloway** [elastic/elasticsearch-py#236]
I am not familiar with this code base at all but did notice the following in logs when debugging my app, from connection/base.py (line 73 in 23609dc02cf23d7744baa9f28acab7dd9c751f71 )

tracer.info("curl -X%s 'http://localhost:9200%s' -d '%s'", method, path, _pretty_json(body) if body else '')

I'm not running ES locally for any of my code - should this reference self.host instead of being hard coded to localhost:9200?

**Comment by HonzaKral** [comment]
In the tracer the idea is for the code to be reproducible for anyone running elasticsearch, or to be used to paste somewhere public with the description of a technique or a problem. Therefore we put in `localhost:9200` explicitly as to not reveal possibly sensitive information and allow people to paste examples created using the tracer into their command line without need for edits.

Does that make sense?

**Comment by rholloway** [comment]
Perhaps. I'm not familiar with the tracer but it seems to turn on automatically when I switch to logging.DEBUG. Just making sure it wasn't a typo. In my case, that was the last line in a log file before the application hung and I thought it was attempting the actual curl request against localhost and hanging or timing out (since I'm not running locally).

Based on your response though it sounds like it's just printing an example curl statement in case it needs to be shared publicly - it's not actually attempting to execute in that way. Thanks for the clarification!

**Comment by HonzaKral** [comment]
Yes, it is just a debugging tool essentially. The real logger (`elasticsearch`) actually reports the correct host:port that is being used.
