### ISSUE TITLE
Reset connections when forking

### ISSUE THREAD

**Issue by aaugustin** [elastic/elasticsearch-py#237]
I have an indexing process that is partly CPU-bound on the server that grabs the data and feeds it to ElasticSearch. I'm trying to parallelize the CPU-bound parts of that process with `multiprocessing`.

Unfortunately, the first action in the subprocess fails with a timeout because this library maintains a connection pool and sockets don't survive forking. I would like to close the connections just before forking. Is there a way to do that?

My alternative is to recreate the connection, but I have a layer of abstraction (`djangoes`) that gets in the way.

EDIT: in fact it doesn't get in the way, I could fix my problem with:

    from djangoes import connections
    del connections['xxx']

I'm OK with closing this issue as wontfix, but some documentation around connection persistence would be nice.

**Comment by HonzaKral** [comment]
Good point, I "fixed" it with docs. If more people will hit this issue I will add some detection (for now I don't believe it is worth the overhead, however small).

Thanks!
