### ISSUE TITLE
Latest download of transitive dependency elastic-transport-python of version 8.10.0 is breaking with an error Cannot Import Name DEFAULT_CIPHERS From Urllib3.Util.Ssl_ On AWS Lambda Layer

### ISSUE THREAD

**Issue by yanamachintalavandana** [elastic/elasticsearch-py#2377]
The version in the line https://github.com/elastic/elasticsearch-py/blob/main/dev-requirements.txt#L1 must be elastic-transport>=8.0.0b1, <8.4.1 else it breaks with the error Cannot Import Name DEFAULT_CIPHERS From Urllib3.Util.Ssl_ On AWS Lambda Layer because there is an update of urllib version in https://github.com/elastic/elastic-transport-python/commit/65424ca058388b9757c7b64e83fbb129c4833fb5#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR5

**Comment by pquentin** [comment]
Hello! And sorry that your installation broke. However, this is not an elasticsearch-py issue or even an elastic-transport-python issue.

As mentioned in the [urllib3 v2 common upgrading issues](https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html#common-upgrading-issues), this means that your version of botocore does not support urllib3 2.0. If you're using Python 3.10 or above, recent versions of botocore supports urllib3 2.0, but that means you may have to update botocore to get a recent version.

I'm not familiar with AWS Lambda, but if you install your dependencies using `pip install --upgrade elasticsearch-py boto3 botocore` (or equivalent), then pip will do the right thing: installing urllib3 2.x only on Python 3.10 or above.
