### ISSUE TITLE
helpers.reindex does not keep _timestamp

### ISSUE THREAD

**Issue by JulienPalard** [elastic/elasticsearch-py#240]
o/

I use a `{"_timestamp": {"enabled": True, "store": True},` mapping to let ES automatically generate timestamp, so my timestamps are typically not in my _source document.

Yet I think getting and reinserting with the correct _timetsamp may be better, if possible.

**Comment by HonzaKral** [comment]
Yes, this is a bug that results in lack of implicit support in elasticsearch (it is being worked on in https://github.com/elastic/elasticsearch/issues/8068).

I will close this ticket in favor of https://github.com/elastic/elasticsearch-py/issues/140 where we track this.
