### ISSUE TITLE
more_like_this bug in django-restframework

### ISSUE THREAD

**Issue by lanhui100** [elastic/elasticsearch-py#2404]
**django_restframework project more_like_this query bug**:

**Elasticsearch version** (`bin/elasticsearch --version`): 8.11.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.11.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**: 
post more_like_this query:
Error Info:
BadRequestError at /api/v1/cdd/search/resume/1/more_like_this/
BadRequestError(400, 'parsing_exception', 'failed to parse More Like This item. unknown field [_type]')

Local vars:
body:
{'query': {'more_like_this': {'fields': ('education_experience.school_name',
                                         'education_experience.major',
                                         'education_experience.degree',
                                         'work_experience.company_name',
                                         'work_experience.job_title',
                                         'work_experience.description'),
                              'like': {'_id': '1',
                                       '_index': 'resume',
                                       '_type': 'properties'}}}}

[ It seems that ES 8 have already remove the _type params? but this version ES-py seems not sync.]
**Steps to reproduce**:
![Uploading 1702960354357.png…]()

**Comment by pquentin** [comment]
Hello! The `more_like_this` functionality comes from [django-elasticsearch-dsl-drf](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/more_like_this.html). We have four libraries involved here:

 *  django-elasticsearch-dsl-drf itself which does not support Elasticsearch 8 and honestly appears a bit unmaintained at first glance (it still mentions Elasticsearch 6 as the latest version). It depends on django-elasticsearch-dsl.
 * django-elasticsearch-dsl is maintained by the community and [recently added support for Elasticsearch 8](https://github.com/django-es/django-elasticsearch-dsl/releases/tag/8.0). It depends on elasticsearch-dsl-py.
 * elasticsearch-dsl-py and dependency elasticsearch-py (you are here!) are maintained by Elastic and also support Elasticsearch 8.

To keep using Elasticsearch 8, you could create a [more-like-this query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html) without using django-elasticsearch-dsl-drf. elasticsearch-dsl-py supports it: https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#more-like-this-query. Which means you could use `django-elasticsearch-dsl` to automatically get a `Document` for you and run this query. See https://django-elasticsearch-dsl.readthedocs.io/en/latest/quickstart.html for details.

In any case, closing as this is not an elasticsearch-py bug. Thank you!

**Comment by lanhui100** [comment]
thank you. 
I have located the bug in MoreLikeThisMixin of django-elasticsearch-dsl-drf.  The library seems out of date.
