### ISSUE TITLE
AsyncElasticsearch client closes event loop when used with TestClient from Pytest after only 2 queries

### ISSUE THREAD

**Issue by pumpkin-pies** [elastic/elasticsearch-py#2410]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.10.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 
7.17.0

**Description of the problem including expected versus actual behavior**:
I have such problem as https://github.com/elastic/elasticsearch-py/issues/2051 but in my case I'm using only TestClient, not AsyncTestClient:
```
@pytest.fixture()
def client() -> TestClient:
    apply_migration()
    return TestClient(app())
```
where app is FastAPI app
and after running a test
```
def test_get_filters_without_params(client: TestClient):
    all_filters = client.get('/request-to-elasticsearch')
    all_filters = client.get('/equest-to-elasticsearch')
```
I have `ConnectionError(Event loop is closed) caused by: RuntimeError(Event loop is closed)`

**Steps to reproduce**:

My request to elasticsearch:
```
try:
    resp = await self._es_client.search(
        index=index,
        body=body,
    )
except Exception as e:
    print('exception: ', e)
```

In previous issue the decision was to create AsyncElasticsearch every time, but I can't do it in my case:( Maybe someone has any ideas to fix it?

**Comment by pumpkin-pies** [comment]
sorry it's not about `AsyncElasticsearch ` client, closing this issue

**Comment by pquentin** [comment]
Glad that you were able to solve your problem! If you can share what the issue was, it will help anyone that is seeing the same error.

**Comment by shoang22** [comment]
Hi @pumpkin-pies! Would you mind sharing how you resolved the issue? I'm currently creating a separate connection for each test, and I want to be able to use only one connection.

**Comment by ShtykovaAA** [comment]
@shoang22 hi! sorry if its too late, I added fixture to conftest file, [link](https://anyio.readthedocs.io/en/stable/testing.html#specifying-the-backends-to-run-on ) to docs  
```python
@pytest.fixture
def anyio_backend():
    return 'asyncio'
```

**Comment by baughmann** [comment]
Im afraid I'm experiencing the same issue. **Exactly** two connections. Unfortunately adding what @ShtykovaAA said to the to conftest did not help
