### ISSUE TITLE
[DOC] Add more Python Client code examples to main Elasticsearch Docs

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch-py#2429]
👋 howdy, team!

**Describe the feature**:

@scranberryjam & I would like to add more [Elasticsearch Client](https://www.elastic.co/guide/en/elasticsearch/client/index.html) content to the [Elasticsearch API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html). 

<details><summary>example difference</summary>

---

Examples for [Cluster API's](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.html)
- does have [Cluster Health](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html)
    <img width="438" alt="image" src="https://github.com/elastic/elasticsearch-py/assets/26751266/08654939-0c4f-44cd-9b78-52158a1a7e31">
- does NOT have [Allocation Explain](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html)
    <img width="432" alt="image" src="https://github.com/elastic/elasticsearch-py/assets/26751266/e94b7e89-7c1b-478c-a498-0d6fb82a00e0">

---

</details>

(Taking Python as the first language, since I'm most comfortable with it,) It doesn't appear these code examples are in-line in the [Elasticsearch docs code](https://github.com/elastic/elasticsearch/tree/main/docs/reference). Instead it appears Python examples surface in Elasticsearch Docs via [this repo's code for "doc examples"](https://github.com/elastic/elasticsearch-py/tree/main/docs/examples). 

Checking these files' history, it appears these may be auto-generated (last done 2023Sep via [#2312](https://github.com/elastic/elasticsearch-py/pull/2312), [commit before](https://github.com/elastic/elasticsearch-py/commit/e3e109a362f98430e123c5e970275712daf4b58d))? (Is that part of the [Auto-generate API](https://github.com/elastic/elasticsearch-py/blob/main/CONTRIBUTING.md#api-code-generation)?) 

Do these need to be re-generated periodically or is there a project here I could help on to fill in more pages?

Initial examples confirmed not having ES-doc Python code examples: [Elasticsearch doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html) 👉 [ES-Py doc > ClusterClient](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/cluster.html)
-  [Allocation Explain](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html) 👉 [`allocation_explain`](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/cluster.html#elasticsearch.client.ClusterClient.allocation_explain) 
- [Get Cluster Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-get-settings.html) 👉 [`get_settings`](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/cluster.html#elasticsearch.client.ClusterClient.get_settings)
- [Update Cluster Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html) 👉 [`put_settings`](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/cluster.html#elasticsearch.client.ClusterClient.put_settings)
- [Health](https://www.elastic.co/guide/en/elasticsearch/reference/current/health-api.html) 👉 [`health`](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/cluster.html#elasticsearch.client.ClusterClient.health)
- [Cluster Reroute](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html) 👉 [`reroute`](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/cluster.html#elasticsearch.client.ClusterClient.reroute) 

**EDIT** : I believe the "list to generate" is determined from [this code](https://github.com/elastic/elasticsearch-py/blob/main/utils/generate-examples.py#L42).

**Comment by pquentin** [comment]
Thanks! I worked on the first step, which is to fix the current script that was failing with the latest examples: https://github.com/elastic/elasticsearch-py/pull/2449.

Adding more pages indeed requires adding entries in `files_to_generate` in that script you found, and see if the result is correct or not.

**Comment by stefnestor** [comment]
Thanks, @pquentin! 💚 

@anniegale9538 / @scranberryjam, wants to take first stab, but I'll put up a PR by next week if she doesn't get to it.

**Comment by stefnestor** [comment]
These examples are live & Annie has the gist on how to do the project. Thanks for the assist, Quentin! We're interested in adding more examples & may reference this issue but core ones needed were listed and are completed, so closing. 💚
