### ISSUE TITLE
Add support for include_named_queries_score param in _search endpoint

### ISSUE THREAD

**Issue by styrmis** [elastic/elasticsearch-py#2443]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.8.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.12.0

**Description of the problem including expected versus actual behavior**:

The `include_named_queries_score` is [present in the REST API spec](https://github.com/elastic/elasticsearch/blob/4faaa284994c02a3b34e4c6f8406e04ddedccb2b/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L244) but it does not appear to have been picked up in the generation process for this library.

There is [a generated example](https://github.com/elastic/elasticsearch-py/blob/6a96e38e3146f0a85939f460958a6aa256456d90/docs/examples/39ce44333d28ed2b833722d3e3cb06f3.asciidoc?plain=1#L6) which uses the param, but this fails for me as the param is not defined, which matches [the docs for the search method](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/elasticsearch.html#elasticsearch.Elasticsearch.search).

To work around this we are currently experimenting with making a lower-level request, e.g.

```
resp = es.transport.perform_request(
    'GET',
    f'/{index}/_search?include_named_queries_score=true',
    headers={'Content-type': 'application/json'},
    body=body
)
```

The expected behaviour is that it be possible to specify the `include_named_queries_score` parameter (as per the example) and that the response would have the `matched_queries` key set, with calculated scores, if the submitted query body contains named queries.

**Steps to reproduce**:

Run [the generated example](https://github.com/elastic/elasticsearch-py/blob/6a96e38e3146f0a85939f460958a6aa256456d90/docs/examples/39ce44333d28ed2b833722d3e3cb06f3.asciidoc?plain=1#L6) which sets `include_named_queries_score`.

**Comment by pquentin** [comment]
Sorry for not replying earlier! This will be fixed in 8.15, most likely, thanks to https://github.com/elastic/elasticsearch-specification/pull/2729.
