### ISSUE TITLE
The index api overwrite the existing doc

### ISSUE THREAD

**Issue by JackWang917** [elastic/elasticsearch-py#245]
When I used the following api, the existing data were overwritten. 
res = es.index(index="panavstream", doc_type='panav', id="aa", body=doc)

For example, I have id=1,name=Tom, right I wanna add job=teacher, but the name field was removed by the new index.

**Comment by HonzaKral** [comment]
Yes, this is defined behavior of elasticsearch. If you want to update an existing document please use the upradet API.

**Comment by JackWang917** [comment]
Thank you so much HonzaKral, is there a updateAndInsert function, I do need insert and update(if the id already exists), Thanks a lot!

**Comment by JackWang917** [comment]
Hi HonzaKral,
When I use update() as the following, it throw an exception:elasticsearch.exceptions.RequestError: TransportError(400, u'ActionRequestValidationException[Validation Failed: 1: script or doc is missing;]
doc1 = {
    "user":"Jack",
    "BJ":"not"
}
map = {'doc_as_upsert': 'true'}
res = es.update(index="panavstream", doc_type='panav', id="111", body=doc1)

Thanks
Jack

**Comment by HonzaKral** [comment]
Yes, update can have an `upsert` clause.

The error you are seeing is because you didn't specify the body in proper format, it should be:
`{'doc': {'user': '...','BJ': '...'}}`. See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html for more information

**Comment by goravsingal** [comment]
Update api accepts the body in "doc"
See: https://www.gyanblog.com/gyan/59-elasticsearch-validation-failed-1-script-or-doc-missing
