### ISSUE TITLE
record search issue

### ISSUE THREAD

**Issue by ChandraReddy97** [elastic/elasticsearch-py#2451]
**Describe the feature**:

1. Not able to get/search records with the new `version 8.12.0`
2. i'm using this query to search records:
`{
    "sort": [{"updated_at": {"order": "desc"}}],
    "query": {
        "bool": {
            "must": [
                {"term": {"app_definition_code": "CCFS"}},
                {"term": {"tenant_id": "545500604902936576"}},
                {"term": {"template_id": "546153145542115328||Customer Collections Offset||DUE_DATE||0"}},
                {"term": {"application_id": "547003561838383104"}},
            ]
        }
    },
}`
3. but with the same query i can able to get records from this version `elasticsearch==7.17.6`

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
i'm not able to get records with the 8.12.0 , my elastic server is also upgraded to 8.12.

after connecting to elastic search server, i'm using this search method to get records:
`self.es.search(index="index-value", body=body, size=size)`

- params: body(above mentioned json search-query),size(100)

can you please suggest me on how to search records with the new version. is there anything to change on searching method or query etc.. please help me on this. that will be much helpful.
**Steps to reproduce**:

**Comment by pquentin** [comment]
Hello! Are you able to reproduce the issue in the Kibana Dev Tools Console? It will tell us if the client is the culprit or not. Alternatively, if you can share a document that would match, I could try to reproduce.

**Comment by pquentin** [comment]
Closing as I have not heard back from you.
