### ISSUE TITLE
reindex,change dynamic_template to non dynamic_template,it's failed.Is it a bug?

### ISSUE THREAD

**Issue by Judyccb** [elastic/elasticsearch-py#247]
I just delete the dynamic_template part of index template,I want to change dynamic_template to non dynamic_template and want to change the @timestamp field format.
However, the @timestamp of new index did not change to new  format
Could you give any suggestion?

**Comment by HonzaKral** [comment]
I am afraid I don't understand what you mean. Could you paste some examples of what you did and what you are trying to accomplish?
Thanks

**Comment by Judyccb** [comment]
There are 2 questions
1. I want to change the format of the @timestamp field from "143142006000" to "XXXX-XX-XX XX:XX:XX:"
by reindex.
The python script I used is:
elasticsearch.helpers.reindex(es, 'oldindexname', 'newindexname'), query=none, target_client=none, chunk_size=500, scroll='5m', scan_kwargs={}, bulk_kwargs={})
The new index has been created, and the mapping of @timestamp field is right,which is I want:
"@timestamp":{
"format":"yyyy-MM-dd HH:mm:ssZZ",
"doc_value":true,
"type":"date"
}
However, the content of @timestamp field is still "143142006000"by curl -XGET.
The mapping of @timestamp field in old index template is:
"@timestamp":{"type":"date","doc_values":true}
The mapping of @timestamp field in new index template is:
"@timestamp":{"type":"date","format":"yyyy-MM-dd HH:mm:ssZZ","doc_values":true}
2. The template of oldindex used dynamic_template. I want to change it to non dynamic by delete
which is as follow from the template of oldindex ,then reindex the index by new template which is without dynamic things.Is it possiable?

**Comment by HonzaKral** [comment]
1) The `format` parameter of `date` fields only dictate the parsing logic - the data is always stored exactly as you send it. Changing the format won't change that.

2) of course - just create a new index and override the mappings. Dynamic settings are most likely set by an index template in your case so you need to get rid of that one first.

**Comment by Judyccb** [comment]
Hi Honza,
Could you give more detail about your second suggestion "2)of course..."
What I need to change is only old index,I am afraid I had to use reindex. Do you mean I need to set the mapping field one by one  in new index template changing the dynamic to non dynamic then to reindex? Is there any convenient way?

**Comment by HonzaKral** [comment]
You have to reindex in order to change the mapping, you can set all the fields at once and you don't have to use idnex templates, you can just specify the mappings when creating the index.

I am afraid though that I still don't understand what you are trying to do, could you provide a concrete example of what you are trying to achieve?

**Comment by Judyccb** [comment]
It's  a long story,thanks for taking your time!
What I am really trying to archieve is change the @timestamp format.Because of your suggestion "1) The format parameter", I give up the way of defining the format I want in new index mapping directly.I used the plugin update-by-query to archieve this，https://github.com/yakaz/elasticsearch-action-updatebyquery, which is effective to 2 kinds of index in fact.However, 1 kind of index is invalid. I opened a new issue about this.
https://github.com/yakaz/elasticsearch-action-updatebyquery/issues/37.I am trying solve this so I compare the index mapping of effective one with invalid one. I found that the invalid one is created by dynamic-template, and the effective one is by non dynamic.So I want to reindex the dynamic index to non dynamic,then change the @timestamp by  update-by-query.
Thanks for taking your time again! any suggestion?

**Comment by HonzaKral** [comment]
Just create a new index with manual mappings and then reindex your data into it using, for example, the `reindex` helper (0). If you want to transform the documents as you reindex you can just see how `reindex` works and duplicate it yourself - call the `scan` and `streaming_bulk` helpers and use python to transform all the documents returning from `scan` before you feed them into `streaming_bulk`.

0 - http://elasticsearch-py.readthedocs.org/en/latest/helpers.html#elasticsearch.helpers.reindex

**Comment by Judyccb** [comment]
Hi HonzaKral
I am so happy to tell you that the problem has some progress.I found the @timestamp field of the invalid one is string type,which type can not be parsed by update-by-query.
However,a new problem appear.When I reindexed the invalid index from dynamic to non dynamic,why the type of @timestamp field of the new index is still string?
The dynamic template is as follow(sorry for the format),
![image](https://cloud.githubusercontent.com/assets/12627595/8600057/7a7c0ef2-2696-11e5-8bd1-567c5479a9c4.png)

**Comment by HonzaKral** [comment]
I am closing this since this is not really a python question, but more about usage of elasticsearch itself. Please turn to the forums (http://discuss.elasric.co) or contact me directly, I will be happy to help.

Thanks, and sorry for the delay.
