### ISSUE TITLE
Strange port behavour

### ISSUE THREAD

**Issue by danpilch** [elastic/elasticsearch-py#250]
When using the non-standard port '9200' elasticsearch seems to emit strange behaviour when using sniffing, more namely args:

sniff_on_connection_fail
sniff_on_start
retry_on_timeout

Checking with tshark I can see after a timeout the port im using '443' is switched back to the default '9200'...

40  41 449.783250 1.2.3.4 -> 5.6.7.8 TCP 76 44253 > 9200 [SYN] Seq=0 Win=14600 Len=0 MSS=1460 SACK_PERM=1 TSval=3468150098 TSecr=0 WS=256

^ I changed the IP addresses above.

Anyone ever seen this sort of behavour when using the non standard 9200 port?

**Comment by HonzaKral** [comment]
Can you share the code how you are instantiating the client please?

Thanks!

**Comment by danpilch** [comment]
def get_elasticsearch():
    """ get hold of the Elasticsearch API via the settings """
    if not hasattr(settings, 'ELASTICSEARCH_HOSTS'):
        err = 'Missing ELASTICSEARCH_HOSTS'
        logger.error(err)
        raise Exception(err)

    kwargs = {
        'hosts': settings.ELASTICSEARCH_HOSTS,
        'use_ssl': settings.ELASTICSEARCH_USE_SSL,

    }
    if getattr(settings, 'ELASTICSEARCH_ENABLE_SNIFF', False) is True:
        sniff_conf = {
            'sniff_on_start': True,
            'sniff_on_connection_fail': True,
            'sniffer_timeout': 60,
            'retry_on_timeout': True
        }
        kwargs.update(sniff_conf)
    if hasattr(settings, 'ELASTICSEARCH_USER') and \
            hasattr(settings, 'ELASTICSEARCH_PASS'):
        kwargs['http_auth'] = (
            settings.ELASTICSEARCH_USER,
            settings.ELASTICSEARCH_PASS)
    if settings.ELASTICSEARCH_USE_SSL:
        kwargs['verify_certs'] = True
        kwargs['ca_certs'] = certifi.where()

    es = Elasticsearch(**kwargs)
    return es

We have yet to supply more than one client so:

ELASTICSEARCH_HOSTS = "client.com:443"

**Comment by HonzaKral** [comment]
And what does your cluster look like, are you connecting directly to the nodes? or are you using a load balancer?

From your setup I guess that you are using a load balancer which means that sniffing won't really work - it will get the list of nodes from elasticsearch and try to connect to them directly on the port which they are running on (9200). Could this be the case?

**Comment by danpilch** [comment]
I've got a cluster of 4 nodes, they are all connected to directly and are using port 433 (proxied behind nginx) as their outbound port. (they're running on localhost:9200 internally) I can't figure out how to get ES to announce it is running on 443 behind a proxy...

**Comment by danpilch** [comment]
I think I just found the setting: 'http.publish_port' !

**Comment by HonzaKral** [comment]
I am sorry, if you are using nginx there is no way for the sniffing mechanism to know about it.

If there is nginx on every node on port 443 you can provide a `host_info_callback` parameter and supply your own callback that will change the port to 443. you can see the default implementation here: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L15-L36

Simply just override the `port` key in the `host` parameter before returning it

**Comment by HonzaKral** [comment]
Or yes, use the `http.publish_port` if you want this information to be visible in the cluster info and not just used in python.

**Comment by danpilch** [comment]
OK I will test this and report back. Thanks for your help.

**Comment by danpilch** [comment]
This fixed the issue with the incorrect port being reported. thanks
