### ISSUE TITLE
Unable to connect via AsyncElasticsearch using ssl fingerprint

### ISSUE THREAD

**Issue by AnujShahSifthub** [elastic/elasticsearch-py#2527]
I had to switch from Elasticsearch to AsyncElasticsearch recently. However, I am facing an issue when attempting to connect using ssl fingerprint using the following key while making a connection. The same seems to be working when using Elasticsearch 

ssl_assert_fingerprint=ELASTICSEARCH_CERTS

The error that pops up is ConnectionError(Connection error caused by: ServerFingerprintMismatch(

**Comment by pquentin** [comment]
Hello! And sorry for the delay in getting back to you. Unfortunately I'm not reproducing your issue. Can you please mention the version of Elasticsearch, elasticsearch-py and elastic-transport-python, as well as your Python version?

Note that if you are using Python 3.10 and above, the Elasticsearch client is able to verify using any certificate in the chain, including the root certificate authority, but `AsyncElasticsearch` does not support that. So if you're for example using the fingerprint of the root certificate authority, it is expect that it works with `Elasticsearch` but not `AsyncElasticsearch`. To check that, you can give a different fingerprint to `Elasticsearch`, and it will report the certificates of the chain, like this (the formatting is mine):

```
elastic_transport.TlsError: TLS error caused by: TlsError(
    TLS error caused by: SSLError(
        Fingerprints did not match.
        Expected "fd6e9b0ef398bcd904c3b2ec167a7b0fda7201c903c53a6a6ae5d0414363ef65", got
        "dc179eb67a0d04ab6d635e4ff2ffb3c3150a3c589e2b8af7b71ca840f28f3f7b",
        "67add1166b020ae61b8f5fc96813c04c2aa589960796865572a3c7e737613dfd",
        "96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6".
    )
)
```

And then you have to make sure to use the first certificate (`dc179eb67a0d04ab6d635e4ff2ffb3c3150a3c589e2b8af7b71ca840f28f3f7b` in this case) when using `AsyncElasticsearch`.
