### ISSUE TITLE
Wildcard behavior while using indices client is a bit unpredictable.

### ISSUE THREAD

**Issue by syllogismos** [elastic/elasticsearch-py#258]
When I'm using wildcard while getting indices stats, its returning me all indices.

```
ic = IndicesClient(es)
inds = ic.status(index = "test-*")['indices'].keys()
```

inds contains all the indexes in the cluster if I don't have any indexes that start with the prefix `test-` in my cluster..

When I do have indices that start with `test-` I am getting only those indices. Is there a reason for that. I was planning to delete a set of indexes that start with some prefix, and when I use this get all the indices that start with a something, and if I don't have any indices that start with that given prefix, `ic.stats` is returning me all indices.

**Comment by HonzaKral** [comment]
I am afraid this is an issue with elasticsearch itself, we are just sending all the parameters over and don't control or interfere with the response. Sorry we cannot be of help here.
