### ISSUE TITLE
py>=3.10 client>7.10.0 can not  run

### ISSUE THREAD

**Issue by 1753936488** [elastic/elasticsearch-py#2582]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Because of this code, I was unable to run clients above version 7.10.0 in an environment above python3.10.
```python
try:
    from collections.abc import Mapping
except ImportError:
    from collections import Mapping
```

how to resove it?

**Comment by pquentin** [comment]
This was fixed in elasticsearch-py 7.12.0. You should upgrade at least to 7.17 and preferably to 8.x. Thanks.
