### ISSUE TITLE
Set canonicals to point to elastic.co

### ISSUE THREAD

**Issue by russorat** [elastic/elasticsearch-py#259]
As per http://docs.readthedocs.org/en/latest/canonical.html, we should set the canonicals on rtdocs.org to point to elastic.co docs so that google indexes the right page.

https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/index.html

@andrewvc

**Comment by HonzaKral** [comment]
The issue is that elastic.co doesn't include the whole docs, just the overview page. And even that one is different.

For technical reasons (asciidoc VS sphinx) we cannot easily mirror the content in both readthedocs and elastic.co.

**Comment by russorat** [comment]
oh, well if the content isn't duplicated, then it doesn't matter. Sorry about that.
