### ISSUE TITLE
SSLError([Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by zzk2021** [elastic/elasticsearch-py#2595]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Error message:

elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([Errno 2] No such file or directory)) [ERROR] - runway_for_ml.experiment : Uncaught exception: <class 'elastic_transport.TlsError'> --> TLS error caused by: TlsError(TLS error caused by: SSLError([Errno 2] No such file or directory))

**Comment by pquentin** [comment]
Hello, I am going to need more information than that to help you. The error message suggests the Python ssl module cannot find the CA certificate files, but I don't know how you are using the client and if you any specific configuration. A small code snippet that reproduces the error would help here, as well as the full output.

**Comment by pquentin** [comment]
Closing as I've not heard back from you, but feel free to provide more detail and I will reopen. Thank you!
