### ISSUE TITLE
delete method of Elasticsearch class can delete mapping or index

### ISSUE THREAD

**Issue by vaibhavnegi9** [elastic/elasticsearch-py#260]
if id argument of delete method is either of None , '' , () or [] , then mapping will be deleted.

delete method invokes _make_path function which creates a URL string from parts of path provided.
It skips a part if it is in (None , '' , () or [] ) and returns the URL string formed. 
delete method then invokes perform_request method with "DELETE" method . 

The document says "Delete a typed JSON document from a specific index based on its id." . But, unknowingly it can delete the mapping in the elasticsearch index.

**Comment by HonzaKral** [comment]
If you pass in an empty value for `id` argument the call will fail with `ValueError` due to the check in the method https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L669-L671

Could you please verify that you have the latest version?
Thanks!

**Comment by vaibhavnegi9** [comment]
I am using version 1.2.0 . I will update to latest version. Thanks .

On Tue, Aug 18, 2015 at 2:14 PM, Honza Král <notifications@github.com>
wrote:

> If you pass in an empty value for id argument the call will fail with
> ValueError due to the check in the method
> https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L669-L671
>
> Could you please verify that you have the latest version?
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-py/issues/260#issuecomment-132121730>
> .
>



-- 

Thanks and Best Regards

Vaibhav Negi

Mob: +91 9990259059
