### ISSUE TITLE
_cat indices returning None for stats for some indices, raw curl returns data

### ISSUE THREAD

**Issue by jascott1** [elastic/elasticsearch-py#2613]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.16.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7-7.17.9

**Description of the problem including expected versus actual behavior**:
Calling "cat.indices" returns None for some indices stats although `curl _cat/indices` returns actual stats.

**Steps to reproduce**:
Instantiate python Elasicsearch version 7 or 8 client.  

Call "cant.indices(format=json,bytes=b)". 

Observe problem index:  
`{'health': 'green', 'status': 'open', 'index': 'myindex', 'uuid': 'XyD5LntFQTO6Oc2VMpd2PA', 'pri': '1', 'rep': '1', 'docs.count': None, 'docs.deleted': None, 'store.size': None, 'pri.store.size': None}`. 

Compare to same index data from curl:
```  
{
    "health" : "green",
    "status" : "open",
    "index" : "myindex",
    "uuid" : "XyD5LntFQTO6Oc2VMpd2PA",
    "pri" : "1",
    "rep" : "1",
    "docs.count" : "312963",
    "docs.deleted" : "0",
    "store.size" : "164202006",
    "pri.store.size" : "98032982"
  },
```

Notes:
* Same result with either client library major version (7 or 8)
* Elasticsearch has over 10k indices
* Data is consistently missing for same indices 
* User is `elastic` with no changes to permissions 

Thamks for any insights!

**Comment by jascott1** [comment]
I am getting same result only using `requests` lib, so it is not a problem with elasticsearch.py. I will close this ticket but please comment if you have any suggestions as to what could be happening here!

**Comment by jascott1** [comment]
This was self-inflicted permissions issues. What threw me off is that most indices were returning full stat data while only a subset were None. Thanks for the rubber duck session :)

**Comment by pquentin** [comment]
Glad you sorted this out!
