### ISSUE TITLE
Getting 404 issue while trying to create index from python client in elastic search

### ISSUE THREAD

**Issue by vaibhavpatankar01** [elastic/elasticsearch-py#2615]
Hello, 
I am trying to create index in elasticsearch using python client but its giving 
elastic.NotFoundError 404

**Comment by miguelgrinberg** [comment]
Hi! Can you share the code that you are using?

**Comment by vaibhavpatankar01** [comment]
![20240722_153837](https://github.com/user-attachments/assets/8b739bc5-0791-482e-b232-f9a5281f11a8)


The above given image contains the my code

**Comment by vaibhavpatankar01** [comment]
from elasticsearch import Elasticsearch
Client = Elasticsearch("http://10.1.3.28:5601", verifiy_certs=False, basic_auth("username", "pass")
Client.ping()
Client.indices.create(index="mynewindex")



Ping is giving me true but the index is not created and its giving 404 notfound error

**Comment by miguelgrinberg** [comment]
Port 5601 is for Kibana, not Elasticsearch. Normally Elasticsearch is on port 9200. Give 9200 a try.

**Comment by vaibhavpatankar01** [comment]
Ok. Thanks
