### ISSUE TITLE
Feature: Allow embedding vector search for max_marginal_relevance_search

### ISSUE THREAD

**Issue by rishabh208gupta** [elastic/elasticsearch-py#2620]
**Describe the feature**: Currently there is no option to perform the max_marginal_relevance_search with only query embeddings vector. The query is mandatory and because of which the embedding service needs to be passed.

**Comment by pquentin** [comment]
Would it help you if the [maximal_marginal_relevance](https://github.com/elastic/elasticsearch-py/blob/6521b55761ccb6e7033ea643037fd1c94ea818c4/elasticsearch/helpers/vectorstore/_utils.py#L39-L45) function was exposed? Or do you really just want an option to only provide `query_embedding` instead of `query` in [max_marginal_relevance_search](https://github.com/elastic/elasticsearch-py/blob/6521b55761ccb6e7033ea643037fd1c94ea818c4/elasticsearch/helpers/vectorstore/_async/vectorstore.py#L344-L357)?

**Comment by rishabh208gupta** [comment]
I was actually looking for an option to only provide `query_embedding` instead of `query` and `embedding_service` in [max_marginal_relevance_search](https://github.com/elastic/elasticsearch-py/blob/6521b55761ccb6e7033ea643037fd1c94ea818c4/elasticsearch/helpers/vectorstore/_async/vectorstore.py#L344-L357)

**Comment by pquentin** [comment]
Sure! The first step is to get the test to pass locally: https://github.com/elastic/elasticsearch-py/blob/6521b55761ccb6e7033ea643037fd1c94ea818c4/test_elasticsearch/test_server/test_vectorstore/test_vectorstore.py#L818-L877

https://github.com/elastic/elasticsearch-py/blob/main/CONTRIBUTING.md could help you here. The formatting step (`nox -rs format`) is important because it generates the sync version of max_marginal_relevance_search from the async version. But only the sync version is tested.

**Comment by rishabh208gupta** [comment]
Thanks! Let me give this a go.

**Comment by pquentin** [comment]
Please ask for help if you get stuck, the current system is quite fragile and does not provide helpful errors when things are not setup in the exact same way as in continuous integration.

**Comment by rishabh208gupta** [comment]
Thanks! so I started elastic search locally using the script `.buildkite/run-elasticsearch.sh`. After that I ran `nox -rs test` (I didn't run `nox -rs format` cause I just wanted to run the existing tests successfully). Some of the test cases including `test_max_marginal_relevance_search` failed due to an authentication error. Is there anything else that I need to do before successfully executing all the existing tests?

**Comment by pquentin** [comment]
And are you able to connect to that Elasticsearch instance?

```bash
$ curl --resolve instance:9200:127.0.0.1 --cacert .buildkite/certs/ca.pem https://elastic:changeme@instance:9200
{
  "name" : "instance",
  "cluster_name" : "elasticsearch-8-11-0-SNAPSHOT-rest-test",
  "cluster_uuid" : "8UO33t3DS9mziGEfeJNfGw",
  "version" : {
    "number" : "8.11.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "edf70163e6e5371a90090831e055b31973958cf0",
    "build_date" : "2023-11-06T18:49:41.957873063Z",
    "build_snapshot" : true,
    "lucene_version" : "9.8.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

The `--resolve` trick is needed because the SSL certificate in `.buildkite/certs/` is for "instance", so curl has to think it's connecting to that host.

**Comment by rishabh208gupta** [comment]
Yeah I was able to connect to the elastic search instance : 

`
rishabhgupta@Rishabhs-MacBook-Pro elasticsearch-py % curl --resolve instance:9200:127.0.0.1 --cacert .buildkite/certs/ca.pem https://elastic:changeme@instance:9200
{
  "name" : "instance",
  "cluster_name" : "elasticsearch-8-11-0-SNAPSHOT-rest-test",
  "cluster_uuid" : "RQFi2OFNTnOr754BMEXPnA",
  "version" : {
    "number" : "8.11.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "edf70163e6e5371a90090831e055b31973958cf0",
    "build_date" : "2023-11-06T18:49:41.957873063Z",
    "build_snapshot" : true,
    "lucene_version" : "9.8.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
`

The error that I can for the test : 

`ERROR test_elasticsearch/test_server/test_vectorstore/test_vectorstore.py::TestVectorStore::test_max_marginal_relevance_search - elasticsearch.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/]')`

**Comment by pquentin** [comment]
OK, this is pretty annoying. I had to add "instance" in /etc/hosts by adding the following entry:

```
127.0.0.1	instance
```

Now, that test runs fine with:

```
STACK_VERSION=8.15.0-SNAPSHOT .buildkite/run-elasticsearch.sh
```

and then:

```
ELASTICSEARCH_URL=https://elastic:changeme@instance:9200 nox -rs test-3.12
```

Also, I added the following change to only run that test:

```
diff --git a/noxfile.py b/noxfile.py
index 69e53417..730fb27d 100644
--- a/noxfile.py
+++ b/noxfile.py
@@ -42,6 +42,8 @@ def pytest_argv():
         "--log-level=DEBUG",
         "--cache-clear",
         "-vv",
+        "-k",
+        "test_max_marginal_relevance_search"
     ]
```

**Comment by rishabh208gupta** [comment]
Thanks a lot! I was able to run the test, I have created a PR

**Comment by rishabh208gupta** [comment]
Hi @pquentin, just wanted to check with you on the status of this, any estimate of when this might be reviewed/merged?
