### ISSUE TITLE
Error while pushing data in a bulk.

### ISSUE THREAD

**Issue by varun-kr** [elastic/elasticsearch-py#263]
When I was trying to index text files in chunks (2000 files in a chunk), I got this error message 
"ConnectionError(('Connection aborted.', error(104, 'Connection reset by peer'))) caused by: ProtocolError(('Connection aborted.', error(104, 'Connection reset by peer')))"

When I reduced the chunk size to 1500 , it worked . The exception message was not very clear about the limit of the data that can be pushed to elasticsearch server .

**Comment by HonzaKral** [comment]
This is a message saying that elasticsearch closed the connection, which it would do if the request is above it's maximum size.

Unfortunately there is no easy way for us to know that that is what happened (as opposed to a regular network failure). There is nothing we can do I am afraid.

This would be solved by #199

**Comment by bipul-inno** [comment]
I encountered this same problem and decreasing bulk size as above fixed it.
