### ISSUE TITLE
Passing `boost` parameter for hybrid search when `rrf=False`

### ISSUE THREAD

**Issue by omriel1** [elastic/elasticsearch-py#2630]
# Feature request - Pass `boost` parameter for hybrid search when `rrf=False`

## Background
Currently, when using `DenseVectorStrategy`, one can choose `hybrid=True`. Additionally, one can choose to use `rrf` method to combine the search results (and also pass additional `rrf` parameters like the window size).

But what if one want to use an alternative way to combine search results, for example the intuitive way of just giving a weight for each search results? For that, we can specify `rrf=False`, and then the combination of the results is like having a `boost=1.0` for each score: `score = 1.0 * match_score + 1.0 * knn_score`. 
(As 1.0 is the default boost, also see - https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#_combine_approximate_knn_with_other_features)

This method for example is also available on Milvus - https://milvus.io/docs/reranking.md.

I believe one should be able to specify the `boost` parameter for each score, which is possible if done directly by composing the body request and specifying the `boost` parameter. Again, as stated in the link above, we can set:

```
{
  "query": {
    "match": {
      "title": {
        "query": "mountain lake",
        "boost": 0.9
      }
    }
  },
  "knn": {
    "field": "image-vector",
    "query_vector": [54, 10, -2],
    "k": 5,
    "num_candidates": 50,
    "boost": 0.1
  },
  "size": 10
}
```
and get `score = 0.9 * match_score + 0.1 * knn_score`.

## Feature request
I want to have the option to specify the `boost` parameter for each sub query when initializing the `DenseVectorStrategy` object with additional parameters of `text_field_boost` and `vector_field_boost` values.

This will be **very** useful for my usecase. I'll also be glad to submit a PR that will add this option, but of course first I want to hear your feedback.

**Comment by miguelgrinberg** [comment]
Have you considered creating a subclass of `DenseVectorStrategy` that injects those `boost` directives in the proper places in the query?

While this sounds good in principle, there's really an incredibly large number of options that can be added to the Elasticsearch query. The intention of the base strategy classes is to cater to the most common use cases, giving you the option to subclass or implement your own strategy class from scratch if that makes sense.

**Comment by omriel1** [comment]
Got it! thanks for the comment. It sounds good, I'll try that.
