### ISSUE TITLE
Add Inner_hits to knn_search

### ISSUE THREAD

**Issue by joancf** [elastic/elasticsearch-py#2648]
Knn search API includes several parameters,  one of them is "inner_hits", that can be used when the vectors are inside nested documents,
as explained here: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#nested-knn-search-inner-hits

but the knn_search function does not seem to support this parameters, and is not mentioned anywhere:
https://github.com/elastic/elasticsearch-py/blob/eb52a027508b9f3bd6ba6aa0f500e8e2806690c9/elasticsearch/_sync/client/__init__.py#L2487
https://elasticsearch-py.readthedocs.io/en/v8.15.0/api/elasticsearch.html#elasticsearch.client.Elasticsearch.knn_search

So, is this parameter missing? Is there any roundabout?  Are there any plans to include it?

**Comment by pquentin** [comment]
Hello! The Python client only encodes the top-level keys: `knn`, but not `inner_hits`. Note that the example you sent a link has a drop-down where you can select Python to show you how to call that API using the client:

```python
resp = client.search(
    index="passage_vectors",
    fields=[
        "creation_time",
        "full_text"
    ],
    source=False,
    knn={
        "query_vector": [
            0.45,
            45
        ],
        "field": "paragraph.vector",
        "k": 2,
        "num_candidates": 2,
        "inner_hits": {
            "_source": False,
            "fields": [
                "paragraph.text"
            ],
            "size": 1
        }
    },
)
print(resp)
```

**Comment by joancf** [comment]
Yes, Thanks , You  are right!
I was trying to use the knn_search function, which uses the _knn_search API that is deprecated
The search function allows to use the knn as a parameter, 
So this is solved
