### ISSUE TITLE
Change the mapping of field, when data is not present for that field?

### ISSUE THREAD

**Issue by shashank-moengage** [elastic/elasticsearch-py#265]
Hi,

Suppose I have a field in an index whose mapping is not yet defined and hence is assigned dynamically.
Now, I added a datapoint with that field but the data type assigned is not the type I wanted it to be.
I deleted that datapoint. Is there a way to delete the mapping for that specific field when there is no datapoint containing that field? I don't want to reindex the index

**Comment by HonzaKral** [comment]
There is no difference whether you define a mapping for a field yourself or if it's assigned dynamically - the result is always that it is now part of the mappings and cannot be changed unfortunately.
