### ISSUE TITLE
[Bug] Vectorstore Helper: Hybrid does not work in Elasticsearch Serverless

### ISSUE THREAD

**Issue by joemcelroy** [elastic/elasticsearch-py#2651]
Expected:
When I enable hybrid and im using Elasticsearch v8.14+, I should be able to retrieve documents from both a bm25 based search and NN search using dense/sparse. 

Actual:
Cannot perform the search as RRF is not supported

Reason:
Hybrid performs two retrieval searches and relies on RRF to balance the different result scores. In 8.14+, top level rank was removed and now the only way to do RRF is through retrievers query.

This is the code that builds the query that retrieves results from different methods and balances with RRF. [link](https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/helpers/vectorstore/_sync/strategies.py#L309)

suggested untested code change to equilivent retriever is:

```
{
  "retriever": {
    "rrf": {
      "retrievers": [
        {
          "standard": {
            "query": {
              "match": {
                                self.text_field: {
                                    "query": query,
                                }
                            }
            }
          }
        },
        {
          "standard": {
            "query": {
              "knn": knn
            }
          }
        }
      ]
    }
  }
}

```

Full example of a query:

```
{
  "retriever": {
    "rrf": {
      "retrievers": [
        {
          "standard": {
            "query": {
              "multi_match": {
                "query": "{query}",
                "fields": [
                  "content"
                ]
              }
            }
          }
        },
        {
          "standard": {
            "query": {
              "knn": {
                "field": "content_embedding",
                "num_candidates": 100,
                "query_vector_builder": {
                  "text_embedding": {
                    "model_id": "openai_embeddings",
                    "model_text": "{query}"
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

**Comment by miguelgrinberg** [comment]
> Cannot perform the search as RRF is not supported

Can you explain this? How did you determine RRF is not supported?  The code you linked uses the old form for specifying RRF, which continues to be supported. We will eventually migrate this code to use retrievers, but that is not required to use RRF.

**Comment by miguelgrinberg** [comment]
Clarification on the above report:

- RRF work well for Elasticsearch Cloud and self-hosted but uses a now deprecated query format.
- For Elasticsearch Serverless only the new style of RRF based on retrievers is supported.

We will migrate to the new style to restore support for Serverless.
