### ISSUE TITLE
Querying the Same Index with `VectorStore`

### ISSUE THREAD

**Issue by omriel1** [elastic/elasticsearch-py#2658]
Hi!
I’m wondering what is the correct approach for querying the same index using a `VectorStore`.

For example, assuming I've created an index with `DenseVectorStrategy` I can query it using the `search` method, but it'll strictly perform what was defined in the implemented `es_query` (knn search or hybrid search if specified).

However, I have a couple of scenarios I’d like to address:

1. How can I query the same index using only BM25 (i.e., without invoking the vector search capabilities)?
2. Is it possible to perform hybrid searches on the same index but vary the merging strategy (e.g., using RRF or applying different boosting scoring) between searches?

Currently, the only option I’ve found is to instantiate a new `VectorStore` object for each query configuration. This feels inefficient, and I’m wondering if there’s a better way to handle these types of queries without recreating the `VectorStore` each time.

Thanks!

**Comment by miguelgrinberg** [comment]
Hi! The `VectorStore.search()` method allows you to pass a `custom_query` argument with a callable. Your function will be called with the Elasticsearch query, to give you the option to make changes to it before the query is executed. That should allow you to issue queries that are different than the one that corresponds to the strategy you selected.

**Comment by omriel1** [comment]
Thank you!
