### ISSUE TITLE
How to get HTTP status code

### ISSUE THREAD

**Issue by aniketpant1** [elastic/elasticsearch-py#2664]
```
from elasticsearch import Elasticsearch

client = Elasticsearch(
    "https://0.0.0.0.:9200",
    basic_auth=("elastic", "elastic"),
    verify_certs=False
)
```

**Comment by pquentin** [comment]
Hello! Since you also [asked on Discuss](https://discuss.elastic.co/t/how-to-get-http-status-code-python/366915/3), I will close this question as the bug tracker is more for tracking issues. Thank you!
