### ISSUE TITLE
BulkIndexError cannot be unpickled

### ISSUE THREAD

**Issue by seagrine** [elastic/elasticsearch-py#2670]
It seems like BulkIndexError cannot be unpickled:

`unpickle_exception\n    inst = func(*args)\n           ^^^^^^^^^^^\nTypeError: BulkIndexError.**init**() missing 1 required positional argument: 'errors`

This creates problems with some libraries that expect errors to be serializable.

I put together a quick PR to fix this.

**Comment by seagrine** [comment]
https://github.com/elastic/elasticsearch-py/pull/2669

**Comment by pquentin** [comment]
Closed in https://github.com/elastic/elasticsearch-py/pull/2669
