### ISSUE TITLE
Wrong query outputs while querying Elasticsearch

### ISSUE THREAD

**Issue by bharvidixit** [elastic/elasticsearch-py#268]
While querying Elasticsearch if we pass the date query where date is generated using datetime module of python, Elasticsearch always return wrong no. of documents even if i use simple count API. 

For example a date created with datetime.datetime.today()

In the query, the generated date after using your json serialization becomes 2015-09-12T11:17:27.008029

The queries are nested including range queries. It always returns wrong result.
The response always include timed_out:true as shown in below snapshot
![image](https://cloud.githubusercontent.com/assets/10341430/9830232/fb4cf912-5943-11e5-8d35-f9c8aff15550.png)

Let me know if you need more information.

**Comment by HonzaKral** [comment]
I am sorry, but I cannot help you here without the data or the expectations you have. Could you try to turn on logging to see the requests being sent and then try them using curl?

To enable logging just do:

    import logging
    logging.basicConfig(level=logging.DEBUG)

Thanks

**Comment by HonzaKral** [comment]
Unfortunately, without further information I cannot help.
