### ISSUE TITLE
help streaming_bulk strange behavior

### ISSUE THREAD

**Issue by chocobn69** [elastic/elasticsearch-py#270]
HEllo,

I tried to bulk index some documents with expand_action_callback like that :

```python
def _index_messages(qs, es, index_name):

        def _message_handle_expand(mess):
            return {
                '_op_type': 'index',
                '_index': index_name,
                '_type': index_name,
                '_id': index_name + '_' + str(mess.id)
            }, {
                ...
            }

        bulk_report = helpers.streaming_bulk(client=es,
                                             actions=qs.all(),
                                             chunk_size=2,
                                             expand_action_callback=_message_handle_expand)

        for success, result in bulk_report:
            if not success:
                logger.warn(result)
```

It always gets me this error :
```
elasticsearch.exceptions.TransportError: TransportError(500, u'IllegalArgumentException[Malformed action/metadata line [1], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]]')
```

Then I tried another way :
```python
def _index_messages(qs, es, index_name):

        def _message_handle_expand(mess):
            return {
                'index': {
                    '_index': index_name,
                    '_type': index_name,
                    '_id': index_name + '_' + str(mess.id)
                }
            }, {
               ...
            }

        bulk_report = helpers.streaming_bulk(client=es,
                                             actions=qs.all(),
                                             chunk_size=2,
                                             expand_action_callback=_message_handle_expand)

        for success, result in bulk_report:
            if not success:
                logger.warn(result)
```

Am I wrong or we should update the doc to handle the second way ?

**Comment by HonzaKral** [comment]
The second way is correct if you are actually using the `expand_action_callback`. The first way would be correct if you went without it. Probably the easiest way to handle your use case would be:

    def generate_actions():
        for instance in qs.all():
            yield {
                '_id': index_name + '_' + str(instance.id),
                ...
            }

    bulk_report = helpers.streaming_bulk(
        client=es,
        actions=generate_actions(),
        index=index_name,
        doc_type=index_name,
    )

    
    for success, result in bulk_report:
        if not success:
            logger.warn(result)

The `_op_type` and other things are handled by the default callback, if you wish to provide your own it is assumed you wish to control exactly what is going to elasticsearch, it is a more low-level approach.

Does this explanation make sense? Thanks

**Comment by chocobn69** [comment]
Yes, perfectly.

I hope your response will be indexed in Google so that others can find it


Thanks !
