### ISSUE TITLE
2.0 release schedule

### ISSUE THREAD

**Issue by imreFitos** [elastic/elasticsearch-py#271]
Hi, when do you think you will release ES2.0 support?

**Comment by HonzaKral** [comment]
Hi, I will do a release soon (next week at the latest), the master branch supports elaticsearch 2.0 already so it's just a matter of doing a release.

**Comment by imreFitos** [comment]
Yay thanks! :)

**Comment by HonzaKral** [comment]
Just released 1.7.0 which is 2.0 compatible
