### ISSUE TITLE
NotFoundError: TransportError when executing `search_exists`

### ISSUE THREAD

**Issue by jstypka** [elastic/elasticsearch-py#272]
In the new 1.7.0 version when I run:
```
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.search_exists(index='non-existing-index', doc_type='not-existent', body={})
...
NotFoundError: TransportError(404, u'IndexMissingException[[non-existing-index] missing]')
```
What's more I even get an error when the index exists:
```
NotFoundError: TransportError(404, u'{"exists":false}')
```
In the 1.6.0 version I just get `False` and nothing blows up which is a much nicer behaviour.
Is it a bug or a feature?

**Comment by Redoubts** [comment]
This surprised me too. I got further confused when I saw #230 marked as closed fixed.

**Comment by HonzaKral** [comment]
Sorry for the delay, fix was pushed, release comnig soon
