### ISSUE TITLE
is elasticsearch-py eventlet compatible?

### ISSUE THREAD

**Issue by Cad** [elastic/elasticsearch-py#273]
Is this library compatible with eventlet?

**Comment by HonzaKral** [comment]
Related to #150

The library itself just passes whatever is returned from the connection class. It uses standard sockets by default (via `urllib3`) so it can be made compatible by monkey patching. Alternatively you can create your own `connection_class` and plug it in.

**Comment by Cad** [comment]
Thanks for the info.
