### ISSUE TITLE
how to create a nested index?

### ISSUE THREAD

**Issue by mgiraldo** [elastic/elasticsearch-py#278]
I am using bulk index to add documents that contain nested items in the form of arrays of dictionaries (`address` in this case):

```
{'Name': 'Smith, John',
 'ID': '3327',
 'Nationality': 'English',
 'address': [
      {
      'ID': '5',
      'City': 'Milwaukee',
      'Latlon': '43.0526,-87.9199',
      'State': 'WI'
      },
     ... 
  ]
}
```

I create a list of actions, one for each document like so:

```
{
        "_index": "myindex",
        "_type": "mytype",
        "_source": the_doc
}
```
And then push the actions via `helpers.bulk(es, actions)`

I want to specify that `address` is a nested object. Where do I indicate this to ES with `elasticsearch-py`?

**Comment by HonzaKral** [comment]
You do that but creating a mapping via the `indices.put_mapping` API or when creating the index via `indices.create`.

If you want a more convenient way to create mappings from python you should check out the DSL library where this could be done by doing:

    from elasticsearch_dsl import DocType, Nested, String, GeopPoint

    class MyType(DocType):
        name = String()
        nationality = String()

        address = Nested(
            properties={
                'location': GeoPoint(),
                'state': String(),
                'city': String(),
            }
        )


Then you can just create the index which will put the mappings into elasticsearch:


    from elasticsearch_dsl import Index

    myindex = Index('myindex')
    myindex.doc_type(MyType)
    myindex.create()

and you can use it. See http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html for more details.

**Comment by mgiraldo** [comment]
The DSL library is working so far, thanks. Now I need to figure out how to query it.

Does the new indexing mean that I have more documents? I have ~100k "persons" and ~160k addresses. With my previous index I saw ~100k "documents" (equal to persons).  Now I'm seeing ~600k "documents". Why the discrepancy?

Also: is there a way to use `include_in_parent`?

**Comment by HonzaKral** [comment]
Once you have the Dsl type you can do:

   s = MyType.search()

and go from there...

Nested documents are indexed as separate documents, so they will show up in your stats.

To specify `include_in_parent` simply add it to the `Nested` line:

    address = Nested(
        include_in_parent=True,
        properties={....}
    )


I will close this issue now because it's not really an issue with the python client. If you have further questions about the discrepancy please use the forums at https://discuss.elastic.co/ or, if you run into a problem with the dsl library, open an issue there.

Thanks!
