### ISSUE TITLE
Does not work on app engine anymore because of new parallel bulk

### ISSUE THREAD

**Issue by sadovnychyi** [elastic/elasticsearch-py#282]
This [line](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L4) prevent it from working under app engine, where multiprocessing is not supported. Exception looks like:
```
 from multiprocessing.dummy import Pool
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
```

How do we can prevent multiprocessing module to being imported while running on app engine?
Its possible to do explicit check, like it is done in [NLTK](https://github.com/nltk/nltk/blob/develop/nltk/data.py#L770) or we could move import statement inside of parallel_bulk function, which is against PEP8 – but it will solve the problem.

**Comment by HonzaKral** [comment]
We can safely move that inside the function, I will do that and do a new release, thank you for the report!
