### ISSUE TITLE
Compability name removed 

### ISSUE THREAD

**Issue by cjgu** [elastic/elasticsearch-py#283]
When looking at upgrading to a later version of this library I saw that a compatibility name (
https://github.com/elastic/elasticsearch-py/commit/5d4640d4c2cfd52aa92121fe41bbb383945cf6d3#diff-40bff9d086abf2457154901fada0d9acL229) was removed in 1.8.0 and not documented in the change log. Was this intentional or an accident?

**Comment by hashtonmartyn** [comment]
If it is intentional it would be nice to see recommended changes to resolve problems this causes.

**Comment by HonzaKral** [comment]
The removal was intentional, not mentioning it in the Changelog is definitely a mistake that I will fix.

Thanks for raising the issue!
