### ISSUE TITLE
Incorrect Documentation for Helpers Scan with Query parameter

### ISSUE THREAD

**Issue by apandita** [elastic/elasticsearch-py#289]
The documentation at https://elasticsearch-py.readthedocs.org/en/master/helpers.html
is not updated when using "query" parameter with scan api
scan(es,
    query={"match": {"title": "python"}},
    index="orders-*",
    doc_type="books"
)
When used returns  with a sample like this

scanResp = helpers.scan(client=es,scroll="5m",query={"match":{"channel_id": "34"}},index="my-index",timeout="10m",size=500)

Returns the below error

Output: RequestError: TransportError(400, u'SearchPhaseExecutionException[Failed to execute phase [init_scan], all shards failed; shardFailures {[lEAncRHvQHKpPqlfw1NWEQ][dev-godam][0]: SearchParseException[[dev-godam][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"match": {"master_channel_id": "34"}}]]]; nested: SearchParseException[[dev-godam][0]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[lEAncRHvQHKpPqlfw1NWEQ][dev-godam][1]: SearchParseException[[dev-godam][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"match": {"master_channel_id": "34"}}]]]; nested: SearchParseException[[dev-godam][1]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[lEAncRHvQHKpPqlfw1NWEQ][dev-godam][2]: SearchParseException[[dev-godam][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"match": {"master_channel_id": "34"}}]]]; nested: SearchParseException[[dev-godam][2]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[lEAncRHvQHKpPqlfw1NWEQ][dev-godam][3]: SearchParseException[[dev-godam][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"match": {"master_channel_id": "34"}}]]]; nested: SearchParseException[[dev-godam][3]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[lEAncRHvQHKpPqlfw1NWEQ][dev-godam][4]: SearchParseException[[dev-godam][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"match": {"master_channel_id": "34"}}]]]; nested: SearchParseException[[dev-godam][4]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }]')

The correct syntax should be

query={"query":{"match": {"channel_id": "34"}}} instead

Been stuck in this from a lot of time :( before i solved it.

**Comment by HonzaKral** [comment]
Fixed in 5e97002, Sorry about that and thanks for the report!
