### ISSUE TITLE
Allow setting assert_hostname when using urllib3

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch-py#291]
In some instances, it may be necessary to set the `assert_hostname` when using the built-in `urllib3.HTTPSConnectionPool` in order to disable hostname verification (e.g., internal SSL certificates that do not supply a hostname).

It would be great if the parameter could be passed in without having to subclass. It may be worthwhile to also to support `assert_fingerprint` at the same time.

**Comment by HonzaKral** [comment]
Fixed in f3315dc, thanks!
