### ISSUE TITLE
Search returns TransportError

### ISSUE THREAD

**Issue by chrisspen** [elastic/elasticsearch-py#292]
I recently upgraded from ElasticSearch 1.1.1 to 2.0.0 and now all search requests fail:

    es = Elasticsearch()
    es.indices.create(index=MYINDEX, ignore=400)
    es.search(
        index=MYINDEX,
        body={
        'query':{
        "function_score": {
            "query": {  
                "match": {
                    "questions": query
                }
            },
            "functions": [{
                "script_score": { 
                    "script": "doc['weight'].value"
                }
            }],
            "score_mode": "multiply"
        }
        },
        },
        )

I get the error:

      File "myscript.py", line 251, in get_instructions
        "score_mode": "multiply"
      File "myproject/.env2.7/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
        return func(*args, params=params, **kwargs)
      File "myproject/.env2.7/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 530, in search
        doc_type, '_search'), params=params, body=body)
      File "myproject/.env2.7/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "myproject/.env2.7/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
        self._raise_error(response.status, raw_data)
      File "myproject/.env2.7/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception')

**Comment by HonzaKral** [comment]
The error means that there is something wrong with your query. You need to look at the entire error message (`.info` on the exception) to see.

My guess would be that you don't have scripting enabled and so your query cannot run.

**Comment by chrisspen** [comment]
You're correct. I guess scripting was enabled by default in the previous version, but not in 2.0.0, so I hadn't previously had to deal with this. Enabling scripting fixed this error. Thanks.

**Comment by ahmadkarim** [comment]
i had a working script but then i was having :
 ```
cause = ', %r' % self.info['error']['root_cause'][0]['reason']

TypeError: string indices must be integers
```
 `

i switched to elasticsearch 2.1.0 but now i get the following error:

```
POST https://XXXXXXXXXX.com:443/elasticsearch/_all/dtyp
e/_search [status:400 request:0.744s]
Traceback (most recent call last):
  File "XXX\ES.py", line 3
67, in <module>

  File "XXX\ES.py", line 2
41, in queryFromKibanaServer
    request_timeout=6  )
  File "\lib\site-packages\elasticsearch\client\utils.py", line
69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "\lib\site-packages\elasticsearch\client\__init__.py", li
ne 530, in search
    doc_type, '_search'), params=params, body=body)
  File "\lib\site-packages\elasticsearch\transport.py", line 307
, in perform_request

    status, headers, data = connection.perform_request(method, url, params,
 body, ignore=ignore, timeout=timeout)
  File "\lib\site-packages\elasticsearch\connection\http_request
s.py", line 78, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "\lib\site-packages\elasticsearch\connection\base.py", li
ne 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, err
or_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'Bad Request')

```

**Comment by HonzaKral** [comment]
It looks like your query is wrong - you have extra `"query"` elements around the `match` queries.

To get more information you should enable `DEBUG` level logging which should return more information about the error.

Hope this helps

**Comment by arun-munagala** [comment]
@HonzaKral 
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', 'Unknown key for a VALUE_NUMBER in [took].') 
any idea what is causing this error?

**Comment by fxdgear** [comment]
What version of elasticsearch are you using?

**Comment by Sphinxs** [comment]
`TransportError(500, 'script_exception', 'compile error')` ?

**Comment by fxdgear** [comment]
@Sphinxs that too me sounds like you're having issues with the painless script compiling.

**Comment by Gourav-infobiz** [comment]
in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'runtime error'

Please help me with this
