### ISSUE TITLE
Allow to invalidate specific filter cache keys

### ISSUE THREAD

**Issue by jarvinia** [elastic/elasticsearch-py#295]
see https://github.com/elastic/elasticsearch/issues/2653

**Comment by HonzaKral** [comment]
This is possible via the `indices.clear_cache` method which accept a `filter_keys` param: A comma-separated list of keys to clear when using the `filter_cache` parameter (default: all)

**Comment by HonzaKral** [comment]
http://elasticsearch-py.readthedocs.org/en/1.x/api.html#elasticsearch.client.IndicesClient.clear_cache
