### ISSUE TITLE
how does parallel_bulk work?

### ISSUE THREAD

**Issue by 4poc** [elastic/elasticsearch-py#297]
python `3.4.1` elasticsearch-py `2.1.0`

I was having some trouble understanding how `parallel_bulk` works, I was trying to use it to index some data (10m records+) but ran into memory issues. I discovered that it uses multiprocessing, so (forked?) processes instead of threads, which I think explains the behavior I see.
regardless I already wrote some memory benchmark that compares it to `streaming_bulk`, maybe we can develop a multithreaded bulk helper instead of the multiprocess one I think this would be useful. Or is there a way to use `parallel_bulk` without this excessive memory usage?

---

```python
import os
from elasticsearch import Elasticsearch
from elasticsearch.helpers import streaming_bulk, parallel_bulk
import psutil
es = Elasticsearch()
try:
    es.indices.create(index='my_test')
except:
    pass

def test(bulk_fn, size):
    def generator():
        for num in range(size):
            yield {
                    '_index': 'my_test',
                    '_id': num,
                    '_type': 'document',
                    '_source': {'some_id': num, 'data': 'A'*1024},
                    }

    i = 0
    for ok, result in bulk_fn(es, generator()):
        if i % (size//5) == 0:
            process = psutil.Process(os.getpid())
            mem = process.memory_info().rss / float(2 ** 20)
            print('item: %d, memory: %.3f MiB' % (i, mem))
        i += 1
    print('----')

print('parallel_bulk (50000):'); test(parallel_bulk, 50000)
print('parallel_bulk (100000):'); test(parallel_bulk, 100000)
print('parallel_bulk (200000):'); test(parallel_bulk, 200000)
print('streaming_bulk (50000):'); test(streaming_bulk, 50000)
print('streaming_bulk (100000):'); test(streaming_bulk, 100000)
print('streaming_bulk (200000):'); test(streaming_bulk, 200000)

es.indices.delete(index='my_test')
```

```
parallel_bulk (50000):
item: 0, memory: 26.773 MiB
item: 10000, memory: 40.105 MiB
item: 20000, memory: 46.570 MiB
item: 30000, memory: 48.066 MiB
item: 40000, memory: 49.355 MiB
----
parallel_bulk (100000):
item: 0, memory: 40.180 MiB
item: 20000, memory: 47.859 MiB
item: 40000, memory: 78.262 MiB
item: 60000, memory: 87.523 MiB
item: 80000, memory: 87.008 MiB
----
parallel_bulk (200000):
item: 0, memory: 40.930 MiB
item: 40000, memory: 89.547 MiB
item: 80000, memory: 143.652 MiB
item: 120000, memory: 163.520 MiB
item: 160000, memory: 161.230 MiB
----
streaming_bulk (50000):
item: 0, memory: 44.742 MiB
item: 10000, memory: 40.688 MiB
item: 20000, memory: 40.703 MiB
item: 30000, memory: 40.715 MiB
item: 40000, memory: 40.711 MiB
----
streaming_bulk (100000):
item: 0, memory: 40.395 MiB
item: 20000, memory: 40.707 MiB
item: 40000, memory: 40.723 MiB
item: 60000, memory: 40.727 MiB
item: 80000, memory: 40.738 MiB
----
streaming_bulk (200000):
item: 0, memory: 40.906 MiB
item: 40000, memory: 40.707 MiB
item: 80000, memory: 40.488 MiB
item: 120000, memory: 40.477 MiB
item: 160000, memory: 40.477 MiB
----
```

**Comment by HonzaKral** [comment]
It uses `multiprocessing.dummy` which just uses threading, no forking involved.

Why the memory can be larger is because it needs to materialize several chunks in memory at the same time - if you are running parallel N then as many as N lists of documents will be in memory, serialized into a string and sent to elasticsearch. The memory won't be freed until the confirmation comes back from ES and new chunk is being sent. So higher memory usage is OK.

Unless the memory keeps growing all the time it's expected behavior.

**Comment by 4poc** [comment]
Thank you for the explanation! Understanding that, definitely solved it for me. I tinkered some with the `thread_count`, `chunk_size` and `max_chunk_bytes` settings, that greatly reduced the memory usage of my script. The parallel_bulk helper is such an incredibly useful tool :+1:
