### ISSUE TITLE
can't run load.py in example directory

### ISSUE THREAD

**Issue by softside** [elastic/elasticsearch-py#300]
In line 105 and 110
`committed_date': datetime(*commit.committed_date[:6])`
`authored_date': datetime(*commit.authored_date[:6])`

The `commit.committed_date` and `commit.authored_date` is a int_seconds_since_epoch,which cause the script can't run .
`datetime.utcfromtimestamp(float(commit.committed_date))` will work,may be caused by different  version of gitpython? After all ,this file has been there for a long time.

Hope to help others who run this file.

And line 200,it need to modify the elasticsearch.yml to enable scripting module,Groovy dynamic scripting off by default from v1.4.3

**Comment by HonzaKral** [comment]
Thanks for the report! I need to figure out how to run the examples with the tests.

**Comment by softside** [comment]
wonderful work!
