### ISSUE TITLE
Question: Connecting to ES

### ISSUE THREAD

**Issue by jkblgithub** [elastic/elasticsearch-py#301]
I plan on using ES in various places in my django app e.g. views, tasks, etc. What I am unsure of is whether or not the connection i.e. `es = Elasticsearch()` can be called multiple times, e.g. whenever I want to use it in a view or task, or whether it should only be called once and saved as some sort of global var? I just want to make sure I don't keep on re-establishing the connection unnecessarily.

**Comment by HonzaKral** [comment]
Yes, you should just use one instance and reuse it, that way you will have all the benefits of persistent connections. Don't worry, the client is thread safe.

**Comment by jkblgithub** [comment]
Thank you!

**Comment by HonzaKral** [comment]
If you are interested you should probably also check out elasticsearch-dsl (0) which also provides an abstraction (1) for configuring even multiple clients and using them. There is also an example django project using it (2)

0 - https://github.com/elastic/elasticsearch-dsl-py
1 - http://elasticsearch-dsl.readthedocs.org/en/latest/configuration.html
2 - https://github.com/HonzaKral/es-django-example

**Comment by jkblgithub** [comment]
Thanks - I did have a look at it but felt that it is a bit too abstract and verbose for the purposes of our app
