### ISSUE TITLE
API Bulk, how to omit line ? 

### ISSUE THREAD

**Issue by azman0101** [elastic/elasticsearch-py#302]
While documentation of [streaming_bulk](https://github.com/elastic/elasticsearch-py/blame/5e97002f28f43089e1cba69b8cb685c68b98ef01/elasticsearch/helpers/__init__.py#L153) to support that expand_action_callback must return `None` if data line should be omitted.
chunk_actions needs an iterable.

```python
def _chunk_actions(actions, chunk_size, max_chunk_bytes, serializer):
    """
    Split actions into chunks by number or size, serialize them into strings in
    the process.
    """
    bulk_actions = []
    size, action_count = 0, 0
    for action, data in actions:
        action = serializer.dumps(action)
        cur_size = len(action) + 1
```
If we send a tuple of `None, None` then bulk_actions is filled with null (due to serializer.dumps(action) of None), making API throw this beautiful exception
```
['null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', '{"update"........]
```
```
elasticsearch.exceptions.RequestError: 
TransportError(400, u'ElasticsearchParseException[Failed to derive xcontent]')
```

A tuple with `action, None` throw that one:

```
elasticsearch.exceptions.TransportError:
TransportError(500, u'IllegalArgumentException[Malformed action/metadata line [11], expected a simple value for field [myfield] but found [START_OBJECT]]')
```

Regards,

Azzz

**Comment by HonzaKral** [comment]
I don't understand, why are you sending `(None, None)`? If data line is omitted (only true for `delete`) you still need to supply the action part so there should never be two `None` objects in one action/data pair.

**Comment by HonzaKral** [comment]
Closing this issue - you should never ever return `(None, None)`, if you want to skip some of the actions from the stream, just filter them out before passing them into the bulk helpers.
