### ISSUE TITLE
API bulk parallel

### ISSUE THREAD

**Issue by rlvoyer** [elastic/elasticsearch-py#303]
It would be really helpful if you could include some examples of how to use the `streaming_bulk` and `bulk_parallel` helpers in the documentation. Specifically, it's unclear what the input should be to the `expand_action_callback` function parameter. Thanks!

**Comment by HonzaKral** [comment]
Well, the callback is passed whatever your iterator returns, the documentation explains what the default callback expects, but if you wish to supply your own you can of course use whatever data fomrat you wish.

hope this helps

**Comment by HonzaKral** [comment]
closing this, if the question is still not answered, feel free to reopen.
