### ISSUE TITLE
handling alphanumeric chars 

### ISSUE THREAD

**Issue by gg4u** [elastic/elasticsearch-py#304]
Hi Honza,

thank you for your work.
I have a couple of questions, here doing a test with topics from wikipedia (english).
I tried to import something very simple like:
```
doc = {'name' : unicode(title,'utf8')}
es.index(index="test", doc_type='wiki', body=doc, id=1)
```
with fairly good results, except ones where topics have non-alphabetic characters in the name.
As example, you get:
=q?google 
return first 
'google+' 
'google'

or 
=q?renaissance
return first elements with this pattern:
'renaissance (...)'
'renaissance (...)'
'renaissance (...)'
and I am not able to match 'renaissance' in first place.

I am looking at the documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/unicode-normalization.html

It is not clear to me:
-- if I should care about the analyser in importing to index, either in querying after being indexed
-- how to index properly with non-alphanumeric character?

I am not sure if the links above are well pertinent, I m digging into;
do you have some suggestion about tweaking the result by having first result exact match, without importing duplicated index for 'match_exact'?

 could you please elaborate on the documentation with examples below the functions?
It is very reach, however translating the ES tutorial of CURL request into ES-py is not that straight forward.

As example, if I would like to use an analyser such as:
https://www.elastic.co/guide/en/elasticsearch/reference/1.4/analysis-stemmer-tokenfilter.html

it is not clear I would use in ES-py.

I tried this, but it is wrong:
```
es.search(index="test", body={"query": {"terms": {"name":['topic1', 'topic2']}},
    "index" : {
        "analysis" : {
            "analyzer" : {
                "my_analyzer" : {
                    "tokenizer" : "standard",
                    "filter" : ["standard", "lowercase", "my_stemmer"]
                }
            },
            "filter" : {
                "my_stemmer" : {
                    "type" : "stemmer",
                    "name" : "light_german"
                }
            }
        }
    }
})
```

Thank you!

**Comment by HonzaKral** [comment]
Hi, sorry for the late reply.
Relevancy of your search results are mostly about analyzers. I would like to point you to https://github.com/elastic/elasticsearch-dsl-py since it has a nicer API for creating analyzers (http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#analysis) that should help you get the syntax right.

**Comment by HonzaKral** [comment]
Closing this issue since it's not really about the python client, but a more generic ES questions. I recommend using http://discuss.elastic.co/ for those.

Thanks!
