### ISSUE TITLE
inserting index on AWS (or remote)

### ISSUE THREAD

**Issue by gg4u** [elastic/elasticsearch-py#305]
When I upload my data into index in local environment, everything goes ok.
When I use the same script on the remote server for production, it takes ages, and eventually looks to stall.
Honestly I am not bulk downloading, but why there should be an issue in uploading record by record? my doc tests are simply jsons with one field.
The script on the server is run on the server itself, not via ssh (I mean, I log in, and from there I launch the script).

Could you please help understanding a possible cause?

Could I eventually simply copy my data/index from my local environment to the server via rsync ?
If so, how?

**Comment by HonzaKral** [comment]
I am sorry, but I cannot help you without seeing the actual code and some more information, mostly if `curl` works, if you can actually connect to the cluster and what's happening in the transport (turn on logging for `'elasticsearch' logger to see all that).

> Could I eventually simply copy my data/index from my local environment to the server via rsync ?

You can use the snapshot/restore API - https://www.elastic.co/guide/en/elasticsearch/reference/2.0/modules-snapshots.html

**Comment by gg4u** [comment]
I was loading data with something simple as:
```python
doc = {'name' : unicode(name,'utf8')}
es.index(index='test',id=0,doc_type='topic',body={'doc':doc})
```
but it goes mega slow and stall when launching on remote on EC2 t2.micro.

I found a workaround using helpers:
```python
#use a function to populate action document
        action = {
        "_index": "test",
        "_type": "topic",
        "_id": counter,
        "_source": {
            "name": unicode(name,'utf8')
            }
        }

actions = [] #append action here
helpers.bulk(es, actions) # using: from elasticsearch import helpers 
```

but not clear to me why it happened.
Could you say if and how helpers fails for any error that could occur? 
suppose you upload groups of hundreds elements at time, how would you catch which one may have failed?
thank you

**Comment by HonzaKral** [comment]
This seems to be something specific in your environment, it is definitely weird and it shouldn't happen, but t2.micro is really underpowered for elasticsearch.

You can turn on logging (http://elasticsearch-py.readthedocs.org/en/master/#logging) to see what's exactly going on.

**Comment by HonzaKral** [comment]
There has been no information for a month, closing this ticket since I cannot replicate this behavior. Thanks!
