### ISSUE TITLE
Should sniffing contact seed nodes before existing nodes?

### ISSUE THREAD

**Issue by jolynch** [elastic/elasticsearch-py#312]
In [``sniff_hosts``](https://github.com/elastic/elasticsearch-py/blob/fb8eb4e38588d0ac582412f1acc020693260dd7e/elasticsearch/transport.py#L200) existing cluster members are contacted for hosts before seed members are. I think I understand that way the sniffing requests are evenly distributed because the connection_pool connections are [``shuffled``](https://github.com/elastic/elasticsearch-py/blob/fb8eb4e38588d0ac582412f1acc020693260dd7e/elasticsearch/connection_pool.py#L118), but in our case it can be rather problematic because our seed connection is a load balancer and we'd like to be able to fail over to another cluster by failing over backends in the seed load balancer. As existing members are contacted first we basically have to restart all our clients to execute a failover (so they re-sniff via the seed).

I'm not sure what people usually put for seed nodes, but depending on what is used it may make sense to contact seed nodes before the existing nodes. If you think that this is generally useful I'm happy to contribute a patch, what do you think?

**Comment by HonzaKral** [comment]
Typically the seed nodes would be still active in the cluster so they would essentially be queried twice - it is only a precaution if everything goes sideways.

For your use case I would recommend doing this logic in the load balancer - never actually return the info about the actual nodes (which you can filter by returning `None` from the callback) - that way you will never talk to actual nodes and you can control what you return as nodes to connect to.

Does that make sense for you?

**Comment by jolynch** [comment]
Are you suggesting we turn off sniffing and route all requests through the load balancer? We have tried that and the performance is subpar so we generally prefer not to send Elasticsearch traffic directly through the load balancer (HAProxy). We have found in practice elasticsearch-py is much better in for maintaining keep alive connection pools to Elasticsearch nodes and properly managing cluster member state. The extra latency of the proxy coupled with the lack of intelligent keep-alives and member failure detection made HAProxy a really poor fit for our query workloads, even if it is a great fit for the sniffing.

Like I guess what I'm saying is that queries going directly from client to ES is wonderful, but the sniffing going directly is less wonderful.

Maybe I'm misunderstanding?

**Comment by HonzaKral** [comment]
Oh I see, it was my mistake, sorry - I assumed you are routing your traffic through a load balancer.

I understand your use case now. I am afraid there isn't much we can do there. It is a very specialized use case so we cannot really support it out of the box.

I'd suggest you don't do the sniffing in the client but instead do it from the outside - retrieve the configuration and, if it has changed, reinitialize the client. You can make it work by providing a custom `transport_class` and replacing its `sniff_hosts` method with your own logic.

If there is any part of that method that you think might make sense to factor out into a separate method to make this easier, let me know - I was already considering ripping the part responsible for the connection parsing and construction (https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L216-L237). That should make things easier.

**Comment by jolynch** [comment]
We already pass in an override transport class so that we sniff out of band of queries, but I'm slightly hesitant to override sniff_hosts since well, it's rather subtle (and important to get right) functionality.

To be honest this would be easy for us to override if we could control the order of the iteration [here](https://github.com/elastic/elasticsearch-py/blob/fb8eb4e38588d0ac582412f1acc020693260dd7e/elasticsearch/transport.py#L200). Maybe a python function or property that we could override? For example:

```python
def get_all_connections(self):
    return chain(self.connection_pool.connections, self.seed_connections)

# ...
# then in sniff_hosts
for c in self.get_all_connections():
    # do normal thing
```

Then for our use case we would just override all_connections to reverse the order.

**Comment by jolynch** [comment]
I'm happy to contribute a PR that factors out the bit you mentioned and the connection part (or just one) if that's what you would like :-)

**Comment by HonzaKral** [comment]
I refactored the network communication into a separate method in a5aa160b81c551d1649baf81a24e9b0c73bd6266

Unfortunately I don't think we can support your use case, but at least now you have a much smaller, and better defined, method that you need to override. I also made the interface more universal (returning a list of dicts) so that you can potentially get the data from other sources (configuration management for example).

Hope this helps.

**Comment by jolynch** [comment]
@HonzaKral, ok that should be easier to override without as much worry of breaking functionality. Thanks for the feedback and quick patch.

**Comment by jolynch** [comment]
fwiw would you be against a PR that factors out the iteration order into ``_get_all_connections`` or something (if so that's cool)?

**Comment by HonzaKral** [comment]
I am sorry, but no. It is very exotic use case so I don't see it as justifying the, albeit small, increase in complexity. With the method factored out you can simply copy&paste it and change the one line. The method hasn't changed in months so it shouldn't cost too much in maintenance.

**Comment by jolynch** [comment]
Ok, sounds reasonable. Thank you very much for the help.
