### ISSUE TITLE
backward compatibilty issue.. "bulk_index=bulk" is missing in helpers/__init__.py

### ISSUE THREAD

**Issue by NaveenIIIT** [elastic/elasticsearch-py#313]
Hi,
I tried to upgrade elasticsearch dsl to latest version.. and it is showing me..

  File "/usr/local/lib/python2.7/dist-packages/elasticutils/__init__.py", line 9, in 
    from elasticsearch.helpers import bulk_index
ImportError: cannot import name bulk_index

so,
I tried to override bulk_index=bulk in __init__.py
correct me if I'm wrong..

**Comment by HonzaKral** [comment]
Hi, it was removed in 1.8.0 - it was documented in the change log.

The proper fix is to just change to `from elasticsearch.helpers import bulk` or `from elasticsearch.helpers import bulk as bulk_index`

I understand this can be frustrating, but we need to remove some features at times, the Changelog should contain all the information needed to migrate to new version.
