### ISSUE TITLE
Chunking data for bulk api

### ISSUE THREAD

**Issue by caulagi** [elastic/elasticsearch-py#314]
It seems to me that the way data is chunked for the bulk api could be wrong.  Specifically, it could happen that the elastic bulk api receives incomplete/malformed json request when the data is chunked outside document boundaries.

... or am I missing something?

**Comment by HonzaKral** [comment]
This really shouldn't happen - the chunking is done on document level (where we count the size of the metadata and the size of the document together). The main function responsible (`_chunk_actions`) returns a list of actions and only puts whole documents with their metadata into that list (see https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L67-L69).
