### ISSUE TITLE
Serializer doesn't support uuid type

### ISSUE THREAD

**Issue by apeters** [elastic/elasticsearch-py#316]
This can be added simply by doing this:

    def default(self, data):
        if isinstance(data, (date, datetime)):
            return data.isoformat()
        elif isinstance(data, Decimal):
            return float(data)
        elif isinstance(data, uuid.UUID): 
            return str(data)
        raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))

I would love to see this added as I would expect this to serialize into a string.
I have a pull request ready to go if you agree.

**Comment by HonzaKral** [comment]
UUID makes perfect sense, could you submit a PR (please include tests)?

Thanks!

**Comment by HonzaKral** [comment]
closed by #317

**Comment by Sphinxs** [comment]
I tried to store the UUID (SQLAlchemy Utils) as a binary: `uuid.uuid4().binary`, but I have received an error.

I tried to convert the `uuid.uuid4().binary` to Base 64, as the example in the Elasticsearch doc shows, and another error.

I tried to store the UUID as a `text`: `str(uuid4())`, and another error.

I tried to store the `int`: `uuid.uuid4().int`, and another error, but if I set the field to `text` and get the `int` representation and convert it to `str` it works, wtf.

**Comment by fxdgear** [comment]
@Sphinxs I'm sorry to hear you're having some issues, can you give a little more information please? 

What version of python? 
What version of elasticsearch?
What version of elasticsearch-py?

What was the field type defined as originally? 

What are the errors you got?
