### ISSUE TITLE
Problem with example es.indices.create(...)

### ISSUE THREAD

**Issue by PierreHao** [elastic/elasticsearch-py#319]
When i do pip install elasticsearch, then write the example code, the problem happens as follows:
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9db39b8b10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9db39b8b10>: Failed to establish a new connection: [Errno 111] Connection refused)
This is a problem with urllib3, how can i solve this problem?

**Comment by HonzaKral** [comment]
Hi, this is not a problem with urllib3, this is a problem with your elasticsearch server not running or you being unable to connect to it over network.

Could you please make sure your elasticsearch is up and running and you can connect to it via curl or the browser? Thanks

**Comment by PierreHao** [comment]
Thank you for your response. I have followed installation pip install elasticsearch, then run the example:
>>> from datetime import datetime
>>> from elasticsearch import Elasticsearch

# by default we connect to localhost:9200
>>> es = Elasticsearch()

# create an index in elasticsearch, ignore status code 400 (index already exists)
>>> es.indices.create(index='my-index', ignore=400)
there will be the error. es = Elasticsearch() runs well. How can I check elasticsearch is up?

**Comment by HonzaKral** [comment]
And do you have elasticsearch server running? To make sure it's running follow the documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html

**Comment by PierreHao** [comment]
After running sudo service elasticsearch start, it works, thank you

**Comment by abhigenie92** [comment]
Where you run sudo service elasticsearch. I was getting the same error.
