### ISSUE TITLE
all utf-8 charactor show as base32 string

### ISSUE THREAD

**Issue by botaruibo** [elastic/elasticsearch-py#320]
index some chinese charactors.py:
#-*- coding: UTF-8 -*-
#python on elasticsearch test dic

from elasticsearch import Elasticsearch
es = Elasticsearch('http://xxxxxx:9200/')
....
body = {"content":u"女款卡其色分层长款外套"}
es.index('vstore','fulltext',body,'3')
body = {"content":"男款口袋手帕修身西服"}
es.index('vstore','fulltext',body,'4')

the result query from browser as follow image
![image_20151213171330](https://cloud.githubusercontent.com/assets/2376855/11766317/e02c416c-a1bc-11e5-9043-fe78e4efd3ae.png)

**Comment by HonzaKral** [comment]
I understand that it looks weird but the value is actually a properly encoded json string holding the value you specified. You can verify that by getting the value and calling `print()` on it in python:

    >>> title = es.get(index='i', doc_type='t', id=47)['_source']['title']
    >>> title
    u'\u7537\u6b3e\u53e3\u888b\u624b\u5e15\u4fee\u8eab\u897f\u670d'
    >>> print(title)
    男款口袋手帕修身西服

**Comment by botaruibo** [comment]
actually those data will be get by others client,like java,not only python. in this case,we have to decode the result  with additional  java code. fixing this issue would  provide convenience for python newbees

**Comment by HonzaKral** [comment]
I see your point, but this should not require additional java code, it is perfectly valid json and safer to handle than utf-8 strings since it's pure ascii.

I have pushed a fix as c305dc5587963bc9e41ae8cf35bb6eff5afb199e for convenience, hope it helps.

**Comment by botaruibo** [comment]
ok.i'll try. thks!
