### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by danzek** [elastic/elasticsearch-py#324]
The README states:

>The development is happening on master and 1.x branches, respectively.

But isn't it actually happening on the 2.x branches? Or perhaps I'm completely confused....

**Comment by HonzaKral** [comment]
It is meant as branches of this repo, there is no `2.x` branch here.

**Comment by HonzaKral** [comment]
Closing this issue since it was most likely just a misunderstanding, please reopen if the issue persists.

thanks!
