### ISSUE TITLE
Default max_chunk_bytes is 1% smaller than advertised

### ISSUE THREAD

**Issue by kengruven** [elastic/elasticsearch-py#333]
In `elasticsearch/helpers/__init__.py`, the docstring says:

    :arg max_chunk_bytes: the maximum size of the request in bytes (default: 100MB)

yet the default value is:

    max_chunk_bytes=100 * 1014 * 1024

which is only about 99MB.  I don't see any reason for the discrepancy, so I assume it's probably just a typo.

**Comment by HonzaKral** [comment]
yes, that is a typo, thanks!

**Comment by density** [comment]
there's a similar typo @ https://github.com/elastic/elasticsearch-py/blob/0f4fa3c97f175e6dc84f1fb56e751fd7e65fd23f/elasticsearch/helpers/__init__.py#L200
