### ISSUE TITLE
Using OrderedDict for search results

### ISSUE THREAD

**Issue by bhairav13** [elastic/elasticsearch-py#335]
Would it be possible to add support for OrderedDict in the results for the search API?

I have been able to add some modifications that help me do this right now.  Here are the changes if it helps.  I've modified it such that the default is still using dict, but can use OrderedDict if requested:

(Note:  The diffs are against v1.6)
serializer.py
```
% diff serializer_orig.py serializer.py
33c33
<     def loads(self, s):
---
>     def loads(self, s, dict_type):
35c35
<             return json.loads(s)
---
>             return json.loads(s, object_pairs_hook=dict_type)
62c62
<     def loads(self, s, mimetype=None):
---
>     def loads(self, s, mimetype=None, dict_type=dict):
73c73
<         return deserializer.loads(s)
---
>         return deserializer.loads(s, dict_type)
```

transport.py
```
% diff transport_orig.py transport.py 
331c331,334
<                     data = self.deserializer.loads(data, headers.get('content-type'))
---
>                     dict_type = dict
>                     if params:
>                         dict_type = params.pop('dict_type', dict)
>                     data = self.deserializer.loads(data, headers.get('content-type'), dict_type=dict_type)
```

client/utils.py
```
% diff utils_orig.py utils.py 
60a61,63
>             # Extract dict_type before it gets escaped to string type
>             if 'dict_type' in kwargs:
>                 params['dict_type'] = kwargs.pop('dict_type', dict)
```

Thanks for a great app.

**Comment by HonzaKral** [comment]
I am sorry, this is definitely out of scope for the library. What you can do however, is have this as an external module and just plug it in when constructing your client. You can provide your own version of the serializer class in that module and possibly even the transport class.

May I ask why you'd want to use `OrderedDict` in the first place? Thanks!

**Comment by bhairav13** [comment]
Thank you for your response.

Reason for wanting this is that eventually, the data gets printed in a table format.  I want to be able to print these in the same order as they were put in, so that the output is consistent across different invocations of outputting to the table.

Is "out of scope" because of technical reasons or just that it doesn't conform to the intended use of this app?  I had thought about using inheritance and overriding those methods, but thought that I might miss out on any changes made to the base class methods.

**Comment by HonzaKral** [comment]
It is out of scope because neither python dicts nor json supports ordering by definition so there is no way of guaranteeing order even if we used OrderedDict everywhere on our side, furthermore there are very few people who'd use that functionality so the extra overhead is not worth it.

If you want consistent output I would recommend just ordering the dict manually before outputting.
