### ISSUE TITLE
elasticsearch2.1,paralle_bulk don't work,why?

### ISSUE THREAD

**Issue by karas2015** [elastic/elasticsearch-py#336]
Hi,I want to import big data to elasticsearch.when I use helpers.parallel_bulk,data can't import to ES,it don't have any response and exception,but helpers.bulk can work properly.so,this's why?   I use centos,python2.6 and elasticsearch2.1.0.
the part code as follow：

           if len(actions)>10000:                
                    es.writeBulkToES(actions)
                    actions=[]
                    print 'excute bulk'    
the function

          def writeBulkToES(self,actions):
                  helpers.parallel_bulk(self.es,actions)

**Comment by HonzaKral** [comment]
It is a generator so you need to consume it:

    for response in parallel_bulk(...):
        ...
