### ISSUE TITLE
TransportError.__str__ fails, making exceptions unprintable

### ISSUE THREAD

**Issue by keturn** [elastic/elasticsearch-py#337]
I got a TransportError and the error-handler bugs out when trying to tell me what it is.

The TransportError.info is::

```.py
{
    u'status': 400, 
    u'error': u'MapperParsingException[No handler for type [attachment] declared on field [file]]'
}
```

As of commit ade841a6805abc4d4422bd49f2a639fee9b81e69, `TransportError.__str__` does

        try:
            if self.info:
                cause = ', %r' % self.info['error']['root_cause'][0]['reason']
        except LookupError:
            pass

The LookupError would catch either a KeyError or an IndexError. However, `self.info['error']` is a string here, and trying to take the `['root_cause']` of a string results in a TypeError, because "string indices must be integers, not str."

(I think this is why #332 has an "unprintable TransportError")

**Comment by HonzaKral** [comment]
What version of elasticsearch and elasticsearch-py are you using? Thanks

**Comment by keturn** [comment]
elasticsearch-py 2.2.0  
elasticsearch 1.7.4

**Comment by HonzaKral** [comment]
That combination is not supported, if you use Elasticsearch 1.x please also use 1.x version of the client. See also http://elasticsearch-py.readthedocs.org/en/master/#compatibility

Thanks!
