### ISSUE TITLE
No way to specify multiple type mappings?

### ISSUE THREAD

**Issue by sjmc7** [elastic/elasticsearch-py#338]
I can't find a way to specify multiple type mappings in a single call. This has become a problem with elasticsearch 2.x because where there are parent/child relationships, the parent mappings now have to be created in the same call as the child. I've tried:

```python
map = {'mappings': {'type1': {'properties': {'a': 'string'}},  'type2': {'properties': {'b': 'string'}}}}
es.indices.put_mapping('test-parent', body=map)
TransportError(400, u'MapperParsingException[Root type mapping not empty after parsing! Remaining fields:   [mappings : {type1={properties={a=string}}, type2={properties={b=string}}}]]')

map = {'type1': {'properties': {'a': 'string'}},  'type2': {'properties': {'b': 'string'}}}
es.indices.put_mapping('test-parent', body=map)
TransportError(400, u'MapperParsingException[Root type mapping not empty after parsing! Remaining fields:   [type1 : {properties={a=string}}] [type2 : {properties={b=string}}]]')
```

Is there a call i'm missing somewhere?

**Comment by HonzaKral** [comment]
It needs to be:

    map = {'mappings': {'type1': {'properties': {'a': {'type': 'string'}}},  'type2': {'properties': {'b': {'type': 'string'}}}}}

note the `type` option.

Also if you are creating mappings you might want to check out the handy dsl library which helps with the syntax: 
http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#doctype

Hope this helps!

**Comment by sjmc7** [comment]
Thanks, that was a mistake typing the example. It looks though like the mapping API has changed significantly between 1.x and 2.x. 

According to the 1.7 docs, put_mapping uses PUT /{index}/_mapping/{type} {"type": {...}}

In 2.x, it looks like you can use PUT /{index} {"mappings": {"type1": { .. }, "type2": {..}}}

I don't see this reflected in the client docs.

**Comment by HonzaKral** [comment]
The second api (`PUT /{index}`) is when you are creating an index and in the API it's as `indices.create` - http://elasticsearch-py.readthedocs.org/en/master/api.html#elasticsearch.client.IndicesClient.create

Unfortunately the put_mapping api doesn't support adding multiple mappings at the same time. You need to create them one by one or do so during the index creation

**Comment by sjmc7** [comment]
Ah, you're right; I was misreading the API documentation examples, my mistake. Thanks for your patience.

**Comment by mjrk** [comment]
> Unfortunately the put_mapping api in 2.x doesn't support adding multiple mappings at the same time.

Is this still true for elasticsearch 5.x?

I wonder if there is a way to add two new parent-child related types to an existing index.

**Comment by HonzaKral** [comment]
@mjrk If you have a type that wasn't designated as a `parent` type before then unfortunately that is not possible. The proper way is to add the `child` type first and point to a non-existent type as parent and then add the parent type. See [0] for more details.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-parent-field.html#_parent_child_restrictions
