### ISSUE TITLE
Reindex docs

### ISSUE THREAD

**Issue by joaojunior** [elastic/elasticsearch-py#339]
Frequently We need to re-index docs and every times we write code to make this. I will write the code with inputs as type-from, index-from, host-from, type-to, index-to, host-to, bulk_size, number_of_shards and number_of_replicas. Then will is very easy and practical do re-index in docs.

**Comment by HonzaKral** [comment]
I am sorry, I don't understand what the issue is, have you looked at http://elasticsearch-py.readthedocs.org/en/master/helpers.html#reindex ?

Thanks

**Comment by joaojunior** [comment]
I'm sorry. Yes, You understand. It is exactly this. I didn't find this is docs. I'm sorry. I close this. Thank you.
