### ISSUE TITLE
helper.streaming_bulk is not really usable in streaming usecases

### ISSUE THREAD

**Issue by kaplun** [elastic/elasticsearch-py#340]
From `helper.streaming_bulk` documentation:
```
[...]
Streaming bulk consumes actions from the iterable passed in and yields
    results per action. For non-streaming usecases use ...
[...]
```

However the first line of `streaming_bulk`:
```python
actions = map(expand_action_callback, actions)
```

transform the iterable `actions` into a simple list (thus blocking until the whole content of `actions` is loaded into memory).

In case one has to e.g. perform 1M actions, this is not really feasible, without chunking the actions *outside* the call to `streaming_bulk`.

**Comment by HonzaKral** [comment]
Thanks for raising the issue.

The `map` in question there is imported from `elasticsearch.compat` which results on `itertools.imap` being used instead on python 2: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/compat.py#L9
