### ISSUE TITLE
Example code on the documentation page does not work

### ISSUE THREAD

**Issue by chfw** [elastic/elasticsearch-py#343]
Hey,

I have tried the example code with Elasticsearch 1.4.0 and ElasticSearch 1.5.2. And I am getting errors:

    >>> from datetime import datetime
    >>> from elasticsearch import Elasticsearch
    >>> doc = {
    ...     'author': 'kimchy',
    ...     'text': 'Elasticsearch: cool. bonsai cool.',
    ...     'timestamp': datetime.now(),
    ... }
    >>> es= Elasticsearch(hosts=['localhost:9200'])
    >>> es
    <Elasticsearch([{u'host': u'localhost', u'port': 9200}])>
    >>> res = es.index(index="test-index", doc_type='tweet', id=1, body=doc)
    Traceback (most recent call last):
      ...
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    elasticsearch.exceptions.NotFoundError: TransportError(404, u'IndexMissingException[[test-index] missing]')

What else is needed to get it run?

**Comment by HonzaKral** [comment]
did you change anything in your elasticsearch configuration? It looks like you have disabled automatic creation of indices (by setting `action.auto_create_index` to `false` in your configuration.

**Comment by chfw** [comment]
I see. I checked '/etc/elasticsearch/elasticsearch.yml' and found it was disabled by 

    action.auto_create_index: +.speicalhost*,-*

Thanks for your quick response!! I learnt

**Comment by HonzaKral** [comment]
In that case when you want to try and explore first create the index manually by calling `es.indices.create(index='test-index')` also check out the DSL library (https://github.com/elastic/elasticsearch-dsl-py/) for some more high-level python interface to elasticsearch.

**Comment by chfw** [comment]
Thanks again! I will check dsl out.

**Comment by chfw** [comment]
Inserting this line before it gets it working:
    >>>
    >>> es.indices.create("test-index", {'mappings': {'tweet':{'properties': {'author':{'type':'string'},'text':{'type':'string'},'timestamp':{'type':'date'}}}}})
    {u'acknowledged': True}
    >>> res = es.index(index="test-index", doc_type='tweet', id=1, body=doc)
