### ISSUE TITLE
Urllib3HttpConnection should have separate client_cert and client_key arguments

### ISSUE THREAD

**Issue by richm** [elastic/elasticsearch-py#344]
Many deployments have the client cert and key in separate files, for security purposes.  You usually want much tighter control of who can read the key file.

Note that the function that is eventually called with these arguments is `ssl.wrap_socket()` https://docs.python.org/3.5/library/ssl.html#ssl.wrap_socket which has separate keyfile and certfile arguments (although certfile supports a file with both the cert and key in it).

**Comment by untergeek** [comment]
@HonzaKral, is there a chance you can merge this and release a new version so I can make Curator dependent on it?

**Comment by richm** [comment]
This bug fix is targeted for the 2.3.0 release? When will 2.3.0 be officially released i.e. an official pypi package and https://github.com/elastic/elasticsearch-py/releases updated with 2.3.0?  Is there a roadmap?

**Comment by HonzaKral** [comment]
I am sorry, it has been released as `2.3.0` to PYPI, I just haven't pushed the tag. Will do so.
