### ISSUE TITLE
Update index with script

### ISSUE THREAD

**Issue by pkphlam** [elastic/elasticsearch-py#348]
Hi,

I'm trying to use es.update() on ES 2.1.1 and with a script and I'm having trouble.
```
es.index(index='boston', doc_type='stem_map', id=111, body={'word': 'showing', 'counter': 29})
es.get(index='boston', doc_type='stem_map', id=111)

{'_id': '111',
 '_index': 'boston',
 '_source': {'counter': 29, 'word': 'showing'},
 '_type': 'stem_map',
 '_version': 1,
 'found': True}
```
```
upscript = {
    'script': {
        'inline': 'ctx._source.counter += count', 
        'params': {
            'count': 100
        }
    }
}
```
Then I tried both of the following:
```
es.update(index='boston', doc_type='stem_map', id=111, body=upscript)
es.update(index='boston', doc_type='stem_map', id=111, script=upscript)
```
I'm getting the following error:

```
RequestError: TransportError(400, 'illegal_argument_exception', '[John Walker][127.0.0.1:9300][indices:data/write/update[s]]')
```
What am I doing wrong?

**Comment by pkphlam** [comment]
My mistake. I did not realize I had to first enable scripting by changing the config/elasticsearch.yml file. My code works after doing that.

**Comment by shakthydoss** [comment]
@pkphlam  How did you enabled scripting in config/elasticsearch.yml. When I enter script.disable_dynamic: false it throws error when restarting the elastic search.

**Comment by pkphlam** [comment]
I added these two lines in elasticsearch.yml:

script.inline: true
script.indexed: true

**Comment by shakthydoss** [comment]
@pkphlam thank you. it is working

**Comment by shakthydoss** [comment]
@pkphlam 
I am getting when i try to update as nested docment like this

	upscript = {
		'script': {
			'inline': 'ctx._source.comments += comment', 
			'params': {
				"comment": [ {"id": 123, "body": "boom" }] 
			}
		}
	}

Error : 
RequestError: TransportError(400, u'illegal_argument_exception', u'[Awesome Android][127.0.0.1:9300][indices:data/write/update[s]]')

May i missing any thing. Please provide your help.

**Comment by amih90** [comment]
Any code fix? Have the same exception while update a nested document via Elasticsearch-DSL

**Comment by fxdgear** [comment]
@amih90 with elasticsearch 6.0+ any script not written in painless will not be valid. 

Similarly you might be setting the `script.inline` and `script.index` in the incorrect spot in your request. 

Please consult the [Elasticsearch Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/modules-scripting.html) for Scripting guidance. this is unfortunately not an issue wrt to the Python client but more an implementation of Elasticsearch.
