### ISSUE TITLE
how to use sync and async API

### ISSUE THREAD

**Issue by JackWang917** [elastic/elasticsearch-py#349]
I'm using Rest API for updating and bulk. But I'm not sure whether this is a sync or async API, my code sample as following:
```
helpers.bulk(es, actions)
es.update(index=self.INDEX, doc_type='users', body=_dic2, id=sid)
or
es.update(index=self.INDEX, doc_type='users', body=_dic2, id=sid,timeout=10)
```
Thanks a lot!

**Comment by HonzaKral** [comment]
Hello, I am afraid I do not understand what you mean by "async API". Elasticsearch doesn't have any asynchronous APIs so I am unsure of what you are trying to achieve. Could you please clarify?

Thanks!

**Comment by JackWang917** [comment]
thanks Honza, I thought ES has Async API, just got to know it's CRUD API always Sync.
