### ISSUE TITLE
es.indices.exists() gives different answer when ignoring warnings

### ISSUE THREAD

**Issue by pkphlam** [elastic/elasticsearch-py#350]
The index 'asdf' does not exist. 

When I do 
```
es.indices.exists('asdf')
```
I get False, which is correct, but I also get a 404 warning returned, which I don't really want.

So then if I do
```
es.indices.exists('asdf', ignore=404)
```
I no longer get the warning returned, but now this returns True, which is incorrect.

Is this expected behavior? Do I have to disable warnings some other way if I don't want them?

**Comment by HonzaKral** [comment]
Can I ask why you are passing the ignore parameter? Essentially you are saying to elasticsearch client to ignore if the index doesn't exist, so if it doesn't exist it will ignore that fact and return true, as expected.

If you do not want warning in the logs you need to disable them using standard logging module in python.
