### ISSUE TITLE
Mismatch between expected and actual transport interface

### ISSUE THREAD

**Issue by TedSinger** [elastic/elasticsearch-py#351]
The perform_request method of RequestsHTTPConnection and Urllib3HTTPConnection both return three values: status, headers, data. The search method in client/__init__.py expects two values: _, data. The search method fails with "Too many values to unpack".

**Comment by davekonopka** [comment]
@TedSinger Did you ever track down what was causing your problem?

**Comment by HonzaKral** [comment]
The interface of `*Connection.perform_request` changed between version of `elasticsearch-py` so I assume this was cause by using a mismatched versions - a custom `*Connection` class meant for newer version run with older version of `Elasticsearch`.
