### ISSUE TITLE
"timeout" in Doc-string for Elasticsearch.bulk should be request_timeout

### ISSUE THREAD

**Issue by sandros666** [elastic/elasticsearch-py#354]
`es.bulk(body=someBody,timeout=30)`
returns:
`elasticsearch.exceptions.RequestError: TransportError(400, 'parse_exception', 'Failed to parse setting [timeout] with value [30] as a time value: unit is missing or unrecognized')`

While:
`es.bulk(body=someBody,request_timeout=30)`
runs like a charm. 

So I think master/elasticsearch/client/__init__.py at line 772 should be:
_:arg request_timeout: Explicit operation timeout_
instead of:
_:arg timeout: Explicit operation timeout_

Two additional things:
1) I am new to this repository stuff, if this should have been a pull request instead of an issue, I am sorry
2) I am using elasticsearch 2.0, I assumed that in the last version it would be the same

**Comment by HonzaKral** [comment]
Thanks for the report, unfortunately the situation with `timeout` is a bit more complex. It is described here: http://elasticsearch-py.readthedocs.org/en/master/api.html#timeout

Hope this helps

**Comment by sandros666** [comment]
From the link you posted, I understand that in es.bulk it should always be `request_timeout`, while `timeout` is set for the general case.

**Comment by HonzaKral** [comment]
yes, that is absolutely correct - `request_timeout` is what you are looking for.
