### ISSUE TITLE
Will mapper attachments be supported

### ISSUE THREAD

**Issue by gerosalesc** [elastic/elasticsearch-py#355]
Now that this [mapper attachments plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/mapper-attachments.html) is part of the elasticsearch official repo, will this library be supporting such feature? I mean, in the case it isn't supported already. If it is I can't find it anywhere in the docs.

**Comment by HonzaKral** [comment]
The mapper attachment plugins doesn't actually have much in terms of APIs, just a few other options for mappings and documents, but those are only ever used in the bodies of requests so they are not affected by this library. Or is there something I am missing?

Thanks!

**Comment by achaussende** [comment]
The mapper attachment plugin does not change anything for elasticsearch-py. I'm using it and it works fine :)

**Comment by HonzaKral** [comment]
thanks for the confirmation @achaussende
