### ISSUE TITLE
AWS Elasticsearch connection fails

### ISSUE THREAD

**Issue by jheld** [elastic/elasticsearch-py#366]
I am trying to connect to my elastic search node on AWS.

My AWSAuth instance, when passed into requests.get, allows me to successfully contact the server and get a 200, via the docs about Basic Usage for requests-aws4auth.

However, following your docs in regards to adding this into the Elasticsearch object instance init, calling ping, etc, show the following:

ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd7540a17b8>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd7540a17b8>: Failed to establish a new connection: [Errno -2] Name or service not known)

I have specified the correct region. My host info is directly from my environment var, and I've verified its value. And again, the aws_auth object with my creds is fine.

Any ideas?

**Comment by jheld** [comment]
All is good. I was saving the connection params into a dictionary and passing that into the Elasticsearch instance init, but I wasn't using star-magic. So, we're good. ping, count, info, work.

Thanks for the documentation as is and for the library.

**Comment by jgardezi** [comment]
I am having issues with connecting to AWS Elasticsearch when used in AWS Lambda function. When I run python function on local machine it works however when I put it in Lambda function it does not works. No connection error nothing on my cloudwatch logs.

This is code 
```
    from elasticsearch import Elasticsearch, RequestsHttpConnection

    try:
        es = Elasticsearch(
            hosts=[{'host': config.es_host, 'port': 80, 'timeout': config.es_timeout}],
            # use_ssl=True,
            connection_class=RequestsHttpConnection
        )
        print (es.info())
        # print(es.cluster.health())
        # print ('Connection info: '.format(es.info()))
    except ElasticsearchException as e:
        print(e)
        print('ElasticSearch client connection issue')
        raise e

    print('Loaded ES Client {}'.format(es))
```
