### ISSUE TITLE
Search returns different results when "routing=None" compared to when it's not added at all

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch-py#375]
Using es 2.2.

The only thing that I change is by commenting or uncommenting the routing value.

    result = es.search(
        index='product',
        doc_type='p',
        size=limit,
        from_=limit * (page - 1),
        body=body,
        #routing=None
    )
I go from ~16M documents when routing is commented, to 3.2M when it's uncommented. Making it '' returns no results at all.

**Comment by HonzaKral** [comment]
We assume a string value for routing (or any other query parameters) so we just serialize them as strings. This means passing in `None` results in a query containing `routing=None` in the query parameters.

There are several possibilities how we can deal with this:

1. do nothing, document this behavior better
2. drop query parameters set to `None`
3. serialize `None` as empty string

I am not a fan of wither of these solutions, which one would people prefer?

**Comment by ddorian** [comment]
1. is required if the implementation doesn't change
2. i don't know how it will affect other parameters, but this makes the most sense
I don't think any query-parameter has a valid value of None in there (from a quick look)
3. nah

Why aren't you a fan of 2 ?

I(everyone?) expect routing=None to be dropped honestly.

**Comment by HonzaKral** [comment]
Thanks for your input (and for the report in the first place!)

2 seems a bit "magical" to me - it could potentially be confusing because there are several parameters that are essentially flags (`pretty`, `v` in `_cat` apis) and even without a value have meaning. I think it might be more surprising then to some people as opposed to us treating everything as a string.

But as I said, I am not a fan of 1 or 3 either.

Let's leave it here for a few days and see if other people react before we decide.

**Comment by ddorian** [comment]
Shouldn't flags be set with something like True/1/whatever, None makes no sense for activating a flag I think (it's not readable to a developer, pretty=None doesn't activate it). 

I understand that elasticsearch probably just looks if 'pretty' is in the query-string and doesn't care for it's value at all.

I think 
    kwargs = {k:v for k,v in kwargs.items() if v is not None}
before sending the data  makes sense and ~should logically not break any code.

**Comment by jbbarth** [comment]
+1 for the "2" solution. Given that the routing parameter has to be a string, I think it makes sense to have that kind of special value here, and it reflects a common practice in many python or ruby libraries. The current behavior is weird imho.

**Comment by sjmc7** [comment]
Adding my 2c - I was also quite surprised by the current behavior last week; dropping parameters with a value of 'None' seems intuitive to me and consistent with other similar libraries (requests, for instance).
