### ISSUE TITLE
reindex doesn't preserve _version

### ISSUE THREAD

**Issue by sjmc7** [elastic/elasticsearch-py#383]
The reindex helper explicitly selects fields=('_source', '_parent', '_routing', '_timestamp') when preparing to scan the source index, which results in _version numbers getting reset. In my particular case we're using external versioning where losing the _version has some unpleasant side effects, but even with the default versioning I can't think of a reason this behavior would be desired given that the versioning is purely to help detect conflicts, not to enable change tracking.

**Comment by HonzaKral** [comment]
Unfortunately the scroll request cannot return back `_version` - it is only returned when you do a `GET` request. Also with new release of elasticsearch there will be a built-in reindex API that allows for preserving versions - https://github.com/elastic/elasticsearch/issues/15201

For these reasons I am afraid we won't be implementing the option in the python helper.

In the mean time what I'd suggest iss essentially implement your own `reindex` function (it is very easy, just use the `scan` and `(streaming_/parallel_)bulk`) and inject your own version information in there.

**Comment by HonzaKral** [comment]
I am closing this issue since there is correctly no way we can provide a scalable solution to this issue and there is a `reindex` api coming to elasticsearch itself soon.
