### ISSUE TITLE
elasticsearch script partial update nested json object into array

### ISSUE THREAD

**Issue by shakthydoss** [elastic/elasticsearch-py#384]
I am getting error when inserting nested json object into an array. 

   upscript = {
		'script': {
			'inline': 'ctx._source.comments += comment', 
			'params': {
				"comment": [ {"id": 123, "body": "boom" }] 
			}
		}
	}
	
Error : RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [comments]')

I have enabled dynamic scripting in my config/elasticsearch.ylm 
script.inline: true
script.indexed: true

May I missing any thing please help.

**Comment by HonzaKral** [comment]
Can you please share your mappings for this document type as well as the code you use to send this to elasticsearch? Thanks!

**Comment by HonzaKral** [comment]
I am sorry, I cannot help you without further information, feel free to reopen the ticket and provide the mappings.

My guess would be that you are using the mapper attachment and the data you provided are not in correct format.

**Comment by NandanPhadke** [comment]
I am facing similar issue using elastic search output with logstash. Here is my sample event
{
"guid":"someguid",
"nestedObject":{
"field1":"val1",
"field2":"val2"
}
}

Here is what I want to have in my elastic search document:
{
"nestedObjects":[{
"field1":"val1",
"field2":"val2"
},
{
"field3":"val3",
"field4":"val4"
},
}

Here is my current elastic search output setting:
elasticsearch {
		index => "elastictest"
		action => "update"
		document_type => "summary"
		document_id => "%{guid}"
		doc_as_upsert => true
		script_lang => "groovy"
		script_type => "inline"
		retry_on_conflict => 3
		script => "
				if (ctx._source.nestedObjects) {
					ctx._source.nestedObjects += event.nestedObject
				} else {
					ctx._source.nestedObjects = [event.nestedObject]
				}
		"
	}

Here is the error I am getting:
response=>{"update"=>{"_index"=>"elastictest", "_type"=>"summary", "_id"=>"64648dd3-c1e9-45fd-a00b-5a4332c91ee9", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [event.nestedObject]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"unknown property [field1]"}}}}

**Comment by HonzaKral** [comment]
@NandanPhadke I am afraid you have the wrong repository as the code you pasted looks more like a logstash configuration.

Either way it looks like you have a conflict in your mappings where it doesn't recognize the `field1` property.
