### ISSUE TITLE
How to control amount of logging in parallel_bulk operation ? 

### ISSUE THREAD

**Issue by asa88** [elastic/elasticsearch-py#385]
I would like to control the amount of logging in the bulk loading operation, I do not see any param in the documentation the can do so. Any Ideas ?

**Comment by HonzaKral** [comment]
`elasticsearch-py` uses the standard logging module, it defines two loggers - `elasticsearch` and `elasticsearch.trace` (0). To control the level of logging just set the level on the `elasticsearch` logger. If there is anything else you'd like to see in your logs, specific for the `parallel_bulk`, please let us know. Thanks!

0 - http://elasticsearch-py.readthedocs.org/en/master/#logging

**Comment by HonzaKral** [comment]
closing this issue since it was answered and there is no new information.
