### ISSUE TITLE
Provide `_scroll_id` within Scan Helper

### ISSUE THREAD

**Issue by brandomr** [elastic/elasticsearch-py#389]
A scan object should provide `_scroll_id` so that if the scan times out it can be restarted from the last `_scroll_id` position. Currently on error the scan must be restarted from the beginning. Scan Helper would then accomodate a `_scroll_id` parameter.

**Comment by HonzaKral** [comment]
How would you imagine this working? Usually when there is an error it means that the scrolling is not recoverable. If you wish to continue you can set the scan helper to ignore errors and not raise exceptions when encountering some.

We can definitely attach the last seen `_scroll_id` to the `ScanError`, would that make sense to you?

Thanks!
