### ISSUE TITLE
log_request_success

### ISSUE THREAD

**Issue by cp2587** [elastic/elasticsearch-py#391]
We recently discovered that the 'log_request_success' method of the class Connection can slow down a query because of the following line: 
`tracer.debug('#[%s] (%.3fs)\n#%s', status_code, duration, _pretty_json(response).replace('\n', '\n#') if response else '')`. 

If the user doesn't take care of its logging configuration ('elasticsearch' logger set to NOTSET for instance), this line will negatively impact the performance of the library. In our case, it was quite visible as we are working with a very heavy returned json (without the logging, overall the function was running in 2s, with it it took 6s !)
Maybe you should state somewhere in the docs to watch your logging configuration when doing some big query ? Also, for now we just set:
`'elasticsearch': {'level': 'CRITICAL'}`

In our logging dicConfig (https://docs.python.org/2/library/logging.config.html#logging.config.dictConfig), do you guys think it is enough to be sure to not have our performance impacted badly by any logging line of the library ?

**Comment by HonzaKral** [comment]
That line is only executed if that logger is enabled - exactly because it is expensive - see the `if` statement around it.

The trace logger that this code belongs to needs to be explicitly enabled and is only meant for debugging, definitely not for production use.

The config you provided is definitely sufficient to disable all logging from elasticsearch since we don't use the `CRITICAL` level at all.

**Comment by cp2587** [comment]
Yes, i figured about the if :) Weird thing is that before setting the logger level to 'CRITICAL', our code was running with a simple dictConfig with disable_existing_logger = True (and no live concerning elasticsearch in our logging config) and so i never explicitely enable the logger but it still passed the if condition.

**Comment by HonzaKral** [comment]
This seems like a bug in the logging library if it is indeed so, could you please share you concrete logging configuration so I can try and replicate it? Thanks!

**Comment by HonzaKral** [comment]
oh, I see what's goin on, we are missing a call to `logger.hasHandlers` as well as `isEnabledFor`, fix incoming
