### ISSUE TITLE
Expose method to create request using URL

### ISSUE THREAD

**Issue by rskumar** [elastic/elasticsearch-py#393]
Given an elasticsearch connection object, I want to hit `/_cluster/stats?human&pretty` . Currently there is no method available to pass url-path.

Ex: 
```
es_client.get('/_cluster/stats?human&pretty', body={})
```

**Comment by HonzaKral** [comment]
There is a dedicated method for this api - http://elasticsearch-py.readthedocs.org/en/master/api.html#elasticsearch.client.ClusterClient.stats

if you want to make requests manually, you can access the `perform_request` method of the `transport` property on the client.

Hope this helps.

**Comment by rskumar** [comment]
Thanks, can you please share an example how to use `perform_request`?

**Comment by HonzaKral** [comment]
Absolutely, have a look at any of the methods in the client, in this particular case https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/cluster.py#L92-L95 is a good example.

Just note that in master the behavior has changed - in previous, released, version the method returned a tuple of `status, data` where it now only returns the `data`.
