### ISSUE TITLE
Bug: termvectors method doesn't work

### ISSUE THREAD

**Issue by clairejaja** [elastic/elasticsearch-py#398]
Running Elasticsearch v 1.5.2, using version 1.9.0 of this library

The termvectors method returns a TransportError ("No handler found for uri") because it is using the syntax introduced by ES versions >=2.0 `_termvectors` instead of that used by ES 1.0 versions `_termvector`.  Should be an easy fix.

**Comment by HonzaKral** [comment]
For elasticsearch `1.5.2` you need to use the `termvector` API:
```
es = Elasticsearch()
es.index(index="i", doc_type='t', id=1, body={"some": "longer text here"})
es.termvector(index="i", doc_type='t', id=1, fields="some")
```
Hope this helps
