### ISSUE TITLE
sort on search query not working for float type

### ISSUE THREAD

**Issue by GabeMath** [elastic/elasticsearch-py#399]
I did a search query, and set the sort parameter on a filed of type float (it was a field containing epoch times). I later repopulated another index with the same data, except that I changed this field to type double. This worked. So is it me or is the api not allowing me to sort on float types?

**Comment by HonzaKral** [comment]
Could you please provide an example of the code that you were using and the data? Without it it's impossible to say what's going on.

Thanks!

**Comment by GabeMath** [comment]
Now that I think of it, I think float did not have enough precision to hold the epoch times.
 
Data (epoch time in microseconds, eg 1458927919.620700):

code:

search =  es.search(index="someIndex", doc_type="sometype",  sort="timefield:asc")

data = search['hits']['hits']
for x in data:
   time = x["_source"]["timefield"]
   print time

**Comment by GabeMath** [comment]
I thought I'd also show how I created the index.
 
```python
mapping = '''
{  
  "mappings":{  
      "sometype": {
      "properties":{  
        "timefield" : {"type" : "float"},
        }
      }
    }
}'''

es.indices.create(index="someIndex", body=mapping)
```

**Comment by HonzaKral** [comment]
Yeah, float is definitely the wrong data type for this. Ideally what you want is to just use the `date` type which is stored internally as number of milliseconds since the epoch. If you really want the microseconds you need to store it as double.

**Comment by koradiya-kaushal** [comment]
i have long datatype for field in index, but when i am sorting by order asc i am getting data in this order => 0.5 , 0.75 , 0.5 , 0.6 , 0.6 .
