### ISSUE TITLE
The client issues GET requests with body 

### ISSUE THREAD

**Issue by ngrigoriev** [elastic/elasticsearch-py#401]
I was trying to test my new installation of elastalert, which depends on elasticsearch-py, and found something odd. A simple test did not work, returning HTTP 400. I tested the GET URL manually and it worked. Long story short, I did a quick tcpdump and found this:

```
GET /structlogs-*/_search?ignore_unavailable=true&size=1 HTTP/1.1
Host: elasticsealan.mydomain.net:myport
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.10.0
Content-Length: 239
{"sort": [{"@timestamp": {"order": "asc"}}], "query": {"filtered": {"filter": {"bool": {"must": [{"range": {"@timestamp": {"gt": "2016-05-09T20:17:31.602083Z", "lte": "2016-05-10T20:17:31.602110Z"}}}, {"term": null, "level": "DEBUG"}]}}}}}

HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Content-Length: 23952
{"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures....
```

A quick check in the client code does make me think that (apparently more than one method) tries to use GET request when a body may be supplied by the caller.

**Comment by HonzaKral** [comment]
You seem to have a misshapen query - `{"term": null, "level": "DEBUG"}` is not a valid query, should be `{"term":{"level": "DEBUG"}}` instead.

There are some issues with GET requests with body, but not by elasticsearch - usually only happens when people use a load balancer or http proxy. This issue is not related to that - since you get a concrete exception it should tell you exactly what's going on.

**Comment by ngrigoriev** [comment]
Oh, I see...I have just realized that ES actually does seem to use GET requests with the body! Luckily, I do not have any HTTP proxy fronting ES so this 400 must be result of, as you said, malformed DSL body.
As for the actual query - it is sent by Elastalert code. Let me try it manually and I will close this issue momentarily.

**Comment by ngrigoriev** [comment]
Yes, sorry for the false alarm. I misinterpreted that 400, it was indeed because of the bad DSL body. I have tried that Elastalert query manually with curl and with your corrected "term" value it works.
