### ISSUE TITLE
Document differences between urllib3 and requests transport backends

### ISSUE THREAD

**Issue by edmorley** [elastic/elasticsearch-py#402]
The transport page mentioned that one can choose between the (default) urllib3 transport backend and a requests-based one:
https://elasticsearch-py.readthedocs.io/en/master/transports.html

However it's not clear as to the advantages/disadvantages of one over the other.

It would be great to add a couple of sentences explaining what their differences are, and use-cases for both :-)

**Comment by HonzaKral** [comment]
Well, ideally you'd always use urllib3, it's only when you need requests for it's extra features (using some plugin like `requests-aws4auth` for example) that you should consider `requests` backend. I will try to add a sentence explaining this to the docs, thanks for pointing out the omission!

**Comment by edmorley** [comment]
Ah that makes sense, thank you.

One other difference that just occurred to me - when using requests you can simply pass `verify_certs=True` and requests handles the setup of certifi (using its vendored copy), rather than needing to do so manually with the urllib3 backend (which #403 would ideally resolve).

**Comment by edmorley** [comment]
That's great, thank you :-)
