### ISSUE TITLE
Automatically set ca_certs if certifi if installed and verify_certs=True

### ISSUE THREAD

**Issue by edmorley** [elastic/elasticsearch-py#403]
At the moment to use SSL certificate verification with the urllib3 backend, [the docs](https://elasticsearch-py.readthedocs.io/en/master/index.html#ssl-and-authentication) say to:
* pass `verify_certs=True`
* either set `ca_certs` to the location of the system root certificates, or else install certifi and use:
```python
import certifi

es = Elasticsearch(
    # ...
    ca_certs=certifi.where(),
)
```

Ideally it would be better to automatically use the value from `certifi.where()` if certifi is available (and the user hadn't set `ca_certs` themselves) - avoiding the need for the boilerplate above.

The elasticsearch-py docs could then be simplified to say something like:
*"To enable certificate verification, install certifi and pass `verify_certs=True`, or manually pass your own certificates like so..."*

This would be similar to the requests library behaviour (except instead of falling back to the vendored version, it would fall back to `None`):
https://github.com/kennethreitz/requests/blob/v2.10.0/requests/certs.py#L17

This could also pave the way in the future to inverting the value for `verify_certs` and actually having it enabled by default (or at least by default iff certifi is found).

I'm happy to open a PR if this would be accepted?

**Comment by HonzaKral** [comment]
Thanks for the proposal. A PR would definitely be most welcome!

**Comment by jpblair** [comment]
I think the docs could be more clear on the current behavior, too:
`To have working SSL certificate validation you need to either specify your own as ca_certs or install certifi which will be picked up automatically.`
There is no indication that you need to `import certifi` and pass `ca_certs=certifi.where()` when constructing the client.

**Comment by HonzaKral** [comment]
You don't have to pass `certifi.where()`, it happens automatically in `5.0` release. In the documentation for `2.4` it is correctly mentioned - http://elasticsearch-py.readthedocs.io/en/2.4.0/#ssl-and-authentication
