### ISSUE TITLE
elasticsearch.exceptions.RequestError: TransportError(400, u'parse_exception', u'Failed to derive xcontent')

### ISSUE THREAD

**Issue by amitsi** [elastic/elasticsearch-py#404]
***Version I am using*****

  "version" : {
    "number" : "5.0.0-alpha2",
    "build_hash" : "e3126df",
    "build_date" : "2016-04-26T12:08:58.960Z",
    "build_snapshot" : false,
    "lucene_version" : "6.0.0"
  },

*****************

>>I get the error towards the end of this message when I try and load some json data into elasticsearch

***Python code****
  r = requests.get('http://172.26.10.1/vRest/client-server-stats', auth=HTTPBasicAuth('admin', 'admin'))
    print json.loads(r.content)
    es.bulk(index='tcpanalytics', doc_type='json', body=json.loads(r.content))
*******************

******Sample data******

{u'result-list': {u'status': u'Success', u'results': [{u'status': u'Success', u'scope': u'local', u'message': u'', u'code': 0, u'api.switch-name': u'local'}]}, u'client-server-stats-show-list': [{u'count': 0, u'server-switch-port': 16, u'est': 14, u'client-ip': u'10.9.10.209', u'last-seen-ago': 454172, u'first-seen': u'2016-05-10T18:42:33', u'fin': 0, u'vlan': 1, u'server-mac': u'00:00:5e:00:01:0a', u'syn': 0, u'server-port': 443, u'server-ip': u'54.230.144.194', u'client-mac': u'b8:4f:d5:0d:96:f3', u'last-seen': u'2016-05-10T18:42:49', u'client-switch-port': 46, u'vxlan': 0}, {u'count': 0, u'server-switch-port': 16, u'obytes': 1043, u'est': 0, u'client-ip': u'10.9.10.193', u'total-bytes': 7364, u'first-seen': u'2016-05-11T10:49:07', u'fin': 2, u'vlan': 1, u'server-mac': u'00:00:5e:00:01:0a', u'syn': 0, u'ibytes': 6321, u'server-port': 80, u'last-seen-ago': 396155, u'avg-dur': 78312844273, u'server-ip': u'54.230.144.194', u'client-mac': u'd8:eb:97:bd:22:0a', u'avg-lat': 7330081, u'last-seen': u'2016-05-11T10:49:46', u'client-switch-port': 46, u'vxlan': 0}, {u'count': 0, u'server-switch-port': 16, u'obytes': 18871, u'est': 0, u'client-ip': u'10.9.10.148', u'total-bytes': 40790, u'first-seen': u'2016-05-11T12:14:36', u'fin': 38, u'vlan': 1, u'server-mac': u'00:00:5e:00:01:0a', u'syn': 0, u'ibytes': 21919, u'server-port': 80, u'last-seen-ago': 289211, u'avg-dur': 90128802635, u'server-ip': u'54.230.144.194', u'client-mac': u'3c:15:c2:e2:de:16', u'avg-lat': 118008111, u'last-seen': u'2016-05-12T16:32:10', u'client-switch-port': 46, u'vxlan': 0}, {u'count': 0, u'server-switch-port': 16, u'obytes': 3944, u'est': 4, u'client-ip': u'10.9.10.70', u'total-bytes': 208511, u'first-seen': u'2016-05-11T16:32:40', u'fin': 7, u'vlan': 1, u'server-mac': u'00:00:5e:00:01:0a', u'syn': 0, u'ibytes': 204567, u'server-port': 80, u'last-seen-ago': 375266, u'avg-dur': 652239407229, u'server-ip': u'54.230.144.194', u'client-mac': u'00:0e:c6:c2:82:d5', u'avg-lat': 4594246990, u'last-seen': u'2016-05-11T16:37:55', u'client-switch-port': 46, u'vxlan': 0}]}

*********

****Full Error Message****

Traceback (most recent call last):
  File "resttoelastic.py", line 98, in <module>
    es.bulk(index='tcpanalytics', doc_type='json', body=json.loads(r.content))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 795, in bulk
    doc_type, '_bulk'), params=params, body=self._bulk_body(body))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'parse_exception', u'Failed to derive xcontent')
root@amitsi:/mnt/hgfs/Documents#

**Comment by HonzaKral** [comment]
The `bulk` API has a very different format and doesn't accept raw documents, each document needs to have a metadata line and a line containing data following it - see https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

To make this simpler the python client has a helper for bulk operations - http://elasticsearch-py.readthedocs.io/en/master/helpers.html#bulk-helpers

Hope this helps

**Comment by amitsi** [comment]
Thanks, Is there a example for the helper that you could point me to?

**Comment by HonzaKral** [comment]
https://github.com/elastic/elasticsearch-py/blob/master/test_elasticsearch/test_server/test_helpers.py is probably a good place to start. mostly trivial examples, but should provide an idea of how bulk helpers work.
