### ISSUE TITLE
Scripts in bulk partial updates [2.x]

### ISSUE THREAD

**Issue by oleduc** [elastic/elasticsearch-py#405]
Hi,

I've noticed that the function "expand_action" which seems responsible for transforming an action array passed to the bulk helpers does not support scripting for bulk actions.

It also seems like its possible to override it by passing a function using the "expand_action_callback" keyword argument, but it seems to me like this could be supported by default. 

I just wanted to check in with the project maintainers before submitting a pull request to this effect. If passing an overrided "expand_action_callback" is whats expected then I won't bother.

Thank you very much.

**Comment by HonzaKral** [comment]
Hi, the callback actually doesn't care whjat's in the document so it should be fine to send a dict containing a script-based update, everything will work.

Do you have concrete example of what doesn't work atm?

Thanks!

**Comment by oleduc** [comment]
Hi, you're right, it seems that if you format a partial update action with a script as such:

            {
                '_op_type': 'update',
                '_index': 'index_name',
                '_type': 'Type',
                '_id': 1,
                '_source': {"script": {
                    "inline": "ctx._source.items[position]=nested_document",
                    "params": {
                        "position": 1,
                        "nested_document": {"foo":"bar"}
                    }
                }}
            }

It does indeed format it as expected. I thought I had to provide the script in a different action with a different "_op_type" field, which led to my initial confusion.

Thank you very much for the quick response and sorry for this non-issue.

**Comment by HonzaKral** [comment]
You don't even have to wrap it in `_source` - having the `script` key on top level will work as well and the dict will make more sense when inspected.

**Comment by oleduc** [comment]
Quite right!

        {
            '_op_type': 'update',
            '_index': 'index_name',
            '_type': 'Type',
            '_id': 1,
            "script": {
                "inline": "ctx._source.items[position]=nested_document",
                "params": {
                    "position": 1,
                    "nested_document": {"foo":"bar"}
                }
            }
        }

Produces the same expected output by popping all the other properties and adding the rest as the next line. I had overlooked the default in the return statement.

    return action, data.get('_source', data)

Thanks again!
