### ISSUE TITLE
exists() should not return always True with ignore=404

### ISSUE THREAD

**Issue by SemanticGames** [elastic/elasticsearch-py#412]
When querying a missing document,
`get(index=index, doc_type=doc_type, id=id)`
raises an exception, and
`get(index=index, doc_type=doc_type, id=id, ignore=404)`
returns no result, as expected, without the exception.

But if
`exists(index=index, doc_type=doc_type, id=id)`
raises an exception, as expected,
`exists(index=index, doc_type=doc_type, id=id, ignore=404)`
returns True, i.e. the incorrect result.

Shouldn't `exists(ignore=404)` return the correct answer without the exception?

**Comment by HonzaKral** [comment]
`exists` should not raise an exception when the document doesn't exist. Can you provide an example of when this happens?

The other part is definitely a bug - `exists` functionality relies on the exceptions for implementation so suppressing the exception leads to wrong results, that is a leak in the abstraction and needs to be fixed.

**Comment by SemanticGames** [comment]
Sorry, I misused "exception", I meant that the following line is displayed in the error output when `ignore=404` is not set:
`HEAD /<index>/<type>/<id> [status:404 request:0.205s]`

But the bug remains: the behavior of `exists()` is not natural with `ignore=404`.

**Comment by HonzaKral** [comment]
Both issues (logging of HEAD 404 responses as warning and HEAD returning True for 404) has been fixed in both `2.x` and `master`. Thanks for the report!
