### ISSUE TITLE
 Add ElasticSearch 5.0 support

### ISSUE THREAD

**Issue by JanMalte** [elastic/elasticsearch-py#416]
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-5.0.html

**Comment by HonzaKral** [comment]
Master branch of this library should compatible with elasticsearch 5.0. Is there anything you are missing there?

**Comment by JanMalte** [comment]
Maybe just a new release on PIP ;)

**Comment by HonzaKral** [comment]
The API for elasticsearch is still evolving a bit so I would like to postpone the release until it has settled.

In the mean time you can always just use pip to install elasticsearch from github for testing purposes: `pip install git+https://github.com/elastic/elasticsearch-py#egg=elasticsearch`

**Comment by speedplane** [comment]
The frontpage README says:

> For Elasticsearch 5.0 and later, use the major version 5 (5.x.y) of the library.

But there is no 5.x.y version of the library in the tags. For now, should it just say to use master?

**Comment by auvipy** [comment]
elk just hit 5.0.0beta-1, does that indicate API freeze? or they do in RC?

**Comment by aspickard** [comment]
It's in RC now either way ;)

**Comment by untergeek** [comment]
@HonzaKral it would be _really_ nice if we put it in pip. There are no more API changed expected. I can't do automated testing in Travis without it being in pip, so I'm asking for this too.

**Comment by HonzaKral** [comment]
Closing via https://pypi.python.org/pypi/elasticsearch/5.0.0

Thanks for your patience, `5.0` was a bit of a moving target :)

**Comment by untergeek** [comment]
@HonzaKral You ROCK!
