### ISSUE TITLE
Support for update_by_query

### ISSUE THREAD

**Issue by vineet-rh** [elastic/elasticsearch-py#417]
Python client support for the newly added update_by_query query

**Comment by HonzaKral** [comment]
Fixed in a359c5fba266df4ff9a8a31e10b9d25abad4f3c9

Thanks!

**Comment by spazm** [comment]
Is there any chance of this getting into the 2.x branch?  `update_by_query` was added in 2.3.  
The commit message for a359c5f is "ES 5.0 APIs" and contains the update_by_query change as well as other changes to support 5.0 changes.

I could extract the `update_by_query` changes for the 2.x branch if that would be useful/appreciated.

thanks.
