### ISSUE TITLE
Is it possible to get search body?

### ISSUE THREAD

**Issue by AbdullaM5** [elastic/elasticsearch-py#420]
How can I get request body? I need it for debug purposes

**Comment by HonzaKral** [comment]
I am afraid I am not sure I understand what you need. When you send a request via the API we just serialize the `body` that you pass in. There is nothing else going on.

Could you provide an example of what you are looking for? Thanks!

**Comment by AbdullaM5** [comment]
@HonzaKral All I need is to see what request(his type, body, address) was send to elastic server

**Comment by HonzaKral** [comment]
All of these things are logged so all you have to do is enable logging via the standard python `logging` module - http://elasticsearch-py.readthedocs.io/en/master/#logging.

Easiest way is to just include the following code:
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by AbdullaM5** [comment]
@HonzaKral Oh, that's my bad. Thanks for the fast answer )
