### ISSUE TITLE
Would it be possible to support ignore option for get call?

### ISSUE THREAD

**Issue by jim12321** [elastic/elasticsearch-py#421]
Would prefer to have support to ignore 404 when a GET call does not find the document and we can just make a call based on results['found'] instead of having to wrap the GET call within a try: except: code.  Given create, index and other calls support he ignore option.

Would allow to make code more standardized.

**Comment by jim12321** [comment]
By the way, paying Elastic client.  Also opened a support ticket, but figured I would post here too.

**Comment by HonzaKral** [comment]
There is indeed an `ignore` parameter that you can use, simply running:
```
from elasticsearch import Elasticsearch
es = Elasticsearch()
doc = es.get(index='i', doc_type='t', id=42, ignore=404)
```
You can find more information about `ignore` at http://elasticsearch-py.readthedocs.io/en/master/api.html#ignore
