### ISSUE TITLE
Option to disable HTTP chunking

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/elasticsearch-py#422]
[This doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) suggests disabling HTTP chunking.
Is there an option to do that?

**Comment by HonzaKral** [comment]
Chunking should be disabled by default in `elasticsearch-py` so this shouldn't be an issue.

**Comment by eugenemiretsky** [comment]
Thanks! 
Is there a way to enable it? (just so we can test performance difference)

**Comment by HonzaKral** [comment]
You would have to create your own connection class by extending `Urllib3HttpConnection` and then override it's `perform_request` method to pass `chunked=True` to the `urlopen` call. Then you just instantiate the client by doing: `Elasticsearch(connection_class=MyConnectionClass)`
