### ISSUE TITLE
Multiple Consecutive index request to elasticsearch fails

### ISSUE THREAD

**Issue by aniamin** [elastic/elasticsearch-py#423]
I am trying send a number of data into elasticsearch using `elasticsearch-py` client. I am iterating over list of data using loop and sending it to elasticsearch.
```
for data in data_list:
    es.index(index=index_name, doc_type=document_type, id=data["_id"], body=json.dumps(data))
```
Sometimes I find that some data is not properly inserted

Should I use `bulk` or anything similar?

**Comment by HonzaKral** [comment]
Hi, you should definitely be using `bulk` for inserting multiple documents at once. You can look at the bulk helpers that make it much simpler - http://elasticsearch-py.readthedocs.io/en/master/helpers.html#bulk-helpers

That said the approach you are using should work, the `bulk` is just way more efficient. What exactly goes wrong when you do this?

**Comment by aniamin** [comment]
I have initialized the elasticsearch in this way.
def __init__(self, host, port):
        self.host = host
        self.port = port
        self.es = Elasticsearch(hosts=[{"host": host, "port": port}])

When I am trying to run this bulk operation
`helpers.bulk(self.elasticsearch_client, bulk_documents, index=self.INDEX_NAME, raise_on_error=True)`

 I am getting below error:
`ElasticSearchClient' object has no attribute 'transport'`

**Comment by HonzaKral** [comment]
Please see my response in https://github.com/elastic/elasticsearch-py/issues/431

**Comment by aniamin** [comment]
Now the issue is resolved
