### ISSUE TITLE
Update by query API

### ISSUE THREAD

**Issue by davidt99** [elastic/elasticsearch-py#425]
There is any plans to add the [update by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) API call?
I know it still considered experimental, but I don't see any reason not to expose it.

**Comment by vineet-rh** [comment]
Would love to have this as part of the actual release too. Its a really useful feature.

**Comment by vineet-rh** [comment]
Any updates on when this should be available as part of a release?
