### ISSUE TITLE
Validate body

### ISSUE THREAD

**Issue by stickperson** [elastic/elasticsearch-py#426]
In my use cases, the `body` param has always needed to be a `dict`. On a couple occasions I accidentally passed something else (say a list) and got some sort of `TransportError, Failed to derive xcontent`. I propose adding a simple validation (perhaps in `Transport.perform_request`) to make these errors more easily identified.

Off the top of my head I'm not sure if `body` is always a dict. If it is this should be straightforward. Otherwise it would take a bit more work, but I think we should have that discussion.

**Comment by HonzaKral** [comment]
Sometimes `body` can also be a string, a list or something that can be serialized into such. That makes any sort of validation unfortunately very difficult. In most cases when you pass in something wrong you will get a `SerializationError`, if it's, however, something that can correctly serialize, there is nothing we can do.

For more tighter control over the body for certain operations you can check out the dsl library - https://github.com/elastic/elasticsearch-dsl-py
