### ISSUE TITLE
Enhance indices.exists_alias() behaviour

### ISSUE THREAD

**Issue by acharp** [elastic/elasticsearch-py#429]
Currently if you call `indices.exists_alias(index=indexname)`  without giving any value for the parameter `name`, it will return `False` even if the index has one or several aliases. According to the HTTP API this behaviour is wrong, such a call should return `True`. 
That could be simply corrected either by adding a condition evaluating the name before making the request or by setting the default value of name at an empty string.

**Comment by HonzaKral** [comment]
The behavior of the python client is consistent with the http API which also returns `404`.
```
curl -X PUT localhost:9200/i
curl -X PUT localhost:9200/i/_alias/a
curl --head localhost:9200/i/_alias
```

If you feel this isn't correct I am afraid you'd need to open a ticket with elasticsearch itself, we only ever copy the behavior of the http API and avoid making any decisions of our own.
