### ISSUE TITLE
ElasticSearchClient' object has no attribute 'transport'

### ISSUE THREAD

**Issue by aniamin** [elastic/elasticsearch-py#431]
I have initialized the elasticsearch in this way.
def __init__(self, host, port):
        self.host = host
        self.port = port
        self.es = Elasticsearch(hosts=[{"host": host, "port": port}])

When I am trying to run this bulk operation
`helpers.bulk(self.elasticsearch_client, bulk_documents, index=self.INDEX_NAME, raise_on_error=True)`

 I am getting below error:
`ElasticSearchClient' object has no attribute 'transport'`

**Comment by HonzaKral** [comment]
HI @aniamin, I am not sure what `self.elasticsearch_client` (we have no class called `ElasticSearchClient`, it must come from somewhere else) is in your example. it looks like you should be doing `self.es` in the call to `bulk`.

Hope this helps.

**Comment by aniamin** [comment]
My mistake was I was not using the client properly. Now the issue is resolved. Bulk indexing is working like a charm.. thanks @HonzaKral
