### ISSUE TITLE
Getting ConnectionTimeout during creating index snapshots.

### ISSUE THREAD

**Issue by vachanda** [elastic/elasticsearch-py#436]
Hi,
I'm using elasticsearch version 1.4.4 running on ubuntu 14.04LTS. Its a 2 node setup with 3.5 GB of heap space for each node. I'm using elasticsearch-py version 1.4.0.

I'm trying to run a script which does the simple job of verifying the es repository and create index snapshots to that repository. 

`             snap_client = client.SnapshotClient(es_client)
               snap_client.get_repository(self.REPO_NAME, request_timeout=60)   
               snap_settings = {'indices': index_name, 'ignore_unavailable': True, 'include_global_state': True}
                snapshot_name = app_name + '-' + time.strftime('%Y%m%d%H%M%S')
                snap_client = client.SnapshotClient(es_client)
                snap_client.create(repository=self.REPO_NAME, snapshot=snapshot_name, body=snap_settings, request_timeout=60)`

But I keep getting, the following exception -
`ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'172.16.249.249', port=9200): Read timed out. (read timeout=60))`

I've even tried to increase the request_timeout, but in vain.

Any ideas on how to resolve it?

**Comment by HonzaKral** [comment]
Hi @vachanda,

unfortunately there is nothing I can do for you here - it looks like the operation is just timing out. Could you please try to replicate the same commands using `curl` on the command line and measure how long it takes?

btw you really shouldn't be instantiating `SnapshotClient` directly but instead be using `es_client.snapshot`.

Thanks!

**Comment by vachanda** [comment]
Hi @HonzaKral ,
Thanks for the response. Will try to use `es_client.snapshot`.

**Comment by vachanda** [comment]
Hi @HonzaKral ,
Increasing the `request_timeout` from the default value to `60` helps. Can it be set globally, at the client instantiation level rather than doing it for each ES function call?

**Comment by HonzaKral** [comment]
To do that you can just specify `timeout=60` when instantiating `Elasticsearch`:
```
es_client = Elasticsearch(["host1", "host2"], ..., timeout=60)
```

**Comment by vachanda** [comment]
@HonzaKral 
Thank you.
