### ISSUE TITLE
Elasticsearch 2.3: `error` attribute not available in bulk error object for delete action

### ISSUE THREAD

**Issue by strife25** [elastic/elasticsearch-py#437]
When I perform a bulk index action that includes a delete action on a document that doesn't exist:

```python
helpers.bulk(
    self.es_client,
   [{
        '_op_type': 'delete',
        '_index': 'my_index',
        '_type': central_message_type,
        '_id': central_id,
    }],
)
```

The object that gets returned has the following structure:

```python
[
    {
        'delete': {
            '_index': 'my_index',
            'found': False,
            '_type': 'my_doctype',
            '_version': 1,
            '_id': '<my_id>',
            'status': 404,
            '_shards': {
                'successful': 2,
                'total': 2,
                'failed': 0
            }
        }
    }
]
```

In that object, the `error` key is not available. From what I can tell, this key was available on documents that were not found when using ES 1.5 (and es-py 1.9.0), but does not exist anymore for this situation in the latest version.

This looks like an undocumented API change. I am unsure if this was due to a change with the Elasticsearch REST API or if this occurred in the library.

**Comment by strife25** [comment]
The workaround I've found for this issue is to change my error handling logic to conditionally check if `error` exists. If it doesn't exist and the `found` key is set to `False` or `status` is `404`, I can deduce that the error is a `Document Not Found` one.

**Comment by HonzaKral** [comment]
I am sorry, but I don't understand the issue. Why do you need the `error` attribute? What is it that you are trying to achieve? Could you please provide some example code for context?

Thank you1

**Comment by strife25** [comment]
I'm sorry about not correctly stating the problem. I have updated the description to better explain the problem I am observing.

> This looks like an undocumented API change. I am unsure if this was due to a change with the Elasticsearch REST API or if this occurred in the library.

Please let me know if there is any other information you need.

**Comment by HonzaKral** [comment]
We don't alter the body in any way so any changes that happened were part of the REST API of elasticsearch itself.

For workaround I would recommend using the `status` field which is also what we are using: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L124
