### ISSUE TITLE
clear_scroll failing on 2.4.0

### ISSUE THREAD

**Issue by slydon-apixio** [elastic/elasticsearch-py#438]
Just upgraded to 2.4.0 and clear_scroll is failing.  

I see in the traceback:
client.clear_scroll(body={'scroll_id': [scroll_id]}, ignore=(404, ))

But the warning log I see says a 400 was returned.

The following is the exception type:
elasticsearch.exceptions.RequestError

Did the usage change for elasticsearch.helpers.scan?  Is this a problem with my application or with the implementation of clear_scroll?

Edit: I should have said that I upgraded from 2.1.0.  I downgraded for now.

**Comment by HonzaKral** [comment]
Thank you for the report, I am, however, having trouble replicating this exception. Could you please provide more information on how to replicate this?

Ideally also a full content of the exception obtained from it's `.info` attribute.

Also, what elasticsearch version are you running?

Thanks!

**Comment by lbx6z** [comment]
![1](https://cloud.githubusercontent.com/assets/6837297/18623625/2100cf68-7e72-11e6-979c-15ac26bb1479.png)

**Comment by rshkv** [comment]
Hi,

I'm having the same issue. I upgraded my client from 2.3 to 2.4. The elasticsearch version is 1.5 (can't update).

The `.info` attribute is:
```python
{
 'status': 400, 
 'error': 'ElasticsearchIllegalArgumentException[Failed to decode scrollId]; nested: IOException[Bad Base64 input character decimal 123 in array position 0]; '
}
```
Doesn't look like the error lies with the parameters I pass to `helpers.scan()`.
This is the whole stack trace I'm getting: <br>
![stacktrace](https://www.dropbox.com/s/29t27v6bap2sgv4/clear_scroll_trace.png?dl=1)

Thank you!

**Comment by rafael-custodio** [comment]
I'm using the ES 1.6 and I'm having the same issue (can't update either)

**Comment by rafael-custodio** [comment]
Sorry, you can ignore my comment, I saw that I have to install an old version of the package.

**Comment by HonzaKral** [comment]
@rshkv `elasticsearcgh-py` 2.x doesn't support Elasticsearch version 1.x, it is not expected to work because behavior of scan/scroll has changed between those versions. You need to use the appropriate version - `1.7.0` in this case. You can see the details here - http://elasticsearch-py.readthedocs.io/en/master/#compatibility

@slydon-apixio what elasticsearch version are you using? Thanks!

**Comment by slydon-apixio** [comment]
Yeah 1.7. Sorry about the confusion on this.

**Comment by jaisharma639** [comment]
What's the fix for this issue? I'm getting 
`RequestError: TransportError(400, u'illegal_argument_exception', u'Failed to decode scrollId')
`
@HonzaKral ,i'm running ES 2.4

**Comment by HonzaKral** [comment]
@jaisharma639 and what version of `elasticsearch-py` are you running?
