### ISSUE TITLE
Error displayed when using indices.exists_alias(): "Undecodable raw error response from server: Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by ersiko** [elastic/elasticsearch-py#439]
Hi

When running the function "indices.exists_alias" against a non-existent index, I get the error:
"Undecodable raw error response from server: Expecting value: line 1 column 1 (char 0)"

If the alias exists, that error doesn't appear. Although the error appears, the return code is correct in both cases:

```
>>> es.indices.exists_alias("picsdaily-20160823","picsdaily-last-1-days")
True
>>> es.indices.exists_alias("picsdaily-20160821","picsdaily-last-1-days")
Undecodable raw error response from server: Expecting value: line 1 column 1 (char 0)
False
```

I thought it was worth mentioning it.

I'm using elasticsearch-py version 2.4 and elasticsearch version 2.3.4.

Thanks!

**Comment by HonzaKral** [comment]
Thanks!

this is fixed via 17131a9a4372e23808a069e7f561183993dfcdbe
