### ISSUE TITLE
Elasticsearch.ndices.exists() emits error message

### ISSUE THREAD

**Issue by atsuoishimoto** [elastic/elasticsearch-py#441]
Following code emits error message to the console if 'test' index does not exists.

``` python
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.indices.exists(index='test')
```

The error message is 

```
Undecodable raw error response from server: Expecting value: line 1 column 1 (char 0)
```

If the index doesn't exist, Elasticsearch returns 404 error with no body. But current implementation tries to parse empty body string as JSON. 

environment: 

Elasticsearch ver 2.3.5
elasticsearch-py ver 2.4.0

**Comment by HonzaKral** [comment]
Thanks for the report!

This has been fixed via https://github.com/elastic/elasticsearch-py/issues/439 and is awaiting a release.
