### ISSUE TITLE
Query output contains 5x results when size is x

### ISSUE THREAD

**Issue by scottydelta** [elastic/elasticsearch-py#442]
I am using this code to fetch a field and I get 5x the results of the size. is it a bug or am I going somewhere wrong?

    In [105]: es = Elasticsearch(host = 'tweetmine.ngrok.io' , port = 80)

    In [106]: search=es.search('project_%s' % (project_id,), search_type="scan", scroll='5m',
        body = { "_source": [ "coordinates" ], "query": { "filtered": { "query": { "exists": 
        { "field": "coordinates" } }, "filter": {} } } }, size=1)

    In [107]: scroll=es.scroll( scroll_id=search['_scroll_id'], scroll='1m', )

    In [108]: len(scroll['hits']['hits'])
    Out[108]: 5

**Comment by HonzaKral** [comment]
When using `scroll` the size is per shard. Since an index has 5 shards by default this is expected behavior.

btw if you want to use scroll you might want to check out the `scan` helper - http://elasticsearch-py.readthedocs.io/en/master/helpers.html#scan - which makes it easier.

**Comment by scottydelta** [comment]
is it possible to provide size in a way that it only fetches one record?

**Comment by HonzaKral** [comment]
Yes, but not with `scroll` and `scan` search type. You should only use `scan`/`scroll` if you want to get *all* the data so specifying a size=1 makes no sense there. If you remove those parameters you should correctly receive just one hit back via the `search` call.
