### ISSUE TITLE
Add Shield API support

### ISSUE THREAD

**Issue by nick-allen** [elastic/elasticsearch-py#443]
Shield API endpoints should be handled via methods provided by a `adapter.shield` client like the `adapter.indices` or `adapter.cluster` clients.

**Comment by HonzaKral** [comment]
Shield API, as well as other `x-pack` related APIs will be part of https://github.com/elastic/elasticsearch-x-pack-py package to be released soon.

Hope this helps

**Comment by nick-allen** [comment]
Perfect, still not in the habit of searching for xpack.
