### ISSUE TITLE
Use of http digest

### ISSUE THREAD

**Issue by Orybon** [elastic/elasticsearch-py#448]
Is it possible to use http digest auth while configuring the elasticsearch client ? 

http_auth seems to wait for a string  :

```
 File "/[snip]/lib/python2.6/site-packages/urllib3/util/request.py", line 62, in make_headers
    b64encode(b(basic_auth)).decode('utf-8')
  File "/usr/lib64/python2.6/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: b2a_base64() argument 1 must be string or read-only buffer, not HTTPDigestAuth
```

**Comment by HonzaKral** [comment]
where does the class `HTTPDigestAuth` come from? If it is the one from `requests` that you need to use `RequestsHttpConnection`: `Elasticsearch(..., http_auth=HTTPDigestAuth(...), connection_class=RequestsHttpConnection)`

Hope this helps

**Comment by Orybon** [comment]
Thank you for your help.

Indeed i need to replace my connection_class to make it works.
