### ISSUE TITLE
Disable logging error on indices.exists()

### ISSUE THREAD

**Issue by dzen** [elastic/elasticsearch-py#449]
Hello,

It seems it's not possible to disable logging on the `exist` method on indices : 
https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/indices.py#L205

Is it possible to add the argument ? I should probably create a PR for that.

**Comment by HonzaKral** [comment]
This has been fixed for #396 and shouldn't happen. What version of `elasticsearch-py` are you using?

Thanks!
