### ISSUE TITLE
ConnectionError caused by urllib3 upgrade to 1.17

### ISSUE THREAD

**Issue by cricketts** [elastic/elasticsearch-py#450]
Hello. Our `elasticsearch` dependency automatically pulled in the latest version of `urllib3` which is 1.17 (released 9/6/16). This broke our call to [Elasticsearch.search](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.search) with this stack trace:

```
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 105, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(Codepoint U+002A at position 1 of u'*' not allowed) caused by: InvalidCodepoint(Codepoint U+002A at position 1 of u'*' not allowed)
```

The URL being connected to is the following (slightly modified for anonymity):

```
https://[REDACTED].us-east-1.aws.found.io:[REDACTED]/domains/domain/_search?search_type=scan&filter_path=_scroll_id%2Chits.hits._id%2Chits.hits._source.url%2Chits.hits._source.first_seen&scroll=1m&size=10000
```

My guess is that the certificate name is `*.us-east-1.aws.found.io` which would explain why there is an asterisk in the first position. The comment in [pyopenssl.py](https://github.com/shazow/urllib3/blob/master/urllib3/contrib/pyopenssl.py) explains why the DNS name gets encoded to idna in the first place:

```
Sadly the DNS names need to be idna encoded and then, on Python 3, UTF-8
decoded. This is pretty frustrating, but that's what the standard library
does with certificates, and so we need to attempt to do the same.
```

I've tracked down the [commit in urllib3](https://github.com/shazow/urllib3/commit/c5f393ae32b0caced3814a0011cd5f4bea3f63e9#diff-4d3aebf8115beaf5ef5f84a36e168b9c) which introduced this issue for us. Our mitigation was to add a direct dependency on `urllib3=1.16` which fixed the issue for the time being.

Is this a specific issue with Elasticsearch? I haven't been able to fully understand why this issue is happening, but I hoped opening an issue would help anyone else encountering this symptom. Is there a specific reason why there is no `urllib3` max version in your [setup.py](https://github.com/elastic/elasticsearch-py/blob/2.x/setup.py#L15)?

Thanks!

**Comment by HonzaKral** [comment]
Hi, thanks for raising the issue!

Could you please investigate where is the `InvalidCodepoint` exception coming from? (accessing `.info` on the `ConnectionError` should give you the exception object)

It looks like this issue has been fixed in `cryptography` which is used in the `pyopenssl.py` file you refer to (https://github.com/pyca/cryptography/issues/2054) so I am curious to know what's going on there.

Thank you!

**Comment by cricketts** [comment]
Thanks for pointing out that commit in `cryptography`. I am having a difficult time reproducing the issue, so I am thinking that it was a certain combination of dependencies that caused this issue to manifest itself. Going forward I will be logging my dependencies and their version upon deployment. If it comes up again I will update this issue. Thanks!

**Comment by HonzaKral** [comment]
I will close this issue for now, please reopen when it manifests again. Thanks!
