### ISSUE TITLE
elasticsearch.exceptions.NotFoundError: TransportError

### ISSUE THREAD

**Issue by ch3njust1n** [elastic/elasticsearch-py#452]
Not sure what's causing this. It's fine with the first 10,000 documents, but throws the below error after.

Here's line 693
for i, doc in enumerate(scanner):
        print doc

Traceback (most recent call last):
  File "retriever-th.py", line 693, in <module>
    main()
  File "retriever-th.py", line 629, in main
    for i, doc in enumerate(scanner):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 290, in scan
    resp = client.scroll(scroll_id, scroll=scroll)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 667, in scroll
    params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'{"_scroll_id":"c2NhbjswOzE7dG90YWxfaGl0czo1OTI1NzQ5Ow==","took":2,"timed_out":false,"_shards":{"total":5,"successful":0,"failed":5,"failures":[{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [10724090]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [5642851]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [10724089]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [4493644]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [4710075]"}}]},"hits":{"total":5925749,"max_score":0.0,"hits":[]}}')

**Comment by HonzaKral** [comment]
Could you please share the rest of the code, especially how you create the `scanner`. Also is this something you can replicate?

thanks!

**Comment by ch3njust1n** [comment]
I'm trying to upload a ton of documents. Could it be a default timeout issue?

parser      = argparse.ArgumentParser()
parser.add_argument('--dEs', type=str, default="esDB", help="Elasticsearch for d_*")
cmdLineOptions = parser.parse_args()
es = Elasticsearch( [ cmdLineOptions.dEs ])
scanner = helpers.scan(es, raise_on_error=False, index='my_repo', doc_type='change', query={"query" : {"wildcard" : {"repository" : "*project*"}}})
for i, doc in enumerate(scanner):
       #do stuff here
       if i % 1000==0:
              es.index(index=''myIndex", doc_type="change", body=doc)

**Comment by HonzaKral** [comment]
This could be because of the timeout, can you make the scroll timeout higher by passing `scroll=15m` to the `scan` helper?

Also am I correct in assuming you are only interested in indexing one in every thousand documents? It would be easier to use the `bulk` helper to batch those together for more performance - indexing documents one by one using `es.index` is very inefficient compared to `bulk`.

**Comment by ch3njust1n** [comment]
Oh I was about to close this issue. 
Yeah, it was b/c the default scroll value. I set it `scroll=60m`.
Also thanks, I wasn't aware of `bulk`.
Thanks!
