### ISSUE TITLE
Wrong documentation of timeout parameter.

### ISSUE THREAD

**Issue by kdubezerra** [elastic/elasticsearch-py#457]
According to the documentation, the `Elasticsearch.index()` method accepts a (string) parameter `timeout` that defines the maximum time to wait for an operation, consisting of a string like `Tu`, where`T` is the time and `u` is the unit (e.g., "30s"). However, when I set this parameter to "30s", I still get:

> ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'172.17.0.40', port=9200): Read timed out. (read timeout=10))

The timeout was still the default value (10 seconds)...

Looking into the code, it seems that `timeout` is just ignored, and that `request_timeout` is used instead, and that it should have a numeric value (not string). Passing `request_timeout` to the `Elasticsearch.index()` method works already, so I think it's just a matter of documentation.

**Comment by HonzaKral** [comment]
Dealing with the timeouts can be a little confusing since some APIs accept an internal parameter `timeout` that has nothing to do with the connection timeout.

This is described in the documentation: http://elasticsearch-py.readthedocs.io/en/master/api.html#timeout

**Comment by HonzaKral** [comment]
Closing this issue since the `timeout` behavior is documented properly. If there is anything we can do to make it clearer please let me know. Thank you!
