### ISSUE TITLE
Argument name wrong in 1.9.0 doc

### ISSUE THREAD

**Issue by znorris** [elastic/elasticsearch-py#459]
Regarding the documentation found here:
http://elasticsearch-py.readthedocs.io/en/1.9.0/api.html#elasticsearch.Elasticsearch.search

The `.search()` method argument, `from`, should be `from_`. As seen here: https://github.com/elastic/elasticsearch-py/blob/1.9.0/elasticsearch/client/__init__.py#L449

**Comment by HonzaKral** [comment]
Thanks for the report, this has been fixed in later versions and the doc also contains a warning at the top about the naming.Due to these factors I cannot justify doing another `1.9.x` release to just fix a typo.
