### ISSUE TITLE
index.exists: Undecodable raw error response from server: No JSON object could be decoded

### ISSUE THREAD

**Issue by esseti** [elastic/elasticsearch-py#461]
Hi all,
in my code i've a call to this method `es.indices.exists(schema_id)` and in the log i see this printed out:
`WARNING [elasticsearch._raise_error:111] Undecodable raw error response from server: No JSON object could be decoded`

the method works (or seems so), but I was wondering what's that error, and if it's problematic.

**Comment by HonzaKral** [comment]
Hi, thanks for the report. This is just a minor issue where an error is logged needlessly. It doesn't affect anything and has been removed in https://github.com/elastic/elasticsearch-py/commit/515197a903a99e204e45ab812e35895f0f94eaa1
