### ISSUE TITLE
Garbage collection on actions in bulk helpers.

### ISSUE THREAD

**Issue by rangolisharan** [elastic/elasticsearch-py#463]
Newbie (to python and ES) here. I am trying to index millions of documents using parallel_bulk / or streaming_bulk. My implemenation is as follows:

```
def actions(self, document_ids):
   for doc_id in document_ids:
      action = <create_action> #This is an external API call
      yield action

def index(self):
    for success, info in helpers.parallel_bulk(self.es_client, self.actions(),
      thread_count=config['worker']['bulk_pool_size'], chunk_size=5,
      request_timeout=config['worker']['es_request_timeout']):
      if not success:
        _log.error('Indexing failed:', info)
      else:
        _log.info(info)
```

Problem is that my documents are fairly large. The indexer instance I'm running on is running out of memory -- probably because actions are not garbage collected until actions() returns and indexing is complete. Should I be circumventing using expand_action_callback? Or am I on the wrong track here?

**Comment by HonzaKral** [comment]
Hi, garbage collection shouldn't be an issue for you - actions is a generator which means it never materializes all the documents in memory and the objects should be collected immediately after execution.

What strikes me as weird is the `chunk_size=5` that is way too low even for larger documents.. Have you experimented with different sizes?

What is the size of your document and what pool size are you using?

Thanks!

**Comment by rangolisharan-minted** [comment]
Thanks for responding quickly. I'll investigate other causes over the next couple of days and post back what I find, here. Pool size is set to 2 (haven't played with that yet). Documents are in the range of 10K to 10MB (two different doc types). The 10 MB document generates a few hundred other documents of about 10K each. "actions()" yields mixed doc types.

**Comment by HonzaKral** [comment]
In this case it would be better to rely on the helper's ability to chunk requests based on size, as opposed to document count, simply state how big you want your batch by specifying `max_chunk_bytes` in your call while leaving the `chunk_size` larger.

**Comment by HonzaKral** [comment]
Closing this issue since there is no new information. Please feel free to reopen if the issue persists with additional details. Thank you!
