### ISSUE TITLE
timeout on parallel_bulk ?

### ISSUE THREAD

**Issue by jpabbuehl** [elastic/elasticsearch-py#464]
Hi

I am trying to index a large set of documents with parallel_bulk but I am facing an ConnectionTimeout issue. Looking at [python documentation](https://elasticsearch-py.readthedocs.io/en/master/helpers.html#elasticsearch.helpers.bulk), it can't find a way to manually set timeout request (default 10).
 
Could you provide some help ?
I tried to reduce chunk size but it doesn't solve the issue...
thank you

**Comment by HonzaKral** [comment]
Hi, you can just pass in `request_timeout` as per https://elasticsearch-py.readthedocs.io/en/master/api.html#timeout - all `kwargs` passed to the helper that aren't specific for that helper will be passed on to the underlying API.

Hope this helps,
Honza

**Comment by jpabbuehl** [comment]
Amazing. I was using timeout by mistake. Thx

**Comment by HonzaKral** [comment]
happy to help
