### ISSUE TITLE
Get individual scores instead of sum score after multi-word query

### ISSUE THREAD

**Issue by jpabbuehl** [elastic/elasticsearch-py#465]
Hi

I would like to know if there is a way to find the score of each word in a multiword query per document instead of obtaining the overall combined score.
The only option I am thinking of is iterating through single word query and then merging results afterwards.
Thank you very much

**Comment by HonzaKral** [comment]
Hi, unfortunately this is not possible directly. You can use the explain API to get partial scores, but it is very expensive and not recommended in production - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-explain.html

This is also an elasticsearch question that has nothing specific for the python client in it so I will close this ticket. If you wish to continue the discussion I would recommend starting one in the official elastic forum: http://discuss.elastic.co/

Thanks!
