### ISSUE TITLE
helpers.scan fail with query containing sort on nested type

### ISSUE THREAD

**Issue by acabrol** [elastic/elasticsearch-py#466]
A query containing parameters related to nested objects works properly with ElasticSearch.search but fail with helpers.scan.

**ES Schema:**

> "doc": {
>        "_parent": {
>          "type": "source"
>        },
>        "_timestamp": {
>          "enabled": true
>        },
>        "_all": {
>          "enabled": true
>        },
>        "properties": {
>         "topics":{
>          "type":   "nested",
>          "properties":{
>           "label":{"type":"string","index":"not_analyzed"},
>           "score":{"type":"float"}
>          }
>         }
>        }
>      }

**Python code:**

```
from elasticsearch import Elasticsearch, helpers
es=Elasticsearch()
gte="now-7d"
lte="now"
query={ "sort" : [ { "topics.score" : { "order" : "dsc", "nested_path" : "topics" } }, "_score" ], "query":{ "bool" : { "must":[ { "range" : { "updated" : { "gte" : gte, "lt" :  lte } }}] } } }

#query success and return results
print es.search(index="myindex",body=query)

# query fail with ES Error: nested: QueryParsingException[[nested] failed to find nested object under path [topics]];
results_gen=helpers.scan(es,query=criteria)
for result in results_gen:
 print result
```

**Comment by HonzaKral** [comment]
I am having trouble replicating this, when I try it everything works for me, could you specify the versions of elasticsearch and elasticsearch-py you are using? Thank yuo!

Also in your example you are running the `search` api with `query` yet then you use a variable called `criteria` in the scan helper, are those the same?

**Comment by acabrol** [comment]
**My elasticsearch-py version:**
> pip freeze|grep elastic
> The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> elasticsearch==2.4.0

**My elasticsearch version:**
> {
>   "name" : "Redneck",
>   "cluster_name" : "elasticsearch",
>   "version" : {
>     "number" : "2.3.4",
>     "build_hash" : "e455fd0c13dceca8dbbdbb1665d068ae55dabe3f",
>     "build_timestamp" : "2016-06-30T11:24:31Z",
>     "build_snapshot" : false,
>     "lucene_version" : "5.5.0"
>   },
>   "tagline" : "You Know, for Search"
> }

Sorry for the criteria keyword, i tried to extract my problem, hereunder my raw code:
```
         if query_size<limit or ("topics.score" in json.dumps(criteria)):
             self.logger.debug("ES query search:"+json.dumps(criteria))
             results=self.es.search(index=self.index,body=criteria,request_timeout=self.timeout)
         else:
             self.logger.debug("ES query: helpers.scan search:"+json.dumps(criteria))
             results_gen=helpers.scan(self.es,query=criteria,scroll=self.config['ES_SEARCH_CACHING_DELAY'],preserve_order=True,request_timeout=self.timeout)
             for result in results_gen:
                 results['hits']['hits'].append(result)
```

**Comment by HonzaKral** [comment]
the `scan` call is missing `index=self.index` parameter. My guess would be that you have other indices that don't contain the nested `topics` field which makes the sort fail. Could you please confirm? Thank you

**Comment by HonzaKral** [comment]
Since there is no new information I assume that it was indeed the missing `index` parameter. If not please reopen the ticket with additional information, thank you!
