### ISSUE TITLE
Specify CA directory

### ISSUE THREAD

**Issue by zmathe** [elastic/elasticsearch-py#472]
I would like to specify a certain CA directory to Elasticsearch:

``` python
cl = Elasticsearch('https:', verify_certs=True,ca_cert_dir='/opt/xxx/yyyy/security/certificates/')
```

I can only specify ca_certs but this is a file. How I can specify a directory?

I proposed a solution: #471 for solving this issue. If there is another way, please let me know.
Thanks,
Zoltan

**Comment by zmathe** [comment]
@HonzaKral I do not know if you are the right person. Could you please have a look this issue? It is very urgent for us. Currently, I have to create a file using the directory content and pass to ca_certs = /opt/xxx/yyyy/certs.pem)
It will be very convenient if I can specify a directory. Thanks!

**Comment by HonzaKral** [comment]
I will definitely have a look soon, I am sorry it's taking so long.

In the mean time I would recommend you create your own connection class outside of `elasticsearch-py` in your code and then pass it into the `Elasticsearch` class as `connection_class` parameter. Absence of this functionality should not hold you back.

**Comment by fxdgear** [comment]
@HonzaKral Is this something in the "road map" for `-py`? Or should we close it and recommend people to create their own connection classes?

**Comment by HonzaKral** [comment]
I think the plan is to support people passing their own `ssl_context` for
the more exotic use cases..

**Comment by fxdgear** [comment]
@zmathe Please try the master branch now. i just merged the SSLContext branch. 

If that suites your needs can you please close this ticket? Thanks

**Comment by zmathe** [comment]
@fxdgear I will test it on Monday and report back to you.

**Comment by zmathe** [comment]
@fxdgear I tested and it work. Thanks again!

**Comment by fxdgear** [comment]
Happy to hear it!
