### ISSUE TITLE
Creating document with automatic ID generation doesn't work in 5.0

### ISSUE THREAD

**Issue by piquadrat** [elastic/elasticsearch-py#474]
It seems to me that a2cd22dbf6 removed the possibility to create a document using [automatic ID generation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#_automatic_id_generation). Is that an oversight?

If yes, I'll be happy to provide a PR that restores this functionality, by changing `id` back to a keyword argument, and using `POST` if it is `None`.

**Comment by HonzaKral** [comment]
If you are not providing an id there is no benefit in using the `create` API and you should instead be using the `index` API which still provides the functionality.

The only benefit of the `create` API is if you have specified an ID the operation will fail if a document with that ID already exists. This is not applicable without an ID value so the parameter has been switched to required.

Hope this helps

**Comment by piquadrat** [comment]
Ah, that makes sense! Sorry for the noise!
