### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by daveio** [elastic/elasticsearch-py#483]
CI is failing on all recent builds because https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.elasticsearch.distribution.zip&a=elasticsearch&e=zip&v=5.0.0-SNAPSHOT does not exist.

This should probably be updated to 5.1.0 - https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.elasticsearch.distribution.zip&a=elasticsearch&e=zip&v=5.1.0-SNAPSHOT

**Comment by ShaneHarvey** [comment]
#478 also fixes this issue.

**Comment by daveio** [comment]
@ShaneHarvey's PR is much cleaner than mine. Closing mine.

**Comment by GlenRSmith** [comment]
Merged and passing. Thanks again @daveio and @ShaneHarvey
