### ISSUE TITLE
Issue with Infinite Float

### ISSUE THREAD

**Issue by AndreSchlegel** [elastic/elasticsearch-py#486]
I've tried do index a dictionary which contains an infinite float. In debug-log I could see the string Infinity without quotes.

Here you can test:
`>>>elasticsearch.Elasticsearch().index(index="test", doc_type="new Type", body={"floatValue":float('inf')})

(...)

elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse')`

Here is a snippet from my real data log which shows a part of the serialized json body:
`(...)   "Model": {"$": Infinity}, "MPN": {"$": Infinity},   (...)`

**Comment by GlenRSmith** [comment]
@AndreSchlegel 
Regarding `inf` and `nan`, they are not valid values in JSON. Further, Elasticsearch will not accept these as numeric values. You'll have to filter these values in some way that prevents attempting to index such values.
