### ISSUE TITLE
RequestsHttpConnection attempts to log undefined values

### ISSUE THREAD

**Issue by ekelly30** [elastic/elasticsearch-py#487]
The perform_request method tries to use the response of session.request when an exception has been raised:

```python
        try:
            response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
        except requests.exceptions.SSLError as e:
            self.log_request_fail(method, url, response.request.path_url, body, time.time() - start, exception=e)
```

`response` will be undefined if an exception is thrown so the logging fails. 

I have forked and created a branch with a suggested fix and test. 
https://github.com/ekelly30/elasticsearch-py/tree/requesthttpconnection-exception-logging

**Comment by HonzaKral** [comment]
fixed via 8e69b98
