### ISSUE TITLE
thread_count

### ISSUE THREAD

**Issue by ttopholm** [elastic/elasticsearch-py#490]
Hi,

We are using the parallel_bulk, and I was wondering how the thread_count is used. So if I pass 10.000 actions into it, and set chunk_size=1000 and thread_count to 24, will it run 24 threads with 1000 actions each, or will it split the 1000 / 24 and run that?

**Comment by HonzaKral** [comment]
There is one thread (the main thread is used for this) that parses the input and splits it into chunks that are then handed over to a thread pool of size `thread_count` that are just calling the `bulk` API.

Implementation can be seen at https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L228-L231 which is just using `pool.imap` from python's `multiprocessing.dummy`.

**Comment by KeithTt** [comment]
Can `cat.thread_pool` API output the `pool_size`?

I followed this page: https://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=thread_pool#elasticsearch.client.CatClient.thread_pool

> By default the active, queue and rejected statistics are returned for all thread pools.

Also, I refer to the official guide here: https://www.elastic.co/guide/en/elasticsearch/reference/7.11/cat-thread-pool.html

I can see the `pool_size, psz` column in the parameter `h`, but it can not be recognized when use it in this SDK.
