### ISSUE TITLE
Validate API with POST is not available

### ISSUE THREAD

**Issue by mats116** [elastic/elasticsearch-py#491]
We can use `validate_query` with GET only.
So the request body is large, `validate_query` can not work...

https://github.com/elastic/elasticsearch-py/blob/2.4.0/elasticsearch/client/indices.py#L748-L785

```python
    def validate_query(self, index=None, doc_type=None, body=None, params=None):
        return self.transport.perform_request('GET', _make_path(index,
            doc_type, '_validate', 'query'), params=params, body=body)
```

**Comment by HonzaKral** [comment]
If your environment doesn't support `GET` requests with body you can specify the `send_get_body_as` parameter to use `POST` instead - http://elasticsearch-py.readthedocs.io/en/master/#environment-considerations
