### ISSUE TITLE
Install in Python 2.6 env has unittest2 package requirement

### ISSUE THREAD

**Issue by pjediny** [elastic/elasticsearch-py#499]
This is probably meant to be only a test requirement. 
Patch for this issue is available in PR #498 with some other tweaks to setup.py.

**Comment by HonzaKral** [comment]
No, that is not the case because we also ship with test helpers that rely on unittest2 - https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/test.py#L5
