### ISSUE TITLE
Bulk helper method raises error

### ISSUE THREAD

**Issue by mohmad-null** [elastic/elasticsearch-py#502]
ES 5.0.0, and elasticsearch Python 5.0.1 in Python 3.5.x

The docs for the bulk help (https://elasticsearch-py.readthedocs.io/en/master/helpers.html) say:

> " It returns a tuple with summary information - number of successfully executed actions and either list of errors or number of errors if stats_only is set to True."

However, any time an error is triggered, it only seems to Raise a **BulkIndexError** exception. It doesn't matter if `stats_only` is set to **True** or **False**.

I'm triggering it with an invalid bbox akin to:
```
{
    "l_bbox" : {
        "type" : "envelope",
        "coordinates" : [ [-180.0, -90.0], [180.0, 500] ]
    }
}
```

**Comment by HonzaKral** [comment]
By default any errors will raise an exception to make `bulk` safe. If you want to ignore exceptions and just report them, set `raise_on_error` parameter to `False`.

Hope this helps.

**Comment by mohmad-null** [comment]
@HonzaKral - That's fine, but that's not what the documentation says. If that's the desired behaviour then the documentation is wrong. It states:

>  and either list of errors or number of errors if stats_only is set to True

It's explicitly stating that what should be received is something different from what actually happens.

**Comment by HonzaKral** [comment]
I will update the documentation to be more explicit, thank you

**Comment by mohmad-null** [comment]
@HonzaKral  - Thanks!
