### ISSUE TITLE
geo-shape fails with exponent float

### ISSUE THREAD

**Issue by mohmad-null** [elastic/elasticsearch-py#504]
If I create a geo-shape with a structure like this:
```
{
				'type': 'envelope',
				'coordinates': [[float(lower_left[0]), float(upper_right[1])],
								[float(upper_right[0]), float(lower_left[1])]]
			}
```
If one of the coordinates is:
_2.09306654939392e+255_

I get an elasticsearch error:

> Y values [-90.0 to 2.09306654939392E255] not in boundary Rect(minX=-180.0,maxX=180.0,minY=-90.0,maxY=90.0)

 Shouldn't the Python API convert the perfectly valid float into a form that ElasticSearch can accept? (It doesn't seem to accept exponents).

**Comment by HonzaKral** [comment]
The problem is not with the format, it's the value of the number - it is a very large number that doesn't represent proper coordinates since those can only be from `-180` to `180`.

**Comment by mohmad-null** [comment]
@HonzaKral 
Oh yes. My bad, I mis-read it. I thought the exponent was for decimal places (so a ridiculously small number), but as you say, it's not.
