### ISSUE TITLE
bulk children documents

### ISSUE THREAD

**Issue by christinazavou** [elastic/elasticsearch-py#505]
Hi, I'm having problems using the API to index children documents at once.

If I index children documents for one parent document using Elasticsearch().index() I have no problem.
However, if I try to index all my parents documents' children ( either with .index(), or using  .bulk() or parallel_bulk() with or without iterator ) I have a problem. Precisely, some of the parent documents get children documents, but most parent documents don't. And I got no Exceptions raised.

I thought maybe ES need some refresh or time.sleep, but from what I 've tried, nothing helped.

Could you please give me an example code to test or any advice ?
Thanks in advance

**Comment by HonzaKral** [comment]
https://github.com/elastic/elasticsearch-py/blob/master/example/load.py#L113 contains an example of loading child documents via bulk.

Hope this helps

**Comment by christinazavou** [comment]
Thanks for the quick response!
However, it's still has the same weird behavior!

here is the code i run based on your example:

# -*- coding: utf-8 -*-
from __future__ import print_function

import pandas as pd

from elasticsearch import Elasticsearch
from elasticsearch.exceptions import TransportError
from elasticsearch.helpers import streaming_bulk


def create_git_index(client, index):
    create_index_body = {
        "settings": {
            "number_of_shards": 5,
            "number_of_replicas": 1,
        },
        "mappings": {
            "patient": {},
            "report": {
                "_parent": {
                    "type": "patient"
                },
                'properties': {
                    'A': {'type': 'text'},
                    'B': {'type': 'text'},
                    'C': {'type': 'text'},
                    'D': {'type': 'text'},
                    'E': {'type': 'text'},
                    'F': {'type': 'text'},
                    'G': {'type': 'text'},
                    'H': {'type': 'text'}
                }
            }
        }
    }
    # create empty index
    try:
        client.indices.create(
            index=index,
            body=create_index_body,
        )
    except TransportError as e:
        # ignore already existing index
        if e.error == 'index_already_exists_exception':
            pass
        else:
            raise


def parse_reports(data, parent):
    """Go through the data and generate a document per row containing all the metadata."""
    for i in range(len(data)):
        source_dict = data[i]
        yield {
            '_id': i,
            '_parent': parent,
            '_source': source_dict
        }


def load_patient(client, patientid, path=None, index='tmp_index'):
    """
    Parse a patient repository with all it's data and load it into elasticsearch
    using `client`. If the index doesn't exist it will be created.
    """
    create_git_index(client, index)

    reports = []
    """---------------------------------------------load csv file----------------------------------------------------"""
    cols = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    cols_types = {'A': str, 'B': str, 'C': str, 'D': str, 'E': str, 'F': str, 'G': str, 'H': str}
    df = pd.read_csv(path, usecols=cols, dtype=cols_types).fillna('')

    for j, row in df.iterrows():  # each row as a child document
        new_dict = {}
        for k in cols:
            new_dict[k] = str(row[k])
        reports.append(new_dict)

    # create the parent document in case it doesn't exist
    client.create(
        index=index,
        doc_type='patient',
        id=patientid,
        body={},
        ignore=409  # 409 - conflict - would be returned if the document is already there
    )

    # we let the streaming bulk continuously process the reports as they come in - since the `parse_reports`
    # function is a generator this will avoid loading all the commits into memory
    for ok, result in streaming_bulk(
            client,
            parse_reports(reports, patientid),
            index=index,
            doc_type='report',
            chunk_size=50  # keep the batch sizes small for appearances only
    ):
        action, result = result.popitem()
        doc_id = '/%s/reports/%s' % (index, result['_id'])
        # process the information from ES whether the document has been successfully indexed
        if not ok:
            print('Failed to %s document %s: %r' % (action, doc_id, result))
        else:
            print(doc_id)


if __name__ == '__main__':
    # instantiate es client, connects to localhost:9200 by default
    es = Elasticsearch()

    # we load the repo and all commits
    load_patient(es, 1, 'example_data.csv')
    load_patient(es, 2, 'example_data.csv')
    load_patient(es, 3, 'example_data.csv')
    load_patient(es, 4, 'example_data.csv')
    load_patient(es, 5, 'example_data.csv')
    load_patient(es, 6, 'example_data.csv')
    load_patient(es, 7, 'example_data.csv')
    load_patient(es, 8, 'example_data.csv')


and in the file example_data.csv I have sample values. precisely :

A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R
448094,FL,CLAY COUNTY,1322376.3,1322376.3,1322376.3,1322376.3,1322376.3,1438163.57,0,0,0,0,30.063936,-81.707664,Residential,Masonry,3
206893,FL,CLAY COUNTY,190724.4,190724.4,190724.4,190724.4,190724.4,192476.78,0,0,0,0,30.089579,-81.700455,Residential,Wood,1
333743,FL,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3
172534,FL,CLAY COUNTY,0,254281.5,0,254281.5,254281.5,246144.49,0,0,0,0,30.060614,-81.702675,Residential,Wood,1
119736,FL,CLAY COUNTY,498960,498960,498960,498960,498960,792148.9,0,9979.2,0,0,30.102261,-81.711777,Residential,Masonry,1
448094,FL,CLAY COUNTY,1322376.3,1322376.3,1322376.3,1322376.3,1322376.3,1438163.57,0,0,0,0,30.063936,-81.707664,Residential,Masonry,3
206893,FL,CLAY COUNTY,190724.4,190724.4,190724.4,190724.4,190724.4,192476.78,0,0,0,0,30.089579,-81.700455,Residential,Wood,1
333743,FL,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3
172534,FL,CLAY COUNTY,0,254281.5,0,254281.5,254281.5,246144.49,0,0,0,0,30.060614,-81.702675,Residential,Wood,1
119736,FL,CLAY COUNTY,498960,498960,498960,498960,498960,792148.9,0,9979.2,0,0,30.102261,-81.711777,Residential,Masonry,1
448094,FL,CLAY COUNTY,1322376.3,1322376.3,1322376.3,1322376.3,1322376.3,1438163.57,0,0,0,0,30.063936,-81.707664,Residential,Masonry,3
206893,FL,CLAY COUNTY,190724.4,190724.4,190724.4,190724.4,190724.4,192476.78,0,0,0,0,30.089579,-81.700455,Residential,Wood,1
333743,FL,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3
172534,FL,CLAY COUNTY,0,254281.5,0,254281.5,254281.5,246144.49,0,0,0,0,30.060614,-81.702675,Residential,Wood,1

So, when I run the above code, some "patient" i.e. parent documents get their "reports" i.e. children documents, whilst other don't. And no errors are raised.

Sorry for copying the whole code here, but if you could check what the problem in this case is would be great. Thanks

**Comment by HonzaKral** [comment]
You seem to be using numbers for the `_id` of the children. Since `_id`s have to be unique you are overwriting the documents. Consider using something like `"%s-%s" (parent, i)` for `_id` instead.
