### ISSUE TITLE
python, namedtuples, range aggregations and "from"

### ISSUE THREAD

**Issue by midget2000x** [elastic/elasticsearch-py#507]
This isn't really an issue, more of just a question.  I'm using some namedtuples to contain keys and values that will get turned into query DSL.  The problem I'm running into is storing range aggregations in a namedtuples due to the word "from".  When I try to assign I get:

`ValueError: Type names and field names cannot be a keyword: 'from'`

The obvious answer is to put an underscore after it to avoid the conflict, but then I need to manipulate the query just before sending to elasticsearch to s/r any instance of "from_" to "from".  Not a gigantic issue but I'm just wondering if there's an easier way.  

I am wondering if maybe elasticsearch has a way to specify an "alias" for keys in situations like this? Or maybe even a built-in way I don't know about?
 
I already tried just using it with the underscore and it doesn't work, also tried using 'gte' and 'lte' instead of 'to' or 'from', no luck there.

Any ideas appreciated, thanks!  Here's a snippet that illustrates the issue (outputs the error above):
```
from collections import namedtuple

def convert(dictionary):
    return namedtuple('GenericDict', dictionary.keys())(**dictionary)

ranges = [
    {
        'to': 20
    },
    {
        'from': 20,
        'to': 50
    },
    {
        'from': 50,
        'to': 100
    },
    {
        'from': 100,
        'to': 200
    },
    {
        'from': 200
    }
]

for i in range(len(ranges)):
    ranges[i] = convert(ranges[i])
```

**Comment by HonzaKral** [comment]
Unfortunately for keys like these you need to either do your post-processing or not rely on structures like namedtuple that require the keys to be valid python identifiers.

For my take on the problem you can have a look at https://github.com/elastic/elasticsearch-dsl-py which, in some places, allow you to use `from_` - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L182

Hope this helps

**Comment by midget2000x** [comment]
Gotcha - thank you!!
