### ISSUE TITLE
Option to suppress logging of ES connection HTTP message bodies

### ISSUE THREAD

**Issue by macdjord** [elastic/elasticsearch-py#509]
Currently, elasticsearch/connection/base.py logs at DEBUG level the body of every request sent to Elasticsearch and every response received back (lines 82, 83, 102, & 107). This is nice in development, but in production, it means that every piece of data that my script sends to or receives from ES - potentially _gigabytes_ of data - is recorded in full in the logs. And, since the entire codebase uses the same logger, I can't turn it off without disabling all DEBUG-level logging for the entire module.

My current workaround is a bit of a hack, creating a new logger, 'elasticsearch.connection', setting it to INFO level, and then manually assigning 'elasticsearch.connection.base.logger' to point to that instead of the orignal.

I propose that something similar be done properly: change line 9 to get a different logger, 'elasticsearch.whatever', in the first place, and document its name, so that users can change the logging level there separately from the rest of the module.

**Comment by HonzaKral** [comment]
The proper solution is not to set `DEBUG` level logging in production. It is really not meant for production. The `DEBUG` level is also not used anywhere else in the library so just setting the level to `WARNING` for the `elasticsearch` logger should be fine in production.

Hope this helps.

**Comment by macdjord** [comment]
@HonzaKral Our policy is to deploy to production with DEBUG level logging, then turn it down to INFO after a couple weeks of stable operation.

**Comment by HonzaKral** [comment]
Then you will be violating your policy either way - by setting `INFO` log level for `elasticsearch.connection` or for `elasticsearch`. Since there is no other `DEBUG`-level logging anywhere else in the module setting `elasticsearch` logger to `INFO` will result exactly in the behavior you are asking for.
