### ISSUE TITLE
Always exact match

### ISSUE THREAD

**Issue by chocolate9624** [elastic/elasticsearch-py#521]
import  elasticsearch 
es = elasticsearch.Elasticsearch()
request_body = {
    "settings" : {
        "number_of_shards": 1,
        "number_of_replicas": 10,
     }
}
res = es.indices.create(index = "test", body = request_body, ignore=400)
es.index(index='test', doc_type='post', id=1, body={
  'author': 'John Doe',
  'blog': 'Learning Elasticsearch',
  'title': 'Using Python with Elasticsearch',
  'tags': ['python', 'elasticsearch', 'tips'],
})

res = es.search(index='test', body={'query': {'match': {'title': 'Python', }}})
res = es.search('test', q="Using")  

Hi, there is an item in my index with the title: Using Python with Elasticsearch
When I search for it, I always get zero hit except  that I search "Using Python with Elasticsearch" exactly.
like:
res = es.search(index='test', body={'query': {'match': {'title': 'Using Python with Elasticsearch', }}})
res = es.search('test', q='title:"Using Python with Elasticsearch"')
and these two always fail,
res = es.search(index='test', body={'query': {'match': {'title': 'Python', }}})
res = es.search('test', q="Using") 

I know the "match"  search can get fuzzy match, but the experiments are not. How can I get a fuzzy match?

Thanks a lot!

**Comment by HonzaKral** [comment]
I am sorry, I cannot replicate your problem, when I run on empty cluster:
```
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.index(index='test', doc_type='post', id=1, body={
'author': 'John Doe',
'blog': 'Learning Elasticsearch',
'title': 'Using Python with Elasticsearch',
'tags': ['python', 'elasticsearch', 'tips'],
})
es.indices.refresh(index='test')
es.search(index='test', body={'query': {'match': {'title': 'Python', }}})
```
I get back the document, same as with `es.search('test', q="Using")`. I think there might be something wrong with your mappings where the field doesn't get analyzed. I would guess that you have something setting the mappings, whether the index directly or maybe an index template. You can verify what the mappings are by running: `es.indices.get(index='test')`.

I am sorry but I have to close this issue now since this is not the proper place for it - it's not an issue with the python client but rather a question about using elasticsearch. For such questions I would recommend you try our forums at https://discuss.elastic.co/

thanks!

**Comment by chocolate9624** [comment]
Thanks @HonzaKral 
You are right! The default mappings for each filed's type are "string". 
However, when I change the filed type from "string" to "text". Another error comes:

elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')

This is the code:
from elasticsearch import Elasticsearch
es = Elasticsearch()
request_body = {
    "settings" : {
       "number_of_shards": 1,
       "number_of_replicas": 10,
    },
    "mappings":{
      "post":{
         "properties":
              {"name":{"type":"test"}}   
      }
    }
}
res = es.indices.create(index = 'test', body = request_body)

Thanks a lot !

**Comment by chocolate9624** [comment]
@HonzaKral , thanks for your reply!
# 1, This is the original code and output :+1: 
code:
import  elasticsearch
INDEX_NAME= 'test_1'
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.index(index=INDEX_NAME, doc_type='post', id=1, body={
'author': 'John Doe',
'blog': 'Learning Elasticsearch',
'title': 'Using Python with Elasticsearch',
'tags': ['python', 'elasticsearch', 'tips'],
})
es.indices.refresh(index=INDEX_NAME)
res = es.indices.get(index=INDEX_NAME)
print res
output:
{u'test_1': {u'warmers': {}, u'settings': {u'index': {u'number_of_replicas': u'1', u'number_of_shards': u'5', u'uuid': u'Z2KLxeQLRay4rFgdK4yo9A', u'version': {u'created': u'2020199'}, u'creation_date': u'1484405704970'}}, u'mappings': {u'post': {u'properties': {u'blog': {u'type': u'string'}, u'title': {u'type': u'string'}, u'tags': {u'type': u'string'}, u'author': {u'type': u'string'}}}}, u'aliases': {}}}

# 2, I change the mappings with the code below:
INDEX_NAME = 'test_1'
from elasticsearch import Elasticsearch
es = Elasticsearch()
request_body = {
    'mappings':{
          'post': {
            'properties': {
              **'title': {'type':'text'}**
            }
        }
     }
}
if es.indices.exists(INDEX_NAME):
    res = es.indices.delete(index = INDEX_NAME)
    print(" response: '%s'" % (res))
res = es.indices.create(index = INDEX_NAME, body= request_body, ignore=400)
print res

The output is 
 response: '{u'acknowledged': True}'
{u'status': 400, u'error': {u'caused_by': {u'reason': u'No handler for type [text] declared on field [title]', u'type': u'mapper_parsing_exception'}, u'root_cause': [{u'reason': u'No handler for type [text] declared on field [title]', u'type': u'mapper_parsing_exception'}], u'type': u'mapper_parsing_exception', u'reason': u'Failed to parse mapping [post]: No handler for type [text] declared on field [title]'}}


# 3, The version of elasticsearhc is  (5, 1, 0, 'dev')

Thanks a lot!!

**Comment by HonzaKral** [comment]
Mapping as `string` (without `index="not_analyzed") should be ok with elasticsearch `2.x`, with `5.x` `string` was replaced by `text`.

You didn't, however, request `fuzzy` matching, you were talking about just matching individual words. To use fuzziness in queries you need to specify it:
```
{"query": {"match": {"title": {"query": "Python", "fuzziness": 1}}}}
```

Also I am sorry but I really cannot help you more here, if you have further questions please ask at the discussion forum, these questions really don't belong here. Thank you!

**Comment by chocolate9624** [comment]
OK, Thank you very much ! I try to get the answer from the forum.
