### ISSUE TITLE
Can't get data to Zabbix

### ISSUE THREAD

**Issue by guidodobboletta** [elastic/elasticsearch-py#527]
I'm trying to set up zabbix with a UserParameter to get the cluster health state. 

This is what my script looks like:

```python
#!/usr/bin/python
from elasticsearch import Elasticsearch
es = Elasticsearch(['http://testing:testing@localhost:9200'])
print(es.cluster.health())
```

If I run it from the command line it works perfectly but when zabbix tries to run it I get this error:

`Sending back [Traceback (most recent call last):
  File "/etc/zabbix/test.py", line 4, in <module>
    print(es.cluster.health())
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/cluster.py", line 30, in health
    'health', index), params=params)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 106, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f137f4b10>: Failed to establish a new connection: [Errno 13] Permission denied) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f137f4b10>: Failed to establish a new connection: [Errno 13] Permission denied)]`

The script has 777 permissions so I'm not sure what's failing here.

**Comment by HonzaKral** [comment]
Could it be that the user you are running this under doesn't have permissions to open network communication? Or perhaps a firewall somewhere along the way?

This is definitely an error outside of `elasticsearch-py` signifying that the connection couldn't be established.

**Comment by guidodobboletta** [comment]
I su as the zabbix user and it works perfectly through command line too. 

`su - zabbix -s /bin/bash`

`-bash-4.3$ /etc/zabbix/test.py `

`{u'status': u'green', u'number_of_nodes': 5, u'unassigned_shards': 0, u'number_of_pending_tasks': 0, u'number_of_in_flight_fetch': 0, u'timed_out': False, u'active_primary_shards': 23, u'task_max_waiting_in_queue_millis': 0, u'cluster_name': u'playtika-cluster', u'relocating_shards': 0, u'active_shards_percent_as_number': 100.0, u'active_shards': 48, u'initializing_shards': 0, u'number_of_data_nodes': 4, u'delayed_unassigned_shards': 0}
`

I'm not sure where the problem would be since from the CLI it works perfectly.

**Comment by HonzaKral** [comment]
I am sorry, but I cannot replicate this issue. Since this is an error on the connection layer (`urllib3`) and not in the elasticsearch library I will close this ticket. Please feel free to reopen if you come across any new information.
