### ISSUE TITLE
AppEngine Support / URLFetchConnection

### ISSUE THREAD

**Issue by soundofjw** [elastic/elasticsearch-py#528]
Didn't know the best place to discuss this.

To mitigate the various issues introduced by using `elasticsearch-py` on AppEngine, we have released a `ConnectionClass` for `google.appengine.api.urlfetch`.

This will resolve issues with warnings related to "Content-Length", among other things.
```
Stripped prohibited headers from URLFetch request: ['Content-Length']
```

https://github.com/Loudr/elasticsearch-urlfetch

**Comment by HonzaKral** [comment]
This is great, thank you. If you could submit a short PR for the docs to link to your project I would be happy to merge it.
