### ISSUE TITLE
helpers.scan: TypeError: search() got an unexpected keyword argument 'clear_scroll'

### ISSUE THREAD

**Issue by qiao-meng-zefr** [elastic/elasticsearch-py#529]
I'm using helpers.scan function to retrieve data. I passed in `clear_scroll=False` to it (following the [documentation here](https://elasticsearch-py.readthedocs.io/en/master/helpers.html#elasticsearch.helpers.scan)). But I got this error:
```bash
File "/var/task/elasticsearch/helpers/__init__.py", line 277, in scan
resp = client.search(body=query, scroll=scroll, size=size, **kwargs)
File "/var/task/elasticsearch/client/utils.py", line 69, in _wrapped
return func(*args, params=params, **kwargs)
TypeError: search() got an unexpected keyword argument 'clear_scroll'
```

I'm using elasticsearch server 2.4.1 and I'm using elasticsearch-py lib 2.4.0

Did I use `scan` wrong? Thank you!

**Comment by HonzaKral** [comment]
`clear_scroll` argument is not present in `2.4.0` release.

That is the documentation for the `master` version, the documentation for `2.4.0` is here: http://elasticsearch-py.readthedocs.io/en/2.4.0/helpers.html
