### ISSUE TITLE
How to access aggregations results on a scrolled query?

### ISSUE THREAD

**Issue by macdjord** [elastic/elasticsearch-py#530]
I have a query which returns a large dataset as well as some aggregations about that data. According to [the elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-scroll.html), aggregation results are indeed returned by the first, and only the first, search call in a scrolled query. What I need to do is:

1. Execute my query
1. Process the aggregation results by the initial query
1. Iterate over and process the dataset, starting with the results returned by the initial query and automatically performing additional scroll queries as needed

I can't find any way to do this right now. Help?

**Comment by qiao-meng-zefr** [comment]
This has been requested in Elasticsearch. I don't think this is possible in 2.4 but not sure in 5. See [this issue](https://github.com/elastic/elasticsearch/issues/4915).

**Comment by macdjord** [comment]
I don't need to paginate the aggregations themselves. They are small enough to handle in a single search. Elasticsearch - as in the database, not the python interface - _does_ support scrolled queries with aggregations. From https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-scroll.html :

> If the request specifies aggregations, only the initial search response will contain the aggregations results.

I'm pretty sure I could do what I want now - if I were willing to do the search() call and subsequent scroll() calls all manually. I'm not; I want the helpers to handle the complicated process of recording the scroll ID, making the subsequent scroll queries automatically as I iterate over the results, and closing the scroll when I'm done with it.

**Comment by qiao-meng-zefr** [comment]
Ah, I see. I misunderstood your question. Sorry!

**Comment by HonzaKral** [comment]
Hi, currently the `scan` helper returns a simple iterator which makes this very tricky to implement. We could change it to allow for returning the aggregations as well, perhaps returning a tuple with the aggregations as one element and the iterator as the second, but I am honestly not sure we should.

This is a fairly rare use case in my opinion (I would welcome comments from other users) and it would complivate the most common use case for `scan`.

Do you have a specific reason why this cannot be implmented as two requests on your part - one just asking for aggregations and then one using the `scan` helper? I understand it is not optimal, but I also believe that, when using `scan`, there is usually some wiggle room when it comes to performance.

Thank you for raising this issue!

**Comment by macdjord** [comment]
@HonzaKral Using two queries is what I ended up doing. However, I first had to redesign the query to use abosulte instead of relative dates, to ensure I would actually be searching the same data set for both.

My suggestions for how to handle this would be to add a new function, `execute_scan()`, which returns a Response object like `execute()` does, only the `.hits` element is a `scan()`-style iterator instead of a list.

Alternately, instead of a new function, you could make it an adjustable property of the Search object itself, so `s = s.scroll(True); s.execute()` executes a scrolled query and returns a Response object with an iterable `.hits` element, while `s = s.scroll(False); s.execute()` executes a normal query and returns a Response object with a static `.hits` element.

**Comment by HonzaKral** [comment]
Unfortunately we don't have a `Search` object, that could be done in `elasticsearch-dsl` where this would definitely make sense but I am not sure it belongs in the `scan` helper.

I will close the issue here and let's move the discussion to the dsl library. I created a ticket to track it there - https://github.com/elastic/elasticsearch-dsl-py/issues/580

Thanks!

**Comment by macdjord** [comment]
In that case, how about going with your idea of returning a tuple? Only don't change the scan helper; add a new helper with the alternate API.

I'm pretty sure the elasticsearch-dsl authors will need something like that in order to implement what I suggested anyway.

**Comment by HonzaKral** [comment]
Well, since I am the author of both we will see what it takes to implement it cleanly. If it would mean adapting the helper or, more likely, adding another one on top of the existing one, we will absolutely explore that.

Thanks again for raising this issue, it makes a lot of sense for us to include this functionality
