### ISSUE TITLE
How to access protected ES (protected with Shield, in ES5 included into X-pack)?

### ISSUE THREAD

**Issue by flamewow** [elastic/elasticsearch-py#531]
How to access protected ES (protected with Shield, in ES5 included into X-pack)?
I've checked documentation and haven't found any info about that.

**Comment by flamewow** [comment]
Found an answer. Using 'headers' in Urllib3HttpConnection does a job.

**Comment by HonzaKral** [comment]
When you want to authenticate against elasticsearch secured with `x-pack` just pass in `http_auth=("username", "secret")` to `Elasticsearch`. You might also find the `x-pack` plugin for `elasticsearch-py` useful in case you wish to use any of the `x-pack` APIs - https://github.com/elastic/elasticsearch-x-pack-py (new PyPI release coming soon).
