### ISSUE TITLE
 Text start by "{" in analyse function return a error 

### ISSUE THREAD

**Issue by JeanHany** [elastic/elasticsearch-py#533]
I'm using version 5.1.0

When you want to analyze a text witch start by "{" the analyse function return this error 

es.indices.analyze(index="publications", analyzer="standard", body="{on")
GET http://localhost:9200/publications/_analyze?analyzer=standard [status:400 request:0.028s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 32, in analyze
    '_analyze'), params=params, body=body)
  File "/usr/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 127, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Failed to parse request body')

If I use the same request with sense it works fine.

GET _analyze
{"analyzer" : "standard",
    "text": "{on" }

{
   "tokens": [
      {
         "token": "on",
         "start_offset": 1,
         "end_offset": 3,
         "type": "<ALPHANUM>",
         "position": 0
      }
   ]
}

It seems this error occur only when "{" is at the start of the text.

**Comment by HonzaKral** [comment]
This is an unfortunate side effect of the automatic content type detection in elasticsearch itself where it tries to detect if the body contains `json` by looking at the first character.

Since this is problematic (as clearly demonstrated by this bug) it is being removed in new versions of elasticsearch where the body will have to be json and text bodies will no longer be allowed.

The fix is to send the exact body as you did here in sense, so instead of:
```
es.indices.analyze(index="publications", analyzer="standard", body="{on")
```
do:
```
es.indices.analyze(index="publications", analyzer="standard", body={"analyzer" : "standard", "text": "{on" })
```

Hope this helps
