### ISSUE TITLE
Scroll with scroll_id parameter is broken on ES 6.x

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch-py#534]
Continuing a scroll and clearing a scroll is broken against the latest master build of Elasticsearch.

The following snippet demonstrates the problems:

```python
import elasticsearch

# force content type header for ES 6.x
class ConfigurableHttpConnection(elasticsearch.Urllib3HttpConnection):
    def __init__(self, **kwargs):
        super(ConfigurableHttpConnection, self).__init__(**kwargs)
        self.headers.update({"Content-Type": "application/json"})


es = elasticsearch.Elasticsearch(hosts=[{"host": "localhost", "port": 9200}], connection_class=ConfigurableHttpConnection)

# first page
r = es.search(body={
    "query": {
        "match_all": {}
    }
}, scroll="10s")

scroll_id=r["_scroll_id"]

try:
	# continue scrolling - will fail with HTTP 400
	es.scroll(scroll_id=scroll_id)
finally:
	# will fail too with HTTP 400
	es.clear_scroll(scroll_id=scroll_id)
```

Workaround: Explicitly define the request body, i.e instead of:

```python
es.scroll(scroll_id=scroll_id)
```

 we can use

```python
es.scroll(body={"scroll_id": self.scroll_id, "scroll": "10s"})
```

and instead of

```python
es.scroll(scroll_id=scroll_id)
```

we can use

```python
es.clear_scroll(body={"scroll_id": [scroll_id]})
```

Elasticsearch Python client version: 5.1.0

**Comment by HonzaKral** [comment]
This should have been fixed in https://github.com/elastic/elasticsearch-py/commit/a96f5f72843584af7e25743e3906ec0701bd5859, are you sure you are using `master`?

**Comment by danielmitterdorfer** [comment]
No, I use the latest released version 5.1.0 but as it is fixed already on master I'm (obviously) fine with closing it. :)

**Comment by danielmitterdorfer** [comment]
I maybe see your confusion. I said:

> Continuing a scroll and clearing a scroll is broken against the latest master build of Elasticsearch.

I really referred to the master branch of Elasticsearch. As stated in the report, the client version is 5.1.0. (but maybe I shouldn't have written this at the end of the report....).

**Comment by HonzaKral** [comment]
Ah, I see. Sorry about the confusion - I saw `master` and stopped reading. My bad.

Also please note that the client follows elasticsearch versioning scheme - `5.x` releases are only compatible with `5.x` releases of elasticsearch itself. If you want to use pre release versions of elasticsearch you need to also use git version of the client.

Thanks!
