### ISSUE TITLE
About aggregation and max result

### ISSUE THREAD

**Issue by 521xueweihan** [elastic/elasticsearch-py#538]
Hi, 

This is the query body data: 
```
        body = {
            "aggs": {
                "distinct_package_name": {
                    "terms": {
                        "field": "package_name",
                        "size": 10000
                    },
                     "aggs": {
                         "max_points": {
                             "max": {
                                 "field": "points",
                             },
                         },
                     }
                },
            }
        }
```

Result:
```
  "aggregations": {
    "distinct_package_name": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "com_chaozh_ireader",
          "doc_count": 7,
          "max_points": {
            "value": 0.30000001192092896
          }
        },
        {
          "key": "com_garena_game_kgtw",
          "doc_count": 7,
          "max_points": {
            "value": 1.2999999523162842
          }
        },....
```

Why the max_points value  float precision?

I think this is elasticsearch problem, so I make the `points` value to `long` type to solve this problem. 

But, when the `point` field is `long` type, The `max_points` also become `float` type, such as `300.0`, I need `300` . How to get this?

 So what does the `max` funcation do? 

Thanks.

**Comment by HonzaKral** [comment]
The `max` aggregation (which returns the maximum value it encountered for the given field) always operates with `double` precision (see [0]) regardless of the underlying data type, if you need integers or longs you have to do the conversion yourself unfortunately.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-max-aggregation.html
