### ISSUE TITLE
put_mapping fails on elasticsearch 1.0.1

### ISSUE THREAD

**Issue by jdve** [elastic/elasticsearch-py#54]
I'm getting an error when attempting to use put_mapping with elasticsearch 1.0.1:

```
es.indices.put_mapping(
   index="myindex",
   doc_type="mytype",
   body={
      "mytype": {
         "properties": {
            "_timestamp": { "enabled": True },
         }
   })
```

Error:

```
InvalidTypeNameException[mapping type name [_mapping] can't start with '_']
```

I think it's caused by change https://github.com/elasticsearch/elasticsearch-py/commit/6c29fca1c8d26b073ded13af56cedb034a3ea3d9 due to swapping the position of `_mapping` in the URI. Should it be switched back?

**Comment by alecklandgraf** [comment]
@jdve :+1: for pointing out that a rogue instance would cause this. I too had 0.90 running along side the newest version. 

Thanks!
