### ISSUE TITLE
Indices.exists_type always return False when you query to Elasticsearch2.x

### ISSUE THREAD

**Issue by natureCode** [elastic/elasticsearch-py#542]
Indices.exists_type in elasticsearch5.2.0 doesn't work for Elasticsearch2.x.
Here's my sample
ES mapping
http://localhost:9200/.kibana/_mapping?pretty=true
`
{
  ".kibana" : {
    "mappings" : {
      "config" : {
        "properties" : {
          "buildNum" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      },
`

Test scripts

`
from elasticsearch import Elasticsearch  
es = Elasticsearch('localhost:9200')  
dtsName = '.kibana'  
chName = 'config'  
print es.indices.exists_type(index=dtsName, doc_type=chName)  
(False)
`

I know elasticsearch>=5.0.0,<6.0.0 and Elasticsearch2.x are not compatible but this is a little confusing.

**Comment by HonzaKral** [comment]
I am sorry but there is nothing we can do - elasticsearch 5 and 2 just are not compatible on the API level. Please make sure you are using the proper elasticsearch-py version for your elasticsearch server
