### ISSUE TITLE
Number of retries for a request

### ISSUE THREAD

**Issue by neo4u** [elastic/elasticsearch-py#544]
Bulk update using the bulk helper fails with the following error. I increased the timeout to 20 and that helped the bulk requests, but I still have some requests that fail with the following error. 

```elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=20))```

While I can increase the timeout, I was wondering if there is a field for setting `Number of Retries` within a request. I wasn't able to find this in the API and was wondering if there is a plan to have this implemented?

I understand that it may cause a problem with the version changing due to double update to the records that didn't fail within the bulk update. But it would be nice to have an option to enable retries.

**Comment by HonzaKral** [comment]
When a timeout happens a request is not retired by default. Typically, especially with `bulk` the timeout means that elasticsearch hasn't been able to perform the required action in time. It does not, however, mean that the action has been cancelled. For `bulk` that means that the documents could have been inserted, retrying can then lead to duplicate documents.

That said, if you wish to override this behavior you can by setting `retry_on_timeout` to `True` and then you can control the number of retries via the `max_retries` parameter to `Elasticsearch` which will be passed to the underlying `Transport` class (0).

Hope this helps

**Comment by neo4u** [comment]
You sir are kind and knowledgeable.

Just to clarify I have to set parameters like `retry_on_timeout` to `True` and `max_retries` while initializing the `Elasticsearch` object or at the respective bulk request?

**Comment by HonzaKral** [comment]
When instantiating `Elasticsearch`, those are global parameters, not a per-request ones.

**Comment by neo4u** [comment]
Okay perfect. Thanks man. Appreciate your time. 👍🏽
