### ISSUE TITLE
Issues with search

### ISSUE THREAD

**Issue by ambodi** [elastic/elasticsearch-py#546]
If initialized like this:

```py
es = Elasticsearch(['host'],
  http_auth=('user', 'pass'),
  port=443,
  use_ssl=True,
  verify_certs=True,
  ca_certs=certifi.where()
  #send_get_body_as='POST'
)
r = es.search(index='estimates', request_timeout=10000)
```

The above search returns result correctly! But once I add *any* type of query like ```body={"query" : {"term" : { "user" : "kimchy" }}}``` I am getting 

```HEAD /elasticsearch/ [status:400 request:0.056s]```

NOTE: 

```es.info()``` returns 
```
{'name': 'Zabu', 'cluster_name': 'elasticsearch', 'version': {'number': '2.3.0', 'build_hash': '8371be8d5fe5df7fb9c0516c474d77b9feddd888', 'build_timestamp': '2016-03-29T07:54:48Z', 'build_snapshot': False, 'lucene_version': '5.5.0'}, 'tagline': 'You Know, for Search'}
```
but ```es.ping() ``` returns False. 

I am very confused! 

**Versions**::
Version: Python 3.6.0
Elasticsearch 2.4.1
Host Elasticsearch 2.4.1
OS: MacOS 10.12.3

**Comment by HonzaKral** [comment]
Are you using any kind of proxy between elasticsearch and your network? How do you handle the authentication? It looks like something is not configured well in your environment since the behavior you describe is inconsistent with raw elasticsearch experience.

**Comment by ambodi** [comment]
Haproxy is handling the authentication of the host and the host is on Azure.

I can query host using POSTMAN on my machine though and it works just fine. Could it be any problem with body? I mean I looked at the code and search is a GET, right? Isn't there a conflict with that and SSL on a proxy or something?

**Comment by HonzaKral** [comment]
No, this is definitely what either elasticsearch or elasticsearch-py would do. You could get a `400` response for search but not for `HEAD` request (and search would never result in a `HEAD` request anyway) and `ping` should always work. Looks like something is misconfigured in your proxy. Could you try to replicate the behavior via `curl` or some other http tool?

Thanks

**Comment by ambodi** [comment]
So curl returns:

```curl -u user:pass -X POST -H "Content-Type: application/json" -H "kbn-version: 4.3.1" -H "Cache-Control: no-cache" -H "Postman-Token: c9d3c6ce-7da4-d30f-c631-f4f7eb13dfd9" -d '{"query" : {"term" : { "user" : "kimchy" }}}' "https://host_name/estimates/_search"
{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}%```

**Comment by HonzaKral** [comment]
That looks good, so can you try the same via the `elasticsearch-py` - just .search and do specify the `send_get_body_as='POST'` parameter when creating the client. That should result in the same request being issued, you can verify that by turning on logging

**Comment by ambodi** [comment]
Yeah but that's the issue, once I enable that:

```
HEAD /elasticsearch/ [status:400 request:0.005s]
POST /elasticsearch/estimates/_search [status:400 request:0.044s]```

**Comment by HonzaKral** [comment]
You have some other configuration in your code since `elasticsearch-py` thinks, for some reason, that you have elasticsearch running not at host:9200 but at a subpath `/elasticsearch/` (`host:9200/elasticsearch`). Can you please share the exact code you use? Without it I cannot help you.

**Comment by ambodi** [comment]
@HonzaKral Thanks so much for the help but this was related to haproxy issue of swallowing headers info I was sending to elastic for authentication.
