### ISSUE TITLE
delete [_type,_index,_version...] from mget response

### ISSUE THREAD

**Issue by chu8129** [elastic/elasticsearch-py#549]
code:
```python
es = Elasticsearch(hosts = [esURL], timeout = es_timeout)
res = es.mget(index = es_index,doc_type = es_doc_type, body = {"docs":queryList}, _source_exclude = "*.*",)
print res
```

response:
```json
{
    "docs": [
        {
            "_type": "profile", 
            "_source": {
                "**id": "8sdfkdskf;", 
                "100302": {}, 
                "100101": {}
            }, 
            "_index": "user", 
            "_version": 1, 
            "found": true, 
            "_id": "8sdfkdskf"
        }, 
        {
            "_type": "profile", 
            "_source": {
                "**id": "234234", 
                "100301": {}, 
                "100101": {}
            }, 
            "_index": "user", 
            "_version": 1, 
            "found": true, 
            "_id": "234234"
        }, 
```

why each cell have useless info(for example:_version)? how can i hide those info?

**Comment by HonzaKral** [comment]
This is a standard response from the `mget` API (0). The metadata fields are needed for some operations. You don't have to use them or you can use response filtering (1) by specifying a `filter_path` parameter to the `mget` API.

Hope this helps

0 - https://www.elastic.co/guide/en/elasticsearch/reference/5.2/docs-multi-get.html#docs-multi-get
1 - https://www.elastic.co/guide/en/elasticsearch/reference/5.2/common-options.html#common-options-response-filtering
