### ISSUE TITLE
failed to index.',{u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': 

### ISSUE THREAD

**Issue by NTAbraham** [elastic/elasticsearch-py#552]
src/espcap.py --file=test_pcaps/test2.pcap --node=localhost:9200
Loading packet capture file(s)
test_pcaps/test2.pcap
[ERROR]  (u'306 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k6_', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7Q', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7d', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7q', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7r', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7t', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7u', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7v', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVrJXZ0r_4B1j-_D7k7w', u'error': {u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}, u'_index': u'packets-2011-05-17'}}, {u'index': {u'st

Not sure what the problem is? Not sure if it with elastic search or espcap! Please help

**Comment by HonzaKral** [comment]
@NTAbraham - the reason is mentioned in the response - `{u'reason': u'Limit of total fields [1000] in index [packets-2011-05-17] has been exceeded', u'type': u'illegal_argument_exception'}`

Elasticsearch limits the number of fields in a type to avoid users overwhelming the cluster which your data exceeds
