### ISSUE TITLE
Provide complete error information in `TransportError.__str__`

### ISSUE THREAD

**Issue by Naitreey** [elastic/elasticsearch-py#553]
I have in times found that when a `TransportError` is raised, its string representation (mainly `error.root_cause[0].reason`) was just  not providing enough information to pinpoint the cause of error. Sometimes `error.reason` shows the more direct and relevant information about error. In these cases, I had to manually catch the exception and inspect complete `TransportError.info`.

Thus I propose we should provide complete `TransportError.info` or something similar in `TransportError.__str__` implementation.

**Comment by HonzaKral** [comment]
Thank you for this issue. We made the decision to only include the crucial information in the `__str__` representation as the data in `info` can be quite large and thoroughly impractical for display purposes.

Then, no matter what we decide, we cannot display more information - I would much rather encourage people to catch the exception and inspect the `info` attribute. We could perhaps try to do something half way like including both `error.reason` and `root_cause[0].reason` (if they are not the same, which is typically the case) as well..

Does this make sense?

**Comment by Naitreey** [comment]
@HonzaKral Yeah, I think including both `reason`s in some way could be better. It will make more exceptions easier to understand, and... less pretty.

How about this, just one small step further: We could include two pairs of `type` and `reason`,
one from the outer `error`, another
from `root_cause[0]`, something like the following in string representation:

```
TransportError(status_code, (type, reason), (root_cause[0].type, root_cause[0].reason))
```

This will certainly make traceback much longer (and more annoying...) than it is now. But it provides two set of info from different exception perspectives.

**Comment by fxdgear** [comment]
@Naitreey please see this PR: https://github.com/elastic/elasticsearch-py/pull/726

It looks like someone is attempting to add more info into the exceptions.

**Comment by sethmlarson** [comment]
`TransportError.__repr__` has changed quite a lot. Maybe now things are good enough? Can reopen if this is still a problem.
