### ISSUE TITLE
Indicate `https` under `scheme` in `repr(client)`

### ISSUE THREAD

**Issue by skatenerd** [elastic/elasticsearch-py#554]
If you make a client: `client = es.Elasticsearch(my_https_url)`, and you type `print repr(client)`, you will see confusing information.

You will see `u'use_ssl': True`, but you will also see `u'scheme': u'http'`.  This is a little bit worrisome because, if we were actually using ssl, you might expect to see `https`.

I believe the behavior comes from [this line](https://github.com/elastic/elasticsearch-py/blob/05ad5ef96bf958a1482274c57feb56a8d873dc8d/elasticsearch/client/__init__.py#L47).

I'd prefer to update it, so that `'use_ssl': True` means you also see `'scheme': 'https'`.  Then again, `https` is just a secure version of `http` so I guess the information displayed isn't technically _wrong_

**Comment by GlenRSmith** [comment]
@skatenerd This has been fixed by [[WIP] remove scheme checking
](https://github.com/elastic/elasticsearch-py/commit/d336c571b913720cb42e3c69229f6fa7a6371dfb) Thank you for reporting!

**Comment by skatenerd** [comment]
Thanks!
