### ISSUE TITLE
forceMerge params are out of date

### ISSUE THREAD

**Issue by untergeek** [elastic/elasticsearch-py#555]
The [elasticsearch-py API docs](http://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.IndicesClient.forcemerge) state:

> Parameters:	
> index – A comma-separated list of index names; use _all or empty string to perform the operation on all indices
> allow_no_indices – Whether to ignore if a wildcard indices expression resolves into no concrete indices. (This includes _all string or when no indices have been specified)
> expand_wildcards – Whether to expand wildcard expression to concrete indices that are open, closed or both., default ‘open’, valid choices are: ‘open’, ‘closed’, ‘none’, ‘all’
> flush – Specify whether the index should be flushed after performing the operation (default: true)
ignore_unavailable – Whether specified concrete indices should be ignored when unavailable (missing or closed)
> max_num_segments – The number of segments the index should be merged into (default: dynamic)
> only_expunge_deletes – Specify whether the operation should only expunge deleted documents
operation_threading – TODO: ?
> wait_for_merge – Specify whether the request should block until the merge process is finished (default: true)

But the [Elasticsearch API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-forcemerge.html) state:

> **max_num_segments** The number of segments to merge to. To fully merge the index, set it to 1. Defaults to simply checking if a merge needs to execute, and if so, executes it.
>
> **only_expunge_deletes** Should the merge process only expunge segments with deletes in it. In Lucene, a document is not deleted from a segment, just marked as deleted. During a merge process of segments, a new segment is created that does not have those deletes. This flag allows to only merge segments that have deletes. Defaults to false. Note that this won’t override the index.merge.policy.expunge_deletes_allowed threshold.
>
> **flush** Should a flush be performed after the forced merge. Defaults to true.

A quick look showed that these 3 parameters have been the only ones acceptable since _Elasticsearch 1.5,_ when it was still called Optimize.

**Comment by HonzaKral** [comment]
Not all parameters are described in the docs since a lot of them are global or implied. The canonical source of the parameter list can be found in the `rest-spec-api` (0) from which this list is periodically generated.

0 - https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/indices.forcemerge.json

**Comment by untergeek** [comment]
Hmm. I think that list ought to be updated, then, because `wait_for_merge` is an invalid flag.

**Comment by HonzaKral** [comment]
If that is indeed the case then you need to open a ticket in elasticsearch repo itself.
