### ISSUE TITLE
Using RequestsHttpConnection in 5.x code with proxies doesn't work

### ISSUE THREAD

**Issue by tektsiq** [elastic/elasticsearch-py#557]
In our environment we use proxy servers. In addition we use AWS Elasticsearch domains hence the need to use the requests connection class with the custom auth.

We have found that proxies are not being honored in the 5.x code, and tracked it down to the change made in #481. Per the guidance issued by the requests authors in https://github.com/kennethreitz/requests/issues/3626, I believe the code should add a call to merge_environment_settings() in order to bring in the proxy settings. e.g. in perform_request() do:
  
```python
request = requests.Request(method=method, url=url, data=body)
prepared_request = self.session.prepare_request(request)
settings = self.session.merge_environment_settings(prepared_request.url, {}, None, None, None)
send_kwargs = {'timeout': timeout or self.timeout}
send_kwargs.update(settings)
response = self.session.send(prepared_request, **send_kwargs)
```

Another approach to take is to just go back to not using prepared requests. The reason I think you want the prepared_request is to be able to get to the `path_url` attr of the prepared request when an exception is raised (the path being used in trace logging). If we could get the path without needing to construct an entire prepared_request then we can simplify the above down to one line again.

**Comment by tektsiq** [comment]
Hello, is there any update on this? I can put in a PR if that would help?

**Comment by conwayb** [comment]
We are running into the same issue when attempting to use signed requests for AWS as outlined in the docs. 
Code supplied by @tektsiq worked for me.

**Comment by HonzaKral** [comment]
Thanks for the report and the link to the fix, it has been merged!
