### ISSUE TITLE
Connection seems to sniff even with sniffing disabled

### ISSUE THREAD

**Issue by k2xl** [elastic/elasticsearch-py#558]
```
es = Elasticsearch([os.environ.get("ES_OUT_URL")],
    retry_on_timeout=True,
    sniff_on_start=os.environ.get("ES_SNIFF", "False").lower()=="true",
    sniff_on_connection_fail=os.environ.get("ES_SNIFF", "False").lower()=="true",
    sniffer_timeout=60
)
```

If I set `ES_SNIFF` to False, it still seems to try to connect to other cluster nodes. This specific process only has access to ES_OUT_URL, not the other nodes to the cluster so it gets connection errors when trying to index. Am I using the API incorrectly?

**Comment by HonzaKral** [comment]
If tries to sniff because you specified the timeout - meaning that you wish the client to sniff every 60 seconds in your case. Set `sniffer_timeout` to `None` to disable sniffing.

**Comment by k2xl** [comment]
Ah okay makes sense. Thanks
