### ISSUE TITLE
update from 5.0.1 to 5.2

### ISSUE THREAD

**Issue by gabriel-tessier** [elastic/elasticsearch-py#560]
Hi,
I freshly upgrade from 5.0.1 to 5.2 and I have the following error:

> File "/home/src/lib/elasticsearch/client/utils.py", line 62, in _wrapped
>     params = kwargs.pop('params').copy()
> AttributeError: 'NoneType' object has no attribute 'copy'
> 

Somehow params = None and it crash, on 5.0.1 I didn't have this problem.

Thanks

**Comment by fatelei** [comment]
in 5.0.1 the related code is:

![image](https://cloud.githubusercontent.com/assets/961094/24537017/b7335a5a-1611-11e7-9dac-071cbaccd500.png)

**Comment by HonzaKral** [comment]
I don't see how this can happen unless you explicitly pass `params=None` in your code to any of the APIs which is something the library cannot reasonably deal with and shouldn't have a special code for imho.

I am closing this issue for now, please feel free to reopen with a sample of the code that is causing this exception to trigger, thank you!
