### ISSUE TITLE
Specifying a pipeline is not supported in the bulk helpers

### ISSUE THREAD

**Issue by mblum14** [elastic/elasticsearch-py#564]
The [expand_action callback](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L37) has a whitelist of action properties `['_index', '_parent', '_percolate', '_routing', '_timestamp',
'_ttl', '_type', '_version', '_version_type', '_id', '_retry_on_conflict']`. I would like to add `pipeline` to the list of properties accepted for bulk actions.

**Comment by HonzaKral** [comment]
Thank you for the report!
