### ISSUE TITLE
Reindex helper does not respect size limit

### ISSUE THREAD

**Issue by Battleroid** [elastic/elasticsearch-py#565]
Not sure if this is possible, but I haven't found a way to apply a maximum number of documents to reindex using the `reindex` helper. Everything I've tried just reindexes everything.

Using a size limit with `search` works as expected, but `reindex` doesn't seem to respect this. I can use curl with the same query for reindexing and it works as expected. Is there something I'm missing by any chance?

Currently using with the 2.4.1 release.

**Comment by Battleroid** [comment]
I've gotten around this issue by doing something silly such as the following:

```python
docs_gen = scan(src_es, index=source)
docs = [next(docs_gen) for _ in range(size)]

def _change_doc_index(hits, index):
    for h in hits:
	h['_index'] = index
	if 'fields' in h:
	    h.update(h.pop('fields'))
	yield h
```

**Comment by HonzaKral** [comment]
The `reindex` helper is meant to reindex the while dataset, if you want to limit the number of documents reindexed you must do it by passing a `query` to it that only matches portion of your data. If you only wish to reindex a few documents it might be easier to get them manually using the `search` api and then use the `bulk` helper to load them back in.

Also note that you should probably be using the `reindex` API directly in elasticsearch for increased performance - https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-reindex.html

**Comment by Battleroid** [comment]
I've actually tried placing a limit using a query, but it seems to disregard the limit when using it the `reindex` helper.

I'll give using search + bulk a shot, but if not the stop gap works well enough. I'm primarily concerned because we typically want to bring in production data from another cluster to a sandbox cluster for testing. So it's a bit annoying when you want to pull only a few hundred documents, but the helper instead brings all the documents for a particular index which can be in the order of gigabytes of documents for an hourly index.

Performance isn't too much of a concern as we're capping this at a low number of documents on a sandbox cluster.

**Comment by HonzaKral** [comment]
yes, the limit is being ignored because `reindex` uses `scan` search to get all the documents, you'd have to craft a query that only matches N documents in your index.

But if you look into the implementation of `reindex` you see how easy it is, it is literally feeding search results into `bulk`, which you can do on your own with the limited `search` API call:

```
data = es_production.search(index='i', body={"size": 1000, "query": {...}})
bulk(es_sandbox, data['hits']['hits'])
```

**Comment by Battleroid** [comment]
Ah ok. Thank you.

On April 17, 2017 6:22:57 PM EDT, "Honza Král" <notifications@github.com> wrote:
>yes, the limit is being ignored because `reindex` uses `scan` search to
>get all the documents, you'd have to craft a query that only matches N
>documents in your index.
>
>But if you look into the implementation of `reindex` you see how easy
>it is, it is literally feeding search results into `bulk`, which you
>can do on your own with the limited `search` API call:
>
>```
>data = es_production.search(index='i', body={"size": 1000, "query":
>{...}})
>bulk(es_sandbox, data['hits']['hits'])
>```

-- 
Casey Weed
