### ISSUE TITLE
OpenTracing support

### ISSUE THREAD

**Issue by carlosalberto** [elastic/elasticsearch-py#566]
Was wondering about any chance to natively support OpenTracing (http://opentracing.io/), which is a technology to do distributed tracing, with support for many languages and ongoing efforts to support many libraries (like SQLAlchemy, or Django).

If that, I could probably create a patch, given the instructions/discussion - else, in order to trace the execution of requests done to the actual ES server, I'd like to create a patch to either have event handling (say, "perform_request" event). If this sounds more feasible, let me know as well ;)

(Right now, the way I found to do this was to create subclass `Transport`, override `perform_request`, do a custom tracing (and calculating the time the request took), and then simply call the base implementation).

Any feedback is welcome. Thanks!

**Comment by HonzaKral** [comment]
Hi, the solution you found makes sense, you might want to override the `Connection`'s `perform_request` though to eliminate outliers that cause retries (I can see arguments both ways, not sure which I'd prefer).

This is, however, something that doesn't make much sense the the library itself, especially when this can very easily live "outside" - I'd recommend just creating a package that will provide a custom `Transport` class and wraps the client library.

Thanks for bringing this up, if you decide to create such package it would be great to leave a comment here for people looking for it.

**Comment by carlosalberto** [comment]
Great, will take the feedback into consideration and will come back to you (rather soon) ;)
