### ISSUE TITLE
Request from python client doesn't work as expected in ES cluster

### ISSUE THREAD

**Issue by tamilveeran** [elastic/elasticsearch-py#567]
Hi All,

We have a private ES cluster in one subnet, 2 data nodes (configured with private ips) and one client node (configured with public ip). Now from a python client in a different network I try to hit the ES cluster through the client node. 
But I get failure response priting the private IP of one of the datanode on ES cluster. 
According to the documentation the client node should sort and return the results. 
This is an issue right? When I hit the client node using REST client I get the correct results. 
Why the python es client does not do the same thing? What am I missing.

Please help.

**Comment by HonzaKral** [comment]
Hi @tamilveeran, did you, by any chance, enable sniffing for the python client? That would cause it to try and connect to the private IPs. Could you please share the code you used to create the python client?

I also have to tell you that having a node available on a public IP is very dangerous and cannot be advised. Whether it is a client node or any other doesn't matter in this case.

**Comment by mmlovely** [comment]
Yes,@HonzaKral is right

**Comment by HonzaKral** [comment]
Thanks, closing this issue.

**Comment by tamilveeran** [comment]
Sniffing was enabled. Thank you!
