### ISSUE TITLE
'+' character in document id replaced with space character in low-level client index operation

### ISSUE THREAD

**Issue by bdecotes-pl** [elastic/elasticsearch-py#570]
Indexing a document into elasticsearch using the low-level client as such:
```
es_client = elasticsearch.Elasticsearch([ES_URL])
es_client.index(
    index=index, doc_type=doc_type,
    id='2017-04-14T16:04:45.000000+0000',
    body=body
)
```
results in an indexed document where `_id="2017-04-14T16:04:45.000000 0000"`. The `+` character is being replaced with a space.

Using the bulk helper performs the indexing correctly:
```
from elasticsearch.helpers import bulk
action = [{
    '_id': '2017-04-14T16:04:45.000000+0000',
    '_index': index,
    '_type': doc_type,
    '_source': body       
}]
bulk(es_client, action)
```

Version: `elasticsearch==5.3.0`

**Comment by untergeek** [comment]
I'm guessing you are connecting to an Elastic Cloud instance, because I reported this just yesterday to them.

At the end of the day, elasticsearch-py _is_ sending properly URL-encoded symbols, including the `+`.  This is what is in my ticket with Cloud:

>When trying to send:
>```
>PUT /<datemath-{now/d+1d}>
>```
>It gets properly URL encoded by the python client (and/or urllib3):
>```
>2017-04-13 10:09:53,559 DEBUG     urllib3.connectionpool          _make_request:395  https://cb75052bb2dca95f5461337874a1a154.us-west-2.aws.found.io:9243 "PUT /%3Cdatemath-%7Bnow%2Fd%2B1d%7D%3E HTTP/1.1" 400 203
>2017-04-13 10:09:53,559 WARNING            elasticsearch       log_request_fail:96   PUT https://cb75052bb2dca95f5461337874a1a154.us-west-2.aws.found.io:9243/%3Cdatemath-%7Bnow%2Fd%2B1d%7D%3E [status:400 request:0.053s]
>```
>
>The Python client reports the error:
>```
>2017-04-13 10:09:53,559 DEBUG              elasticsearch       log_request_fail:109  < {"error":{"root_cause":[{"type":"parse_exception","reason":"operator not supported for date math [/d 1d]"}],"type":"parse_exception","reason":"operator not supported for date math [/d 1d]"},"status":400}
>```
>
>This is missing the plus symbol, which is `%2B`, but the `%2B` is in the proper place in the url encoded string that was sent.

**Comment by untergeek** [comment]
At any rate, it's clear that it _is_ properly URL encoding the `+` as `%2B`, but something on Cloud's end is messing with it.  The best guess they gave me was that it was their proxy.  They'll look into it.

If you confirm that you are using Cloud, I will attach this issue to theirs.

**Comment by HonzaKral** [comment]
Thanks @untergeek!

I can indeed confirm that it is not an issue when talking directly to elasticsearch:
```
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.index(index='i+i', doc_type='t', id='1+2', body={}, refresh=True)
print(es.search(index='i+i')['hits']['hits'][0]['_id'])
```

**Comment by bdecotes-pl** [comment]
Interesting! I am not using the cloud service, but the cluster I'm connecting to is an older version of elasticsearch (5.0.0). Perhaps that's where this issue lies for me.

**Comment by untergeek** [comment]
Do you have a load balancer or a proxy in front of it?

**Comment by bdecotes-pl** [comment]
Yes, there is an nginx proxy in front of the cluster.

**Comment by untergeek** [comment]
I just tried this on 5.0.0:
```
Python 2.7.13 (default, Mar 19 2017, 12:50:26)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from elasticsearch import Elasticsearch
>>> es = Elasticsearch()
>>> es.info()
{u'cluster_name': u'untergeek-test', u'cluster_uuid': u'KAQRxVsjSfGNrhUr9xBfrA', u'version': {u'lucene_version': u'6.2.0', u'build_hash': u'253032b', u'build_snapshot': False, u'number': u'5.0.0', u'build_date': u'2016-10-26T04:37:51.531Z'}, u'name': u'uHf7YjI', u'tagline': u'You Know, for Search'}
>>>
>>> es.index(index='i+i', doc_type='t', id='1+2', body={}, refresh=True)
{u'_type': u't', u'_index': u'i+i', u'forced_refresh': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 2}, u'_version': 1, u'created': True, u'result': u'created', u'_id': u'1+2'}
>>>
>>> print(es.search(index='i+i')['hits']['hits'][0]['_id'])
1+2
```

**Comment by untergeek** [comment]
So I'm guessing it's the proxy.

**Comment by bdecotes-pl** [comment]
Thank you so much for the rapid responses! I agree that it looks like the proxy is the culprit here.
