### ISSUE TITLE
Please put back client.indices.get_aliases

### ISSUE THREAD

**Issue by seperman** [elastic/elasticsearch-py#573]
`client.indices.get_aliases` is removed from the v5 branch of this library. It is still there in ES5 API.
Not sure why it is removed in this library but `get_aliases` is indeed useful and I have used it in the v2 before.

**Comment by HonzaKral** [comment]
The `get_aliases` API is no longer supported by elasticsearch, please use `get_alias` instead as per the documentation - https://www.elastic.co/guide/en/elasticsearch/reference/5.3/indices-aliases.html

Thank you!
