### ISSUE TITLE
'prepared_request' referenced before assignment

### ISSUE THREAD

**Issue by uoo** [elastic/elasticsearch-py#577]
There's a try/except block in connection/http_requests.py in perform_request() that calls log_request_fail() with (among other things) prepared_request, which is assigned in the try block.  However, if the preceding Request() call fails for any reason (authentication error is one possibility), prepared_request isn't initialized and it bombs with a stack trace.  Perhaps use "url" instead of "prepared_request.path_url"?

**Comment by HonzaKral** [comment]
This is no longer the case since c318f7fa63b94c3c126ed192bc09e792a6f6da91

Thanks for the report, this new code will be released soon.
