### ISSUE TITLE
indices.create() calls doesn't stop if index settings not parsable

### ISSUE THREAD

**Issue by uludag** [elastic/elasticsearch-py#582]
e.g. if I make the following calls for an Elasticsearch-2 server, the new index created is unhealthy and later my _index()_ calls return with _unavailable_shards_exception_, if I make the same calls for an Elasticsearch-5 server, I do not get any errors unless if I save and print the return value of the indices.create() call, and the new index is created with ignoring whole settings, i.e including the _refresh_interval_ setting in this example

```python
    indxcfg = {"settings": {
        "index.number_of_replicas": 0, "index.refresh_interval": 360}}
    es.indices.create(index=index, params={"timeout": "10s"},
                      ignore=400, wait_for_active_shards=1, body=indxcfg)
    #es.indices.put_settings(index=index, body=indxcfg)
```
If I move the settings to an _indices.put_settings()_ call I nicely get the following error and I'm able to understand what I'm missing

> can't process the settings: [[index.refresh_interval] - Failed to parse setting [index.refresh_interval] with value [360] as a time value: unit is missing or unrecognized]

I'm using elasticsearch-py-5.3.0
I understand that you may not want to change how the indices.create() calls behave
--mahmut

**Comment by HonzaKral** [comment]
You are explicitly silencing errors when saying `ignore=400`, in that case we cannot guarantee proper behavior. If you remove that call you will get an exception informing you about what's going wrong.

Hope this helps.

**Comment by uludag** [comment]
Thanks Honza.
I forgat that I was using the ignore option. I have repeated my test case after removing the ignore option. My indices.create() call for Elasticsearch-5 now returns the parser error however the same call for Elasticsearch-2 doesn't return an error or exception.
--mahmut

**Comment by HonzaKral** [comment]
Unfortunately checking the content of the body is out of scope for this client since it is very complicated and highly dependent on version. Even elasticsearch started checking everything in `5.x` as you can see.

For now I am afraid the only option is to rely on tests for `2.x` to verify proper behavior and upgrade to the more stable `5.x` as soon as possible.
