### ISSUE TITLE
problems working with snapshots

### ISSUE THREAD

**Issue by nfplatzke** [elastic/elasticsearch-py#583]
The snapshot status method only reports the status of snapshots being created. In order to see the state of a snapshot being deleted you need to make calls to the delete method and catch/inspect the exception. I'd like to see a similar method to status for getting the status of deletes as well as creates. This is particularly problematic if you are scripting cleanup operations since only one delete can run at a time. It leads to some very ugly code where you are forced to catch exceptions for successful calls or to get a status.

**Comment by nfplatzke** [comment]
Looking at this a bit more, It seems this is caused by the fact that the delete action attempts to stay connected until the operation finishes. Unlike the create method, which by default disconnects immediately unless the wait_for_completion is set to True. It would be nice to have this same behavior for the delete method.

**Comment by HonzaKral** [comment]
I understand your problem but unfortunately there is nothing we can do here as that is the behavior of elasticsearch itself. `elasticsearch-py` only provides a convenient and safe way to interact with it from python but it doesn't alter or add on top of any of the APIs.
