### ISSUE TITLE
`parallel_bulk` silently swallows non-Transport errors

### ISSUE THREAD

**Issue by ahmadia** [elastic/elasticsearch-py#584]
Simple example:

```
def foo(): yield {'stuff': 'breaks'}; raise ValueError(); yield {'stuff': 'broken'}
list(streaming_bulk(es, foo())) # raises ValueError
list(parallel_bulk(es, foo())) # returns [] 
```

Discussion:

I'm having a difficult time figuring out how to reproduce the error, but I'm guessing it's in the handling of the parallel thread pool exceptions.

**Comment by GlenRSmith** [comment]
@ahmadia Have you had any further luck trying to reproduce this?

**Comment by ahmadia** [comment]
No, we explicitly chunked the code to feed non-iterators in to `parallel_bulk` and moved on :)

**Comment by ClonedOne** [comment]
Having the same problem. 

I may be wrong but it seems to me that the exceptions in the generator function is captured and suppressed by a `try: ... finally:...` statement [here](https://github.com/elastic/elasticsearch-py/blob/f8dbb1168d21c7ade126b027b31cd1ac0241a23a/elasticsearch/helpers/__init__.py#L303).

**Comment by fxdgear** [comment]
unable to reproduce so I'm going to close this issue. If you come up with more information later please feel free to re-open and provide any additional information. 

Thanks

**Comment by lsyarn** [comment]
@fxdgear 
> **unable to reproduce** so I'm going to close this issue. If you come up with more information later please feel free to re-open and provide any additional information.

You can pass a wrong kwargs to parallel_bulk for reproduce this bug.
```
def my_acitons():
    for i in range(10):
        yield "foo"
parallel_bulk(myclient, foo(), wrong_kwargs="wrong" )
```
This may due to the code in `_process_bulk_chunk` funciton, line 96 `except TransportError as e:`
https://github.com/elastic/elasticsearch-py/blob/7751fede5a4733130e210b62ab1f99ab9763c9c7/elasticsearch/helpers/__init__.py#L86
