### ISSUE TITLE
InvalidGitRepositoryError(epath)

### ISSUE THREAD

**Issue by SunnyxBd** [elastic/elasticsearch-py#585]
Heyy, I'm new to coding and I'd appreciate some help here please.
When I run "**python load.py**" it generates this error ```
" File "/usr/local/lib/python2.7/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: "
```
I'm using python 2.7 as you can tell with the error and ES 5.4.

Thank for your help! :)

**Comment by HonzaKral** [comment]
Hey @SunnyxBd, welcome to coding! Sorry for the delay in replying. It looks like you tried to run this from outside of a `git` repository. How did you get the `load.py` file? Di you clone this repo and then ran it from there?

**Comment by GlenRSmith** [comment]
@SunnyxBd Going to assume you sorted this out.
