### ISSUE TITLE
Why can I not specify 'https' for an SSL connection?

### ISSUE THREAD

**Issue by jthoni** [elastic/elasticsearch-py#586]
Why am I not able to pass 'https' scheme on through to the connection of the Elasticsearch client? Here is the definition of my host:

	{"use_ssl": True, "host": "[my server].cloudapp.net", "port": "443", "scheme": "https", "transport_schema": "https"}

From the [documentation][1]:

	kwargs – any additional arguments will be passed on to the Transport class and, subsequently, to the Connection instances.

I would assume that the scheme and/or transport_schema would be forwarded on through.

I create the client as:

	client = Elasticsearch(hosts=[self.host], timeout=80, use_ssl=True, scheme="https", verify_certs=True, client_cert=cert_file_path, client_key=key_file_path)

When I create the client, I get:

	ERROR  Exception encountered.  Detailed info: ImproperlyConfigured('Scheme specified in connection (https) is not the same as the connection class (Urllib3HttpConnection) specifies (http).',)

This is happening in transport.py in _create_connection():

            if 'scheme' in host and host['scheme'] != self.connection_class.transport_schema:

                raise ImproperlyConfigured(

                    'Scheme specified in connection (%s) is not the same as the connection class (%s) specifies (%s).' % (

                        host['scheme'], self.connection_class.__name__, self.connection_class.transport_schema

                ))

When I break here, I can see that:

self.kwargs['transport_schema'] = 'https'

but:

self.connection_class.transport_schema = 'http'

I would have thought that the kwarg would have been forwarded on to the connection_class.  I manually set the transport_schema to 'https' and this allows me to get past this error.

If this is not the way to set it, then how do I specify https?

**Comment by HonzaKral** [comment]
just use `use_ssl=True` as you are and do not specify `schema` as that is something else, a leftover from time where elasticsearch supported different transport protocols like `thrift`.

Thanks for bringing this to my attention, I should remove the scheme checking.

**Comment by HonzaKral** [comment]
this should now be fixed in master via d336c571b913720cb42e3c69229f6fa7a6371dfb

thanks for the report!
