### ISSUE TITLE
msearch doesn't works

### ISSUE THREAD

**Issue by mexekanez** [elastic/elasticsearch-py#59]
trying with 
es = elasticsearch.Elasticsearch()
es.msearch(body=[{"query" : {"match_all" : {}}}],index=['tvshows'],doc_type=['tvshows'])

and getting error:
TransportError(500, u'ActionRequestValidationException[Validation Failed: 1: no requests added;]')

Could you please point me, what I doing wrong, or this is an issue?

**Comment by rparkhunovsky** [comment]
So, where is the helper for msearch?

**Comment by mexekanez** [comment]
@rparkhunovsky in docs

**Comment by rparkhunovsky** [comment]
@mexekanez could you please point me to msearch helper in ther docs page: http://elasticsearch-py.readthedocs.org/en/latest/helpers.html or to whereever you saw that?
Thanks.

**Comment by HonzaKral** [comment]
There is currently no helper unfortunately, you have to construct the request yourself using the raw API (0), which also means presenting the body in a proper form - a list of dicts where first one is the metadata line and the second the query (1).

Hope this helps

0 - http://elasticsearch-py.readthedocs.org/en/latest/api.html#elasticsearch.Elasticsearch.msearch
1 - https://github.com/elastic/elasticsearch-py/issues/59#issuecomment-37099911

**Comment by revelc33** [comment]
@HonzaKral 
The syntaxis it is not correct on your comment .  Wich kind of object is body ? a list, a string? Can you please clarify this?

Thanks !
> That would look like:
> 
> ```
> es.msearch(body=[
>   {"index": "tvshows", "type": "tvshows"},
>   {"query": {"match_all": {}}}
>   {"index": "tvshows", "type": "tvseries"},
>   {"query": {"match_all": {}}}
> ])
> ```
> So just 1-1 mapping to http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-multi-search.html
> 
> I am closing this ticket but I will give some thought to creating a helper like we did for bulk for this exact version - it's confusing. Thanks

**Comment by revelc33** [comment]
ok i think i have it. You forgot some comas.

es.msearch(body=[
  {"index": "tvshows", "type": "tvshows"},
  {"query": {"match_all": {}}},
  {"index": "tvshows", "type": "tvseries"},
  {"query": {"match_all": {}}},
])
