### ISSUE TITLE
Update document counters

### ISSUE THREAD

**Issue by adarshlx** [elastic/elasticsearch-py#595]
I am fairly new to elastic and am busting my head to solve this particular problem.

I am inserting the documents of the following format into elasticsearch.
```
_json = {
 'title' : 'This is the title',
 'text' : 'This is the text',
 'counter' : 1
}

```

(the 'id' of the documents is the 'title' field).

There are multiple documents with the same 'title'(id field). I want to increment the counter when a document with the same title is being inserted again into the index.
I have already tried using the following piece of code however it does not work for some reason and I cannot seem to find the reason as to why.

```
upscript = {
    'script': {
        'inline': 'ctx._source.counter += 1'
    }
    'doc': _json,
    'doc_upsert': True
}
es.index(index='test', doc_type='test1', id=_json['title'], body=upscript).
```

-Regards,
Alex

**Comment by HonzaKral** [comment]
use `es.update` API instead of `es.index`. `es.index` is only used for inserting (whether new or overwriting existing) whole documents.

Hope this helps,
Honza
