### ISSUE TITLE
How to apply `filter_path` when using `scroll` API?

### ISSUE THREAD

**Issue by Josca** [elastic/elasticsearch-py#599]
I have documents of type `page` with two fields: `url` and `content`. I want to search in both `url` and `content` values but I want to get only `url` in my results. It can be done using `filter_path` param when using `search` API. But I need to use `scroll` API to get bigger number of results. But result of `scroll` API contains `content` values too.

How can I force `scroll` API to return required fields only?
Thank you.

**Comment by HonzaKral** [comment]
For this I woulnd't recommend `filter_path` but instead use source filtering (0):
```python
from elasticsearch import Elasticsearch, helpers
helpers.scan(es, index='my-index', query={'_source': ['url']})
```

Hope this helps

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html

**Comment by Josca** [comment]
Oh, sorry, I was wrong. I can use `filter_path` with no problem when using `scroll` API. Why you recommend to use scan instead of search?

**Comment by sand33p-23** [comment]
@Josca how u used filter_path with scroll API?
im getting the empty response when im using the filter_path with scroll API.

**Comment by HonzaKral** [comment]
`filter_path` is a bit dangerous with `scroll` or `scan` because you can accidentally strip out parts of the response that you need for it to work. That is why I recommend source filtering instead which will just let you control which fields you want to get back without doing potentially harmful things.

**Comment by sand33p-23** [comment]
@HonzaKral thanks, using the source filtering i got the desired result that i was looking for.

**Comment by sand33p-23** [comment]
@HonzaKral i am facing one more problem while using source filtering, i cant get the value in nested source, using filter_path im able to do that.
