### ISSUE TITLE
Set `application/x-ndjson` content type on bulk requests

### ISSUE THREAD

**Issue by jmcarp** [elastic/elasticsearch-py#609]
As of elastic 5.x, requests to `/_bulk` should set `Content-Type` to `application/x-ndjson`. If not, elastic logs a warning. It looks like this library defaults to `application/json`. To fix, I'm thinking we should accept an optional dict of headers at `https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/connection/http_urllib3.py#L94`. If that sounds reasonable, I'd be happy to submit a patch.

cc @cnelson @wjwoodson

**Comment by HonzaKral** [comment]
A patch would be most welcome. I think the proper way to implement this would be very similar to how we handle `ignore` and `request_timeout` parameters in `Transport`.

Let me know if there is anything I can help you with.
