### ISSUE TITLE
`bulk_update` throws BulkIndexError instead of returning failures

### ISSUE THREAD

**Issue by asldevi** [elastic/elasticsearch-py#610]
when we call `bulk_update`, let's say with some missing documents, it throws `elasticsearch.helpers.BulkIndexError` with the failing docs, despite of the fact that it does complete the action. Instead it should return a tuple `(number_of_successfully_updated_docs, list_of_failures)` as the ES server does.

**Comment by HonzaKral** [comment]
Hi, there is no such api called `bulk_update`. If you mean one of the bulk helpers than, if you don't want an exception thrown, just specify `raise_on_error=False`.
