### ISSUE TITLE
Use autogenerating IDs for documents

### ISSUE THREAD

**Issue by soopanova** [elastic/elasticsearch-py#615]
In the Elastic API they state that you can create a document in an index with automatic id generation. Can this be replicated in the module. Currently you must provide an ID when creating a new document.

**Comment by HonzaKral** [comment]
You don't have to provide an `id` when creating a new document:
```
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.index(index='i', doc_type='t', body={})
```

**Comment by soopanova** [comment]
This is not true for the es.create. If no id is given an exception is thrown. Is index the preferred method of document creation?

**Comment by HonzaKral** [comment]
That is true - see my answer in https://github.com/elastic/elasticsearch-py/issues/516

Thanks!
