### ISSUE TITLE
Should the Elasticsearch() client be shared by multiple processes?

### ISSUE THREAD

**Issue by dvaldivia** [elastic/elasticsearch-py#616]
Hi, I'm trying to figure out wether I should instantiate my ES client once and re-use it as many times as possible or should I instantiate the ES client for every request/session I get?

It's not very clear, I've seen in the documentation that there's an underlying `connection pool` from urllib3, and also an option to not use it.

my use case is in `django` I usually create a new client and perform multiple operations on it, but I'm wondering if I should open the connection once and share it across all request, is there a reconnect mechanism?

thanks

**Comment by HonzaKral** [comment]
Definitely reuse the single instance. It is, however, not recommended to share across processes. 

In Django's case definitely just create a single instance and keep using it.

**Comment by vietvudanh** [comment]
You might consider put this in the document, as I (and might be someone else too) have been searching for many pages for the best practice. I am using for Django too.
