### ISSUE TITLE
Bulk Helper Error([('SSL routines', 'ssl3_write_pending', 'bad write retry')])

### ISSUE THREAD

**Issue by hadoopjax** [elastic/elasticsearch-py#620]
Hi,

I have a text document and am attempting to load it into an AWS Elasticsearch (v 5.3) index using Python 2.7. My workflow is pulling the document from S3, cleaning it up a bit (see code below) and pushing it to Elasticsearch. I receive the following error:

elasticsearch.exceptions.ConnectionError: ConnectionError([('SSL routines', 'ssl3_write_pending', 'bad write retry')]) caused by: Error([('SSL routines', 'ssl3_write_pending', 'bad write retry')])

My code is:

```import boto3
import re
from elasticsearch import Elasticsearch, helpers

# unicode mgmt
import sys
reload(sys)
sys.setdefaultencoding('utf8')

s3 = boto3.resource('s3')
bucket = s3.Bucket('somebucket')

# go get elasticsearch connection
from esconn import esconn
es = esconn()

def filing_text():
    for obj in bucket.objects.all():
        key = obj.key
        body = obj.get()['Body'].read()
        clean = body.strip()
        data_load = re.sub('\s+', ' ', clean)
        yield {'filing_type': 'afiletype', 'filing_text': data_load}

# bulk insert into index
helpers.bulk(es, filing_text(), index='myindex')
```
I haven't been able to track down the cause. I've tried separating the document I'm uploading into several pieces and it works fine as long as I don't do it all at once. I've played with varying settings for `chunk_size` and nothing seems to work if I try to do the whole document all at once. 

I pasted the document text [here](https://gist.github.com/hadoopjax/940131c8053d56c8e66e38e7773f7dc5#file-sample_text-txt)

**Comment by mihneadb** [comment]
I'm seeing something similar, what I can say re: chunksize is that it makes sense, since that triggers the SSL write retry, so the size is not the main issue. Another issue suggested sending `str` not `unicode`, but that's not the case either.

+1 to this.

**Comment by jminuscula** [comment]
The folks over urllib3 have been trying to debug this —It looks like the library is sending the wrong type of data. Please have a look at this thread:

https://github.com/shazow/urllib3/issues/855#issuecomment-317770680

**Comment by jminuscula** [comment]
After much debugging, my issue was caused by unicode headers generated in requests_aws4auth https://github.com/sam-washington/requests-aws4auth/issues/24

@hadoopjax could that be your issue too?

Anyway, sorry for the noise!

**Comment by fxdgear** [comment]
@hadoopjax Curious if you're still seeing issues.

**Comment by fxdgear** [comment]
@hadoopjax are you still having issues? Please see the comment from @jminuscula https://github.com/elastic/elasticsearch-py/issues/620#issuecomment-318311885

If you are still having issues please feel free to open a ticket.
