### ISSUE TITLE
AWS Lambda Python function using AWS Elasticsearch service

### ISSUE THREAD

**Issue by jgardezi** [elastic/elasticsearch-py#623]
Hi All,

I am having issues with connecting to AWS Elasticsearch when used in AWS Lambda function. When I run python function on local machine it works however when I put it in Lambda function it does not works. 

I have posted this issue here https://forums.aws.amazon.com/thread.jspa?messageID=794863&#794863 and 

This is code for python 2.7
```
    from elasticsearch import Elasticsearch, RequestsHttpConnection

    try:
        es = Elasticsearch(
            hosts=[{'host': config.es_host, 'port': 80, 'timeout': config.es_timeout}],
            connection_class=RequestsHttpConnection
        )
        print (es.info())
        # print(es.cluster.health())
        # print ('Connection info: '.format(es.info()))
    except ElasticsearchException as e:
        print(e)
        print('ElasticSearch client connection issue')
        raise e

    print('Loaded ES Client {}'.format(es))
```

The errors I am getting
```
GET http://search-xxxx-em7tzo65iadgddg33vtzcm.ap-reagon-2.es.amazonaws.com:80/ [status:N/A request:60.068s]
Traceback (most recent call last):
File "/var/task/elasticsearch/connection/http_requests.py", line 76, in perform_request
response = self.session.send(prepared_request, **send_kwargs)
File "/private/var/folders/31/9svbz77d1llbxdg2drcbrv0w0000gn/T/pip-build-mh_F6u/requests/requests/sessions.py", line 612, in send
File "/private/var/folders/31/9svbz77d1llbxdg2drcbrv0w0000gn/T/pip-build-mh_F6u/requests/requests/adapters.py", line 496, in send
ConnectTimeout: HTTPConnectionPool(host='search-xxxxxx-em7tzo65ipuzgkfzcq3xqvtzcm.ap-region-2.es.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbb1226e190>, 'Connection to search-xxxxxx-em7tzo65iadgddg33vtzcm.ap-region-2.es.amazonaws.com timed out. (connect timeout=30)')) 
```

and 

```
ConnectionTimeout caused by - ConnectTimeout(HTTPConnectionPool(host='search-xxxxx-xxxxxxx.ap-region-2.es.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbe05109b50>, 'Connection to search-xxxxx-xxxxxxx.ap-region-2.es.amazonaws.com timed out. (connect timeout=30)'))): ConnectionTimeout
Traceback (most recent call last):
File "/var/task/src/es_lambda.py", line 22, in handler
print (es.info())
File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
return func(*args, params=params, **kwargs)
File "/var/task/elasticsearch/client/__init__.py", line 220, in info
return self.transport.perform_request('GET', '/', params=params)
File "/var/task/elasticsearch/transport.py", line 312, in perform_request
status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
File "/var/task/elasticsearch/connection/http_requests.py", line 84, in perform_request
raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionTimeout: ConnectionTimeout caused by - ConnectTimeout(HTTPConnectionPool(host='search-xxxxx-xxxxxxx.ap-region-2.es.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbe05109b50>, 'Connection to search-xxxxxxxx-xxxxxxxxxxx.ap-region-2.es.amazonaws.com timed out. (connect timeout=30)')))
```

Kinds regards,
Javed Gardezi

**Comment by HonzaKral** [comment]
I am sorry, but all I am seeing is a connection timeout on the network, nothing to do with this library, it is either your configuration or an AWS-specific issue. Can you make this work just by using `urllib3` or `requests` directly? Does:
```
import requests
requests.get('http://%s/' % config.es_host).json()
```
work? If so please reopen the issue and we can have a look. Until then I am sorry but I really cannot help you since the issue is in the network connection itself.

**Comment by venkateshmora23** [comment]
Hi @HonzaKral , I was trying to connect to AWS elastic search from lambda . I tried requests but it throws me 403 error , Also tried the below. 

The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
}
Below is my code and I am running into the above issue. Please let me know if you find any issue with the code.

import boto3
import certifi
from elasticsearch import Elasticsearch, RequestsHttpConnection
from aws_requests_auth.aws_auth import AWSRequestsAuth
import json

session = boto3.session.Session()
print(session)
credentials = session.get_credentials().get_frozen_credentials()
print(credentials)
es_host = 'https://search-myelasticsearch-url:443'
awsauth = AWSRequestsAuth(
aws_access_key=credentials.access_key,
aws_secret_access_key=credentials.secret_key,
aws_host=es_host,
aws_region='us-east-1',
aws_service='es')

def getdata(event, context):
es_client = Elasticsearch('https://search-dcoupon-qhohs46gwoglizdeyp337u4ege.us-east-1.es.amazonaws.com:443',
connection_class=RequestsHttpConnection,
use_ssl = True,
verify_certs=True,
ca_certs=certifi.where(),
http_auth=awsauth)
es_info = es_client.info()
return es_info
@jgardezi were you able to resolve this ?

**Comment by fxdgear** [comment]
@venkateshmora23  it looks as if you're having errors connecting to your AWS ES instance. 

Can you `curl` and connect to ES using those same creds?
If you can successfully `curl` I'd attempt to then make a request using `requests` as Honza suggested previously. 

If you can't connect in either of those examples, maybe your creds are wrong. BUT a 403 means you're unauthorized to access something (ie your creds are correct but you've configured either a proxy or security layer to block access to a specific resource that you're trying to access)

**Comment by venkateshmora23** [comment]
@fxdgear Hey Nick, Thanks for your response. I did test it out using curl and I figured out it was an IAM issue after checking on ES. As I was checking out curl initially from the host which has access to ES, I thought roles were already set up.
