### ISSUE TITLE
Bump to 5.5?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-py#624]
Will this client be bumped to 5.5?

**Comment by tylerjharden** [comment]
Are you aware of any breaking changes between version 5.4 and 5.5 that this library will need to change around? I have yet to check thoroughly but intend to shortly.

**Comment by tomahawklin** [comment]
I'm having trouble connecting my python client to my elasticsearch 5.5 instance with x-pack plugin as I don't know how to set username and password info. Is there anything I can do using the current 5.4 version of es-py to tackle this?

**Comment by HonzaKral** [comment]
just supply `http_auth={'username': 'secret'}`

**Comment by fxdgear** [comment]
Going to be bumping to 6.x the 5.x client should be compat with 5.5 and 5.4. If you have any issues though please open a new issue.
