### ISSUE TITLE
Fast reindex via parallel scan (sliced scroll) and parallel_bulk

### ISSUE THREAD

**Issue by leobuskin** [elastic/elasticsearch-py#626]
I know that helpers.reindex is a deprecated API (and mostly all of us are using new ReIndex API), but it's still useful in some cases (like complex docs preprocessing in python). What's the best way to redirect sliced scans to parallel_bulk at this moment?

I mean smth like this:
```
    gens = []
    for id in range(slices):
        gens.append(scan(es, index=index, query={
            "slice": {
                "id": id,
                "max": slices
            }
        }))
```
And then somehow redirect to parallel_bulk pool. Is it possible?

**Comment by WisdomPill** [comment]
Sorry for being late. Why not use a painless script on the reindex api directly on elasticsearch?

Hope it helps

**Comment by HonzaKral** [comment]
@WisdomPill that is great solution, I was assuming we are talking reindex between different clusters where elasticsearch's `_reindex` cannot use `slices` when doing reindex from remote.

**Comment by leobuskin** [comment]
@HonzaKral, @WisdomPill there're still a lot of scenarios when you cannot use built-in scripting at all (and you need extra logic or extra dependencies involved into the reindex process), and reindex helper is a great solution (+ cross-cluster and so on). So, what do you think about possible implementation?

**Comment by fxdgear** [comment]
@leobuskin, first of all thanks for raising the issue. After having a think about this I decided that this is something that's better handled outside the client library and instead you can implement this functionality by using python's multi processing. 

You can spawn x processes and each are given a slice to operate on. 

I hope this helps/makes sense.
