### ISSUE TITLE
cat.py should allow for shards to utilize bytes.

### ISSUE THREAD

**Issue by jb4x** [elastic/elasticsearch-py#630]
I had a customer asking for support for bytes in shards within the python api. 

It looks like it would be pretty simple to alter here:

https://github.com/elastic/elasticsearch-py/blob/843ce9ee24b8a20a3dafdc8d845a54a38dc5f982/elasticsearch/client/cat.py#L204

**Comment by HonzaKral** [comment]
If `cat.shards` should accept byte we should also fix it in https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/cat.shards.json which is the authoritative source for API parameters (see https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/cat.fielddata.json#L19-L23 for example)

**Comment by GlenRSmith** [comment]
https://github.com/elastic/elasticsearch/pull/26952

**Comment by GlenRSmith** [comment]
Resolved by https://github.com/elastic/elasticsearch-py/pull/654
