### ISSUE TITLE
es.search Failed to establish a new connection: [Errno 111] Connection refused) 

### ISSUE THREAD

**Issue by dengyuning** [elastic/elasticsearch-py#631]
The elasticsearch service was running.But when I try to run the test.py, it stops working and gives me a error says that:
`GET http://localhost:9200/cs_2007/news/_search [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/var/www/myflask/ENV/lib/python3.4/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/var/www/myflask/ENV/lib/python3.4/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/var/www/myflask/ENV/lib/python3.4/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`
I'm confused because in test.py I just tried a very simple search function which should work:
`es = Elasticsearch(timeout=300)
i = IndicesClient(es)
q = {"query": {"match_phrase": { "content": {"query": query}}},"highlight":{"pre_tags": ["<b>"],"post_tags": ["<b>"],
"fields":{"content":{"fragment_size":20,"number_of_fragments":20}}}}
result = es.search(index=index_name,doc_type="news",body=q)
`

**Comment by dengyuning** [comment]
From the log file I got this `[2017-08-16T10:57:19,458][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead`.

**Comment by HonzaKral** [comment]
It looks like it cannot connect to the server, could you verify by some other means that the service is responding on `localhostL9200`? Ideally use `curl` or something similar: `curl localhost:9200`, does that work?

Thanks!

**Comment by dengyuning** [comment]
@HonzaKral Thanks. The service did not respond on localhostL9200. I cannot figure why and I reinstalled the Elasticsearch.
