### ISSUE TITLE
SSLError([Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by mgmacias95** [elastic/elasticsearch-py#632]
Hi, I am trying to connect to Elasticsearch. My problem is that I don't have a single CA Cert file (I have 3 files) and, because of that, I can't use `ca_certs` option in Elastic. I've decided to use `verity_certs=False`. This is my script:

```python
#!/usr/bin/env python

from elasticsearch import Elasticsearch

es = Elasticsearch(
    ["https://my_host_url:9200"],
    http_auth=("elastic", "my_passwd"),
    use_ssl=True,
    verify_certs=False,
)

print es.info()
```

I don't know why it shows me the following error in line `print es.info()`:

```
elasticsearch.exceptions.SSLError: ConnectionError([Errno 2] No such file or directory) caused by: SSLError([Errno 2] No such file or directory)
```

Another solution I'm trying is using `connection_class` parameter to call [`HTTPSConnection`](http://urllib3.readthedocs.io/en/latest/reference/index.html#urllib3.connection.VerifiedHTTPSConnection) class from `urllib3` and use `ca_cert_dir` parameter. This solution isn't working because `HTTPSConnection` class doesn't have the `perform_request` method defined.

**Comment by mgmacias95** [comment]
Hi again, I've tried changing `connection_class` to `RequestsHttpConnection` and now works ok with `verify_certs=False` 👍 .

**Comment by fxdgear** [comment]
@mgmacias95 If you have time could you please try the master branch? A PR for using SSLContext has just been merged which would allow you to create an SSLContext object which can accept a cert path or a cert file and you can control the verification of certs there as well. Should make instantiating your ES client a little easier.

**Comment by fxdgear** [comment]
I'm going to close this issue as I believe that SSLContext will also address the original issue. Please feel free to open a new ticket if you continue to have problems.
