### ISSUE TITLE
Outdated elasticsearch-py/docs/helpers.rst - Deprecated search type

### ISSUE THREAD

**Issue by pant03** [elastic/elasticsearch-py#633]
It seems the 5.X docs for the python module of elastic are outdated as they include the deprecated helper [scan](https://github.com/elastic/elasticsearch-py/blob/master/docs/helpers.rst#scan) which has been removed since [2.1.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/breaking_50_search_changes.html#_literal_search_type_scan_literal_removed)

**Comment by pant03** [comment]
As from 5.0 on the helper can only be used with the flag preserve_order=True to avoid: 
```
if not preserve_order:
        kwargs['search_type'] = 'scan'
```
Should the documentation be updated or the helper be remodeled

**Comment by HonzaKral** [comment]
The `search_type` has been removed but the functionality is still there (0) which is what the helper in `elasticsearch-py` `5.x` uses (1).

Hope this helps.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-scroll.html
1 - https://github.com/elastic/elasticsearch-py/blob/5.x/elasticsearch/helpers/__init__.py#L354-L356
