### ISSUE TITLE
SerializationError on subsequent calls to es.ping() and es.cluster.health()

### ISSUE THREAD

**Issue by tylerjharden** [elastic/elasticsearch-py#638]
We use the elasticsearch-py library with a `wait_until` function to ensure that our ES cluster is ready to go before performing some operations.

In some instances, such as accessing from multiple processes, or when there is a lot of activity back to back, something odd will happen ES side and it breaks the `es.cluster.health()` endpoint, where it won't receive the right headers or perhaps the response is truncated.

Logs:
<pre>
app_1            |   File "/app/sherlock_ui/utils/__init__.py", line 130, in wait_until
app_1            |     if predicate(*args, **kwargs):
app_1            |   File "/app/sherlock_ui/api/services/result/utils/__init__.py", line 91, in <lambda>
app_1            |     return wait_until(lambda: bool(es.ping() and es.cluster.health().get('status', '') in ['yellow', 'green']),
app_1            |   File "/usr/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
app_1            |     return func(*args, params=params, **kwargs)
app_1            |   File "/usr/lib/python3.6/site-packages/elasticsearch/client/cluster.py", line 33, in health
app_1            |     'health', index), params=params)
app_1            |   File "/usr/lib/python3.6/site-packages/elasticsearch/transport.py", line 342, in perform_request
app_1            |     data = self.deserializer.loads(data, headers.get('content-type'))
app_1            |   File "/usr/lib/python3.6/site-packages/elasticsearch/serializer.py", line 76, in loads
app_1            |     return deserializer.loads(s)
app_1            |   File "/usr/lib/python3.6/site-packages/elasticsearch/serializer.py", line 40, in loads
app_1            |     raise SerializationError(s, e)

elasticsearch.exceptions.SerializationError: ('HTTP/1.1 200 OK\r\ncontent-type: application/json; charset=UTF-8\r\ncontent-length: 392\r\n\r\n{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":26,"active_shards":26,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":26,"delayed_una', JSONDecodeError('Expecting value: line 1 column 1 (char 0)',))
</pre>

**Comment by HonzaKral** [comment]
Did you make sure to create a new connection from every process? It looks like your processes forked, inherited the file descriptors of the parent process and then signals got crossed where two different responses got squashed together causing a parse error.

**Comment by tylerjharden** [comment]
The processes were using Flask-ElasticSearch and were sharing a context upon forking. We resolved this by creating new contexts manually.

**Comment by deter3** [comment]
in case somebody has similar problem ,  I am sharing my problem and solution . 
when I used python multiprocess sharing one elasticsearch connection instance to read one big json file in chunk size , each chunk size as a generator ,  bulk index each generator by using total 16 processes , I got JSONDecodeError inside elasticsearch.exceptions.SerializationError .  After I have all processed  initiate their own   "elasticsearch connection instance" when start , the problem was gone .

**Comment by canw1nter** [comment]
> in case somebody has similar problem , I am sharing my problem and solution . when I used python multiprocess sharing one elasticsearch connection instance to read one big json file in chunk size , each chunk size as a generator , bulk index each generator by using total 16 processes , I got JSONDecodeError inside elasticsearch.exceptions.SerializationError . After I have all processed initiate their own "elasticsearch connection instance" when start , the problem was gone .

Hello, could you please tell me how to reproduce this issue?
