### ISSUE TITLE
TransportError, JsonParseException raised when trying to send mustache tags without quotes

### ISSUE THREAD

**Issue by mwangersjo** [elastic/elasticsearch-py#641]
After reading the two issues linked below I have gotten most of my code putting in search templates to work. However, it seems that it is not possible to put templates that use mustache tags that are not within quotes, such as {{#toJson}}. I have no problem adding them from e.g Kibana. 

An example:
`
template = {
    "template": { "query": {
        "terms": {
            "test": "@{{#toJson}}anArray{{/toJson}}@" }}}
}

client.put_template('test', json.dumps(template).replace('"@','').replace('@"',''))
`

Is there any smooth way to get this to work? Am I doing something wrong or is it a bug? 

Reference
https://github.com/elastic/elasticsearch-py/issues/639 
https://github.com/elastic/elasticsearch-py/issues/376

**Comment by HonzaKral** [comment]
In this case what is recommended to have the template as a string in python, so:
```python
template_body = {
  "template": '''{
    "query": {
      "terms": {
        "test": {{#toJson}}anArray{{/toJson}}
      }
    }
  }'''
}
```

Then it will get properly serialized as:
```json
{"template": "{\n    \"query\": {\n      \"terms\": {\n        \"test\": {{#toJson}}anArray{{/toJson}}\n      }\n    }\n  }"}
```

Which is what the API will accept.

Hope this helps!

**Comment by mwangersjo** [comment]
Oh, wow. Thanks @HonzaKral . I _am_ passing a string though, converting the dict using json.dumps() and passing that. Do you have any idea what might differ in your case and mine? You're using the docstring string literal, for any specific reason?

**Comment by HonzaKral** [comment]
@mwangersjo the problem is that if you pass it as json encoded string then elasticsearch will try to parse it as json when it is not valid. You'd have to escape all the relevant quotes etc. essentially replicating the logic that `json.dumps` can do for you by just putting in a string.

The main problem is that the `template` part is not valid json so you need to manually control the string yourself.
