### ISSUE TITLE
`indices.exists` is misleading with wildcard indices

### ISSUE THREAD

**Issue by robx** [elastic/elasticsearch-py#643]
Since `indices.exists(ix)` is more or less defined to be `HEAD /ix == 20x`, `indices.exists("*")` always returns true, even if there are no indices. I see two sensible things to do here, maybe there are others?

1. change `indices.exists` to return `len(GET /ix)` (at least if wildcards are involved)
2. document this behaviour explicitly (that using `indices.exists` with wildcard indices is not what you're likely to want, and recommend to call `len(indices.get())` instead

**Comment by HonzaKral** [comment]
Thanks for raising this issue, unfortunately this is out of our control, it is behavior of elasticsearch itself and must be resolved there. `elasticsearch-py` is just a wrapper around the elasticsearch rest APIs and as such cannot alter any functionality as that would lead to more surprises for users.

**Comment by robx** [comment]
Well you could certainly document this unexpected behaviour. That would have kept me from having to debug elasticsearch-py. I'm sure I'm not the only one running into this.
