### ISSUE TITLE
[feature request] max_retry support for parallel_bulk

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch-py#645]
[parallel_bulk](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L268) does not have max_retries parameter like other methods (streaming_bulk) does. 

Please kindly consider adding it.

**Comment by sethmlarson** [comment]
You can now configured your client to have a `max_retries` value via `.options(max_retries=...)` and pass that client to `parallel_bulk`. Going to close this one.
