### ISSUE TITLE
about query string 

### ISSUE THREAD

**Issue by linweijun** [elastic/elasticsearch-py#648]
My query involved special characters. When I used the browser to query, the results returned without problems，
the code：
http://127.0.0.1:9200/m/z/_search?q=ban:"D-86H"
 results count: 227
but when I used Python to process them, they returned to other situations
the code:
 client.search(index="m", doc_type="z", body={"query":{"match":{"ban":"\\"D-86H\\""}}})
results count: 3890

What should I do?

**Comment by HonzaKral** [comment]
`match` query is different than `query_string` query - it doesn't parse the query and assign special meaning to quotes, it just uses the whole text as an input to the analyzer used. The standard analyzer will, in this case, produce two tokens - `d` and `86h`. My assumption is that you have many documents that have `d` as a token in that field.

It looks like `ban` is some sort of identifier - in that case you should be using a `term` query on the `.keyword` subfield which will do an exact match:
```
 client.search(index="m", doc_type="z", body={"query":{"term":{"ban.keyword":"D-86H"}}})
```
