### ISSUE TITLE
No handlers could be found for logger "elasticsearch"

### ISSUE THREAD

**Issue by cynosureabu** [elastic/elasticsearch-py#67]
I might miss something apparent, I am trying to call
if es.indices.exists_type(resource_index, resource_type) :
      // delete my resource_type,

but always receive error No handlers could be found for logger "elasticsearch"
what does it  mean? how can I call exists_type correctly?
Thanks,
Chen

**Comment by filippog** [comment]
any news/activity on this? personally I think the module should follow `logging` recommendation to set a top level nullhandler and not mess with users' stdout

**Comment by HonzaKral** [comment]
@filippog I don't understand, we are adding the `NullHandler` for python versions 2.7 - 3.2 where this is an issue. For later versions we are following the recommendation stated explicitly in [0] (emphasis mine):

> If the using application does not use logging, and library code makes logging calls, then (as described in the previous section) events of severity WARNING and greater will be printed to sys.stderr. **This is regarded as the best default behaviour.**

Also nothing should be ever printed on stdout, the logging uses stderr. Or am I missing something?

Thanks

0 - https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

**Comment by filippog** [comment]
ah my bad! I was confused by the issue history, the null handler is indeed there in the last version -- all good, sorry for the noise :+1:
