### ISSUE TITLE
Releasing older versions for each separate Python package

### ISSUE THREAD

**Issue by curatorman** [elastic/elasticsearch-py#670]
Would it be possible to also publish older versions of each package, e.g. 2.0.0 of elasticsearch2? I say this because I want to use these separately named packages, but prefer a specific version and not the latest one because that's what we've been using and I wouldn't need to worry about trying to make my code compatible with the provided version. This is for both the elasticsearch2 and elasticsearch5 packages. (For reference, I'm in need of 2.0.0 and 5.1.1)

**Comment by HonzaKral** [comment]
I am sorry, but we cannot maintain that amount of different versions with the resources we have. The differences between different minor versions should be, however, backwards compatible, so upgrading should be a relatively easy task. I highly recommend that you upgrade to the last version which will allow you to use the versioned packages as well.
Hope this helps!
