### ISSUE TITLE
Question: content-type header [] not supported

### ISSUE THREAD

**Issue by akshaths** [elastic/elasticsearch-py#677]
Hi! I am getting the following error with ES6.0.0: 
`Error: elasticsearch.exceptions.TransportError: TransportError(406, u'Content-Type header [] is not supported')`

I know that this is because I am not explicitly setting the Content-Type to application/json, or something similar, but I have been unsuccessful in making this work. Can I have some guidance on how to set the header via python?

**Comment by HonzaKral** [comment]
Hi @akshaths, the `Content-Type` header is being set by `elasticsearch-py` itself, if you are using the proper version. What version are you using? Thanks

**Comment by akshaths** [comment]
Fixed it. I am running ES6.0.0 on a Heroku instance, and I'm not sure why this worked, but explicitly setting elasticsearch==6.0.0 (as opposed to elasticsearch>=6.0.0,<7.0.0) in requirements.txt solved the issue. but ran into another puzzling error: `Error: elasticsearch.exceptions.ImproperlyConfigured: Root certificates are missing for certificate validation. Either pass them in using the ca_certs parameter or install certifi to use it automatically.`

However, I am importing the certifi package and I've specified it in my requirements.txt file (certifi==2017.11.5). Is there something more I need to do to enable cert verification?

**Comment by akshaths** [comment]
Resolved with [#669](https://github.com/elastic/elasticsearch-py/issues/669).

**Comment by WakeDown-M** [comment]
may I ask you please where did you find that file "requirements.txt"? I have a same issue but I cannot find the settings. Thank you

**Comment by akshaths** [comment]
You must create it yourself to specify which versions you are using for specific packages

**Comment by WakeDown-M** [comment]
ok, but where to place it? Could you please i.e. send me the location where you have that file?

**Comment by HonzaKral** [comment]
@WakeDown-M `requirements.txt` is not specific to this library but instead a generic way some poeple use to install dependencies for their python projects, you can read more about it here (https://pip.pypa.io/en/stable/user_guide/#requirements-files) or see some other alternatives like pipenv (http://pipenv.readthedocs.io/en/latest/)
