### ISSUE TITLE
Question: How to run tests for 6.x

### ISSUE THREAD

**Issue by curatorman** [elastic/elasticsearch-py#678]
I was wondering how to run the tests locally for the master branch using the docker container method. The latest version for that right now seems to be 5.4. If this is not possible right now, are there any alternative methods to test?

**Comment by 3lnc** [comment]
If this is question on elasticsearch itself - check out https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

Elastic decided to move out of docker hub in favour of their own image registry.

**Comment by fxdgear** [comment]
@curatorman I need to build the new container for ES6. I will do that later today.

**Comment by fxdgear** [comment]
Just pushed a 6.0.0 image. 

Please note that the `start_elasticsearch.sh` script hasn't been modified to be version independent yet. 

So I'm sorry about that. 

This line:
https://github.com/elastic/elasticsearch-py/blob/master/test_elasticsearch/start_elasticsearch.sh#L9

Is not a valid argument in Elasticsearch 6. So if you're runngin 6 please delete it. locally. 

I'll submit a PR later (unless you want to) that checks if the version > 6  and it removes the scripts param, else leaves it there.
