### ISSUE TITLE
index() method appears to only always update/overwrite

### ISSUE THREAD

**Issue by uovobw** [elastic/elasticsearch-py#679]
Greetings, this might be a false positive due to my scarse knowledge of ES, but i am not being able to perform a simple insert.

To provide a bit of context i have a flask application that has an [after_request](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.after_request) that i use to send to elasticsearch a number of info about the request itself.

```
# import lines omitted for clarity
# i can create the elasticsearch client within or without the decorator function and the behaviour does not change
es = Elasticsearch(hosts=["my_host:myport"], ca_certs=certifi.where())
document = {
     "some" : "fields",
     "and": {
          "other": "nested",
     },
}
es.indices.create(index="my_index", ignore=400)
es.index(index="my_index", doc_type="same_doc_type", body=document)
```

as expected i get `created: True` on the first invokation.

After the first invokation (i can appear to only set a given doc_type once) each time I change the document structure deeply and try to insert again (ie: the next flask request) i get a `created: False` and the document is "overwritten" (even if i restart my service, that makes me think of an error in the way the request is sent) every time.

This sounds like a logical error in the way i am using the library, i have checked that the `create` function has recently been modified to force the use of an id and that the `index` one now can omit the id parameter to have one created on the server.

Finally, i am running python3 in a virtualenv, using elasticsearch on aws2 (version 5.5), and the library as specified in the readme, elasticsearch>=5.0.0,<6.0.0

Thanks for the attention

**Comment by uovobw** [comment]
adding some info as i debug more: when i query the created documents via kibana (those that are always updated) i get as many documents as the different `doc_type` values that i have specified, one for each. also, documents have the `_id` field set to the doc_type and `_type` field set to the index name.

**Comment by HonzaKral** [comment]
@uovobw that is weird, what is the name of your index? It looks like you have some weird configuration with `url_prefix` being set to something. How exactly are you instantiating the client?

Thanks!

**Comment by uovobw** [comment]
after some more debugging i found out that the url was being _printed_ as `host:port/` but in the client _creation_ the code was using `host/:port`, thus creating an index called `:port`, breaking everything.
sorry for the noise, closing this one.
