### ISSUE TITLE
Problems with bulk api

### ISSUE THREAD

**Issue by jonathan-zageno** [elastic/elasticsearch-py#683]
I'm trying to run the following with the python wrapper

```
from django.conf import settings
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk as elastic_bulk

action = {
    '_op_type': 'delete',
    '_index': settings.ELASTICSEARCH_INDEX,
    '_type': 'product',
    '_id': 112910
}

client = Elasticsearch('localhost:9200')
elastic_bulk(client, action)
```

The error that I get is 
```
TransportError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: type is missing;3: index is missing;4: type is missing;5: index is missing;6: type is missing;7: index is missing;8: type is missing;')
```

**Comment by HonzaKral** [comment]
The `bulk` api, and the helper, was designed to perform multiple actions at once, therefore it expects an iterable of actions, not just a single one. in your case the simplest fox would be to wrap the `action` dict in a list before passing it in: `elastic_bulk(client, [action])`

Hope this helps!

**Comment by jonathan-zageno** [comment]
Ah, thanks of course. Stupid mistake of mine!
