### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by kxxoling** [elastic/elasticsearch-py#696]
There's a typo here: https://github.com/elastic/elasticsearch-py/blob/8c13060c879bbe2cedac4a699a162fb9a9cb487f/elasticsearch/transport.py#L135

`crate` should be corrected to `create`.

**Comment by fxdgear** [comment]
@kxxoling can you please submit a PR? :)

**Comment by ao** [comment]
Created one for you ;) https://github.com/elastic/elasticsearch-py/pull/699

**Comment by fxdgear** [comment]
closeed via https://github.com/elastic/elasticsearch-py/pull/699
