### ISSUE TITLE
timeout arg in client.* should be request_timeout

### ISSUE THREAD

**Issue by royrusso** [elastic/elasticsearch-py#700]
In transport.py, you seem to be appending the timeout to the request, but are looking for "request_timeout" as an argument: https://github.com/elastic/elasticsearch-py/blob/43ddb3d56b159532b118d9c34ee00fea81bcc58f/elasticsearch/transport.py#L305

However, all of the client methods that call in to transport.perform_request, have in their documentation, to use "timeout" as the arg. Using "timeout" fails, but "request_timeout" works. I believe the simplest change is to update all of the method docs?

This is what is currently shown:
`        :arg timeout: Explicit operation timeout    `

**Comment by eranhirs** [comment]
`request_timeout` is a client timeout, as I understand it won't affect elasticsearch operations.
`timeout` is a parameter sent to elasticsearch search to stop the operation if not finished.

What I don't understand is why `timeout` is not working as expected, even if I set `timeout=1ms` the operation does not timeout.

**Comment by HonzaKral** [comment]
`:arg timeout:` is used when the `elasticsearch API accepts `timeout` as a parameter, it is an internal timeout of the operation and not related to the network timeout at all. For that use `request_timeout` or the global `timeout` (passed when constructing `Elasticsearch` instance - both of there parameters expect a number of seconds so `1ms` is not a valid value and should be `0.001` instead.

You can see the description here - https://elasticsearch-py.readthedocs.io/en/master/api.html#timeout

Hope this helps!
