### ISSUE TITLE
test_all_chunks_sent is flaky

### ISSUE THREAD

**Issue by felixonmars** [elastic/elasticsearch-py#701]
Tested with Python 2.7.14, elasticsearch-py 6.1.0. A simple retry passes the tests, so I assume it's slightly flaky:
```
======================================================================
FAIL: test_all_chunks_sent (test_elasticsearch.test_helpers.TestParallelBulk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/build/python-elasticsearch/src/elasticsearch-py-6.1.0-py2/test_elasticsearch/test_helpers.py", line 16, in test_all_chunks_sent
    self.assertEquals(50, _process_bulk_chunk.call_count)
AssertionError: 50 != 48

----------------------------------------------------------------------
Ran 106 tests in 21.736s

FAILED (SKIP=2, failures=1)
```

**Comment by silne30** [comment]
I have run this test several times but this particular test does not fail. I ran this using python setup.py test. Any other info that may be pertinent?

**Comment by felixonmars** [comment]
Hrm, the test seems to be very slightly flaky. I didn't yet find a way to reproduce it stably.

**Comment by fxdgear** [comment]
@felixonmars thanks for the issue, but just like @silne30 I can't find a way to reproduce the flaky-ness of this test. 

I'm going to close this now. But if you can find a way to reproduce the failure please re-open the ticket. 

Thank you
