### ISSUE TITLE
Support for search_after param?

### ISSUE THREAD

**Issue by jamesrwhite** [elastic/elasticsearch-py#705]
Am I missing something or does the python client not support the `search_after` param described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html)?

I can't find any reference to it on https://elasticsearch-py.readthedocs.io/en/master/, the only mention of pagination is using `scroll`.

**Comment by HonzaKral** [comment]
The `search_after` parameter is part of the `body` which `elasticsearch-py` doesn't control or limit 9it is just passed through) so you can pass it in as needed.

Hope this helps!

**Comment by jamesrwhite** [comment]
Oh ok, thanks.

Are `size` and `sort` not also part of the `body` yet the client seems to implement those as params?
