### ISSUE TITLE
Unit Test against Elastic Cloud and ECE

### ISSUE THREAD

**Issue by robgil** [elastic/elasticsearch-py#707]
ECE and Elastic Cloud both use Elastic's Proxy services. I've seen discrepancies in the behavior for EC and ECE and we should test for them.

**Comment by HonzaKral** [comment]
What kind of discrepancies? Is this really something that we can and should account for in the client? Sounds more like something that should be part of the EC/ECE tests. Thanks!

**Comment by HonzaKral** [comment]
This appears to be more an issue with EC/ECE than `elasticsearch-py` so I am closing this issue.
