### ISSUE TITLE
helpers._chunk_actions produces chunks bigger than max_chunk_bytes

### ISSUE THREAD

**Issue by etataurov** [elastic/elasticsearch-py#716]
Hello! Thanks for the library.

We started to get ocasional errors from Elasticsearch
```
org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
```
So I investigated and found an issue in `helpers._chunk_actions`
There are two cases

1. If `max_chunk_bytes` is pretty low, `_chunk_actions` will split actions one by one, but each chunk will be bigger than `max_chunk_bytes`. It's actually used in test https://github.com/elastic/elasticsearch-py/blob/64202273e02ab5f0b99271771d4e8143b3599c3e/test_elasticsearch/test_helpers.py#L35 Maybe it makes sense to raise a warning in this case. 
2. **Most important** `_chunk_actions` count characters instead of bytes to check for chunk size. If user passes actions with unicode values it is possible that output chunk size will exceed `max_chunk_bytes`. This test failes
```python
class TestChunkActions(TestCase):
    def setUp(self):
        super(TestChunkActions, self).setUp()
        self.actions = [({'index': {}}, {'some': u'€€€€€€€€', 'i': i}) for i in range(100)]

    def test_chunks_are_chopped_by_byte_size_properly(self):
        chunks = list(helpers._chunk_actions(self.actions, 100000, 90, JSONSerializer()))
        self.assertEquals(100, len(chunks))
        for chunk in chunks:
            chunk = u''.join(chunk)
            chunk = chunk if isinstance(chunk, str) else chunk.encode('utf-8')
            self.assertLessEqual(len(chunk), 90)
```
`_chunk_actions` should produce 100 chunks (each less than 90 bytes), but produces 50 chunks (each ~114 bytes)

**Comment by albertferras** [comment]
Can confirm I have the same issue
