### ISSUE TITLE
timestamp= parameter seems to have no effect

### ISSUE THREAD

**Issue by regulatre** [elastic/elasticsearch-py#717]
Regardless of the time I put in the timestamp= parameter or @timestamp field of the payload, when indexing a message, the timestamp that gets placed on that message always seems to be the timestamp of when the data was indexed, as opposed to the date of the value in the timestamp= field or @timestamp within the payload! 

This breaks queuing logic that may be indexing messages that built up during an outage for example. When the outage is restored and the queue is emptied, all messages from within the queue get indexed on top of each other in terms of the timestamp due to this bug.

**Comment by hatdropper1977** [comment]
FWIW, I know how to fix this using the [Elasticsearch DSL](https://github.com/elastic/elasticsearch-dsl-py) python client.  This may point you in the right direction.

You can extend the save method on DocType as follows:

```python
def save(self, ** kwargs):
        self.lines = len(self.body.split())
        self['@timestamp'] = datetime.now()
        return super(Article, self).save(** kwargs)
```

If you send to an existing logstash index, you may need to explicitly set the timestamp format, for example:

```python
def save(self, ** kwargs):
        self.lines = len(self.body.split())
        t = datetime.now()
        self['@timestamp'] = t.strftime('%Y-%m-%dT%H:%M:%S.%fZ')
        return super(Article, self).save(** kwargs)
```

More information [here](https://www.freshlex.com/add-timestamp-to-your-python-elasticsearch-dsl-model.html).

**Comment by HonzaKral** [comment]
I am sorry @regulatre, but I am having trouble understanding what you are doing. Elasticsearch doesn't alter your data, nor does `elasticsearch-py`. If you have a `@timestamp` field in the payload when indexing a document, that value will be used for the field's index and you can query by it.

I am not sure what you mean by `timestamp=` parameter, if you mean using the built-in `_timestamp` field (0) it has been deprecated in `2.0` and later removed.

Can you please share the code you are using? Thank you

btw @hatdropper1977, thank you so much for the sample code, there shouldn't ever be a need to call `strftime`, or `isoformat`, even when using an existing logstash index.

**Comment by regulatre** [comment]
@HonzaKral 

Indeed, I found my error after writing a test app to demonstrate what I was seeing. Apologies for the confusion.
