### ISSUE TITLE
search_after usage

### ISSUE THREAD

**Issue by muratungor** [elastic/elasticsearch-py#733]
Hello
how can I use search_after with this API ?
elastic documentation is here
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html
best regards
Murat

**Comment by fxdgear** [comment]
@muratungor When making a query against Elasticsearch all you need to do is construct the `body` in the same way you would if you were using any other search request in Elasticsearch. 


So in the example from the link to the docs you provided, the search request would like like this...

```
es.search(body={
    "size": 10,
    "query": {
        "match" : {
            "title" : "elasticsearch"
        }
    },
    "search_after": [1463538857, "654323"],
    "sort": [
        {"date": "asc"},
        {"_id": "desc"}
    ]
})
```

Please note that the `search_after` is included in the dictionary passed to the `body` of the `search` method.
