### ISSUE TITLE
search method "default_operator" option raises an exception

### ISSUE THREAD

**Issue by dtrizna** [elastic/elasticsearch-py#734]
Hi!

It looks that usage of "default_operator" in search method of ElasticSearch client produces a following exception:

> elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'request [/my_index/_search] contains unrecognized parameter: [default_operator]')

Without this option all works, of course with no necessary logics, using "OR" between boolean operands.
Code fragment:
`        search = es.search(
                index='my_index',
                _source=fields,
                request_timeout=600,
                size=5000,
                default_operator='AND',
                sort=['@timestamp'],
                body={
                "query": {
                 "bool": {
                    "filter": {
                        "term": {
                          "field": "value"
                        }
                      },
                      "must_not": {
                        "term": {
                          "field": "value",
                          "field": "value2"
                        }
                      }
                    }
                  }
                }
                )`

Accroding to https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.search it should work:

> default_operator – The default operator for query string query (AND or OR), default ‘OR’, valid choices are: ‘AND’, ‘OR’

Am I doing smth wrong or the query to ES indeed isn't created correctly?

pip package: 6.1.1
ES cluster: 5.4.0

Regards,
Dmitry

**Comment by fxdgear** [comment]
@dtrizna sorry for the late response. 

It's not very clear, and I apologize for that, but the `default_operator` only works for `query_string` queries. What that means is you need to use the `q` parameter as well in your `search()`. 

```
search = es.search( index='my_index', _source=fields, request_timeout=600, size=5000, default_operator='AND', q='some query string', sort=['@timestamp'], body={ "query": { "bool": { "filter": { "term": { "field": "value" } }, "must_not": { "term": { "field": "value", "field": "value2" } } } } } )
```

Documentation for [query string queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)
