### ISSUE TITLE
query_param decorator does not preserve signature

### ISSUE THREAD

**Issue by beniwohli** [elastic/elasticsearch-py#736]
The `query_param` decorator is used on pretty much all client methods. It uses `functools.wraps` to copy `__module__`, `__name__`, `__doc__` etc. Unfortunately, `wraps` does not preserve the signature of the wrapped function, so `inspect.getargspec()` and friends become pretty much useless (`inspect.signature()` works but only in Python 3.5+, and only because it cheats).

This makes it difficult for e.g. code completion in IDEs to work correctly. On a more egoistic note, it also makes it more difficult for things like Elastic APM to introspect the client 😊 

Preserving the signature is a bit less trivial than preserving `__doc__` etc, but there are a few utilities that could help: 

 * [`decorator.py`](https://github.com/micheles/decorator)
 * [boltons](https://github.com/mahmoud/boltons) (specifically `boltons.funcutils.wraps`)

There's also [wrapt](https://github.com/GrahamDumpleton/wrapt), but that might be a bit too heavy just to preserve the signature.

We could either add one of the two libraries as a dependency, or vendor them (they are both BSD).

**Comment by SN9NV** [comment]
I have the same question.

But why not just use `**kwargs`? There's already a docstring that explains possible parameters.
Removing `query_parmas` will fix the pylint errors and I think it's more pythonic to use `**kwargs` for additional parameters

**Comment by HonzaKral** [comment]
This would certainly be nice, but unfortunately it's not as easy as using a proper decorator tool - the interface of the methods (ability to do `es.search(q="hello")`) is not an interface of any actual method or function. It is, therefore, not a question of preserving it but actually manufacturing a custom one based on the list passed to `query_params`.

it is definitely doable, just a different problem.

**Comment by beniwohli** [comment]
Yes, totally. One of the two decorators could be a starting point (they
basically use the same approach of having a FunctionBuilder that builds a
wrapper with the correct signature). If y'all are OK with carrying a bit of
somewhat magic code unrelated to the core functionality in the codebase to
solve this problem, I'm happy to give it a shot and implement it.

**Comment by fxdgear** [comment]
@beniwohli if you wanna take a stab at it please feel free! :+1:
