### ISSUE TITLE
Issues with streaming_bulk when literally streaming

### ISSUE THREAD

**Issue by rohitgcs** [elastic/elasticsearch-py#737]
```
for success, info in streaming_bulk(es, launchConsumer(consumer), chunk_size=500, max_chunk_bytes=104857600):
                                if not success:
                                        print info
```
For streaming data, acts like just another bulk process.
When trying to insert data from a live stream, if the chunk doesn't fill up to 500, the actions aren't processed, and we're left with missing data.
That kind of defeats the purpose of having a streaming bulk api given that there's no real way for us to know if the data we get is in orders of 500 or 600.
eg: I got an inital load of 12804

With chunk size =500, I get 12500 ingested and 304 remaining.
With chunk size = 2, its too slow and isn't usable.

Is there something else here that we can use to push the remaining data through after a timeout or something? Happy to PR if I could get some guidance.

**Comment by fxdgear** [comment]
@rohitgcs thanks for raising the issue. You are not the first person to have this [request](https://github.com/elastic/elasticsearch-py/issues/480).

I'd like to avoid implementing any timers in the logic here.
What you can do is in your application is you can wrap your incoming stream in a while loop which controls the timeout. Please see the example provided [here](https://github.com/elastic/elasticsearch-py/issues/480#issuecomment-263854897)
