### ISSUE TITLE
Keep track which server holds which shards to lower number of hops ?

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch-py#738]
So when you do a query, the client will try to contact the right server using as few hops as possible ? Same when doing routing ? 

Makes sense ?

**Comment by fxdgear** [comment]
I'm not 100% sure I follow. 

The client does not keep track of cluster state. The master nodes will do that. When you send a query to ES it will get processed by the node who revived the request and then using  internal logic to ES it will route the request to the relevant shards and then return the data collected from each shard. Then it will collate the response and send it back to the client. 

I hope this helps

**Comment by ddorian** [comment]
I know the current state.

But would it make sense the client-layer to do that, thus reducing by 1(sometimes) the number of hops ? Assuming you're not using dedicated query nodes.

Cassandra,hbase,Solr etc do this on the client.

**Comment by fxdgear** [comment]
So this is not something that you want to be doing in the client with Elasticsearch. Unless you are always going to be querying on just one shard, every time. Elasticsearch will be sending the query to all the nodes anyway. 

Also, please note coming in ES 7 (experimental feature now in 6) is [Adaptive Replica Selection](http://nocf-www.elastic.co/guide/en/elasticsearch/reference/current/search.html#search-adaptive-replica) which will handle the routing of requests to the most optimal shards.

**Comment by ddorian** [comment]
It could still be activated on only 1-shard-requests. And for insert/update/delete which go to 1 shard.
But it's ok for now.
