### ISSUE TITLE
mapping

### ISSUE THREAD

**Issue by wflooney** [elastic/elasticsearch-py#743]
Hi
I am having some troubles with mappings.
I am creating a mapping for an index in the kibana console
similar to....
PUT edi_claim/_mapping/_doc
{	"properties":{
	"EDI_CLAIM":{
		"properties":{
			"EDI_TRANS_ID_CD":{"type": "keyword"},
      			"EDI_TRANS_SET_CTL_NUM":{"type":"keyword"},
      			"EDI_CLAIM_NUMBER":{"type":"keyword"},
       			"EDI_CLAIM_DATE":{"type":"date"},

but when i populate the index from the python elasticsearch library it seems to loose/redefine the mapping.

my indexing statement looks like...

res = es.index(index='edi_claim', doc_type='_doc', id=claimid, body=myjson)

specifically I have some nested datatypes in the mapping that seem to take when I do the PUT.  When I run my code and look at the index via GET /edi_claim/_mappings

the nested types no longer indicate nested.

Am I missing something ?

Thanks
Bill

**Comment by fxdgear** [comment]
@wflooney 

so i did a quick check in the kibana dev console: 

```
PUT edi_claim
{}

PUT edi_claim/_mapping/_doc
{
  "properties": {
    "EDI_CLAIM": {
      "properties": {
        "EDI_TRANS_ID_CD": {
          "type": "keyword"
        },
        "EDI_TRANS_SET_CTL_NUM": {
          "type": "keyword"
        },
        "EDI_CLAIM_NUMBER": {
          "type": "keyword"
        },
        "EDI_CLAIM_DATE": {
          "type": "date"
        }
      }
    }
  }
}

GET edi_claim/_mapping

PUT edi_claim/_doc/1
{
  "EDI_CLAIM": {
    "EDI_TRANS_ID_CD": "foobar",
    "EDI_CLAIM_NUMBER": "bazfoo"
  }
}

GET edi_claim/_doc/1
```
```json
{
  "_index": "edi_claim",
  "_type": "_doc",
  "_id": "1",
  "_version": 1,
  "found": true,
  "_source": {
    "EDI_CLAIM": {
      "EDI_TRANS_ID_CD": "foobar",
      "EDI_CLAIM_NUMBER": "bazfoo"
    }
  }
}
```

So it seems that things seem to be working as expected there. 

Then trying again in python

```
In [8]: es = Elasticsearch()

In [11]: myjson = {
    ...:     "EDI_CLAIM": {
    ...:       "EDI_TRANS_ID_CD": "foobar",
    ...:       "EDI_CLAIM_NUMBER": "bazfoo"
    ...:     }
    ...:   }
In [13]: claimid=2
In [14]: res = es.index(index='edi_claim', doc_type='doc', id=claimid, body=myjson)
In [18]: es.get(index='edi_claim', id=claimid)
Out[18]: 
{'_id': '2',
 '_index': 'edi_claim',
 '_source': {'EDI_CLAIM': {'EDI_CLAIM_NUMBER': 'bazfoo',
   'EDI_TRANS_ID_CD': 'foobar'}},
 '_type': 'doc',
 '_version': 1,
 'found': True}

In [20]: es.indices.get_mapping(index='edi_claim')
Out[20]: 
{'edi_claim': {'mappings': {'doc': {'properties': {'EDI_CLAIM': {'properties': {'EDI_CLAIM_NUMBER': {'fields': {'keyword': {'ignore_above': 256,
          'type': 'keyword'}},
        'type': 'text'},
       'EDI_TRANS_ID_CD': {'fields': {'keyword': {'ignore_above': 256,
          'type': 'keyword'}},
        'type': 'text'}}}}}}}}

```
> please note: that in my python example I didn't create the mapping beforehand, BUT you will note that the mapping that comesback from the index request is nested. 


I'm curious what `myjson` looks like then in your example. Maybe the document you're trying to index does not actually match the mapping you've defined.

**Comment by wflooney** [comment]
Nick

Thanks

I am checking on that to make sure.

I think there is a setting for strict compliance for the doc to the mapping.  I'm going to try that and look for exception.

 Will post result



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by fxdgear** [comment]
@wflooney I think what you're wanting to look at is: https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html

```
PUT my_index
{
  "mappings": {
    "_doc": {
      "dynamic": (true | false |  strict),  <<<<
      "properties": {
        "user": { 
          ...
  }
}```

**Comment by fxdgear** [comment]
I'm going to close due to lack of activity. 

@wflooney if you feel like there might be an issue with the python lib please feel free to re-open with more information.
