### ISSUE TITLE
put_template TransportError(400, 'illegal_argument_exception'

### ISSUE THREAD

**Issue by ehf5307** [elastic/elasticsearch-py#745]
attempting to use put_template to create a template in ES.
ES is running on localhost:9200

```
es = Elasticsearch()
resp = es.put_template(id=template_name, body=body)
```

template_name has the string name for the template and body contains the JSON for creating the template (note, I've successfully created this template before using CURL, the template currently does not exist).

The error is:
`elasticsearch.exceptions.RequestError: TransportError(400, 'invalid_index_name_exception', "Invalid index name [_search], must not start with '_', '-', or '+'")`

But at the beginning of the error I can see:
`PUT http://localhost:9200/_search/template/events [status:400 request:0.018s]`

Why is it attempting to create the template by PUTing to the _search endpoint and not the _template endpoint?

Did I miss something or is this broken?

**Comment by fxdgear** [comment]
@ehf5307 Oh no! 

You found a bug :( I'm sorry about this. 

https://github.com/elastic/elasticsearch-py/blob/32239539f9c1f502c1506977f7a19d6bef4ccbfd/elasticsearch/client/__init__.py#L1293-L1305

Looking at the code here, the url being generated is going to `_search` :(

I will fix shortly I'm sorry about this.

**Comment by fxdgear** [comment]
@ehf5307 my bad I jumped the gun here. 

i noticed you're trying to create an index template by using the search template method. 

There's a sublt difference here. 

1. [Search Template](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html)

```python
es = Elasticsearch()
resp = es.put_template(id=template_name, body=body)
```

2. [Index Template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html)

```python
es = Elasticsearch()
resp = es.indices.put_template(name=template_name, body=body)
```
