### ISSUE TITLE
async and pycurl for elasticsearch-py

### ISSUE THREAD

**Issue by fbacchella** [elastic/elasticsearch-py#751]
I have written two extensions to elasticsearch-py.

The first one is a AsyncTransport  (https://github.com/fbacchella/escmd/blob/master/eslib/asynctransport.py) that extends Transport to allows asynchronous coding in python.

The second is a pycurl connection (https://github.com/fbacchella/escmd/blob/master/eslib/pycurlconnection.py) that can also be used asynchronously.

Please feel free to take any idea or code you want in it.

**Comment by fxdgear** [comment]
Thanks @fbacchella good stuff there. 

I'm not sure if you've seen the async library? https://github.com/elastic/elasticsearch-py-async

If not please check it out. Also feel free to contribute to that library!

Thanks
