### ISSUE TITLE
Index and search Japanese content using es.index()

### ISSUE THREAD

**Issue by abhinavmishra590** [elastic/elasticsearch-py#755]
I am trying to **index** data which is in **Japanese** language. I have already installed the **kuromoji** plugin but my code is not working properly:

```
from elasticsearch import Elasticsearch

def create_es_knowledgebase(q,q_doc_type):

    try:
        es = Elasticsearch([{'host': 'localhost', 'port': 9200}])

    except Exception as e:
        print('Error in connecting to Elasticsearch server - {}'.format(e))
        return ('Failure')

    try:
        qna = q['qna']
        for items in qna:
            es.index(index=str(q_doc_type).lower(), doc_type=str(q_doc_type).lower(), id = items['qid'], body=items)
    except Exception as e:
        print('Error in creating knowledgebase in Elasticsearch - {}'.format(e))
        return ('Failure')

def search_es(content,index_type):

    es = Elasticsearch([{'host': 'localhost', 'port': 9200}])

    data = {
        "query": {
            "function_score":{
                "query":{

                    "match": {
                        'q': {
                            "query":question,
                            'analyzer': 'kuromoji'
                        }

                    }
                },
                "field_value_factor":{
                    "field":"votes",
                    "modifier":"log1p"
                }
            }
        }
    }
    response = es.search(index=str(index_type).lower(), body=data)
```

When I execute the above code I get incorrect answer.
My sample json data is:

`{'qna': [{'qid': '1.0', 'q': ['ツール内のコンテンツを編集する方法'], 'a': 'ツール内のコンテンツを編集する方法', 'votes': 0}, {'qid': '2.0', 'q': ['添付ファイルをアップロードする方法'], 'a': '添付ファイルをアップロードする方法', 'votes': 0}]}`
I think the issue is in es.index() above. Somehow I am not able to specify Kuromoji plugin there. How can I specify kuromoji analyzer in index() and search()?

**Comment by fxdgear** [comment]
@abhinavmishra590 Thanks for the issue and a detailed example of what you're trying to do. This is very helpful for me in diagnosing your issues. 

I'm reviewing your code and it does not look like you are creating an index before you index the documents. 

When you use a "custom" analyzer for ingestion you need specify the analyzer when you create the index or in a template that well be used when the index is created. 

Please refer to the elastic docs for using [custom analyzers](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html)

as I said before you can either create the index beforehand and then index the documents into that index. 
OR you can use a [template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) which will apply settings to any index created whos name matches a particular pattern.
