### ISSUE TITLE
despite the elasticseach documentation, `indices.exists_alias` returns 400 BAD REQUEST

### ISSUE THREAD

**Issue by naoko** [elastic/elasticsearch-py#756]
`indices.exists_alias` is giving me 400 BAD REQUEST.
I see `HEAD` is the method as in documentation.
but when I run
```
curl -XHEAD 'localhost:9200/_alias/2016?pretty'
```
I get
```
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
``` 

and it hangs.

but method `GET` works

```python
>>> import urllib3
>>> url = 'localhost:9200/kw.search/_alias'
>>> http = urllib3.PoolManager()
>>> r = http.request('HEAD', url)
>>> r.status
400
>>> r = http.request('GET', url)
>>> r.status
200
```

**Comment by fxdgear** [comment]
@naoko I'm sorry to hear you're having problems with the library. I'm not certain how you're running into issues with the python client though as you didnt' provide an example of how you're executing the request with the client. 

I was able to do a quick little test to verify that the `exists_alias` functionality is working... 

```In [8]: es.indices.exists_alias(name='foo')
Out[8]: False

In [9]: es.indices.exists_alias(index="customer", name='foo')
Out[9]: False

In [10]: es.indices.put_alias(index="customer",name="foo")
Out[10]: {'acknowledged': True}

In [11]: es.indices.exists_alias(index="customer", name='foo')
Out[11]: True

In [12]: es.indices.exists_alias(name='foo')
Out[12]: True
```

If you don't specify an index or an alias name you will get a 405 response. 

Maybe a better implementation would be to verify that something was passed in to the call?

**Comment by naoko** [comment]
@fxdgear , you are right. because I didn't provide example in the library i don't have record of how I was using but now I'm unable to reproduce thus I must be doing something wrong. thank you for taking time to review. I'm closing this.
