### ISSUE TITLE
Incorrect exception handling in Transport

### ISSUE THREAD

**Issue by LawYard** [elastic/elasticsearch-py#757]
Hi!

My case:

```py
client = Elasticsearch('melk-vla-01.test.net', port=9202,  timeout=15, max_retries=1, retry_on_timeout=False)
s = Search(using=client, index='my_index').filter(..)
response = s.execute()
```

Port 9202 is closed by firewall, so `ConnectionTimeout` exception is expected here.

And there is what `connection.perform_request` returns: 

```
ConnectionError((<urllib3.connection.HTTPConnection object at 0x1089de1d0>, u'Connection to melk-vla-01.test.net timed out. (connect timeout=15)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x1089de1d0>, u'Connection to melk-vla-01.test.net timed out. (connect timeout=15)'))
```

But thats `ConnectionError` that **caused** by `ConnectTimeoutError`, so option `retry_on_timeout` not worked here :(

Maybe its a good reason to add new option `retry_on_connect_error`? Or inspect reason of `ConnectionError` and find that problem in `ConnectTimeoutError`?

Something like that:

```py
retry = False
if isinstance(e, ConnectionTimeout):
    retry = self.retry_on_timeout
elif isinstance(e, ConnectionError):
    if e.info.__class__.__name__ == 'ConnectTimeoutError':
        retry = self.retry_on_timeout
    else:
        retry = True
```

**Comment by fxdgear** [comment]
@LawYard I'm not following this example I'm sorry. 

There is no `Search` class in this library and as such I think you might be using a different library. 

Can you please tell me how you installed the elasticsearch lib into your python project?

**Comment by LawYard** [comment]
Oh! Sorry! Wrong repo T_T
