### ISSUE TITLE
helpers.streaming_bulk result does not include `_source` if asked (_op_type `index`)

### ISSUE THREAD

**Issue by ardumont** [elastic/elasticsearch-py#759]
Hello,

I tried to use the `elasticsearch.helpers.streaming_bulk` to trigger bulk indexation on a generator.
And then continue working on the generator result but on the `_source` of the indexation. 

The indexation works no problem but no **_source** is part of the result even though i try hard to make it happen.

Is this possible at all?

It was my understanding of the code that i could place some part of the input (the `_source` doc i index) back into the bulk's generator result.
The documentation does not explicit this (from the [elasticsearch.helpers.streaming_bulk](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L139-L219) api at least) but the  [existing packaged code i have and current one](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L95) do. As does the [elasticsearch.bulk](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L1109-L1150) api used within.

Here is the snippet of code i use:
```
actions = ({'_op_type': 'index',
            '_source': data,
           '_index': index_name,
            '_type': 'task'} for data in data_stream)
yield from streaming_bulk(
    client=self.storage,
    actions=actions,
    chunk_size=chunk_size,
    raise_on_exception=False,
     # params={'fields': ['task_id']}  # elastic search instance 6.2.2 says using 'fields' is deprecated
                                      # and to use `_source` instead (still no _source in result):
                                      # elasticsearch-6.2.2 | [2018-03-27T14:01:35,462]
                                      # [WARN ][o.e.d.r.a.d.RestBulkAction] Deprecated field
                                      # [fields] used, expected [_source] instead
    # params={'_source': True}
    # params={'_source': 'task_id'}
    # params={'_source': ['task_id']}
    # params={'_source': True,
    #         '_source_include': ['task_id']}
)
```
Note:
`# params...` are the tests i made each time to no avail, no `_source` in streamed result.

Result call sample (format: `result: ok, item: {...})
```
DEBUG:swh.scheduler.cli.archive:result: True, item: {'index': {'_index': 'swh-tasks-2016-03', '_type': 'task', '_id': 'CU56aGIBwbOv3oTGx0q4', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 0, '_primary_term': 1, 'status': 201}}
```

Down the line, i iterate over this generator (so it's consumed).
My goal is to archive in elasticsearch data, then delete what's indexed in the original system (`_source`).

For now, i'm stucked.

# version
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (buster)
Release:        testing
Codename:       buster
$ dpkg -l python3-elasticsearch
...
ii  python3-elasticsearch                                          5.4.0-1                              all                                  Python client for Elasticsearch (Python3 version)
```

Does someone have any hints?

Thanks for your time.

Cheers,

**Comment by fxdgear** [comment]
@ardumont I am sorry to leave you struggling on this for so long alone. 

The Elasticsearch API does not return the `_source` of the index'd document. 

if you were to skip using the python client and execute the bulk api using just curl in the command prompt:

```bash
$ curl -XPOST 'localhost:9200/customer/_doc/_bulk?pretty&pretty' -H 'Content-Type: application/json' -d'
{"index":{"_id":"1"}}
{"name": "John Doe" }
{"index":{"_id":"2"}}
{"name": "Jane Doe" }
'

{
  "took" : 445,
  "errors" : false,
  "items" : [
    {
      "index" : {
        "_index" : "customer",
        "_type" : "_doc",
        "_id" : "1",
        "_version" : 1,
        "result" : "created",
        "_shards" : {
          "total" : 2,
          "successful" : 1,
          "failed" : 0
        },
        "_seq_no" : 0,
        "_primary_term" : 1,
        "status" : 201
      }
    },
    {
      "index" : {
        "_index" : "customer",
        "_type" : "_doc",
        "_id" : "2",
        "_version" : 1,
        "result" : "created",
        "_shards" : {
          "total" : 2,
          "successful" : 1,
          "failed" : 0
        },
        "_seq_no" : 0,
        "_primary_term" : 1,
        "status" : 201
      }
    }
  ]
}```

for more information on how the [bulk api](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) works please refer to the elastic docs
