### ISSUE TITLE
Content-Type header [application/x-www-form-urlencoded] is not supported

### ISSUE THREAD

**Issue by Yi3nz** [elastic/elasticsearch-py#762]
Hi guys,

I'm trying to run the elastic search on my Ruby on Rails application.
I have installed:

> elasticsearch 6.2.3

And include the gems:

> gem 'elasticsearch-rails'
> gem 'elasticsearch', ' ~> 5.0.4'
> gem 'elasticsearch-model', ' ~> 5'

According to the documentation I have also enable the content-type by adding 

> #http.content_type.required: true

 into my **elasticsearch.yml** file, but nothing works on my side. 

The full error:

> 406 : {"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}

Could anyone suggest any resolution? Thanks a million!

**Comment by fxdgear** [comment]
@Yi3nz this is the github issue for the python library. 

I think you want https://github.com/elastic/elasticsearch-ruby or https://github.com/elastic/elasticsearch-rails

**Comment by Yi3nz** [comment]
Thanks for replying but have no luck with this ;( Getting the same error unfortunately.

**Comment by fxdgear** [comment]
Sorry to sound like a broken record, but this library is python. Not ruby. 

Please open a ticket with the ruby client. I actually haven’t ever used ruby before so I wouldn’t be a very good resource for you.

**Comment by Yi3nz** [comment]
Oh sorry it's for python, didn't catch that from the first reply.

Thank you for your quick response!
