### ISSUE TITLE
how to close the connection in a python script

### ISSUE THREAD

**Issue by liuxi653** [elastic/elasticsearch-py#763]
hi,
  if i use below cmds to create a connection to the cluster,how can i close it in the python script

"conn = Elasticsearch(request_timeout=25)" //this cmds is in the script

if the connetion not closed in the script ,evry time the script stop running, the http total_opened will increase

      "http" : {
        "current_open" : 1,
        "total_opened" : 110578
      }

thanks a lot

**Comment by fxdgear** [comment]
You can explicitly close connections using the [`close`](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L348-L352) method.
