### ISSUE TITLE
Body shouldn't be decoded needlessly

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch-py#765]
Body decoding in https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/connection/base.py#L78-L79 should only be done if we are actually going to use it in the logs by either `log_request_success` or `_log_trace`

**Comment by fxdgear** [comment]
Not sure I follow what you're asking here. Lets talk about at Pycon

**Comment by sethmlarson** [comment]
This shouldn't be necessary anymore. Body isn't decoded for logging by the client itself, all logging happens within elastic-transport which only works on bytes.
