### ISSUE TITLE
Delete by document ID returns NotFoundError

### ISSUE THREAD

**Issue by sharmalakshay93** [elastic/elasticsearch-py#769]
I'm running an AWS Elasticsearch Service cluster with ES 5.5, and am trying to perform a delete document operation using the Python API.

When searching for the document using a document ID string, the API returns True.

```
doc_exists = esClient.exists(index='debug', doc_type='_all', id=doc_id)
```

However, when I try to delete it using the same document ID, I receive a NotFoundError.

```
esClient.delete(index='debug', doc_type='_all', id=doc_id)
```
exception received:

```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)elasticsearch.exceptions.NotFoundError: TransportError(404, '
{
    "found": false,
    "_index": "debug",
    "_type": "_all",
    "_id": "some-id-with-dash_and_underscore",
    "_version": 1,
    "result": "not_found",
    "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
    }
}
'): NotFoundError
```

Can't figure out what's wrong here.

**Comment by fxdgear** [comment]
@sharmalakshay93 can you replicate the issue using straight curl? 

First try to "get" the document:
```
curl -X GET "localhost:9200/debug/_all/<doc_id>"
```

```
curl -X DELETE "localhost:9200/debug/_all/<doc_id>"
```

also can you try to `get` the document as opposed to just `exists`. 

```
doc = esClient.get(index='debug', doc_type='_all', id=doc_id)
```

**Comment by sharmalakshay93** [comment]
Turns out the problem was that I was passing in `doc_type='_all'` while calling the `delete` method. Retrieving the type and passing this in for the `doc_type` parameter while calling `delete` solved it. Thanks @fxdgear!
