### ISSUE TITLE
How can I set up block mode in connection pool

### ISSUE THREAD

**Issue by ray-guo** [elastic/elasticsearch-py#770]
In multithread situation, the block mode is quite important especially when maxsize is not enough or less than thread count instead of throwing an exception about time out.

**Comment by fxdgear** [comment]
@ray-guo you can override the `ConnectionPool` object to do what ever you want. 
Though the issue comment doesn't seem to make sense with the issue title. 

Trying to understand what you are asking, please correct me if I'm wrong. 

You are trying to index data into elasticsearch in a multi-threaded environment, and the issue you're running into it seems is that there are too many threads and or not enough data streaming and as such you're not able to reach the "maxsize" threshold and you get a time out. 

Did I understand your question?
