### ISSUE TITLE
How to set custom timeout to bulk helper

### ISSUE THREAD

**Issue by just1602** [elastic/elasticsearch-py#773]
In a project the bulk insert timeouted and when I tried to pass the `timeout` or `request_timeout` keyword it did nothing and I had to edit the connection default timeout to be able to make my bulk query passe.

Does the `**kwargs` passed to `streaming_bulk` is hen passed to `connection` or other low-level function or there is other way to set the timeout for `bulk`?

**Comment by fxdgear** [comment]
@just1602 thanks for the ticket I'm going to be a bit verbose in this response so I can figure this out myself. (sorry I wasn't the original author here so I'm trying to understand the layers of complexity myself while explaining to you)

So the `bulk` client call accepts a `timeout` query parameter https://github.com/elastic/elasticsearch-py/blob/408093440c15a1708d0c1d379753a52f92d16ceb/elasticsearch/client/__init__.py#L1109-L1111

But the [`_process_bulk_chunk`](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L86) accepts `**kwargs` but `**kwargs` are not passed in as query parameters, we should add some support for `*args` so the timeout will be translated into a `query_param` as well. 

thanks for raising this issue. I'll get to work on it.

**Comment by just1602** [comment]
Thanks for the answer and to fix this ! :)
