### ISSUE TITLE
How can i Filter an exists in a range like query?

### ISSUE THREAD

**Issue by prabin525** [elastic/elasticsearch-py#781]
I have an index with workingHour as an nested object that contains day, stat and end.
```
    class WorkingHourIndex(InnerDoc):
	    day = Keyword()
	    start = Date()
	    end = Date()
```

Everything is indexed properly now when i search for documents i want to perform a query with day and a time and i want elasticsearch to check if the day exists of not and if it does , does the time exists between start and end.

**Comment by fxdgear** [comment]
@prabin525 i'm thinking that you're using https://github.com/elastic/elasticsearch-dsl-py/ correct?

This is the lower level client. And as such doesn't support the `InnerDoc` class objects. 

Unfortunately I'm not as well versed on the DSL client. (I'm still coming to speed on that one). Maybe try opening this issue on the `-dsl-py` repo.
