### ISSUE TITLE
update_by_query modifies document when _source is specified as a list of fields to return.

### ISSUE THREAD

**Issue by imedmar** [elastic/elasticsearch-py#782]
It is [documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) that 
> The simplest usage of _update_by_query just performs an update on every document in the index without changing the source

But, when I make an update call using elasticsearch-py as such:
`es.update_by_query(index=<index>, doc_type=<type>, body=query, size=1, _source=["likes", "field2"])`

Where `query` looks something like:
```json
{
    "script": {
        "source": "ctx._source.likes += params.likes",
        "lang": "painless",
        "params": {
            "likes": 1
        }
    },
    "query": {
        "term": {
            "id": "1234"
        }
    }
}
```
The source document gets modified in that all fields are removed, except the updated `likes` and `field2` fields.

However, when I pass `_source=True` to the `update_by_query` call, the document remains in it's original form with an updated `likes` as expected.

Not sure if I did something wrong, but let me know if you need more details in order to reproduce the issue.

**Comment by HonzaKral** [comment]
This is an issue with Elasticsearch itself and its documentation, there is nothing specific there for the python library, I am sorry but we cannot help you here.
