### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by untergeek** [elastic/elasticsearch-py#788]
Python 2.6's EOL was with the [2.6.9 release in October 2013](https://www.python.org/download/releases/2.6.9/).  That's nearly 5 years past the release date. And [2.7 isn't going to last much longer](https://pythonclock.org/).

If issues like #787 are, indeed, from functions not working as expected—whether in our code, or the code of dependencies—we should remove support for Python 2.6 [here](https://github.com/elastic/elasticsearch-py/blob/master/setup.py#L50), to say nothing of support for deprecated versions 3.2, 3.3, and 3.4.

They would also need to be removed [here](https://github.com/elastic/elasticsearch-py/blob/master/.travis.yml#L4), and [here](https://github.com/elastic/elasticsearch-py/blob/master/.travis.yml#L6-L7)

**Comment by hugovk** [comment]
Note Python 3.4 is not yet EOL until 2019-03-16. 

![image](https://user-images.githubusercontent.com/1324225/40123053-e69353ee-592d-11e8-9bf8-331962a7622c.png)

https://en.wikipedia.org/wiki/CPython#Version_history

---

Here's the pip installs for elasticsearch from PyPI for April 2018, showing low numbers for 2.6 and even lower for 3.2 and 3.3:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  57.69% |        350,098 |
| 3.6            |  23.78% |        144,329 |
| 3.4            |   9.88% |         59,932 |
| 3.5            |   8.11% |         49,221 |
| 2.6            |   0.48% |          2,916 |
| 3.3            |   0.03% |            180 |
| 3.7            |   0.02% |            131 |
| 3.2            |   0.01% |             32 |
| 3.8            |   0.00% |              1 |
| Total          |         |        606,840 |

Source: `pypinfo --start-date 2018-04-01 --end-date 2018-04-30 --percent --pip --markdown elasticsearch pyversion`

Please see #791 to remove the EOLs.

**Comment by fxdgear** [comment]
I really appreciate bringing this subject up. Before I took over maintenance of this project I wanted to drop 2.6 myself and advocated for it. Though after discussion and a realization that redhat is a slow mover, we still have people who have a dependency on python26.
