### ISSUE TITLE
Can support wait for a moment before retries

### ISSUE THREAD

**Issue by vc1** [elastic/elasticsearch-py#792]
https://github.com/elastic/elasticsearch-py/blob/1cae2b7eb0324c133be76a18e01a58d2b17485c0/elasticsearch/transport.py#L332

```python
if attempt == self.max_retries:
    raise
else if self.retry_wait:
    time.sleep(self.retry_wait)

```

I use AutoSSH tunnel to connect to es, the network is sometimes unstable, will disconnect for a few seconds, and then automatically restore.

**Comment by vc1** [comment]
present solution
```python
i = 1
while i <= 3:
    try:
        rs = self.elasticsearch.indices.exists(index_name)
        break
    except TransportError as e:
        i += 1
        if i > 3:
            print('retry error')
            raise
        else:
            print('retry')
            time.sleep(5) # sleep


```

**Comment by fxdgear** [comment]
@vc1 Thanks for bringing up this issue. 

I'm just trying to understand what your asking. 

So because you have an unstable connection to an ES Cluster you have to wrap every call to ES around a try/wait loop? 

OR you only need to have a try/wait around the initial request to the ES cluster. Once you've connected things are 💚? 

Thanks

**Comment by vc1** [comment]
@fxdgear 

Not just during initialization
The network may be unstable at each execution of the query task

My use scenario is a remote-to-business customer's network. Using the VPN provided by the customer, I use AutoSSH to forward the server's local ES port, and then run a script on my computer to complete the work. VPN software and AutoSSH can automatically reconnect.

In addition to this situation, there may be network problems when connecting to a remote or foreign cloud host through the public network.

**Comment by fnavarrogonzalez** [comment]
A little improve over the solution of @vc1 could be instead of an linear retry, start with a lower value and increase it in every iteration (poly/exp).

**Comment by fxdgear** [comment]
pls see https://github.com/elastic/elasticsearch-py/pull/794
