### ISSUE TITLE
put_template() is not working as expected

### ISSUE THREAD

**Issue by glestel** [elastic/elasticsearch-py#797]
Hello,

Following the official documentation on [indice template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) I wanted to use the method `put_template` to add an index template. But the method constructs the API call to `PUT /_search/template/{id_of_template}` [code here](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L1323) which doesn't seem to work on elasticsearch 6
I corrected the code with the correct API call and it's successfully creating a template index : 
```python
return self.transport.perform_request('PUT', _make_path('_template', id), params=params, body=body)
```
Was I right to correct the method or should I use another method to create index template ?

Best regards

**Comment by fxdgear** [comment]
@glestel thank you for the ticket. 

Unfortunatly the method call you linked to is a different type of template. The method you linked to is for creating a `search template`: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L1314-L1315 The docs for which can be found [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html)

The index template which it seems you want to create is in the `indices` module: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/indices.py#L427-L447

I hope this helps

**Comment by glestel** [comment]
Ok my bad, sorry for the noise, and thank you for the info, I'll use that.
