### ISSUE TITLE
[docs] `verify_certs` is True by default but documented as False

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/elasticsearch-py#800]
There is a mismatch between docs and implementation:

https://github.com/elastic/elasticsearch-py/blob/7751fede5a4733130e210b62ab1f99ab9763c9c7/elasticsearch/client/__init__.py#L120

https://github.com/elastic/elasticsearch-py/blob/7751fede5a4733130e210b62ab1f99ab9763c9c7/elasticsearch/connection/http_requests.py#L30

At first I was scared about the bad default value of `verify_certs=False` but happily it is only the docs that are wrong 😉

**Comment by fxdgear** [comment]
Ahh ok there's actually a disconnect between `requests` and `urllib3`. Because off by default is what we get in `urllib3`. I'll clean up the docs.
