### ISSUE TITLE
v5.5.3 tagged but not released on PyPI

### ISSUE THREAD

**Issue by slint** [elastic/elasticsearch-py#808]
v6.3.0 is tagged and released properly on PyPI, though v5.5.3 isn't: https://pypi.org/project/elasticsearch/#history

**Comment by fxdgear** [comment]
Thanks for the issue. But there’s a separate package on PyPI for es5. 

Please take a look at `elasticsearch5`

https://pypi.org/project/elasticsearch5/#history

Thank you!

**Comment by reupen** [comment]
> Thanks for the issue. But there’s a separate package on PyPI for es5.
>
> Please take a look at elasticsearch5

I thought we discussed before – elasticsearch5 is not useful or helpful for most people: https://github.com/elastic/elasticsearch-py/issues/667

It was just for people running multiple versions of Elaticsearch.

**Comment by fxdgear** [comment]
you're right I'm sorry. 

I pushed it now.

**Comment by javierbeaumont** [comment]
The next versions (v5.5.4 and v5.5.5) are tagged but not released on PyPI (they are only in elasticsearch5 package).
