### ISSUE TITLE
Document how to use generator with bulk()

### ISSUE THREAD

**Issue by melissachang** [elastic/elasticsearch-py#813]
It would be nice if https://elasticsearch-py.readthedocs.io/en/master/helpers.html?highlight=generator#bulk-helpers showed an example of how to use a generator with bulk().

**Comment by fxdgear** [comment]
@melissachang Is it ok to look in the `example` directory and look at the `load` [module](https://github.com/elastic/elasticsearch-py/blob/master/example/load.py#L76-L130)

There's an example of how to use generators with `bulk()`.

**Comment by melissachang** [comment]
It would be nice to have a self-contained example, like:
```
    k = (
        {
            '_op_type': 'update',
            '_index': index_name,
            # type will go away in future versions of Elasticsearch. Just use any string
            # here.
            '_type': 'type',
            '_id': row[primary_key],
            'doc': {
                readable_field_name: row[field_name]
            },
            'doc_as_upsert': True
        } for _, row in df.iterrows())

    bulk(es, k)
```
In this example, `df` is a dataframe. The documentation should probably be more generic.

https://elasticsearch-py.readthedocs.io/en/master/helpers.html?highlight=generator#bulk-helpers is where I would expect to see an example.
