### ISSUE TITLE
elasticsearch.helpers.parallel_bulk() hangs forever on Python 3.7.0

### ISSUE THREAD

**Issue by brainix** [elastic/elasticsearch-py#816]
I haven't had a chance to dig into what's new in Python 3.7.0, or how `elasticsearch.helpers.parallel_bulk()` works.  But for some reason, it hangs forever on Python 3.7.0.

`elasticsearch.helpers.streaming_bulk()` works fine on Python 3.7.0, and my app isn't indexing-heavy, so I've just switched to streaming for now.

**Comment by fxdgear** [comment]
@brainix thanks for the issue. 

If you have a chance to dig please update the ticket. I'll try to reproduce on my own.

**Comment by monktastic** [comment]
FWIW, here's the stack trace I get:

```
Traceback:
  File "upload_pb.py", line 40, in <module>
    for success, info in gen:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 581, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 819, in _help_stuff_finish
    inqueue.put(None)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 139, in put
    self.not_full.wait()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
```

**Comment by sirdodger** [comment]
We see the same problem on Python 3.5

**Comment by sirdodger** [comment]
Okay, found the problem.  If you increase thread_count to be greater than queue_size, then when the pool terminates and calls _help_stuff_finish(), it can block on the put() that inserts sentinel Nones into the queue.  Those sentinels are what helps workers terminate cleanly.  Eventually, the main thread gets locked dropping sentinels in, and all the workers have terminated (except for the daemonized _repopulate_pool() threads).

test_chunk_sent_from_different_threads() triggers the case by setting thread_count to 10, but leaving the default queue_size at 4.

A good solution would be to set queue_size to min(queue_size, thread_count).  That would allow bigger pools, but stop them from getting so small that the main thread can block.

**Comment by sirdodger** [comment]
I submitted a pull request.  I am able to run the tox tests with it, though with concurrency bugs, there is always the chance that it doesn't fully address the underlying problem.  I see the symptoms, but did not fully root cause it.  It could be that any blocking during teardown could cause the problem, and increasing the queue size just reduces the chance of that happening.

https://github.com/elastic/elasticsearch-py/pull/894

I'll be testing out a larger pool size on my installation to see how the change affects real-world runs, and if hangs still occur occasionally.

**Comment by sirdodger** [comment]
The SimpleQueue class in Python 3.7 would likely fix the issue, since it is better able to handle reentrant code... but it does not support max queue size blocking semantics either.
