### ISSUE TITLE
Please add verbose feature for reindex

### ISSUE THREAD

**Issue by Sashkow** [elastic/elasticsearch-py#823]
Sometimes `elasticsearch.helpers.reindex` takes long time. It would be nice to be able to observe some progress while waiting.

**Comment by fxdgear** [comment]
@Sashkow thanks for bringing this up. BUT unfortunately this is not something I want to include in the lib. Think about how this would work for a multi TB index. Your python execution would be blocking for hours (days). 

Fortuanly there's a way around this. If you use the [`wait_for_completion=False`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#_url_parameters_3) url parameter you will get back a task ID in the response. This will allow you to then query the [Tasks API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-task-api) to monitor the status of your reindexing process. The python method for getting task information can be found here: http://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-pending.html

I hope this helps.
