### ISSUE TITLE
Multi termvectors raised an error if huge documents IDs are passed as parameter

### ISSUE THREAD

**Issue by ShwethaThakur** [elastic/elasticsearch-py#825]
doc_type, '_mtermvectors'), params=params, body=body)
File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
self._raise_error(response.status, raw_data)
File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'too_long_frame_exception', u'An HTTP line is larger than 4096 bytes.')

Hey there! i am trying to use multitemvectors in elasticsearch to get most frequent unigrams, bigrams and trigrams across an entire index. The number of documents is approx. 50000. When i give 300 IDs, it works fine. But When i give all IDs of 50000 documents, it raises this error. Doesn't multitermvectors work with large no. of documents? or is there a way to figure out this error?

**Comment by HonzaKral** [comment]
You cannot have a `URL` that is longer than 4kb, if you want to pass in that many ids please pass it via the `body` parameter in json format as described in [0]. Thanks!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-termvectors.html
