### ISSUE TITLE
put_template should be updating the index template

### ISSUE THREAD

**Issue by rubtoa** [elastic/elasticsearch-py#828]
Method put template is defined as "Create an index template that will automatically be applied to new indices created"

In fact it updates the search template (_search/template) and not /_template/TEMPLATE_NAME

`    @query_params()
    def put_template(self, id, body, params=None):
        """
        Create a search template.
        `<http://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html>`_

        :arg id: Template ID
        :arg body: The document
        """
        for param in (id, body):
            if param in SKIP_IN_PATH:
                raise ValueError("Empty value passed for a required argument.")
        return self.transport.perform_request('PUT', _make_path('_search',
            'template', id), params=params, body=body)`

**Comment by fxdgear** [comment]
@rubtoa I'm sorry you're having issues. this is actually quite common. Though not sure how to update, maybe put a comment in there saying "If you're looking for index templates you're in the wrong place"

The method to `PUT` *index* templates is actually in the `indices` module: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/indices.py#L420-L442
