### ISSUE TITLE
no support to delete a type

### ISSUE THREAD

**Issue by nbraem** [elastic/elasticsearch-py#83]
There's no way of doing this:
curl -XDELETE 'http://{server}/{index_name}/{type_name}/'

Although it's not documented anywhere, it works and is a convenient way to delete all documents of a specific type and their mapping.

I'm glad to add it, if you tell me where to add it.

**Comment by harpreetsb** [comment]
there is no such method in that link

**Comment by HonzaKral** [comment]
It has been removed in master because it doesn't exist in es 2.0. It is still there in the 1.x branch.
