### ISSUE TITLE
Cant find any easy functionalities for counts, unique values or aggregates

### ISSUE THREAD

**Issue by zwep** [elastic/elasticsearch-py#834]
I have searched a lot.. but I cant seem to find it. Can anyone point out the location?

Searching through the documentation did not help, and the only help I found via google is by using their JSON-query language.
If needed, I am willing to contribute to this package for some easy functionalities... but I first want to check if it isnt already there

**Comment by HonzaKral** [comment]
If you want to count unique values please use the `cardinality` aggregation (0) which can be used in this package just by passing the proper `body` to the `search()` method.

Note that for a more pythonic API you might also want to have a look at `elasticsearch-dsl` (1)

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html
1 - https://github.com/elastic/elasticsearch-dsl-py
