### ISSUE TITLE
some error in elasticsearch5\conection\http_urllib3.py

### ISSUE THREAD

**Issue by woodywuuu** [elastic/elasticsearch-py#838]
I try to use Elasticsearch.count() and it went wrong.
like `global name 'headers' is not defined.`
I can't find global headers in elasticsearch5\conection\http_urllib3.py,and no self.http_compress in class Urllib3HttpConnection.
Now I use version 6.X.X.work fine.XD

**Comment by Songzr** [comment]
I got the same error too with lib version 5.5.4 connect ES version 5.6.9.
Then, I use the previous lib --- version 5.5.3 instead. It works fine.
Try `pip install elasticsearch5==5.5.3`

**Comment by fxdgear** [comment]
Sorry this is a result of a bad cherry pick I must have forgotten a commit in here. Give me a second to find it and I'll push a `5.5.5`

**Comment by fxdgear** [comment]
ok new version pushed. i'm sorry about that.
