### ISSUE TITLE
How to write the bulk body?

### ISSUE THREAD

**Issue by wangqiqianggithub** [elastic/elasticsearch-py#840]
coding:
es = Elasticsearch(
            [self.eshost],
            http_auth=(self.user, self.password),
            port=self.port,
            timeout=self.timeoutsecond
        )
es.bulk(index="testindex",doc_type="testtype",body=?)

i used body like this:
{
    '_op_type': 'index',
    'doc': {'question': 'The life, universe and everything.'}
}
but it faild,I think the body must contain an iterable object to satisfy the so-called bulk insert. Can you help me？thank you

**Comment by mazzma12** [comment]
Indeed you should put the body you have in a list or a generator : https://elasticsearch-py.readthedocs.io/en/master/helpers.html?highlight=bulk%20#example

**Comment by wangqiqianggithub** [comment]
I also read this article and solved the problem, but I still want to thank you
