### ISSUE TITLE
elasticsearch.helpers.parallel_bulk unexpected indexing failure behavior

### ISSUE THREAD

**Issue by karimjp** [elastic/elasticsearch-py#841]
**===Versions===**
Server: elasticsearch-6.2.4
Client: elasticsearch==6.3.1

**===Problem/Observation===**
Varying the chunk_size parameter value of elasticsearch.helpers.parallel_bulk for a fixed size data set with an invalid field value on one record, in some cases will not raise an elasticsearch.helpers.BulkIndexError.  I expected a  BulkIndexError raised for all values of chunk_size.

**===Tests===**
Passed a five-record data generator to elasticsearch.helpers.parallel_bulk, where the fifth record is expected to trigger a type validation error.  The first four records contain a field called "key" of type float, and the fifth record is an int type.

**Test 1:**
actions = gendata(5)
pb = helpers.parallel_bulk(es, actions, chunk_size=1)
Result:
No Exceptions
docs.count = 5

**Test 2:**
actions = gendata(5)
pb = helpers.parallel_bulk(es, actions, chunk_size=2)
Result:
Exception:
`Traceback (most recent call last):
  File "EStest.py", line 57, in <module>
    deque(pb, maxlen=0)
  File "/Users/karim/Desktop/CrackingTheCodeInterview/elastics/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 306, in parallel_bulk
    _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
elasticsearch.helpers.BulkIndexError: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'mytype', u'_index': u'test-index', u'error': {u'reason': u'mapper [key] cannot be changed from type [float] to [long]', u'type': u'illegal_argument_exception'}, u'_id': u'4', u'data': {'key': 4}}}])`
docs.count = 4

**Test 3:**
actions = gendata(5)
pb = helpers.parallel_bulk(es, actions, chunk_size=3)
Result:
Same as Test 2.

**Test 4:**
actions = gendata(5)
pb = helpers.parallel_bulk(es, actions, chunk_size=4)
Result:
Same as Test 2.

**Test 5:**
actions = gendata(5)
pb = helpers.parallel_bulk(es, actions, chunk_size=4)
Result:
No Exceptions
docs.count = 5

The following mapping is generated by Elasticsearch:
```
{
  "test-index": {
    "mappings": {
      "mytype": {
        "properties": {
          "key": {
            "type": "float"
          }
        }
      }
    }
  }
}
```

**===Code to reproduce===**

```
from elasticsearch import Elasticsearch
from elasticsearch import RequestError
from elasticsearch import helpers
from collections import deque
import json

def gendata(maxRange):
	for x in range(maxRange):
		yield {
		"_index": "test-index", 
		"_type": "mytype",
		"_id": x, "_source": { 
		"key": (x + .5) if x < maxRange-1 else x }
		}  

es = Elasticsearch(['localhost'])
try:
	es.indices.create(index="test-index")#, body=mapping)
except RequestError:
	es.indices.delete(index="test-index")
	es.indices.create(index="test-index")#, body=mapping)

actions = gendata(5)
pb = helpers.parallel_bulk(es, actions, chunk_size=2)

deque(pb, maxlen=0)
```

**Comment by technige** [comment]
Given this issue is nearly 4 years old and references version 6.x, I am going to close the issue. Please reopen if this specific issue is still occurring with recent versions of the products.
