### ISSUE TITLE
urllib3.exceptions.ConnectTimeoutError but requests.get works

### ISSUE THREAD

**Issue by benregn** [elastic/elasticsearch-py#843]
I'm trying to use `elasticsearch-py` to connect to `http://distribution.virk.dk` but I get a `urllib3.exceptions.ConnectTimeoutError` when I try to connect. However sending requests works just fine with `requests`.

`requests` code:
```python
resp = requests.get(url="http://distribution.virk.dk")
print(resp.json())
```

`elasticsearch-py` code:
```python
es = Elasticsearch(["http://distribution.virk.dk"])
es.info()
```

cluster info:
```
{
  "name": "eu-west-1c-i-94863a18",
  "cluster_name": "Erst.Distribution.AWS.Prod.Cluster",
  "cluster_uuid": "vzyirCYtSDeKp5xRIMxebw",
  "version": {
    "number": "6.2.4",
    "build_hash": "ccec39f",
    "build_date": "2018-04-12T20:37:28.497551Z",
    "build_snapshot": false,
    "lucene_version": "7.2.1",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  },
  "tagline": "You Know, for Search"
}
```

`requests` version: 2.19.1
`elasticsearch-py` versions tested: `6.3.1` and `6.2.0`

Any ideas?

**Comment by HonzaKral** [comment]
The `elasticsearch-py` defaults to port `9200`, if you want to use port `80` you need to specify it explicitly as `'http://host:80'`

Also note that having your elasticsearch exposed to the internet like this is *very* dangerous and not recommended at all!

Hope this helps!
