### ISSUE TITLE
log_request_success string interpolation not formatted correctly

### ISSUE THREAD

**Issue by drewpearce** [elastic/elasticsearch-py#848]
https://github.com/elastic/elasticsearch-py/blob/cb6f09bbe74eca6cbf5bb2519c1f3d791c0dd820/elasticsearch/connection/base.py#L81-L84

This line consistently yields log messages of `"%s %s [status:%s request:%.3fs]"` despite confirmation via debugger that values are passed. Statement should be reformatted to correctly substitute values.

**Comment by sethmlarson** [comment]
`logging.StreamHandler` shows proper values meaning the `.info()`, etc calls are working properly.
If you're using a custom handler you may need to format the `LogRecord.args` yourself to recreate the proper messages.
