### ISSUE TITLE
Running elasticsearch-py on google app engine 

### ISSUE THREAD

**Issue by Zhipeng-Chang** [elastic/elasticsearch-py#851]
Hi, 
I'm having trouble with running the elasticsearch-py on Google app engine, I don't have a lot of experiences about network/route, so I posted the error message and my code here. I noticed that the document mentioned this problem:https://elasticsearch-py.readthedocs.io/en/master/#environment-considerations, but after I changed to "es = Elasticsearch(send_get_body_as='POST')", I'm still getting the same error. 
Thanks!

-------------------code-----------------
from elasticsearch import Elasticsearch
es = Elasticsearch(send_get_body_as='POST')

        for question, property_list in QUESTION_DIC.items():
            index = property_list[0]
            answer = property_list[1]
            if len(property_list)==3:
                link = property_list[2]
            else:
                link = None
            data = {
            'question': question,
            'answer': answer,
            'link': link,
            }   
            res = es.index(index="google", doc_type='question', id=index, body=data)
        es.indices.refresh(index="google")

------------------error message---------------------------
'An error occured while connecting to the server: %s' % e)
ProtocolError: ('Connection aborted.', error('An error occured while connecting to the server: DNS lookup failed for URL: http://localhost:9200/google/_search',))

**Comment by Zhipeng-Chang** [comment]
update: 

I tried[ elasticsearch-urlfetch
](https://github.com/Loudr/elasticsearch-urlfetch), but got the following errors

2018-10-08 21:20:17.618 MDT
  File "/base/data/home/apps/m~chatbot-216118/20181008t211838.413136967834347186/lib/elasticsearch/transport.py", line 318, in perform_request
2018-10-08 21:20:17.618 MDT
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
2018-10-08 21:20:17.618 MDT
TypeError: perform_request() got an unexpected keyword argument 'headers'

**Comment by Zhipeng-Chang** [comment]
Hi @HonzaKral! Could you please help me look into this problem? Thank you!

**Comment by fxdgear** [comment]
It looks like you might have the wrong url? Localhost:9200. 

Where is your es instance running?

**Comment by Zhipeng-Chang** [comment]
Hi @fxdgear! Thanks for helping out! 
I'm not quite sure where my app engine is running...(I'm assuming it's running at https://<my project id>.com/? ) I'm new to App engine, I feel like the elasticsearch service is not running on the google app engine. Do you know how to turn the elasticsearch on or is there anything I should configure before I use the elasticsearch-py?

**Comment by fxdgear** [comment]
I’ve never used app engine. 

But tell me this, did you set up the elasticsearch sever? Or did someone else?

**Comment by Zhipeng-Chang** [comment]
Hi! No, I didn't run any commands to start the elasticsearch service, and looks like google app engine couldn't host the elasticsearch service.... so I'm transferring everything to a computer engine now ... Thank you for helping!
