### ISSUE TITLE
Support multiple versions including versions 1.x

### ISSUE THREAD

**Issue by Offir** [elastic/elasticsearch-py#858]
Hello,
Is there a way to support all versions including versions 1.x?
Until now i have support for 2.x.y, 5.x.y and 6.x.y (
I followed the information in the link [elasticsearch -compatibility](https://elasticsearch-py.readthedocs.io/en/master/#compatibility)

My install_requires in setup.py:
```
install_requires=[
        "elasticsearch2",
        "elasticsearch5",
        "elasticsearch>=6.0.0,<7.0.0",
        "certifi==2017.4.17"
    ],
```
The problem is that i need to support also versions 1.x.y.
I tried to collect data for elasticsearch version 1.x.y and I got an error:
```
  File "/Users/Offir/ve/elasticsearch/lib/python2.7/site-packages/es/es.py", line 37, in wrapped
    print str(e)
  File "/Users/Offir/ve/elasticsearch/lib/python2.7/site-packages/elasticsearch/exceptions.py", line 58, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers
```
I added  "elasticsearch>=1.0.0,<2.0.0" to the install_requires and I was able to get my data without errors (for elasticsearch version 1.x.y) but then I didn't had support for elasticsearch version 6.x.y and i got different error:
```
File "/Users/Offir/ve/elasticsearch/lib/python2.7/site-packages/es/es.py", line 44, in wrapped
    raise Exception(msg)
Exception: Content-Type header is missing
```

I tried to do add something like `elasticsearch>=1.0.0,<7.0.0` and `elasticsearch1`  but it didn't work and I got the same error for elasticsearch version 6.x.y.

**Comment by rlopezro** [comment]
@Offir you should be able to use `elasticsearch1`. Also you need to import the correct library matching your elasticsearch version. If you are using ES 1.x you need to import `elasticsearch1` by either using `import elasticsearch1` or `import elasticsearch1 as elasticsearch` (if you have references to elasticsearch in your code)

**Comment by fxdgear** [comment]
as @rlopezro mentioned you need to install `elasticsearch1`. You can find it on pypi here: https://pypi.org/project/elasticsearch1/

**Comment by Offir** [comment]
@fxdgear Tnx but I don't understand why you close this issue.
I need to support all elasticsearch version.
When i install `elasticsearch1` and add it to 
```

**Comment by Offir** [comment]
@fxdgear Tnx but I don't understand why you close this issue.
I need to support all elasticsearch version.
When i install `elasticsearch1` and add it to 
```

**Comment by Offir** [comment]
@fxdgear Tnx but I don't understand why you close this issue.
I need to support all elasticsearch version.
When I install `elasticsearch1` and add it to the `install_requires` in  setup.py I get errors for the other versions.

**Comment by fxdgear** [comment]
@Offir  I'm sorry I re-read your issue and I'm not seeing an error about installing `elasticsearch1` alongside the other versions of elasticsearch. 

The error you mention is about a `Content-type` header missing. Starting with Elasticsearch 6.0 the contenttype header is a strict requirement. https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

Can you please explain a bit more? I'm making a guess here but you're trying to create a `wrapper` for elasticsearch-py that supports all versions of elasticsearch. Which is not going to be an easy task. There are breaking changes for each major version upgrade of elasticsearch. So you will be unable to blindly support all versions of elasticsearch. Your application will have to know which version of elasticsearch each cluster is running before you instantiate the connection. This means you will have to do stuff like @rlopezro mentioned and do soemthing like:

```python
from elasticsearch1 import elasticsearch as elasticsearch1
from elasticsearch2 import elasticsearch as elasticsearch2
from elasticsearch5 import elasticsearch as elasticsearch5
from elasticsearch import elasticsearch as elasticsearch6
```

Then you before you can create the connection you need to know which version your host is. 

Also for the record Elasticsearch 1.x is no longer supported (as of 2017-01-16)
And 2.x went EOL on 2018-02-28. 
> https://www.elastic.co/support/eol

**Comment by Offir** [comment]
@fxdgear Thank you for your explanation.
I was able to install

**Comment by Offir** [comment]
@fxdgear Thank you for your help :)
I installed `elasticsearch2`, `elasticsearch5` and `elasticsearch>=6.0.0,<7.0.0` 
then using `import elasticsearch` (according to https://elasticsearch-py.readthedocs.io/en/master/#compatibility) I was able to support all versions of elasticsearch (expect of `elasricsearch1`). That's why I taught that installing elasricsearch1 will work as well so I could avoid doing:
```
from elasticsearch1 import elasticsearch as elasticsearch1
from elasticsearch2 import elasticsearch as elasticsearch2
from elasticsearch5 import elasticsearch as elasticsearch5
from elasticsearch import elasticsearch as elasticsearch6
```
When I added `elasricsearch1` to the `install_requires` I was able to fetch data from elasticsearch 1 cluster version but I got an error `Content-Type header is missing` when trying to fetch data from elasticsearch 6 cluster version.

**Comment by fxdgear** [comment]
> When I added elasticsearch1 to the install_requires I was able to fetch data from elasticsearch 1 cluster version but I got an error Content-Type header is missing when trying to fetch data from elasticsearch 6 cluster version.

this is to be expected because an elasticsearch cluster running es6 has a strict requirement on the Content-Type header. You can see here that the support for explicitly adding a Content-Type was added https://github.com/elastic/elasticsearch-py/commit/d862c8a799e485649da3beaef7037860d01ac3e5

Prior to this commit, content-type was not sent along in the request to Elasticsearch, which means if you're trying to use a connection class from before this commit (ie in elasticsearch1) it will not have the header information built into the connection class. 

There are other issues as well with trying to use a connection class from a prior version fo Elasticsearch-py on a current version of Elasticsearch. Which is why you need to import them all. Then you need to have knowledge of what version a particular cluster is running before you create the connection object.
