### ISSUE TITLE
elasticsearch 5.5.3 with sniff_on_start and http_auth in hosts url, do not pass http_auth to node.

### ISSUE THREAD

**Issue by Ricky-Hao** [elastic/elasticsearch-py#871]
## Problem
When initial client with `Elasticsearch(hosts="user:pass@host:port", sniff_on_start=True)`, the `http_auth` dose not apply to every node.  

### __init__.py
We could see the `__init__.ElasticSearch` send `hosts` url to `_normallize_hosts`, extract `http_auth` and send back to `transport_class`.   
### transport.py
In `Transport` class, it store `hosts` in `self.hosts`, but the `http_auth` which in `hosts` dose not copy to `self.kwargs`.  
 In the `set_conenctions` function, the line 152 `kwargs = self.kwargs.copy()` do not copy the   `http_auth`. So, the node of this client would connect without `http_auth`, which cause `Unauthorized` error.

**Comment by sethmlarson** [comment]
elasticsearch-python 5.x is unlikely to receive any further updates as the Elastic Stack v5.x isn't actively supported. Sorry about that.

**Comment by KristobalJunta** [comment]
Yeah, but this issue is all the way in the 8.x version too.
