### ISSUE TITLE
How to manage Elasticsearch connection

### ISSUE THREAD

**Issue by Sphinxs** [elastic/elasticsearch-py#873]
How to manage Elasticsearch connection in a Flask application. Should I create a global connection for all users or a connection to each user, in global or local scope ?

**Comment by Winterflower** [comment]
Hi @Sphinxs ! What kind of application are you developing? Is it a web app with something like Flask or a command line app or something else?

**Comment by Sphinxs** [comment]
Hi, @Winterflower , I'm developming a web application with Flask, I have modeled a `class` to create the connection with Elasticsearch and I had extended two other classes to the connection, then I create an instance of the connection inside the file where the Flask routes are in.

I'm thinking about create a file to the connection and use it, something like the SQLAlchemy connection, or create a connection to each user and add it to the Flask session.

**Comment by fxdgear** [comment]
the best way to think of working with Elasticsearch is that you connect to Elastic over a REST api. So it, does not work the same way a connection to SQL would work using SQL alchemy. 

When you are connecting to a rest api you don't open a connection and then leave it open. 
So the same applies when using Elasticsearch. 

When you need to connect to ES you instanciate the connection transmit your data and then let the python garbage collection handle the rest.

**Comment by Sphinxs** [comment]
@fxdgear , 'the best' would be to 'create' the connection inside each route, get the resources and let the garbage handle the rest ?!? (this way I could implement the class methods as `@classmethod` and remove the instances of the connection class)

**Comment by Sphinxs** [comment]
Awesome, thanks, both of you for the support ^ - ^

**Comment by viglia** [comment]
@Sphinxs I'm closing this ticket since it seems that your question has been answered. 

Please feel free to reopen it if you need to follow up on this.
