### ISSUE TITLE
streaming_bulk indexing is slower than single document indexing

### ISSUE THREAD

**Issue by ned2** [elastic/elasticsearch-py#878]
I've read that `streaming_bulk` for indexing a stream of documents is meant to be much faster than running `index` for each document. I'm experiencing the exact opposite though. Using `index` in a for loop, is much faster. I've tried experimenting with different `chunk_size` from 10 through 500, and none come close. 500 is the fastest chunk_size. 

I suspect I'm doing something wrong, but cannot find anything helpful via googling for this issue. Is there just some simple parameter tuning I need to do, or could this be an issue?

**Comment by zealot-shin** [comment]
how about setting chunk_size to about 5000 or 10000. 
I thing there's another parameter which is chunk_max_bytes， try setting this to about 10mb.

**Comment by ezzy1337** [comment]
Not sure how this might help but just yesterday I wrote this code and indexes ~5mil documents in about 6 hours. Doing individual indexing was going to take ~108hours for that same amount. 
NOTE: snapshot_generator() is just a generator that returns mock data for me to do load testing with.

```
    for status, _ in streaming_bulk(client=client, index=index, actions=snapshot_generator(**kwargs)):
        print(status)
```

**Comment by sethmlarson** [comment]
This isn't so much an issue of the client / Elasticsearch as performance requires testing to make sure you're hitting the optimal performance for your use-case. Check out all the options on the bulk helpers and configure until you find what works best for you.
