### ISSUE TITLE
Different results when searching

### ISSUE THREAD

**Issue by javixeneize** [elastic/elasticsearch-py#879]
Hi

I am having different results when running a query in elasticsearch-py and in the console

In the console i run this:

GET /javi/_search?q=result.url:"http://myurl.com/login" and it returns 18 results, which is correct

Using the python library, 

print (s.es.search(index="javi", body={"query": {"match": {"result.url": "http://myurl.com/login"}}})['hits']['total'])

It returns 150 results

I think the problem is that your library it is not doing an full match, as it is finding all the results that have a partial match.

Thanks

**Comment by fxdgear** [comment]
@javixeneize thanks for the issue but this example you've given is like comparing apples and oranges unfortunately. 

Your curl example is doing a `uri search`: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html
and the python library is doing a `request body search`: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html

If you look at the [parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html#_parameters_3) section of the `uri search` documentation you will see that by doing a search with `q=foo` the query is actually mapped to a query string query, so to get the same results in the python code you have to pass in a query string query, and not a match query. 

For example:
 
```python
s.es.search(index="javi", body={
    "query": {
        "query_string" : {
            "default_field" : "result.url",
            "query" : "http://myurl.com/login"
        }
    }
}
```
