### ISSUE TITLE
Is it possible to use YAML in request body?

### ISSUE THREAD

**Issue by armanzor** [elastic/elasticsearch-py#899]
Hello!
I would like to use YAML in requests, like this:
```
from elasticsearch import Elasticsearch
YAML_BODY = """
---
query:
  bool:
    filter:
      term:
        error.keyword: 'ERROR'
"""
ES = Elasticsearch(hosts=['localhost'], port=9200, headers={'content-type': 'application/yaml'})
ES_PAGE = ES.search(index='my-index', body=YAML_BODY)
```
but got an error: `Cant't retrieve data from Elasticsearch cluster: Unknown mimetype, unable to deserialize: application/yaml`

**Comment by fxdgear** [comment]
No, the body needs to be a dictionary. The dict will get converted to JSON before being sent to Elasticsearch. Elasticsearch only accepts JSON. 

IF you want to use YAML, I'd create your request using yaml, for readability, then convert the yaml to a dict then pass the dict into your request.

**Comment by armanzor** [comment]
Hmm, that's strange, because I managed to send requests to ES in YAML and get answer from it without errors just using HTTP header 'content-type' with value 'application/yaml' in REST API client

**Comment by fxdgear** [comment]
@armanzor I'm sorry for misleading you there re the elasticsearch rest bit. 

BUT regardless the body for the python client does expect a dictionary.

**Comment by sethmlarson** [comment]
You could implement your own serializer for YAML and set the `Content-Type` header to `application/yaml` on the client. In general though the low-level client accepts JSON and the easiest way would probably do as @fxdgear suggests and dump the YAML into JSON before passing off to the client.
