### ISSUE TITLE
Thrift SSL support is lacking in a few places.

### ISSUE THREAD

**Issue by nkvoll** [elastic/elasticsearch-py#9]
Looking at https://github.com/apache/thrift/blob/master/lib/py/src/transport/TSSLSocket.py, for reference.

1. It requires either passing ``validate = False`` or the path to a ``ca_certs`` file, usually downloaded from http://curl.haxx.se/ca/cacert.pem .

2. The default TSSLSocket implementation does not support wildcard certificates.

**Comment by HonzaKral** [comment]
We are deprecating the thrift transport anyway, so I am closing this ticket.
