### ISSUE TITLE
indices.create doesn't support include_type_name request parameter

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch-py#901]
[indices.create](https://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=indices%20create#elasticsearch.client.IndicesClient.create) supports `wait_for_active_shards` however, the recent Elasticsearch commit: https://github.com/elastic/elasticsearch/pull/38270 forces the use of `?include_type_name=true` to allow use of the `_doc` type in 7.0. Types are deprecated in 7.0 and will be [completely removed in 8.0](https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types).

So for users sticking to _doc for the lifetime of 7.0, it's necessary to pass this query/parameter.

It'd be great if support for this would be added. To avoid having to follow up future parameters, would it make sense to just allow passing any arbitrary parameters that the user elects to?

**Comment by dliappis** [comment]
> To avoid having to follow up future parameters, would it make sense to just allow passing any arbitrary parameters that the user elects to?

To close this, specifying `params={}` allows passing arbitrary parameters -- serialization needs to be done by the user though, so best used only for strings. Thanks @HonzaKral .

**Comment by apeters** [comment]
This parameter doesn't seem to be documented like other (eg: `wait_for_active_shards`).  Should it be?  
I know this issue is closed, but it seemed like the most appropriate place for it.

**Comment by aclowkey** [comment]
How about ?
`indices.put_template(name="data", body=template, params={'include_type_name': 'true'})` - doesn't work for me 

elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.')
