### ISSUE TITLE
typos in ConnectionSelector documenation

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch-py#903]
Documentation of ConnectionSelector is

>  Example of where this would be useful is a zone-aware selector that would only select connections from it's own zones and only fall back to other connections where there would be none in it's zones.

The **it's** should be changed to **its**

**Comment by sethmlarson** [comment]
Could you open a PR with this fix? Thank you!

**Comment by bartier** [comment]
@the-vishal Are you working on this? If not, can I open a PR to this issue? :)

**Comment by sethmlarson** [comment]
@bartier I think you can go ahead and take this issue if you're up for it :)

**Comment by the-vishal** [comment]
@bartier Hi mate, this has been merged already here : https://github.com/elastic/elasticsearch-py/pull/1160

**Comment by sethmlarson** [comment]
Oh thanks for finding that :)
