### ISSUE TITLE
Add index name in traceback NotFoundError

### ISSUE THREAD

**Issue by mazzma12** [elastic/elasticsearch-py#906]
Hi,

Would it be possible to display the index name in the traceback raised by a NotFoundError Exception ? 

```python
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')
```
When this error is raised it's hard to see which index is at fault. 
Haven't dived in the code yet but maybe `urllib` returns error codes only?  

Using versions 6.3.1

**Comment by fxdgear** [comment]
theoretically it should be possible. If you want to create a patch I'll happily review it for you.

**Comment by sethmlarson** [comment]
This issue has been fixed. Thanks for the contribution!
