### ISSUE TITLE
Document Types Support for Major Release 7.x

### ISSUE THREAD

**Issue by anottrott** [elastic/elasticsearch-py#910]
The Python library for interfacing with the Elastic stack still requires input specification for Document Types in Index Mappings. Understanding that Types are are deprecated and will no longer exist in 7.0
https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping.html
the Python Elasticsearch library is not compatible with 7.0, this is impacting me as I'm testing the 7.0.0 beta 1 release as it appears the helpers require a Document Type to be specified in the function calls. Any plans in the works for a 7.x release update?

**Comment by fxdgear** [comment]
Yes there is.

**Comment by fxdgear** [comment]
the 7.x compatible version of this client has been released.
