### ISSUE TITLE
ES version 7 supported?

### ISSUE THREAD

**Issue by stevegszabo** [elastic/elasticsearch-py#916]
When running elastalert with ES v7 we get this error:

RequestError(400, u'illegal_argument_exception', u'request [/filebeat-*/_search] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?')

seems to be related to:

https://github.com/stevegszabo/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L321

**Comment by stevegszabo** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/docs-get.html

If you only need one or two fields from the complete _source, you can use the _source_include & _source_exclude parameters to include or filter out that parts you need.

vs

https://www.elastic.co/guide/en/elasticsearch/reference/7.0/docs-get.html

If you only need one or two fields from the complete _source, you can use the _source_includes and _source_excludes parameters to include or filter out the parts you need.

**Comment by fxdgear** [comment]
ES7 is still in Beta. 

But the pull request is right here: https://github.com/elastic/elasticsearch-py/pull/911

**Comment by fxdgear** [comment]
Elasticsearch-py 7.0.1 is out.

**Comment by gboddin** [comment]
Was this fixed ? We're still getting 7.0.1 using `_source_include`

**Comment by gboddin** [comment]
nvm it's a application issue
