### ISSUE TITLE
ValueError during scroll call

### ISSUE THREAD

**Issue by sadiya** [elastic/elasticsearch-py#917]
`es.scroll(scroll_id=next_scroll_id, scroll='1m')`

Sometimes the next scroll call fails, returned error has data as json that seems to have chunks missing. Happens randomly, same call on same index passes next time. 

Exception: 
`ValueError("Expecting ',' delimiter: line 1 column 4068794 (char 4068793)",))`

`(u'{"_scroll_id":"DnF1ZXJ5VGhlbkZldGNoAwAAAAAAARroFjFGbXJSenh6U29pTmV2WGI4X0U4bEEAAAAAAAEK-xY0aVl4czROYVRNaXo2NVZVYlVYLUd3AAAAAAAA74YWSjV3Y1NaLUpUYnVOV1pGMW5YLTltdw==","took":437,"timed_out":false,"terminated_early":true,"_shards":{"total":3,"successful":3,"skipped":0,"failed":0},"hits":{"total":713349,"max_score":1.0,"hits":[...`

What we see in the hits JSON:
Expected:
`{“_index”:”name-of-index"`
Actual:
`{“_inBkwlqr29vOAis`

After _in the rest of the characters are unexpected.

Expected:
`“_source”:{“field-name"`
Actual:
`“_s”name-of-index`
After _s the rest of the characters are unexpected.

Python version: 2.7.5
Python Elasticsearch Client: 6.3.0
Elasticsearch version: 6.4.2

**Comment by sethmlarson** [comment]
This looks like the connecting proxy/load balancer is cutting off a large response, potentially reduce the size of responses and you won't hit this issue? But I'm not sure there's anything we can do about this since the "server" is returning invalid JSON.
