### ISSUE TITLE
verify_certs ignored when REQUESTS_CA_CERTS set

### ISSUE THREAD

**Issue by impguard** [elastic/elasticsearch-py#929]
Hi! In our codebase we have REQUESTS_CA_CERTS set so that we can set the cert bundle to use for requests calls.

When using the RequestsHttpConnection with elasticsearch, passing verify_certs=false doesn't override this environment variable. I checked out the codebase, and it seems like RequestsHttpConnection leverages the merge_environment_settings requests call to prepare the session request. This overrides the code level verify parameter with the setting in REQUESTS_CA_CERTS.

Expectation: That the code level override trumps over the environment variable.

Actual: The code level override is ignored, and requests verifies the ElasticSearch request with the cert bundle specified in REQUESTS_CA_CERTS.

In our case, we want to verify all other requests with that bundle, but not the one for ElasticSearch (in this case, it's behind a bastion for us, and we leverage SSH tunneling locally to develop, which the certs are invalid for).

Should be as straightforward as passing the verify_certs parameter down to merge_environment_settings to allow that override through. It might even be beneficial to pass down all the other possible parameters to allow the user fine grained control of the ElasticSearch client regardless of that status of the rest of the codebase.

Thanks!

**Comment by sethmlarson** [comment]
Unfortunately this is a Requests-ism, I'm not sure there's even a way to tell Requests to not make a specific decision based on `REQUESTS_CA_CERTS` without setting `trust_env=False` (which also isn't great because some options are nice to get from the environment). The work-around is to not set `REQUESTS_CA_CERTS`, closing this issue.
