### ISSUE TITLE
Elasticsearch.delete_by_query() unrecognized parameter `doc_type`

### ISSUE THREAD

**Issue by iamtodor** [elastic/elasticsearch-py#935]
Elasticsearch.delete_by_query() unrecognized parameter `doc_type`. 

Docs API https://elasticsearch-py.readthedocs.io/en/master/api.html states the following: `doc_type – A comma-separated list of document types to search; leave empty to perform the operation on all types`

Encounter on the last version Elastic and this issue is missing with `6.3.1` version

**Comment by fxdgear** [comment]
Ahh that's unfortunate, It would appear that the link between readthedocs and this repo have broken :( 

Thanks for bringing this to my attention. I'll work on getting readthedocs hooked up again and figure out why it stopped :( 

`doc_type` is not a parameter that has been deprecated in Elasticsearch 7.0, as such it's been removed (or turned into a defaulted kwarg) in as many places as possible, with the goal of the `doc_type` being removed completely in Elasticsearch 8. 

If you're using elasticsearch6.x I'd recommend installing the elasticsearch6 version of this client `pip install elasticsearch6`.

**Comment by iamtodor** [comment]
@fxdgear thank you for the clarification. I have decided to stay at 6.3.1, didn't know about the 6.4.0
Probably will move to the last version `pip install elasticsearch6`. Won't it be modified any more?

**Comment by fxdgear** [comment]
I will back fill bug patches but it won’t get features anymore. Hope that helps. :)
