### ISSUE TITLE
Documentation site is not up to date.

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch-py#952]
The documentation page isn't updated with API and code breaking changes for elasticsearch 7.  https://elasticsearch-py.readthedocs.io/en/master/

**Comment by dnwobu** [comment]
I posted this with my old account which I recently deleted.

The documentation page isn't updated with API and code breaking changes for elasticsearch 7. https://elasticsearch-py.readthedocs.io/en/master/

**Comment by Winterflower** [comment]
Hi @dnwobu ! Thanks for reporting this - I'm taking a look at this!

**Comment by sethmlarson** [comment]
This issue is resolved, thanks!
