### ISSUE TITLE
Change HTTP method to POST for Elasticsearch.search

### ISSUE THREAD

**Issue by dalazx** [elastic/elasticsearch-py#954]
A Google Load Balancer does not proxy HTTP GET requests with a body and immediately responds with `400 Bad Request`, so if ES sits behind a GCP LB, any search queries just fail.
Please see a related issue: https://issuetracker.google.com/issues/36886282

According to ES REST API reference,
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/search-request-body.html#_parameters_4
```
Both HTTP GET and HTTP POST can be used to execute search with body. Since not all clients support GET with body, POST is allowed as well.
```
, thus we could easily change
https://github.com/elastic/elasticsearch-py/blob/c4f0454285cebefaa905ce62482a36485dc92d89/elasticsearch/client/__init__.py#L817-L819
to POST to allow exposing ES via that type of LB.

I think, this could be addressed in versions 6 and 7 at least.

Turns out same applies to Scroll.
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/search-request-scroll.html#search-request-scroll
```
GET or POST can be used and the URL should not include the index name — this is specified in the original search request instead.
```

**Comment by fxdgear** [comment]
@dalazx So Google is a known "problem". Instead of changing the method we've added the ability to instantiate your ES client with the parameter `send_get_body_as`. 

https://elasticsearch-py.readthedocs.io/en/latest/#environment-considerations
