### ISSUE TITLE
Can't create index with body with ES 7.0.1

### ISSUE THREAD

**Issue by lpanichi** [elastic/elasticsearch-py#961]
I'm using elasticsearch docker image 7.0.1, python3 and this lib : *elasticsearch==7.0.0* which I installed with pip3.
I run the following code :
```
from elasticsearch import Elasticsearch
es = Elasticsearch()

index = "my-index"

mybody = {
  "settings": {
    "index":{
      "number_of_shards": "5",
      "number_of_replicas": "1",
    },
    "analysis":{
      "analyzer": {
        "myanalyzer": {
          "filter": ["lowercase", "asciifolding"],
          "tokenizer": "standard"
        }
      }
    }
  },
  "mappings": {
    "mymapping":{
      "properties":{
        "name": {
          "analyzer": "myanalyzer",
          "type": "text"
        }
      }
    }
  }
}


es.indices.create(index=index, ignore=400, body=mybody)
```

and no index is created. When I change the mapping to 
```
  "mappings": {
    "properties":{
      "name": {
        "analyzer": "myanalyzer",
        "type": "text"
      }
    }
  }
```
an index is created, the mapping is named *_doc*. Is it the expected behaviour ?

**Comment by fxdgear** [comment]
It would appear that you’ve run into an issue where there have been changes to the way Elasticsearch indexes work with relation to the doc_type, specifically it is being removed. 

For more information please read: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

The behavior you are noticing is correct. 

On major version changes (from 6 to 7) you should expect breaking changes, and as such it would be wise to review the changes as published from elastic. https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes.html
