### ISSUE TITLE
Please get rid of DeprecationWarnings

### ISSUE THREAD

**Issue by MeggyCal** [elastic/elasticsearch-py#968]
When I launch tests, I get many DeprecationWarnings:
DeprecationWarning: Please use assertEqual instead. (very common)
DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
DeprecationWarning: invalid escape sequence \[
DeprecationWarning: invalid escape sequence \?

Could you please improve the code in order not to break with newer Python?

**Comment by fxdgear** [comment]
Thanks for the issue, but deprecation warnings do not break newer python, they are just warning that features will be going away or changing. 

You must also keep in mind that there are at least 9000 other packages/projects that depend on this project and not all of those are compatible with the latest python versions. As such I need to maintain backwards capabilities for as long as possible. 

If you'd rather not see them you can still mute the deprecation warnings yourself in your own codebase.  https://stackoverflow.com/questions/879173/how-to-ignore-deprecation-warnings-in-python 

I hope this helps, thanks

**Comment by petervandenabeele** [comment]
On Python 3.7.3 with elasticsearch6, this now failed (not a warning, but a failure):

```
./test-es.py
Traceback (most recent call last):
  File "./test-es.py", line 9, in <module>
    es = Elasticsearch(cloud_id="test001:ZX__________==", http_auth=('elastic','_______________'))
  File "/usr/local/lib/python3.7/site-packages/elasticsearch6/client/__init__.py", line 192, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch6/transport.py", line 127, in __init__
    self.set_connections(hosts)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch6/transport.py", line 177, in set_connections
    connections = list(zip(connections, hosts))
  File "/usr/local/lib/python3.7/site-packages/elasticsearch6/transport.py", line 173, in _create_connection
    return self.connection_class(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch6/connection/http_urllib3.py", line 106, in __init__
    decodestring(cloud_id.encode("utf-8")).decode("utf-8").split("$")
NameError: name 'decodestring' is not defined
```

The fix turned out to be to change in `elasticsearch6/connection/http_urllib3.py`

```
...
import base64
...
#                 decodestring(cloud_id.encode("utf-8")).decode("utf-8").split("$")
                base64.decodebytes(cloud_id.encode("utf-8")).decode("utf-8").split("$")
```

Hope this helps anyone.
