### ISSUE TITLE
Any plans to add API for Rollups?

### ISSUE THREAD

**Issue by tommygod3** [elastic/elasticsearch-py#977]
It would be nice if I could use the elasticsearch client to create/manage rollups instead of needing to do it manually with requests :) [Rollup API](https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-apis.html)

**Comment by alexk307** [comment]
Hi @tommygod3, the Rollup API was added recently here: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/rollup.py
