### ISSUE TITLE
Test fails on Python 2.7.12

### ISSUE THREAD

**Issue by alexk307** [elastic/elasticsearch-py#979]
Cloned from this repo, on master branch, ran `tox`:

```
======================================================================
FAIL: test_decimal_serialization (test_elasticsearch.test_serializer.TestJSONSerializer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Work/developer/elasticsearch-py/test_elasticsearch/test_serializer.py", line 29, in test_decimal_serialization
    self.assertEquals('{"d":3.8}', JSONSerializer().dumps({"d": Decimal("3.8")}))
AssertionError: '{"d":3.8}' != '{"d":3.7999999999999998}'
```

When I try to reproduce in my python interpreter:

```
>>> from decimal import Decimal
>>> JSONSerializer().dumps({"d": Decimal("3.8")})
'{"d":3.7999999999999998}'
```

Looks like the Jenkins tests are running [2.7](https://clients-ci.elastic.co/job/elastic+elasticsearch-py+master/), but not 2.7.12.

The test itself skips for python 2.6:

```
    def test_decimal_serialization(self):
        if sys.version_info[:2] == (2, 6):
            raise SkipTest("Float rounding is broken in 2.6.")
        self.assertEquals('{"d":3.8}', JSONSerializer().dumps({"d": Decimal("3.8")}))

```

Maybe it should also skip for certain versions of 2.7?

**Comment by filipmnowak** [comment]
Python 2.7 reaches its EOL within a month. this issue probably should be closed with `won't fix` at this point of time.

**Comment by HonzaKral** [comment]
Yeah, I am not worried about this failure as long as our CI reports green for 2.7 which we have - https://travis-ci.org/elastic/elasticsearch-py

it is clearly just a testing thing and indicates no bug in the code, closing.

Thank you for the report, @Alex3k
