### ISSUE TITLE
exists_alias command is failing if you don't specify name parameter

### ISSUE THREAD

**Issue by zzacharo** [elastic/elasticsearch-py#984]
The command [exists_alias](https://github.com/elastic/elasticsearch-py/blob/5.0/elasticsearch/client/indices.py#L357) has a default to the name parameter to `None` but if you specify the index parameter without the name it tries to make a HEAD request similar to `http://localhost:9200/<index_name>/_alias`. This ends up to a bad request error response. 

My question is: Is this expected behaviour or should be the `index` and `name` parameter required for `ES versions<6` ?

**Hints**: I found the issue using ES 5.6.4

**Comment by sethmlarson** [comment]
Unfortunately ES5 is no longer supported. If you're experiencing this issue using ES6+ please reopen this issue.
