### ISSUE TITLE
Support for dense and sparse vectors

### ISSUE THREAD

**Issue by asktree** [elastic/elasticsearch-py#985]
Do we have support for dense and sparse vectors? Attempting to update a document's field of type `dense_vector` with a list of floats will give the error `'Failed to parse object: expecting token of type [VALUE_NUMBER] but found [START_ARRAY]'`

**Comment by minung-park** [comment]
The maximum number of dimensions that can be in a vector should not exceed 2048.
(https://www.elastic.co/guide/en/elasticsearch/reference/master/dense-vector.html)
I think you need to check your vectors.

**Comment by JingxinLee** [comment]
Hi, here are my problem. There are one INTENT text with a list of query texts in each line. I encoded the list of queries, for example every query's dimension is 384,  10 queries in this list may exceed 2048,  how to get the most similar INTENT by using ES?
