### ISSUE TITLE
es.indices.exists allow_no_indices default is misleading

### ISSUE THREAD

**Issue by zQuantz** [elastic/elasticsearch-py#988]
Hi.

When using es.indices.exists, the default value for allow_no_indices is documents to be False. It seems like the default value is actually True. See my exam below:
`
from elasticsearch6 import Elasticsearch
es = Elasticsearch([{"host" : "localhost"}])
es.indices.create("is_bug-a")
es.indices.create("is_bug-b")

## Says allow_no_indices default = False
es.indices.exists("is_bug_*") # Returns True

## Setting to false gives different result
es.indices.exists("is_bug_*", allow_no_indices=False) # Returns False

## Setting to True gives same result
es.indices.exists("is_bug_*", allow_no_indices=True) # Return True

`

elasticsearch6 version -> 6.4.2

**Comment by sethmlarson** [comment]
This issue must be solved upstream as is mentioned in #1036
