### ISSUE TITLE
search(sort=...) argument doesn't support complex values

### ISSUE THREAD

**Issue by hexvolt** [elastic/elasticsearch-py#995]
I'm using ES version 5.6 and the client version 5.5.3.

The `sort` parameter in the `search()` method is `– A comma-separated list of <field>:<direction> pairs`. So it just allows you to specify only the field and the order.
While the [actual sorting API allows you to specify way more different parameters](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-request-sort.html).

To use them you need to pass a list of dicts there, not just a list of strings but there seem to be no way to do that.

When I pass a list of dicts `search(..., sort=[{...},{...}])`, it crashes here:
```
def _escape(value):
    ...

    # make sequences into comma-separated stings
    if isinstance(value, (list, tuple)):
        value = ','.join(value)
...
```

**Comment by hexvolt** [comment]
The possible workaround is to put everything to the body: `search(body={..."sort": [...]}   `. Not sure if this is the issue of `sort=` argument or a design decision. But seems that since we have the `sort` argument, it would be great for it to accept the values ES supports

**Comment by sethmlarson** [comment]
The workaround mentioned is the proper way to implement complex sorting for searches. In 7.x the `sort` parameter always goes the querystring and not the body. This may change in 8.x.
