### ISSUE TITLE
Hello guys. I have difficulty applying a customized Analyzer when using query match. Need help.

### ISSUE THREAD

**Issue by XinXia2019** [elastic/elasticsearch-py#997]
I customized an analyzer called 'custom_lowercase_stemmed' and used es.indices.put_settings to update index setting. However, it couldn't find the analyzer when I do a search. I also looked into the parameter 'analyzer' in es.search, but it returns error "'..unrecognized parameter: [analyzer]'" Can I get any suggestions here in terms of a customized analyzer? Thank you!

query_body = {"query": {
                        "match": { 
                                 "employer":{
                                 "query": txt,
                                 "fuzziness": 'AUTO',
                                 "analyzer" : 'custom_lowercase_stemmed'
                                            }
                                 }
                        }
              }

es.search(index='hello',body=query_body)

RequestError: RequestError(400, 'search_phase_execution_exception', '[match] analyzer [custom_lowercase_stemmed] not found')

**Comment by tzurlevi** [comment]
can u plz explain how you handle the problem? i get the same exception...
